### ISSUE TITLE
No action for remove (without if)?

### ISSUE THREAD

**Issue by tower120** [ericniebler/range-v3#1015]
Is there a particular reason, why there is no `action::remove` / `view::remove` ?

**Comment by ericniebler** [comment]
No reason, short of a lack of time. Can I interest you in submitting a PR?

**Comment by tower120** [comment]
I'm trying to implement `action::remove` as wrapper around `action::remove_if` .

I think, I'm bumped into the same thing as with views. Are actions **must** be Semiregular too?

Following wan't compile:
https://wandbox.org/permlink/2cqBMYc1lTAoJ5w2

```cpp
#include <iostream>
#include <vector>

#include <range/v3/action/remove_if.hpp>


struct Pred{    
    int i = 2;
        
    Pred(const Pred&) = delete;
    Pred(Pred&&) = default;
    Pred() = default;
    
    bool operator()(int other) const {
        return other == i;
    }
};

void test_value_capture(){
    using List = std::vector<int>;
    List list{};
    list |= ranges::action::remove_if(Pred());

    std::cout << list.empty();
}

int main()
{
    test_value_capture();
}
```
