### ISSUE TITLE
view::addressof

### ISSUE THREAD

**Issue by tower120** [ericniebler/range-v3#1030]
There is `view::indirect` which makes references from pointers of all forms(dereference), but there is no reverse operation.
What about `view::addressof`?
Something as simple as : 
```
    const auto addressof = ranges::view::transform([](auto& element) -> auto* {
        return std::addressof(element);
    });

```

**Comment by CaseyCarter** [comment]
This seems useful to me, although it needs some thought on what the constraints should be. Obviously we want to require the underlying range to have a reference type that's actually an lvalue reference, but there's also some subtlety around iterator category as well. We require that references obtained from `Forward` iterators must be valid while the iterator's range is valid, but there's no such requirement for single-pass iterators. Someone needs to investigate whether allowing `view::addressof` to accept single-pass ranges could lead to badness.

**Comment by tower120** [comment]
At first: truly Single-pass range, will probably deference to value, or something like shared_ptr...
At second: if range deferences to lvalue reference, it is expected that we can actually do something with that reference. And it not becomes invalid immediately after read, and will live until some predictable point in time. And until that reference alive - it's pointer/address valid.
