### ISSUE TITLE
Range Concepts, constrain by element type

### ISSUE THREAD

**Issue by tower120** [ericniebler/range-v3#1036]
Passing container/span/range as template argument is quite common:
```cpp
template<class Rng>
void run(Rng&& rng){
   for(int v : rng){
      // do something with i
   }
}
```

Also, quite often we would like to work with range elements of certain type:
```cpp
template<class Rng, /* long SFINAE, where we constrain Rng to Range && range_value<Rng> == int */>
void run(Rng&& rng){
   for(int v : rng){
      // do something with i
   }
}
```

I think this case is quite common.

Concepts solves this. But current RangeTS and range-v3 does not have range concepts which constrain by element type. It is possible to express range constraint by element type as-is, but it is not that brief.

If Range, InputRange, ForwardRange, etc. would accept "optional"  second type as required value type (like OutputRange do), it would become much simpler to constrain range by element: 

```cpp
template<class Rng, CONCEPT_REQUIRES_(ForwardRange<Rng, int>())>
void run(Rng&& rng){
}
```

Alternatively, RangeValue concept could look like this:
```cpp
template<class Rng, CONCEPT_REQUIRES_(ForwardRange<Rng>() && RangeValue<Rng, int>())>
void run(Rng&& rng){
}
```

In C++20 terms this would look like:

```cpp
template<class Rng> requires ForwardRange<Rng, int>
void run(Rng&& rng){
}
```
Or
```cpp
template<ForwardRange Rng> requires RangeValue<Rng, int>
void run(Rng&& rng){
}
```

Alas, C++20 concepts can appear only at namespace scope, and `using` is not applicable for concepts. It seems this form is not achievable:

```cpp
template<ForwardRange<int> Rng>
void run(Rng&& rng){
```

**Comment by h-2** [comment]
You can already do:
```cpp
template <ForwardRange R>
    requires Same<range_value_t<R>, int>
void run(R && r){}
```
Although this might be better for most situations:
```cpp
template <ForwardRange R>
    requires CommonReference<range_reference_t<R>, int&>
void run(R && r){}
```

**Comment by tower120** [comment]
> You can already do:

True. The idea was, to have compile-timed `any_view<T>` interface version.
Something like C#'s `IEnumerable<T>` interface.
If language would have concept aliases, that could look that simple:
```cpp
template<Range<int> Rng>
void show(Rng&& rng){
   for(int i : rng) cout << i;
}
```

---

But maybe you're right.  
`Same<range_value_t<R>, int>` actually not that longer then `RangeValue<R, int>`
