### ISSUE TITLE
trouble diagnosing failed assertion in cartesian_product.hpp

### ISSUE THREAD

**Issue by david8dixon** [ericniebler/range-v3#1043]
I am having a difficult time generating a reproducer for an assertion that I see in `ranges::view::cartesian_product` so I was hoping to get some insight on possible meaning behind the following:
```
 Assertion failed: (n < my_size || (N == 1 && n == my_size)), function advance_, file range-v3-adapter/src/include/range/v3/view/cartesian_product.hpp, line 208.
```
I have roughly the following:
```c++
auto cp = ranges::view::cartesian_product(x,y);
auto range = ranges::view::zip_with(make_foo, cp, z) | ranges::view::strided(2);
auto it = ranges::view::lower_bound(range, val, std::less{}, projection);
auto not_match = ((*it).val != val)
it = ranges::prev(it, not_match); // if vals do not_match is 1; otherwise 0 i.e. no-op
```
It is the call to `ranges::prev` that causes the assertion failure.

Many thanks!

**Comment by CaseyCarter** [comment]
That assertion changed in #920, which fixed bugs - hopefully including the one you are hitting - in `cartesian_product_view`. I suggest trying `master` and seeing if your problem goes away.

@ericniebler, it's probably time to cut another (possibly the last) `master` release.

**Comment by david8dixon** [comment]
Thanks so much! You guys are awesome!

**Comment by david8dixon** [comment]
The bug was fixed. Thanks!
