### ISSUE TITLE
group_by does not behave as expected

### ISSUE THREAD

**Issue by daniel-oelert** [ericniebler/range-v3#1066]
```
int main(int argc, char** argv){
std::vector<std::string> cmdline(argv, argv + argc);

  {
    using std::string;
    using namespace ranges;
    
    cmdline | view::tail |
        view::group_by([](string a, string b) { return (a.rfind("-",0) != 0) != (b.rfind("-",0) != 0); }) |
        view::take(8) |
        // view::chunk(2) |
        // view::split([](string s){return s.rfind("-",0) == 0;}) |
        // iterator_past_the_delimiter);}) | view::chunk(3) |
        // action::transform([](auto s){for_each(s,print); return;});
        view::transform([](auto r) {
          return view::concat(view::single(string("new group")), r);
        }) |
        // ranges::view::intersperse(ranges::view::single(string("test"))) |
        // view::join |
        view::transform([](auto s) {
          std::cout << s << std::endl;
          return s;
        }) |
        action::join;
  }
return 0;
}
```

To reproduce:
Call ${executable} -a d -b sa ff -s -s
(or other command line arguments of similar form)

The output I get is:
```
[new group]
[new group]
[new group]
[new group]
[new group]
[new group]
[new group]
[new group]
```
The ouput I would expect is:
```
[new group,-a,d]
[new group,-b,sa,ff]
[new group,-s,s]
```

I have read through the documentation for quite a long time now and I'm sure I 
would expect this to work. If tried lots of different permutations of this and most other 
view:: members work fine for me. view::chunk(2) instead of view::group_by also 
outputs what would be expected.
I'm quite an amateur though, so I might be overlooking something.

Additional information:
Compiler: clang6
Linux Mint 18.3
range-v3 @ 64467567

**Comment by Mog-Closet** [comment]
I used the following lambda to get desired output:
```
[](string a, string b) 
{ 
    if( a==b ) 
        return true; 
    else 
        return (a.rfind("-",0) != 0) != (b.rfind("-",0) != 0); 
}
```
It seems the first item is compared agains itself first and this has to return true otherwise we get stuck in an infinite loop. 

I do not know if this is the intended behaviour and documented somewhere! @ericniebler

**Comment by daniel-oelert** [comment]
Ah I see, thank you!
What confused me was probably the documentation. 
I would suggest expanding the documentation to include this information.
Also more of a meta question:
Is this really desirable behavior?

Anyways thank you and I will close the issue.
