### ISSUE TITLE
building tests when composing range-v3 library in super project

### ISSUE THREAD

**Issue by david8dixon** [ericniebler/range-v3#1067]
Using range-v3 as a subproject yet the range-v3 (header) tests are building.

**Comment by david8dixon** [comment]
Recent change to the build system in this PR: https://github.com/ericniebler/range-v3/pull/1052

**Comment by ericniebler** [comment]
@dpacbach your cmake changes seem to be confusing people. What do you say? I'm inclined to revert.

**Comment by david8dixon** [comment]
I should have been more descriptive but had a busy day when reporting this issue. I believe what @dpacbach provided is useful and probably only requires a hotfix (in fact either myself or @apmccartney) plan to provide a fix if @dpacbach doesn't beat us to it. 

@dpacbach did you test #1052 in the context of using range-v3 as a submodule with `find_package` and `add_subdirectory?` I could get to a reference PR before the end of the day.

**Comment by dpacbach** [comment]
@david8dixon if you have a hotfix that would be great; I tested my changes with range-v3 as a submodule but only with the following:

`add_subdirectory( extern/range-v3 EXCLUDE_FROM_ALL )`

but not with `find_package` (apologies for that).  @ericniebler it sounds like @david8dixon might have a fix, but in any case if things don't get resolved to your satisfaction soon then feel free to revert.

**Comment by david8dixon** [comment]
It turns out that I conflated a few things from cmake extensions used in my project consuming range-v3, but there is still some behavior I didn't expect to see. Consider the three following cases:

case 1:
```
include(CTest)
add_subdirectory(dependencies/range-v3)
```
case 2:
```
include(CTest)
add_subdirectory(dependencies/range-v3 EXCLUDE_FROM_ALL)
```

case 3:
```
add_subdirectory(dependencies/range-v3)
include(CTest)
```
For *case 1*, you see extra configuration print out along these lines:
> -- Performing Test RANGES_HAS_WEVERYTHING" 

and the super project builds the range-v3 header tests e.g.:

> [  7%] Building CXX object dependencies/range-v3/CMakeFiles/test.header.range.v3.view.zip_with.hpp.dir/headers/range/v3/view/zip_with.cpp.o

For *case 2*, you see extra configuration print out but you do not build range-v3 header tests. For *case 3*, there is no noticeable difference between the super-project config/build behavior before and after #1052. In other words, with this new logic consuming projects must be aware that the order in which you consume range-v3 and `include(CTest)` matters - bummer. Or maybe this was always the case and we just happened to switch around the order after #1052 went in.

I noted early that I conflated stuff from my build system with changes in #1052. To clarify, we extended `find_package` to search through a .gitmodules file for dependencies and then consume the dependency via `add_subdirectory`. As it turns out, we are not using EXCLUDE_FROM_ALL in our cmake extension. Furthermore, we are `include(CTest)` before we add range-v3 which seems to be what causes the tests to register with our project.

I don't know how to proceed (thoughts @apmccartney @dpacbach ) but it seems like the weirdness with order of module inclusion could bite other projects. Especially, if they are not aware of `EXCLUDE_FROM_ALL` (which I wasn't - @dpacbach thanks for that little jewel).

**Comment by david8dixon** [comment]
I still have not properly tested `find_package`. More on this later...

**Comment by david8dixon** [comment]
I think the solution is to set the testing to OFF by default. If you want subproject testing ON then specify it via a cache variable.

**Comment by dpacbach** [comment]
@david8dixon Makes sense to have subproject testing off by defaultf... were you planning to submit a PR for that or want me to?

**Comment by david8dixon** [comment]
I filed a PR. So It looks to me like `RANGE_V3_TESTS` is not a cache variable.

**Comment by david8dixon** [comment]
I can't find any closed PRs where this was resolved, but looking at master
the BUILD_TESTING behaviour that was causing problems is gone.

I think that this issue can be closed.
