### ISSUE TITLE
view::filter invokes predicate twice per element

### ISSUE THREAD

**Issue by dpacbach** [ericniebler/range-v3#1072]
```c++
int count = 0;
vector<int> v{1, 2, 3, 4, 5, 6}; 

vector<int> result = v | view::filter( [&]( int ) { 
                           count++;
                           return true;
                         } );

assert( count == 11 ); // ??
```

I could be missing something really basic here, but that was surprising to me when I noticed it.  Is that expected?

**Comment by CaseyCarter** [comment]
The range constructor of `std::vector` is required to perform at most one reallocation when given forward iterators.  To meet that requirement it must find the distance between its arguments, allocate space for that many elements, and then initialize the elements. For non-random access iterators, that results in two passes over the input range.

**Comment by dpacbach** [comment]
That makes sense, thanks for the explanation.
