### ISSUE TITLE
Duplicate test for zip_with?

### ISSUE THREAD

**Issue by slnovak** [ericniebler/range-v3#1083]
Hi. Just noticed potentially duplicated test code for [`zip_with`](https://github.com/ericniebler/range-v3/blob/ef9a650d4da87f02c5c079055e09017825c92fb3/test/view/zip.cpp#L101-L121).

Is this intentional?

Thanks!

**Comment by CaseyCarter** [comment]
I am happy to announce that `git blame` reveals this was not my fault ;)
