### ISSUE TITLE
ranges::for_each with temporary view

### ISSUE THREAD

**Issue by ddemidov** [ericniebler/range-v3#109]
This [example](https://gist.github.com/802fdc2503b1be181ad5) fails to compile with
```
for_each_view.cpp:42:5: error: no matching function for call to object of type 'const
      ranges::v3::for_each_fn'
    ranges::for_each(
    ^~~~~~~~~~~~~~~~
/home/demidov/work/range-v3/include/range/v3/algorithm/for_each.hpp:50:15: note: 
      candidate function [with Rng = ranges::v3::take_view<counter>, F = (lambda at
      for_each_view.cpp:44:13), P = ranges::v3::ident, I =
      ranges::v3::basic_iterator<ranges::v3::detail::counted_cursor<ranges::v3::basic_iterator<counter::cursor,
      ranges::v3::default_sentinel>, long>, ranges::v3::detail::counted_sentinel>,
      _concept_requires_49 = 42, $5 = 0] not viable: expects an l-value for 1st argument
            I operator()(Rng &rng, F fun, P proj = P{}) const
              ^
/home/demidov/work/range-v3/include/range/v3/algorithm/for_each.hpp:36:15: note: 
      candidate function template not viable: requires at least 3 arguments, but 2 were
      provided
            I operator()(I begin, S end, F fun_, P proj_ = P{}) const
              ^
1 error generated.
```

This works with 9932cd6c889a24e5d33462f7706568d86edbdf2b, but the question is, is the behavior intended/am I missing something?

**Comment by anders-sjogren** [comment]
This is in essence a duplicate of https://github.com/ericniebler/range-v3/pull/81 . See the conversation there for more info.

**Comment by ddemidov** [comment]
Thanks, I searched in issues for this, but forgot to look through pull requests!

**Comment by anders-sjogren** [comment]
You're welcome! As you see in the comments of #81 I believe that it would be nice to allow it as well.

**Comment by ericniebler** [comment]
> This works with 9932cd6

Um, how did you commit to my repo?

**Comment by ddemidov** [comment]
It's a fork :)

**Comment by ericniebler** [comment]
When I click that link, it takes me to <https://github.com/ericniebler/range-v3/commit/9932cd6c889a24e5d33462f7706568d86edbdf2b>. That is, it looks like a commit in my repo. I'm so confused.
