### ISSUE TITLE
Can't avoid __builtin_readcyclecounter

### ISSUE THREAD

**Issue by mikezackles** [ericniebler/range-v3#1094]
When building for aarch64 with the Android NDK r19c version of clang, `__builtin_readcyclecounter` fails with an illegal instruction at runtime:
`mrs x0, pmccntr_e10`

I was going to file a bug upstream, but I noticed this from the clang docs:
"Query for this feature with __has_builtin(__builtin_readcyclecounter). Note that even if present, its use may depend on run-time privilege or other OS controlled state."

So it seems like it might be a bug to assume that this is going to work if `__has_builtin` succeeds.

Perhaps it would be sufficient to allow the user to define RANGES_CPU_ENTROPY manually to disable this?

**Comment by CaseyCarter** [comment]
I'm going to burninate the "entropy-gathering" code from `utility/random.hpp`; it's not worth the bother to try to provide non-deterministic seeding for platforms with a broken `std::random_device`.

> Perhaps it would be sufficient to allow the user to define `RANGES_CPU_ENTROPY` manually to disable this?

I have absolutely no idea what I was thinking when I didn't put the `__builtin_readcyclecounter` detection inside `#ifndef RANGES_CPU_ENTROPY`. 🤷‍♂️ I suppose it won't matter after it's gone.

**Comment by mikezackles** [comment]
:dragon:

**Comment by CaseyCarter** [comment]
Closed by #1097.

**Comment by mikezackles** [comment]
Many thanks for the quick fix!

**Comment by CaseyCarter** [comment]
> Many thanks for the quick fix!

It wasn't that quick, considering that I said I was going to make this change in #769 in January of 2018. But you're welcome ;)
