### ISSUE TITLE
[docs] List of sentinels with a different type

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#110]
It would be useful (to me) to have a small section in the documentation listing the ranges / views whose sentinels have a different type.

**Comment by ericniebler** [comment]
Why?

**Comment by gnzlbg** [comment]
For those ranges / views the `RANGES_FOR` macro is necessary.

**Comment by ericniebler** [comment]
The list could change as more efficient optimizations occur to me. I don't want to be constrained by the docs. If you're using range-v3, you should probably be using `RANGE_FOR`. That's not ideal, I know.

**Comment by gnzlbg** [comment]
I meant it as a documentation of an implementation detail subject to change, not as part of the library API. For example I've realized that when the range-based for works for random access iterators, I can add OpenMP pretty easily, whereas when I need to use the RANGE_FOR macro this becomes more problematic.
