### ISSUE TITLE
`view_adaptor::base` method const overload

### ISSUE THREAD

**Issue by apmccartney** [ericniebler/range-v3#1115]
I noticed this afternoon that the `view_adaptor` CRTP's `base` method is overloaded for `const`-ness, where the `const` overload returns a const reference to the underlyng range.

My understanding is that views are subject to a set of semantics along the lines of those for pointers and/or iterators. With an iterator, the `const`-ness of the iterator instance is orthogonal to the `const`-ness of the indirected values. This overload violates those semantics.

This behavior may have been intentional, so please excuse me if I've overlooked a subtlety.

**Comment by tower120** [comment]
But it seems, that the main reason for this - is that all(?) views, that have some cache inside (like `remove_if`, `drop_while`) - have non-const(!) only iterators/sentinels. For example, `remove_if::begin()` is non-const only.

**Comment by CaseyCarter** [comment]
> the main reason for this - is that all(?) views, that have some cache inside (like `remove_if`, `drop_while`) - have non-const(!) only iterators/sentinels

This. See #385 for a voluminous discussion.
