### ISSUE TITLE
Uniform namespace conventions between Meta and Range/utility/Meta

### ISSUE THREAD

**Issue by Manu343726** [ericniebler/range-v3#113]
I'm trying to make Range work bootstrapping Meta into it first, instead of having (maintaining) both copies of the same library. My idea is to make this change least intrusive possible. Given the current `meta.hpp` file in range, what I'm doing is: 

``` cpp
#if defined(BIICODE)
#include <meta/meta.hpp>
#else
#include <type_traits>
#include <initializer_list>
#include <range/v3/utility/nullptr_v.hpp>
#include <range/v3/utility/static_const.hpp>
...
```

The dependency works perfectly, but I'm not able to compile since Meta and Range are using different namespaces to declare/define Meta features. Relying on sorcery like `#include` inside a nested namespace is not a solution for me, neither for you I guess (Ignoring that trick would potentially generate name issues with STL things etc).

Maybe we can study the effort neccesary to unify both naming conventions.

**Comment by gnzlbg** [comment]
@Manu343726 see [pull request 105](https://github.com/ericniebler/range-v3/pull/105) and the discussion there. 

In a nutshell keeping range-v3 dependency free outweighs the cost of keeping meta in sync.

**Comment by ericniebler** [comment]
Here's how I imagine this could work:

* I add meta.hpp and meta_fwd.hpp from the meta project to range/v3/third_party/meta.
* I \#include meta_fwd.hpp in range_fwd.hpp
* range_fwd.hpp does:
  ```cpp
  namespace range {inline namespace v3 { namespace meta = ::meta; } }
  ```
* range/v3/utility/meta.hpp simply \#includes meta/meta.hpp (and range_fwd.hpp)
* The CMakeLists.txt adds range/v3/third_party as an include directory *unless* you're building with biicode (right?)

I confess I don't know how biicode works. My naive assumption is that if meta.hpp is not found in the include path, that biicode will pull it in. That could be way off base.

Let me know what you think of this.

**Comment by ericniebler** [comment]
@gnzlbg There's proto-0x, but it has a dependency on Boost. :-( The other utilities in range/v3/utility are useful for many things, but few of them are as feature-complete at their Boost equivalents, or offer the guarantees that the Boost components do.

**Comment by gnzlbg** [comment]
What about versioning? IIRC in the old pull request CMake just checks if
there is a "recent enough" meta in the include path and if it isn't it gets
the latest meta from github (or a specific meta version via commit-hash or
version tag).

How does biicode handle versioning and how would the meta version be
specified? E.g. supposing one checks out an old commit from range-v3, would
the according at-that-time-used version of meta be found or pulled?

**Comment by ericniebler** [comment]
Good point. I guess only the version of range-v3 from biicode should use meta from biicode. I assume @Manu343726 knows the required CMake magic to make that happen. @Manu343726 ?

**Comment by gnzlbg** [comment]
@ericniebler I have been using the variant and concept checking ~~without any~~ with really minor [*] problems. I just love the variant and its implementation (the recursive union is genius, you should write a post about it, it would be awesome for learning how to use meta too). 

[*] All macros in range-v3 are "NAMESPACED_" except e.g. concept check macros, so I namespace them my self and then undefine those from range-v3 for use in my programs. 

But that's it, I actually have been keeping less of an eye on meta because I killed it as a dependency as I found myself needing some other range-v3 utilities. So I just have a header file where I include the range-v3's meta and put it in its own namespace.

**Comment by gnzlbg** [comment]
@ericniebler if proto-0x were to target only conformant C++11/14 compilers, would it still need the boost dependency (except for the e.g. Boost.Fusion/Boost.Range... extensions?)?

> I add meta.hpp and meta_fwd.hpp from the meta project to range/v3/third_party/meta.

There is also the possibility of "starting" by just moving meta out of utility into include/meta. That way one can use meta in range-v3 as if it were an installed library, but its code is _still_ in the range-v3 repo (`git mv` should preserve the history). It doesn't solve the problem of using meta from its own repo, but it is a start, and those users that install range-v3 can use meta in their own projects without pulling the whole range-v3 library since it would be in their include path.

**Comment by ericniebler** [comment]
> if proto-0x were to target only conformant C++11/14 compilers, would it still need the boost dependency (except for the e.g. Boost.Fusion/Boost.Range... extensions?)?

Yeah, it uses some of Boost.PP and Boost.MPL and maybe some other stuff. I could replace MPL with Meta, but the Boost.PP dependency is a tough one. I can't actually remember what needs PP. Maybe that could be revisited.

> moving meta out of utility into include/meta

That's a better idea.

**Comment by Manu343726** [comment]
Each biicode block has a `biicode.conf` file with settings such as parent block version, block include paths, and in this case a `[requirements]` entry with the explicit versions of the dependencies you want. See our [docs](http://docs.biicode.com/c++/dependencies.html#modifying-the-version-you-depend-on). 

For example, here's part of the `biicode.conf` file of our [Boost.Coroutine example](http://docs.biicode.com/c++/examples/boost.html#boost-coroutine):

```
[requirements]
    biicode/boost: 7
```
That means the example block depends on the `biicode/boost`  block (The block which sets up Boost) version 7. [We have tags too](http://docs.biicode.com/c++/dependencies.html#depending-on-a-tagged-version) if you like.

Finally there are tracks, similar to git branches. These aim to maintain multiple versions of a library. Following with the Boost example:

``` cmake
[requirements]
    biicode/boost(1.56.0): 2
```
Now the example depends on the Boost block track which sets up Boost 1.56.0 (Default is 1.57.0), version 2 of that block.

About CMake black magic, we have a `BIICODE` global cmake variable to check easily if we are running a biicode build. These are the only `CMakeLists.txt` changes I have on my range-v3 fork:

``` cmake
if(BIICODE)
    ADD_BIICODE_TARGETS()

    add_definitions(-DRANGE_V3_EXTERNAL_META_BIICODE)

    string(REPLACE " " ";" TARGET_CXX_FLAGS         ${CMAKE_CXX_FLAGS})
    string(REPLACE " " ";" TARGET_CXX_FLAGS_DEBUG   ${CMAKE_CXX_FLAGS_DEBUG})
    string(REPLACE " " ";" TARGET_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE})     

    target_compile_options(${BII_LIB_TARGET} INTERFACE ${TARGET_CXX_FLAGS}
                           $<$<CONFIG:Debug>:${TARGET_CXX_FLAGS_DEBUG}>
                           $<$<CONFIG:Release>:${TARGET_CXX_FLAGS_RELEASE}>)

    return()
endif()
```

Then inside `include/range/v3/utility/meta.hpp`:

``` cpp
#ifndef RANGES_V3_UTILITY_META_HPP
#define RANGES_V3_UTILITY_META_HPP

#if defined(BIICODE) && defined(RANGE_V3_EXTERNAL_META_BIICODE)
//Trust the deps manager and decouple Meta development.
//See biicode.conf [includes] entry to understand the path.
#include <meta/meta.hpp>

#else
```

Where `meta/meta.hpp` is an include mapped to the biicode dependency.

**Comment by ericniebler** [comment]
And what would it look like if meta.hpp moved to include/meta (with a forwarding header in range/utility/v3/meta.hpp for back-compat) as I describe above? I apologize that I don't have time to read biicode's docs or grok the cmake magic right now. But if you made a pull request, I'd take it.

**Comment by Manu343726** [comment]
My main problem are the namespaces, not the include itself. Biicode knows how to handle includes (Even you can specify how to map that includes, that's what I'm actually doing). 
Don't worry, I'm taking this time explaining such things only to make you understand my changes. I'm glad to do all the job. It's only that I never accept changes that I don't fully understand on any project of mine, that's the reason of my long explanations/references. Whenever you can/want to, take a time to look at them.

**Comment by ericniebler** [comment]
Was my suggestion to use namespace aliases unsatisfactory?

**Comment by Manu343726** [comment]
Nope. It leads to "*No template named meta::...*"-like errors. I tried with this too:

``` cpp
namespace ranges
{
    inline namespace v3
    {
        namespace meta
        {
            using namespace ::meta;
        }
    }
}
```
But does not work though. "*Invalid use of undefined template*" both on Clang and GCC. I will push my fork tomorrow, maybe we can better analyze this if we look at the different alternatives together.

**Comment by ericniebler** [comment]
I guess you didn't know what I meant, so I just went ahead and did it.

**Comment by Manu343726** [comment]
Thanks a lot, it's working. Now I have to use the full `<manu343726/meta/include/meta/meta.hpp>` since `<meta/meta.hpp>` hides the possible mapping. But it works perfectly with an `#ifdef BIICODE` enclosing the include guards. I feel Range looks better after this refactor, there's no difference between Meta and the Meta dependency inside Range, independently that dep is resolved via biicode or the sources directly.

**Comment by ericniebler** [comment]
There are a lot of files that \#include <meta/meta.hpp>. I'd prefer if you didn't add \#ifdef BIICODE and the full <manu343726/meta/include/meta/meta.hpp> to every one. That's ugly. Better if that logic appeared in only one place.

**Comment by Manu343726** [comment]
It appears in one place only, the `meta.hpp` file. [See](https://github.com/Manu343726/range-v3/commit/279920626695cf0676ca246bff5d55d869050776)

**Comment by ericniebler** [comment]
I like the `ignore.bii` suggestion better. It feels like less of a hack. Thanks!

**Comment by Manu343726** [comment]
Ok, squashed and ready. Thanks Eric.

**Comment by anders-sjogren** [comment]
It seems there is a drawback with having meta in the include dir of ranges: I can no longer `-Iranges/include` if I also want to include the full meta, since it will include that as well. I thought the main reason for having an empty include dir with only the name of the current project (=ranges) (instead of having the ranges include dir (named meta) right in the ranges dir) is to not accidentally includes some folder that might clash with some other project that I want to use. 

It might be possible to work-around using symlinks or .biiignore or the like, but it might be worth considering.

**Comment by ericniebler** [comment]
What does, "if I also want to include the full meta" mean? This version of meta.hpp is character-by-character identical to the one in its own repo.

**Comment by Manu343726** [comment]
I mean the full include path. Note without biicode ignore file I have to write the full path to the `meta.hpp` file on biicode, that is `manu343726/meta/include/meta/meta.hpp`. With `ignore.bii` + mapping there's no need since we mapped `meta/meta.hpp` includes to the above. That's what the `[path]` entries in `biicode.conf` do.

**Comment by anders-sjogren** [comment]
I think Eric's input might be on my note which I realized was a bit unclear and thus deleted before it got replied on. I'm sorry if it brought confusion. Please disregard it.

**Comment by anders-sjogren** [comment]
Note to self: think first, then write... ;-)

**Comment by Manu343726** [comment]
Ok, that explains it. I was doing Ctrl + F in chrome and saying "WTF he's talking about?" :)
