### ISSUE TITLE
No "head" view? 

### ISSUE THREAD

**Issue by melg8** [ericniebler/range-v3#1134]
Why there is such view as tail, but no mirrored view as head? Which would be like "Given a source range, return a new range without the last element."  I mean, is it because nobody were interested in creating one, or there is some more deep reason, why it shouldn't exist?
I've encountered case where i have container of bytes, and last byte contain crc8 checksum of previous bytes. So with "head" view i could accumulate checksum on all but last element and compare it with last one.

**Comment by tower120** [comment]
There soon will be `drop_last()`.  https://github.com/ericniebler/range-v3/pull/1112
```
auto head = drop_last(1);
```

**Comment by melg8** [comment]
That's great! But then why tail_view is not implemented in terms of drop_view? Isn't it duplicated code?

**Comment by tower120** [comment]
Have no idea. I don't see why it needed in the first place, since you have drop(1).

**Comment by ericniebler** [comment]
> why tail_view is not implemented in terms of drop_view?

Because `tail` can skip one element in its `begin()` member without caching and retain its amortized O(1) complexity, but `drop` has to cache the begin position, which has Implications.

**Comment by ericniebler** [comment]
> Why there is such view as tail, but no mirrored view as head?

In functional programming, "tail" is everything but the first, and "head" is the first. I think `drop_last` is what you're looking for.
