### ISSUE TITLE
Allow actions to strore references/pointers

### ISSUE THREAD

**Issue by tower120** [ericniebler/range-v3#1136]
Actions which accept values as parameters, currently highly inefficient by design. All passed values to action, required to be stored as value. That's **greatly** reduces their efficiency. **And** forbids use of move-only objects.
```cpp
std::list<HeavyObject> list;       // What if HeavyObject move-only?

void foo(const HeavyObject& obj){
     list |= action::remove(obj, pred);   
     // I don't want obj to be copied !!
     // Maybe there is even no obj in list !   
}
```
----
I propose following:
  * store passed rvalues/rvalue references as values.
  * store passed references / const references as pointers.

Distinguish between const T& and T&& with this:

http://coliru.stacked-crooked.com/a/a54daa2b7933e5c4
```cpp
    template<class T>
    void g(const T&){
        std::cout << "T&" << std::endl;
    }
    
    // or std::is_rvalue_reference_v<T> || !std::is_reference_v<T>
    template<class T, typename = std::enable_if_t< !std::is_lvalue_reference_v<T> >>  
    void g(T&&){
        std::cout << "T&&" << std::endl;
    }
```

We'll make concept trait so it don't look so ugly.

----

Dangling.

Storing pointers/references introduce situations were action may outlive stored value pointer. That's true. But I think, considering the fact, that most actions applied here and now, benefits greatly overweight potential "safety". 

Besides that's not something unique to C++. Range as pair of iterators may become invalid by the same reason.

**Comment by ericniebler** [comment]
I am opposed to changing something like lifetime based on something as ephemeral as an expression's value category. Consider:

```
template <Semiregular Pred = ranges::less>
auto sort_and_unique(Pred pred = {}) {
  return action::sort(pred) | action::unique; // Oops!
}
```

Possibly there should be a protocol like how `std::bind` uses `std::ref` through which users can communicate what things should be stored by reference. But I feel that storing by value is the correct default, and that users should have to explicitly opt in to storing by reference.

**Comment by tower120** [comment]
OFFTOPIC ON

> ...  something like lifetime based on ...

What is, "lifetime based", in terms of C++? Ownership based?

>  Consider:
> ```
> template <Semiregular Pred = ranges::less>
> auto sort_and_unique(Pred pred = {}) {
>   return action::sort(pred) | action::unique; // Oops!
> }
> ```

Purely matter of habit:
```cpp
template <Semiregular Pred = ranges::less>
auto sort_and_unique(Pred pred = {}) {
   // could be std::move, getting reference, etc. 
   // Anything typed often in nearby code becomes unnoticed.
   return action::sort(std::ref(pred)) | action::unique; 
}
```

There is simply no language "stack" lifetime monitor/control facilities, to induct (not just deduct) such things.

But maybe its just me, because I against `safe_iterator` / `dangling` too. Now I can't do this in one line https://github.com/tower120/range_tagged_view#viewtag, even if I can prove that it will not dangle.

OFFTOPIC OFF

----

> Possibly there should be a protocol like how std::bind uses std::ref through which users can communicate what things should be stored by reference. 

In C that protocol called pointers... If not null issues (assert is not an option? :) )...

Standard reference_wrapper will probably work. I didn't like the fact that they have ununiform "makers", but with deduction guides it became ok-ish.

_If it would be possible to have user-defined UTF-8 prefix operator :) ..._

**Comment by ericniebler** [comment]
> ```c++
> template <Semiregular Pred = ranges::less>
> auto sort_and_unique(Pred pred = {}) {
>    // could be std::move, getting reference, etc. 
>    // Anything typed often in nearby code becomes unnoticed.
>    return action::sort(std::ref(pred)) | action::unique; 
> }
> ```

This is more obviously (to me) a dangling reference. That's why I prefer making it explicit.

> > Possibly there should be a protocol like how std::bind uses std::ref through which users can communicate what things should be stored by reference.
> 
> In C that protocol called pointers... If not null issues (assert is not an option? :) )...

Taking the address of something is also an explicit opt-in to unsafe code. But no part of range-v3 should be accepting pointers and implicitly dereferencing them. When I instantiate `vector<int*>`, I expect to get back `int*`'s, not `int&`'s. And using pointers as an explicit opt-in was not what you were suggesting.

**Comment by tower120** [comment]
Ok. No pointers. Initially suggested proposal bad for safety reasons.

So what -  `std::ref`?

**Comment by tower120** [comment]
In order for `std::ref` to work, all "range adaptor objects" must not unwrap reference_wrappers. I'll make special bind_back (analogous to std::bind_front),  which does not call std::invoke internaly, thus leaving reference_wrappers unwrapped; and replace all internal "range adaptor objects" binds with it.

Besides that, "mostly", views/actions should work with `std::ref` as is.

**Comment by tower120** [comment]
Since actions already work with `std::ref`. I close this issue.
