### ISSUE TITLE
Add ends_with as an algorithm

### ISSUE THREAD

**Issue by cjdb** [ericniebler/range-v3#1144]
C++20 adds `starts_with` and `ends_with` as member functions to `basic_string`. I think `ends_with` would be a useful refactoring of `mismatch(x | view::reverse, y | view::reverse).in2.base() == end(y)`.

**Comment by johelegp** [comment]
I'd like to have a go at implementing this.

**Comment by cjdb** [comment]
Silly me forgot that `equal` expects both ranges to have the same distance. I'll make another issue to track `starts_with` when I'm ready to commit.

**Comment by cjdb** [comment]
Silly me forgot that `equal` expects both ranges to have the same distance. I'll make another issue to track `starts_with` when I'm ready to commit.
