### ISSUE TITLE
std map conversion issues with latest 1.0-beta branch

### ISSUE THREAD

**Issue by voivoid** [ericniebler/range-v3#1145]
Hi!

The following code sample

```
#include "range/v3/view.hpp"
#include "range/v3/range/conversion.hpp"

#include <map>

int main()
{
    auto r1 = ranges::view::indices( size_t{ 100 } );
    auto r2 = ranges::view::zip( r1, r1 );

    std::map<size_t, size_t> m = r2; // error
    r2 | ranges::to<std::map<size_t, size_t>>; // error
}
```

doesn't compile with latest 1.0-beta branch. But it compiled fine before c9d18a1 commit.

Tested with clang 8.0 and gcc 8.2.1

The issue looks similar to https://github.com/ericniebler/range-v3/issues/1141

**Comment by ericniebler** [comment]
Thanks for reporting these. We'll probably have a long tail of these bugs. The assumption that the difference type is a built-in integral is pernicious and pervasive. Keep filing 'em and I'll keep squashing 'em.

**Comment by voivoid** [comment]
Fixed. Thank you for your really great work.
