### ISSUE TITLE
Concept support for non-movable types

### ISSUE THREAD

**Issue by cartec** [ericniebler/range-v3#115]
`ranges::Destructible<std::mutex>()` is `false`. In fact *none* of the concepts in range-v3 accept non-movable types. The fundamental issue is in the implementation of `detail::models_`:

    template<typename...Ts, typename Concept,
             typename = decltype(std::declval<Concept &>().template requires_<Ts...>(std::declval<Ts>()...))>
        auto models_(Concept *) ->
        // ...

The type(s) of `std::declval<Ts>()...` is/are `Ts&&...`. All of the concept definitions, for example `Destructible` (Note that I have fixed the declaration by putting the open brace on the first line where all True Scotsmen put open braces):

    struct Destructible {
        template<typename T>
        auto requires_(T) -> decltype(
            concepts::valid_expr(
                concepts::is_true(std::is_destructible<T>{})
            ));
    };

have member function templates `requires_` that accept parameters *by value*. If `T` is a non-movable type then a `T&&` cannot initialize a `T` and substitution failure occurs for the `requires_` function template declaration before even getting into the meat in the trailing return type.

I believe the fix for this is simply to change the signatures of the `requires_` templates to accept forwarding references, i.e., replace `T` with `T&&`. Yes, this is scary. However, since `models_` always instantiates `requires_` with xvalue arguments, changing the parameter declarations from `T` to `T&&` does not alter the type deduced for `T`. A cursory examination of the 102 occurrences of `requires_` in the source revealed no other code interacting with the `requires_` declarations, so I am reasonable sure nothing is going to pass lvalue argument types to a `requires_` function and wreak all sorts of havoc with forwarding reference parameter declarations.

Does this sound reasonable? Should I prepare a patch?

**Comment by ericniebler** [comment]
I prefer to do the investigation. There is much subtlety in this code. In particular, the template parameter to `requires_` is always specified explicitly, so you can't use a forwarding reference. Thanks for raising the issue.

**Comment by cartec** [comment]
According to N4296, "A *forwarding reference* is an rvalue reference to a cv-unqualified template parameter." whether the template parameter types are deduced or explicitly specified is immaterial; the point is that reference collapsing will do the right thing. A function parameter `T&& t` will have the type `int&&` when `T` is specified to be `int` or `int&&`, and `int&` when `T` is specified as `int&`. When evaluated as an expression, the parameter is an lvalue of type `int` in either case.

The only observable effect I can see from the change is that `decltype(t)` will be `int&&` instead of `int`. None of the concept definitions I looked at used `decltype` on a parameter. All tests pass with the changes in place, and my `forward_list<std::atomic<int>>` instantiation doesn't complain to me anymore that `std::atomic<int>` is neither Destructible nor Allocatable.

**Comment by ericniebler** [comment]
Interesting. Then feel free to pay no attention to me. :-) Would you be willing to submit a pull request?

**Comment by ericniebler** [comment]
Fixed in d2f2fc3
