### ISSUE TITLE
Add contains algorithm

### ISSUE THREAD

**Issue by johelegp** [ericniebler/range-v3#1152]
In C++20, the associative containers got a `contains()` member that return whether the value of the `Key` argument is stored in the container. It'd be great if this were generalized, similar to `boost::algorithm::any_of_equal`. If it's okay, I already got one written that just needs to be ported to Range v3.

**Comment by tower120** [comment]
`contains()` search by Key and return bool.

Why not make something like
`find(Key) -> std::optional<iterator>`
`find_if(Pred) -> std::optional<iterator>`
?

Well, of course, `find` already occupied...

**Comment by johelegp** [comment]
Here's what I'm actually proposing. Part of the generalization includes searching by the range's value and not some key.

---

```C++
template <class I, class S, class T, class Proj = ranges::identity>
bool contains(I first, S last, const T& value, Proj proj = {});
template <class R, class T, class Proj = ranges::identity>
bool contains(R&& r, const T& value, Proj proj = {});
```
_Constraints:_

For the first form:
- `ranges::InputIterator<I>` is `true`,
- `ranges::Sentinel<S, I>` is `true`, and
- `ranges::IndirectRelation<ranges::equal_to, ranges::projected<I, Proj>, const T*>`
  is `true`.

For the second form:
- `ranges::InputRange<R>` is `true`, and
- `ranges::IndirectRelation<ranges::equal_to, ranges::projected<ranges::iterator_t<R>, Proj>, const T*>`
  is `true`.

_Returns:_ `true` if `ranges::invoke(proj, *i) == value` is `true`
for some iterator `i` in the range [`first`, `last`),
and `false` otherwise.

_Complexity:_
At most `last - first` comparisons and applications of the projection.

---

Recently, I changed it to use return a result type. Your proposed form was rejected in #171.

---

```C++
template <class I>
struct contains_result {
    bool value;
    I in;

    explicit constexpr operator bool() const noexcept
    {
        return value;
    }

    template <class I2>
    constexpr operator contains_result<I2>() const&;

    template <class I2>
    constexpr operator contains_result<I2>() &&;
};

template <class I, class S, class T, class Proj = ranges::identity>
contains_result<I> contains(I first, S last, const T& value, Proj proj = {});
template <class R, class T, class Proj = ranges::identity>
contains_result<ranges::safe_iterator_t<R>> contains(
    R&& r, const T& value, Proj proj = {});
```
_Constraints:_

For the first form:
- `ranges::InputIterator<I>` is `true`,
- `ranges::Sentinel<S, I>` is `true`, and
- `ranges::IndirectRelation<ranges::equal_to, ranges::projected<I, Proj>, const T*>`
  is `true`.

For the second form:
- `ranges::InputRange<R>` is `true`, and
- `ranges::IndirectRelation<ranges::equal_to, ranges::projected<ranges::iterator_t<R>, Proj>, const T*>`
  is `true`.

_Returns:_ `{true, i}` for the first iterator `i` in the range [`first`, `last`)
for which `ranges::invoke(proj, *i) == value` is `true`,
and `{false, last}` otherwise.

_Complexity:_
At most `last - first` comparisons and applications of the projection.

```C++
template <class I>
template <class I2>
constexpr contains_result<I>::operator contains_result<I2>() const&;
```
_Constraints:_ `ranges::ConvertibleTo<const I&, I2>` is `true`.

_Returns:_ `{value, in}`.

```C++
template <class I>
template <class I2>
constexpr contains_result<I>::operator contains_result<I2>() &&;
```
_Constraints:_ `ranges::ConvertibleTo<I, I2>` is `true`.

_Returns:_ `{value, std::move(in)}`.

**Comment by tower120** [comment]
> ```cpp
>     template <class I2>
>     constexpr operator contains_result<I2>() const&;
> 
>     template <class I2>
>     constexpr operator contains_result<I2>() &&;
> ```

What is this for? As I understand, this is the reason why you don't use `std::optional`...

> Complexity:
> At most last - first comparisons and applications of the projection.

O(n) complexity is not what `std::map::contains` offers. Since `std` containers have some kind of "interface" for `find` methods from the one side, and does not provide `std::find` specialization, from the other side - why not try using container's O(log(n)) version first, then fallback to algorithm O(n) version?

_By the way, this "optimisation" can be used for `find`,  `lower_bound`, `upper_bound`, etc._

**Comment by johelegp** [comment]
The conversion operators allow the algorithm taking ranges to be implemented in terms of those taking iterators. `contains(std:array{0, 1, 2, 3}, 1)` returns `contains_result<std::ranges::dangling>` and is implemented in terms of the corresponding iterator version which returns `contains_result<std::array<int, 4>::iterator>`. All works thanks to the conversion operators.

As for why not using std::optional. That was rejected in #171. It seems that using result types is the proper way to go about it.

Why not use the `contains` member function of the ranges? This algorithm is a generalization. For the associative containers they take a key, but in this case they'd take their value type (key/value pair). Also, the points raised in #962 apply.

**Comment by tower120** [comment]
> As for why not using std::optional. That was rejected in #171. 

For me, it looks like that the reason was to just leave range-v3 std-compatible.

>  Also, the points raised in #962 apply.

Ok, name clashes is convincingly enough. The only way then - to allow container implementors to make specialized overloads for `std::find`, `ranges::find` etc...

**Comment by tower120** [comment]
You know, I have similar algorithm in my project (called `ranges_::find`). I tried to rename it to `ranges_::contains` and it looks like it does not match it's name:

```cpp
    std::optional found = contains(m_sequences, &sequence, get_ptr);
    assert(found);
    m_sequences.erase(*found);
```

... Maybe `lookup`? Or other not occupied `find` synonym.

```cpp
    std::optional found = lookup(m_sequences, &sequence, get_ptr);
    assert(found);
    m_sequences.erase(*found);
```
