### ISSUE TITLE
Add view::take_last

### ISSUE THREAD

**Issue by johelegp** [ericniebler/range-v3#1162]
# `view::take_last`

The name `view::take_last` denotes
a range adaptor object (http://wg21.link/range.adaptors#def:range_adaptor_object).
For some subexpressions `E` and `N`,
the expression `view::take_last(E, N)`
is expression-equivalent to `view::drop_exactly(E, ranges::size(E) - N)`,
except that `E` is only evaluated once.

**Comment by johelegp** [comment]
Thanks @BRezzin.

**Comment by CaseyCarter** [comment]
To be perfectly clear: This issue is closed by #1218.
