### ISSUE TITLE
About optimizing fill / generate

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#119]
It seems that `fill(rng, value) <=> generate(rng, [&](){ return value; })`.

In this case, if:
- `ValueType<Rng>` is `TriviallyCopyAssignable`, and
- `Rng` is `RandomAccessRange`, 

then for `fill`:
- either `value` is of type `ValueType<Rng>` or a `ValueType<Rng>` can be constructed from it [0] 

and for `generate`:
- iff the `Generator` is `const` (and lambdas are `const` by default), then:
- a single `ValueType<Rng>` can be constructed and `fill` could be used [0].

The complexity of `generate` says that _exactly_ `std::distance(first, last)` invocations of the generator will be performed but I think that if the `Generator` is `const` this behavior is not observable (otherwise UB) and thus a single invocation of the generator is allowed.

Libc++ does not perform this optimization so maybe this isn't allowed, but if it is I can submit a patch.

Maybe it would be better to implement a new algorithm (e.g. `assign`?) that takes either a value or a generator, and has these optimizations, and then implement `fill` and `generate` on top of it. I find it weird that `fill` and `generate` don't have the same interface.

[0] If the implementation of `fill` were to use the `copy` algorithm this should perform a `memmove` if `copy` were optimized for `TriviallyCopyAssignable` types. Libc++ `fill_n` has also a `memset` optimization.

**Comment by cartec** [comment]
For `generate`, the `Generator` being immutable does not imply that it is `Regular` and always returns the same value. E.g., the lambda in:
```
int some_ints[42];
std::mt19937 engine{};
std::uniform_int_distribution<int> dist{};
ranges::generate(some_ints, [&]{ return dist(engine); });
```
is not mutable, but most definitely NOT a Regular function.

**Comment by ericniebler** [comment]
@cartec right.

**Comment by sean-parent** [comment]
There is a large difference between const and regular as Eric points out -
 you would also be adding the requirement that the result of generator is
copyable. It may not be, or it may be copyable but the result of copy
changes the semantics of generate. examples:

// const but not regular
    int x = 0;
    const auto f = [&](){ return ++x; };

// regular but not copyable
    const auto f = [](){ return make_unique<int>(42); };

// regular, copyable, but copying changes semantics of generate
   const auto f = [](){ return make_shared<int>(42); };

**Comment by gnzlbg** [comment]
TIL that an immutable generator doesn't mean that it is side-effect free. Thanks.
