### ISSUE TITLE
Ranges which take a sentinel should be constructable from {Iterator, Sentinel}

### ISSUE THREAD

**Issue by ThePhD** [ericniebler/range-v3#1192]
As the title states, the idea is that a range that is an `Iterator` + `Sentinel` should be constructible for a `Iterator` + `Sentinel`. Consider, for a moment, an `unbounded` view passed to an alrogithm which takes an input and an output range. Code that pulls apart the `unbounded` into begin and end will not be able to reconstruct it generically, because the expectation is that all ranges take their begin and end:

```
template <typename InputRange>
auto my_generic_algorithm( InputRange input_range ) {
     auto input_first = ranges::cbegin(input_range);
     auto input_last = ranges::cend(input_range);
     /* move input_first forward a few times ... */
     // signal to user how much we've moved forward / consumed
    return ForwardRange( std::move(input_first), std::move(input_last) );
}
```

The above code is broken by `unbounded`, which is fixed by Pull Request #1190.

The real-world use case is the code I am working on for text. I am new at working with ranges so I did solicit some help, but I very well may be wrong in how I work with it: here [here is an example of compiling code with range-v3 that does not compile when it is handed an `unbounded` view](https://github.com/ThePhD/phd/blob/master/include/phd/text/utf8.hpp#L230).

`unbounded` with these algorithms is a useful way to signal that you have allocated enough space for the output, and thusly can have the compiler fold away all the `if` blocks that check if we have reached the end of the output range because `it == sentinel` is always `false` for a sentinel of `unreacheable`.

Thoughts?

**Comment by ericniebler** [comment]
Construction from an iterator and a sentinel is not a required expression of the `ForwardRange` concept, and it shouldn't be. There are many such ranges that do not and cannot provide such a constructor; e.g., C-style arrays and `std::array`.

**Comment by ThePhD** [comment]
(Oops, sorry; I meant to put InputRange and input_range in the function signature, but the same point you raised still stands).

I think it's fair enough I don't expect it to work with C-style arrays or `std::array` or C-style strings. But even if the requirement is not part of the concept, I think that `unbounded` -- and other `unreachable`-sentinel-based views and ranges like it -- should be constructible from {Iterator, Sentinel}. Is there a general objection to offering this functionality on views where it is applicable?

**Comment by ericniebler** [comment]
> Is there a general objection to offering this functionality on views where it is applicable?

That's not how this works. I don't add things because I can't find a reason not to. I add things selectively based on need and on design integrity.

There is no _generic_ code that can use the functionality you are proposing because that expression is not part of any concept. And if you are writing _non_-generic code, you don't want to specify an extra parameter that will always be ignored.
