### ISSUE TITLE
Cannot compile tests with GCC 7.3 and C++17

### ISSUE THREAD

**Issue by chissg** [ericniebler/range-v3#1196]
The following `cmake` command configures range-v3 in such a way that building the tests is unsuccessful on Scientific Linux 7.6 with GCC 7.3.0 (not the native compiler) and C++17:
```
cmake3 -DCMAKE_BUILD_TYPE=Debug -DRANGES_CXX_STD=17 \
-DRANGES_VERBOSE_BUILD=ON -DRANGE_V3_DOCS=OFF \
-DRANGE_V3_EXAMPLES=OFF -DRANGE_V3_HEADER_CHECKS=OFF \
-DRANGE_V3_TESTS=ON \
-DCMAKE_INSTALL_PREFIX=~/tmp/range-v3 ../../sources-ref/range-v3
```
There are several failures, please see the attached
[range-v3-cmake.log](https://github.com/ericniebler/range-v3/files/3187312/range-v3-cmake.log) and [range-v3-build.log](https://github.com/ericniebler/range-v3/files/3187198/range-v3-build.log).
These failures occur with master, but can be reproduced with `0.5.0` with patch 0c20dbf05973368339aeae0c4e106560e2dcf76b.
The build is successful if I configure with the only change from above being `-DRANGES_CXX_STD=14`.
Is there something I'm missing here, or is this a real issue?

**Comment by chissg** [comment]
I should add that compilation is successful with `0.4.0`.

**Comment by CaseyCarter** [comment]
The log suggests a bug in `std::is_trivial`, which sounds like https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85723, but that bug should be in *all* versions of GCC. Could you try patching line 131 of box.hpp:
```diff
             template<typename T, typename = meta::if_<
-                meta::strict_and<std::is_empty<T>, std::is_trivial<T>>>>
+                meta::strict_and<std::is_empty<T>, std::is_trivially_copyable<T>,
+                    std::is_trivially_default_constructible<T>>>>
             constexpr box_compress box_compression_(int)
             {
                 return box_compress::coalesce;
             }
```
and see if that fixes it?

**Comment by chissg** [comment]
@CaseyCarter Can confirm that problem is *not* observed in GCC 6.4, but *is* observed with GCC 8.2 (all other things being equal). Can confirm the patch above fixes the issue with both compilers. Thank you for the quick diagnosis!
