### ISSUE TITLE
Overload algorithms for temporaries and just return void

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#120]
Consider:

```c++
std::vector vec(10);
copy(view::ints(0, 10), begin(vec));
```

As users of `range-v3` know, this won't compile because `copy` returns an iterator to the input range; since the `view::ints` passed to `copy` is a temporary range, the iterator returned would contain a dangling reference. Awesomely, `range-v3` prevents us from making this mistake by refusing to compile broken code. Yeah!

However, is the user of `range-v3` really doing anything unsafe at all? Well, it isn't using the return value... so what about:  

`Algorithm: You gave me a temporary? Then you get nothing (void)!` 

That is, if _any_ of the range arguments passed to an algorithm is a temporary, that algorithm returns `void`. 

Some geniuses from the future might find a better return type, and `void` can be changed to anything else in a backwards compatible way. This remains safe, incurs minimal implementation, interface, and proposal overhead, and if the `erase_if` proposal is accepted, there would be precedence about returning `void` and delegating the problem of finding a better return type to our future selves.

**Comment by ericniebler** [comment]
I've considered this myself. This inability of the ranges to accept temporaries is a pain point for users. But it might be surprising that a simple reorg of code can change an algorithm's return type. I'm not *strongly* opposed, I don't think, but I'd also like to brainstorm other solutions. 

Another option would be to define `ranges::begin` and `ranges::end` to do something "special" when passed an rvalue `Iterable`. (After all, these functions are unsafe when used with rvalues too.) One option is to return the iterator wrapped in something that makes it not-an-iterator. You would need to call some method (with an obvious-sounding name like `unsafe` or `trust_me_i_am_a_professional`) to access the iterator. All the algorithms could then safely return exactly what they currently return, since any potentially dangling iterators would be wrapped.

The problem with this is that rvalue iterables never model `Iterable` since `begin` doesn't return an iterator. And then the algorithms wouldn't accept rvalue not-`Iterables`. The solution for that would be to define `unsafe_begin` and `unsafe_end` that unconditionally returns the (unwrapped) iterators. (These, in fact, would become the customization points. They would use ADL to dispatch (unqualified) to `begin` and `end` under the covers.) Then `ranges::begin` and `ranges::end` would be implemented in terms of `unsafe_begin` and `unsafe_end`, wrapping iterators when called with rvalue iterables. The `Iterable` concept would be defined in terms of `unsafe_begin` and `unsafe_end`.

A minor variation of the above would be to leave `begin` and `end` alone, and define `safe_begin` and `safe_end` wrapper functions.

Thoughts?

**Comment by gnzlbg** [comment]
> But it might be surprising that a simple reorg of code can change an algorithm's return type. 

It will be surprising and it won't result in broken programs, one could think about improving error messages here like returning some type that when used in any way it would just tell the user at compile-time _why_ his code doesn't compile. 

> A minor variation of the above would be to leave begin and end alone, and define safe_begin and safe_end wrapper functions. [...]
>
>A minor variation of the above would be to leave begin and end alone, and define safe_begin and safe_end wrapper functions.

I don't think I understand this.  If I pass an rvalue range to an algorithm I won't get an iterator back, but an iterator wrapper. That is, the return type of the algorithm "has changed". Furthermore, the generic implementation of the algorithm must at least contain a layer of indirection to wrap rvalue iterators, something like: 

```c++
pair<I, I> iterator_version(I, I, ...) { /* ... */ }
pair<I, I> range_version(lvalue_range r...) {  
    return iterator_version(begin(r), end(r), ...); 
}
pair<ItWrapper<I>, ItWrapper<I>> range_version(rvalue_range r...) {
   auto r = iterator_version(begin(r), end(r), ...); // this is fine right?
   return wrap_iterators(r);
}
```

But then I cannot do anything with the `pair<ItWrapper<I>, ItWrapper<I>>`, those iterators are effectively dead. So I'd rather get a `pair<DeadIterator, DeadIterator>` and a nicer compile-time error.

Maybe you could sketch some pseudocode about how you think an algorithm can be implemented using `safe_begin` and `safe_end`? (I prefer to not change `begin` and `end`). I'm pretty sure I'm not following your thoughts correctly.

**Comment by ericniebler** [comment]
I would expect there to be a wrapper like:

```cpp
template<typename I>
struct dangling_iterator {
private:
    I it_;
public:
    dangling_iterator() = default;
    dangling_iterator(I i);
    I get_unsafe() const;
};
```

Then `safe_begin` would be:

```cpp
template<typename Rng>
meta::if_<std::is_lvalue_reference<Rng>,
    range_iterator_t<Rng>,
    dangling_iterator<range_iterator_t<Rng>>>
safe_begin( Rng && rng ) {
    return ranges::begin(rng);
}
```

We could define a helper alias template:

```cpp
template<typename Rng>
using range_safe_iterator_t = decltype(safe_begin(std::declval<Rng>()));
```

Finally, a range-based algorithm overload:

```cpp
template<typename I, typename S,
    CONCEPT_REQUIRES_(IteratorRange<I,S>())>
pair< I, I >
some_algorithm( I first, S last ) {
    // ...
}

template<typename Rng,
    CONCEPT_REQUIRES_(Iterable<Rng>())>
pair< ranges_safe_iterator_t<Rng>, ranges_safe_iterator_t<Rng> >
some_algorithm( Rng && rng ) {
    return some_algorithm( begin(rng), end(rng) );
}
```

Now, when calling `some_algorithm` with an rvalue iterable, either you don't care about the return type (in which case it can be safely ignored), or else you want to use the iterators and believe the iterators to in fact *not* be dangling (say, if the rvalue range is itself a simple pair of iterators), in which case you can say:

```cpp
auto first = some_algorithm( rvalue_range_expr{...} ).first.unsafe_get();
```

Does that help?

**Comment by ericniebler** [comment]
I would expect there to be a wrapper like:

```cpp
template<typename I>
struct dangling_iterator {
private:
    I it_;
public:
    dangling_iterator() = default;
    dangling_iterator(I i); // implicit!!!
    I get_unsafe() const; // explicit!!!
};
```

Then `safe_begin` would be:

```cpp
template<typename Rng>
meta::if_<std::is_lvalue_reference<Rng>,
    range_iterator_t<Rng>,
    dangling_iterator<range_iterator_t<Rng>>>
safe_begin( Rng && rng ) {
    return ranges::begin(rng);
}
```

We could define a helper alias template:

```cpp
template<typename Rng>
using range_safe_iterator_t = decltype(safe_begin(std::declval<Rng>()));
```

Finally, a range-based algorithm overload:

```cpp
template<typename I, typename S,
    CONCEPT_REQUIRES_(IteratorRange<I,S>())>
pair< I, I >
some_algorithm( I first, S last ) {
    // ...
}

template<typename Rng,
    CONCEPT_REQUIRES_(Iterable<Rng>())>
pair< ranges_safe_iterator_t<Rng>, ranges_safe_iterator_t<Rng> >
some_algorithm( Rng && rng ) {
    return some_algorithm( begin(rng), end(rng) );
}
```

Now, when calling `some_algorithm` with an rvalue iterable, either you don't care about the return type (in which case it can be safely ignored), or else you want to use the iterators and believe the iterators to in fact *not* be dangling (say, if the rvalue range is itself a simple pair of iterators), in which case you can say:

```cpp
first = some_algorithm( make_range(first, last) ).first.unsafe_get();
```

Does that help?

**Comment by gnzlbg** [comment]
>Does that help?

Yes, a lot. I like it. When I call it with an lvalue range everything just works as of now, and when I call it with an rvalue range I have to explicitly use `unsafe_get`. 

Do `safe_begin`/ `safe_end` remain an implementation detail of `range-v3` (i.e. they are not customization points)? 

In the following, did you meant to use `safe_begin`/`safe_end` or in the rvalue case is a pair of safe iterators constructible from a pair of normal iterators?

```c++
template<typename Rng,
    CONCEPT_REQUIRES_(Iterable<Rng>())>
pair< ranges_safe_iterator_t<Rng>, ranges_safe_iterator_t<Rng> >
some_algorithm( Rng && rng ) {
    return some_algorithm( begin(rng), end(rng) );  // Did you meant safe_begin/safe_end here?
}
```

If not it would seem that the only thing that needs to be changed is the return types of the "range" algorithms and the lvalue references of the arguments to forwarding references.

**Comment by ericniebler** [comment]
> Do `safe_begin`/ `safe_end` remain an implementation detail of range-v3 (i.e. they are not customization points)?

They are neither implementation details nor customization points. They're just utility functions in the `ranges` namespace.

> In the following, did you meant to use `safe_begin`/`safe_end` or in the rvalue case is a pair of safe iterators constructible from a pair of normal iterators?

The later. Notice that a `dangling_iterator<I>` is implicitly convertible from an `I`. So a pair of them will also be implicitly convertible. I haven't tried it, but it should all just work.

**Comment by ericniebler** [comment]
FWIW, I just tried this scheme with `ranges::for_each` and it seems to work.

**Comment by gnzlbg** [comment]
I keep my fingers crossed.

**Comment by ericniebler** [comment]
Fixed in e98504e

**Comment by gnzlbg** [comment]
Awesome!

**Comment by gnzlbg** [comment]
@ericniebler after playing with the rvalue ranges for a couple of weeks, I think I just like `safe_begin` and `safe_end` too much. 

So much that I'd rather have `begin` -> `unsafe_begin`, and `safe_begin` -> `begin`.

Consider the current broken code:

```c++
#include <range/v3/all.hpp>
#include "./simple_test.hpp"
int main() {
    using namespace ranges;
    auto it2 = begin(view::iota(0, 20) | view::remove_if([](int i) { return i % 2 == 0; }));
    CHECK(*(++it2) == 3);  // KABOOM
    return 0;
}
```

With `safe_begin` that won't even compile and the mistake is made clear (cannot do this and that on a `dangling` iterator). With the current implementation an assertion will be triggered in debug mode (which is better than nothing). 

I don't know the implications of this tho... all algorithms/view/actions will probably need to switch to `unsafe_begin` internally, among others, so it seems like a very large change.

**Comment by ericniebler** [comment]
`begin`/`end` shouldn't accept rvalues. I just made that change. I don't feel that they should return `dangling`. I'd rather it was just an error. So I see no need for `unsafe_begin`/`unsafe_end`.

**Comment by gnzlbg** [comment]
That's even better thanks!
