### ISSUE TITLE
narrowing conversion warning with `size()->int`

### ISSUE THREAD

**Issue by raccoonmonk** [ericniebler/range-v3#1207]
The following code:
```
#include <range/v3/all.hpp>
#include <QList>

int main() {
	QList<double> vec {0, 1, 0};
	auto rng = vec | ranges::view::filter([](double value) {
		return value > 0;
	});
	return 0;
}
```
gives a warning `narrowing` with g++ 7.3.0
and pretty much the same but as an error with clang 8.0.0
on the range-v3 tag 0.5.0
```
/include/range/v3/view/all.hpp:48: warning: narrowing conversion of ‘(& ranges::v3::CPOs::{anonymous}::size)->ranges::v3::_size_::fn::operator()<QList<double>&>((* & t))’ from ‘int’ to ‘ranges::v3::size_type_t<QList<double>::iterator> {aka long long unsigned int}’ inside { } [-Wnarrowing]
                     return {begin(t), end(t), size(t)};
                                               ~~~~^~~
```
All Qt containers' `size` methods return `int`.
Looks somewhat related to #1145

**Comment by ericniebler** [comment]
There is no such code on the master branch, so I'm assuming this is fixed.

**Comment by raccoonmonk** [comment]
Right.
I couldn't build with master at that moment. I thought it's unstable so I had chosen the tag 0.5.0.
Everything is good on master now, thanks.
