### ISSUE TITLE
[bug] A View that isn't Viewable

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#1209]
By definition every type that models View should also model ViewableRange. However I have run into a very strange situation where GCC claims this isn't the case. Checking View passes via static_assert or run-time assert (or implicitly when checked on a function argument). Checking ViewableRange fails for all cases.

If I have the following function:
```cpp
template <::ranges::ViewableRange t>
void foobar(t &&) {}
```
And I put in a temporary of my type, I get:
```
/home/hannes/devel/seqan3/test/unit/range/view/view_translate_test.cpp: In instantiation of 'void nucleotide_view_translate_single_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = seqan3::rna15]':
/home/hannes/devel/seqan3/test/unit/range/view/view_translate_test.cpp:228:1:   required from here
/home/hannes/devel/seqan3/test/unit/range/view/view_translate_test.cpp:73:11: error: cannot call function 'void foobar(t&&) [with t = seqan3::detail::view_translate_single<ranges::ref_view<std::vector<seqan3::rna15> > >]'
     foobar(vec /*| view::complement */| view::translate_single(translation_frames::FWD_FRAME_0));
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hannes/devel/seqan3/test/unit/range/view/view_translate_test.cpp:39:6: note:   constraints not satisfied
 void foobar(t &&) {}
      ^~~~~~
In file included from /home/hannes/devel/seqan3/submodules/range-v3/include/range/v3/range/concepts.hpp:21:0,
                 from /home/hannes/devel/seqan3/include/seqan3/std/ranges:21,
                 from /home/hannes/devel/seqan3/include/seqan3/core/concept/core_language.hpp:19,
                 from /home/hannes/devel/seqan3/include/seqan3/alphabet/concept.hpp:23,
                 from /home/hannes/devel/seqan3/include/seqan3/alphabet/nucleotide/concept.hpp:15,
                 from /home/hannes/devel/seqan3/include/seqan3/alphabet/nucleotide/all.hpp:15,
                 from /home/hannes/devel/seqan3/test/unit/range/view/view_translate_test.cpp:14:
/home/hannes/devel/seqan3/submodules/range-v3/include/range/v3/range/concepts.hpp:400:5: note: within 'template<class T> concept const bool ranges::_eager_::ViewableRange<T> [with T = seqan3::detail::view_translate_single<ranges::ref_view<std::vector<seqan3::rna15> > >]'
     CPP_def
                                                                  ^        
```
Which is obviously not really helpful; the macros completely obfuscate what's going on.

If I change the function to:
```cpp
template <typename t>
concept bool MyViewableRange = ::ranges::Range<t> &&
                              (::ranges::ForwardingRange_<t> || ::ranges::View<::ranges::detail::decay_t<t>>);

template <MyViewableRange t>
void foobar(t &&) {}
```

Then everything is fine. But cccording to GCC's intermediate code the range's concept macro literally resolves to the same code:
```
inline namespace _eager_
{ 
template<typename T> concept bool ViewableRange = Range<T> && (ForwardingRange_<T> || View<detail::decay_t<T>>); 
}
```

Any hints how I can further debug this?

**Comment by BRevzin** [comment]
Can you provide a minimal, complete, reproducible example? Maybe a godbolt link or something?

**Comment by ericniebler** [comment]
Agree, without a repro I can't help.

I _will_ say that I have often seen weird concepts Heisen-bugs like this when code has accidentally introduced a cyclic requirement. This is most common with converting constructors that accidentally become copy or move constructor candidates. 

So, for instance, instead of:

```c++
struct my_view {
  template <View V>
  my_view(V v) {... }
};
```

you are better off doing:

```c++
struct my_view {
  template <class V>
    requires (!Same<V, my_view>) && View<V>
  my_view(V v) {... }
};
```

There's a 50/50 chance something like this is lurking in your code somewhere. There's an outside chance the problem is in range-v3 itself, but I've tried to squash all such bugs.

**Comment by h-2** [comment]
Indeed, it was cyclic requirements check once again. I always already have guards set up against the "self-type" like you mention above, but the current case was even a little more awkward :expressionless: 

This constructor triggers the problem:
```cpp
    template <typename rng_t>
        requires !std::Same<remove_cvref_t<rng_t>, view_translate_single> &&
                 std::ranges::ViewableRange<rng_t> &&
                 std::Constructible<urng_t, std::ranges::all_view<rng_t>> 
    view_translate_single(rng_t && _urange)
        : urange{std::view::all(std::forward<rng_t>(_urange))}
    {}
```

This workaround does not trigger the problem:
```cpp
    template <typename rng_t>
        requires !std::Same<remove_cvref_t<rng_t>, view_translate_single> &&
                 std::ranges::ViewableRange<rng_t> &&
                 std::Constructible<urng_t, ranges::ref_view<std::remove_reference_t<rng_t>>>
    view_translate_single(rng_t && _urange)
        : urange{std::view::all(std::forward<rng_t>(_urange))}
    {}
```
So it's guarding against the own type is not enough, something in view::all also leads to cyclic checks. 

Curiously (and in contrast to previous issues that led me to check the constructors for bugs), it's totally possible to create the object using the first constructor above. The object created behaves exactly as expected, it just doesn't model ViewableRange.

¯\_(ツ)_/¯
