### ISSUE TITLE
Conan package could always be compatible, as it's header-only

### ISSUE THREAD

**Issue by Quincunx271** [ericniebler/range-v3#1212]
Being a header-only library, it should be possible to make the range-v3 conan package always compatible with any compiler/architecture/build type/etc. There's no need to re-package range-v3.

Care has to be taken with `write_basic_package_version_file`, though, as it requires matching architecture, which a header-only library does not need. Either we could upgrade to CMake 3.14 and use the `ARCH_INDEPENDENT` option, we can use a custom versioning system, or we can use a hack and set `CMAKE_SIZEOF_VOID_P` to nothing before calling `write_basic_package_version_file`.

**Comment by ericniebler** [comment]
Sounds reasonable. I'm not a Constant expert. PR's welcome.

**Comment by Quincunx271** [comment]
Do you know where the conan package is being created and uploaded to the conan repository? I had a quick look at the package defined there, and it looks as if it's already using the `ARCH_INDEPENDENT` option, despite `ARCH_INDEPENDENT` not being used in the root CMakeLists.txt here.

**Comment by Quincunx271** [comment]
I'll submit the PR later, but note-to-self on what needs to be changed: `package_info` -> `package_id` (looks like a typo)

https://github.com/ericniebler/range-v3/blob/6924fd8c1768ef5becb29aa2a86d155c74a4208b/conanfile.py#L40-L41
