### ISSUE TITLE
Extra call to filter function

### ISSUE THREAD

**Issue by FloopCZ** [ericniebler/range-v3#1220]
It appears that filtering function is called two times for the last element when converting a `filter_view` of at least two elements to a vector. Consider the following code:

```c++
#include <range/v3/all.hpp>
#include <iostream>
#include <vector>

int main()
{
    std::vector<int> a = {1, 2};
    int i = 0;
    std::vector<int> rng =
      ranges::view::filter(a, [&](int v) {
        std::cout << "i++: " << i++ << ", " << "v: " << v << std::endl;
        return true;
    });
}
```
Output:
```
i++: 0, v: 1
i++: 1, v: 2
i++: 2, v: 2
```

However, if the underlying container contains only a single element, this does not happen:
```c++
    ...
    std::vector<int> a = {1};
    ...
```
Output:
```    
i++: 0, v: 1
```
Is this the expected behavior?

I have encountered this when migrating [HiPipe](https://github.com/iterait/hipipe) to `v1.0-beta` and I was getting a strange double free (not yet sure if it is related, probably not since v0.5.0 does the same thing).

Thank you and have a great day!

**Comment by FloopCZ** [comment]
One more strange thing. When the filtering function always returns `false` instead of `true`, the filtering function is called only twice:
```c++
        ...
        return true;
        ...
```
Output:
```
i++: 0, v: 1
i++: 1, v: 2
```

**Comment by FloopCZ** [comment]
ok, I know where the problem is. :slightly_smiling_face: 

When `libstdc++` detects that the iterators from which to construct e.g. `std::vector` are of forward category, it first computes the distance between them, then preallocates the memory and afterwards it iterates through the iterators once again and dereferences and stores the values to the vector. The reason why the first element of the range is not repeated and the second one is repeated is that `remove_if` and `filter` cache the `begin()` value, so when iterating the range once over, they don't need to check the predicate on the first element.

Is this the expected behaviour or is there a recommended way to handle this? Thanks!

**Comment by ericniebler** [comment]
That sounds right, and it's expected.

It's long been on my to-do list to offer users a way of explicitly demoting the category of a range. That might come in handy in this situation: if the range were Input and not Forward, then you would only get a single traversal.

I don't have time to work on that right now, but it wouldn't be hard to knock together your pen adaptor that does this. If you do, please make a PR.

Note that you will replace a single vector allocation with an exponential growth strategy. That may or may not be a perf win in your case.

**Comment by ericniebler** [comment]
Closing this since the behavior is expected.
