### ISSUE TITLE
ranges::to doesn't convert view-of-view to container-of-container

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#1223]
I discussed this briefly with @cor3ntin who was also author of the wg21 paper. He said you discussed this before and were reluctant about it?

We are currently switching our code from using the implicit conversions (good riddance), but it breaks in the cases where we have two-dimensional input. Although conversion to container happens *mostly* in unit tests, there are a few cases where it happens in library code and I don't see an immediate reason why it shouldn't be possible.

having looked at the code, an extra member of `detail::to_container` like this should suffice:

```cpp
template<typename Rng, typename ToContainer>
friend auto operator|(Rng &&rng, fn<ToContainer>(*)(to_container)) ->
    CPP_broken_friend_ret(container_t<ToContainer, Rng>)(
        requires InputRange<Rng> &&
            !ConvertibleToContainer<Rng, container_t<ToContainer, Rng>> &&
            InputRange<range_reference_t<Rng>>
            /* && possible to call to on element type*/)
{
    return std::forward<Rng>(rng) | view::transform([] (auto && elem)
    {
        return std::forward<decltype(elem)>(elem) | to<range_value_t<ToContainer>>;
    }) | to<ToContainer>;
}
```

There were a few issues, like missing forwards and circular include  dependencies when including view/transform.hpp in range/conversion.hpp so I wanted to ask if you would accept such a PR before I spend more time on it.

I think it would be quite useful, especially since there is no obvious workaround for people moving from the range-v3 code to c++20 code.

**Comment by ericniebler** [comment]
I agree it's a problem, both with range-v3 and with the `ranges::to` proposal. I would prefer `ranges/conversion.hpp` to not include `view/transform.hpp`. We probably need some hidden `transform_iterator` for exclusive use by `ranges::to`.
