### ISSUE TITLE
Allow views to store values as std::reference_wrapper s

### ISSUE THREAD

**Issue by tower120** [ericniebler/range-v3#1234]
Views can store heavy values inside. Let's make them `std::ref` aware.

```cpp
auto rng1 = vi | view::remove(std::ref(str));  // must act as rng2
auto rng2 = view::remove(vi, std::ref(str));   // std::ref(str) stored as is inside remove(_if)_view
```

In order to achieve this:
1) All related constrains must be `std::ref` aware.
2) All `view::bind`s inside must NOT unwrap `std::reference_wrapper`.
3) Views must internally unwrap values/predicates before use.

**Comment by ericniebler** [comment]
I don't really like generic code that treat some types as special. It always ends up biting when users expect the type to be handled like the others. Reference wrappers and nested binds are a great source of subtle complexity. I'd rather encourage alternate solutions. In your example, I would replace the `view::replace` with a `view::replace_if` that takes a predicate that has captured `str` by reference.
