### ISSUE TITLE
Latest Concept Syntax For VS 2019 Preview 4

### ISSUE THREAD

**Issue by IkoLogs** [ericniebler/range-v3#1240]
Hi

I am testing Range/Concept library for use on a project.

I have read most documentation i could find and several blogs

But seems the latest Syntax for concepts  does not match any info 
cause its old and syntax moved on.

Was using Tick library, till i had issues with its flexibility.

I am looking for latest syntax to declare concept 

CPP_def
(
	template<class T>
	concept CPT_Test(T),
	requires(T&& t)
	(
		typename T::tango
	)

);

Tried the above , but does not compile on MSVC.

I also tried using the CPP_template

Also dont have a clue if i need to use CPP_ret

CPP_template(class Iter, class Sent, class Comp = /*...some_default..*/)
(requires Sentinel<Sent, Iter>)
void my_algorithm(Iter first, Sent last, Comp comp = Comp{})
{
	// ...
}

Looking for latest syntax to define concept, and to use it in either class or function declaration.
Most of the examples i could find in range library show how concept  works with template function, but hardly did i see any example of concept use on template class definition.

I am familiar with Concept TS syntax, previously used it on gcc, but i almost clue less as to what the current syntax is for concepts in Range library.

By the way excellent work with the library, I have my hopes hope that Range Concepts , and also planning to us Meta library.

Thanks very much

**Comment by ericniebler** [comment]
With the just-released 0.9.0, you should be able to:

```c++
CPP_def(
  template(class T)
  concept CPT_Test,
    ranges::type< typename T::tango >
);
```

Feel free to reopen if that doesn't work for you.
