### ISSUE TITLE
[question] Runtime performance 150 times slower than STL & bad compilation times

### ISSUE THREAD

**Issue by blockspacer** [ericniebler/range-v3#1241]
Is it still true https://aras-p.info/blog/2018/12/28/Modern-C-Lamentations/ ? (see section about range-v3) 
Compilation times and bad performance seems critical for range-v3.

**Comment by ericniebler** [comment]
I know unoptimized runtime performance matters to some people, but range-v3 was not designed with that in mind. If you care about unoptimized runtime, don't use range-v3.

Build times have come down ~20%, but they are still a pain point.
