### ISSUE TITLE
Suggestion: view::from_tuple

### ISSUE THREAD

**Issue by Yitzi2** [ericniebler/range-v3#1247]
In addition to the view adaptors present, it might be useful to have a view that iterates through the elements of a tuple.  The type returned by dereferencing would thus have to be a variant of reference_wrappers (which could then be piped through a view::transform that calls std::visit, although an alternative transform view that automatically applies std::visit to variants might be worth considering as well).

**Comment by tower120** [comment]
I think this wil became obsolete with upcoming builtin C++ "tuple foreach" facilities...

Hence, probably not worse trying...

**Comment by ericniebler** [comment]
This feels like hammering a screw. Ranges are for homogeneous sequences. I see where you're going with this, and it's not completely unreasonable, but it is also not something I want range-v3 to provide out of the box.
