### ISSUE TITLE
compile error when copying from one std::array to another

### ISSUE THREAD

**Issue by wickedmic** [ericniebler/range-v3#1250]
I  was trying to copy one std::array to another (simplified version):

```c++
    std::array<int, 2> a;
    std::array<int, 2> b;
    ranges::copy(a, b);
```
[https://godbolt.org/z/94G4Bw](https://godbolt.org/z/94G4Bw)

But this is rejected by clang and gcc with a note that some requirement was not satisfied.

I'd argue that the example above should compile fine. Or am I missing something?

Changing the `std::array` to a C-array like this:
```c++
    int a[2];
    int b[2];
    ranges::copy(a, b);
```
makes the code compile.

I tried clang and gcc in various versions, but the problem seems not compiler dependent.
When I encountered the problem is was using the commit 25deec48. After updating to the current master (commit cc767352) the error is still there.

I also tried to figure out what requirement was causing this error. In the gcc output I found this:
```
template<class T, bool Enable>using enable_if_t = meta::invoke<concepts::detail::identity<typename std::enable_if<Enable, void>::type>, T>
[with
    T = ranges::detail::in_out_result<int*, std::array<int, 2> >;
    bool Enable =(
        (   
            (   
                ((bool)ranges::InputRange<std::array<int, 2>&>)
                &&  
                ((bool)ranges::WeaklyIncrementable<std::array<int, 2> >)
            )   
            &&  
            ((bool)ranges::IndirectlyCopyable<int*, std::array<int, 2> >)
        )   
        ||  
        concepts::detail::CPP_false((concepts::detail::Nil{}, concepts::detail::Nil()))
    )   
]
```
Judging by the names, I'd say both arrays satisfy input range, they are both incrementable (not sure about the 'weakly'), and both are copyable (again not sure about 'indirectly').

Well, that is all I got. I would still argue, that this should work. But maybe I'm missing something.

**Comment by ericniebler** [comment]
`std::array` is not incrementable; that is, you cannot do `++` on an instance of `std::array`. This – and the `IndirectlyCopyable` constraint – is telling you that the second argument to `ranges::copy` should be an output iterator.
