### ISSUE TITLE
Range-v3 failed to build due to errors C2559 C2672 C3313 C3536 C3517 C3539 C2338 C2893 C2780 C2440 with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [ericniebler/range-v3#1253]
Environment:
Windows Server 2016 + VS2017 + Range-v3 master branch latest srouce code.

Range-v3 failed to build due to errors C2559 C2672 C3313 C3536 C3517 C3539 C2338 C2893 C2780 C2440 with MSVC on windows. It can be first reproduced on master revision 0b9bd54 . Could you help have a look about this issue? Thanks in advance!

 1.git clone https://github.com/ericniebler/range-v3 D:\Range-v3\src
 2.Open a VS 2017 x86 command prompt as admin and browse to D:\Range-v3
 3.mkdir build_x86 && pushd build_x86
 4.cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DCMAKE_BUILD_TYPE=Release ..\src
 5.pop
 6.pushd build_x86
 7.msbuild Range-v3.sln /p:Configuration=Release /p:Platform=win32 /m /t:Rebuild

[log_x86_build.log](https://github.com/ericniebler/range-v3/files/3491289/log_x86_build.log)

Actual result:
D:\Range-v3\src\include\range/v3/functional/bind_back.hpp(70): error C2559: '_invoke_result_<void,const Fn&,CallArgs...,const Args...>::type ranges::detail::bind_back_fn_<Fn,Args...>::operator ()(CallArgs &&...) noexcept(<expr>) const': cannot overload a member function without ref-qualifier with a member function with ref-qualifier [D:\Range-v3\build_x86\test\view\view.zip.vcxproj]
D:\Range-v3\src\include\range/v3/functional/pipeable.hpp(109): error C2672: 'ranges::pipeable_access::impl_<Pipe>::pipe': no matching overloaded function found
D:\Range-v3\src\include\range/v3/functional/pipeable.hpp(109): error C2893: Failed to specialize function template 'auto ranges::view::view<ranges::detail::pipeable_binder<ranges::detail::bind_back_fn_<ranges::view::sample_fn::bind::<lambda_e14146e47b632caaaddd9327c2a1098c>,unsigned int,std::reference_wrapper<URNG>>>>::pipe(Rng &&,Vw &&,identity<enable_if<ranges::ViewableRange<Rng>&&ranges::Invocable<View&,Rng>||'function',void>::type>::invoke<concepts::detail::Nil>)' [D:\Range-v3\build_x86\test\view\view.sample.vcxproj]
error C3313: 'rng': variable cannot have the type 'void' [D:\Range-v3\build_x86\test\view\view.sample.vcxproj]
error C3536: 'rng': cannot be used before it is initialized [D:\Range-v3\build_x86\test\view\view.sample.vcxproj]
error C3517: 'Rng' an alias-declaration cannot have a type that contains 'auto' [D:\Range-v3\build_x86\test\view\view.sample.vcxproj]
error C3539: a template-argument cannot be a type that contains 'auto' [D:\Range-v3\build_x86\test\view\view.sample.vcxproj]
error C2338: Concept assertion failed : InputView<Rng> [D:\Range-v3\build_x86\test\view\view.sample.vcxproj]
error C2893: Failed to specialize function template 'identity<enable_if<ranges::InputRange<Rng>&&ranges::WeaklyIncrementable<O>&&ranges::IndirectlyCopyable<unknown-type,O>||'function',void>::type>::invoke<ranges::detail::in_out_result<if_then<ranges::ForwardingRange_<R>>::apply<unknown-type,ranges::dangling>,O>> ranges::cpp20_copy_fn::operator ()(Rng &&,O) const' [D:\Range-v3\build_x86\test\view\view.sample.vcxproj]
D:\Range-v3\src\test\view\sample.cpp(24): error C2780: 'identity<enable_if<ranges::InputIterator<I>&&ranges::Sentinel<S,I>&&ranges::WeaklyIncrementable<O>&&ranges::IndirectlyCopyable<I,O>||'function',void>::type>::invoke<ranges::detail::in_out_result<I,O>> ranges::cpp20_copy_fn::operator ()(I,S,O) const': expects 3 arguments - 2 provided [D:\Range-v3\build_x86\test\view\view.sample.vcxproj]
D:\Range-v3\src\test\view\sample.cpp(25): error C2440: '=': cannot convert from 'void' to 'int' [D:\Range-v3\build_x86\test\view\view.sample.vcxproj]

**Comment by spacelg** [comment]
Hi, 

Is there anyone looking at this issue? It can be still reproduced on latest master revision.

Thanks,
Lin

**Comment by ericniebler** [comment]
Have you read the README or the docs about how to configure your MSVC build for range-v3?
