### ISSUE TITLE
Extension header for is_range

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#126]
The trait `is_range ` fails for e.g. `boost::container::vector`, `boost::container::static_vector`, ... 

Maybe we could have an extensions directory to allow these containers to be used with the library, e.g.:

- in `range/v3/extensions/boost/container/vector.hpp` :

  ```c++
namespace ranges {

template <class T, class Alloc>
struct is_range<boost::container::vector<T, Alloc>> : std::false_type {};

}  // namespace ranges
  ```

- in `range/v3/extensions/boost/container/static_vector.hpp` :

  ```c++
namespace ranges {

template <class T, std::size_t capacity>
struct is_range<boost::container::static_vector<T, capacity>>
 : std::false_type {};

}  // namespace ranges
  ```

I don't really know why `is_range ` fails for `boost::container::vector` tho.

**Comment by ericniebler** [comment]
When you say, "The trait is_range fails for e.g. `boost::container::vector`", do you mean, it returns false? Because it should. It's a container, not a range.

**Comment by gnzlbg** [comment]
It returns positive :/

I have to specialize it for it to return false.

**Comment by ericniebler** [comment]
Figuring out why that is would be the first order of business.

**Comment by ericniebler** [comment]
Let's see what the Boost people say about [this](https://groups.google.com/d/msg/boost-developers-archive/q0BvrZwfX54/vBAlrOPhw-MJ)

**Comment by gnzlbg** [comment]
Thanks for figuring it out. I basically tried all the concepts from
LValueContainerLike up to is_range, and then in is_range i tried the
concepts up to here:
https://github.com/ericniebler/range-v3/blob/d2f2fc3f2fdc3847b0983768e31271dc06350bb5/include/range/v3/range_concepts.hpp#L387
and then I arrived at ContainerLike_ here:
https://github.com/ericniebler/range-v3/blob/d2f2fc3f2fdc3847b0983768e31271dc06350bb5/include/range/v3/range_concepts.hpp#L191
and then I gave up since I had a workaround and not enough time :/

**Comment by gnzlbg** [comment]
I'll try to check the other containers in `boost::container` and `boost::dynamic_bitset` since I also had the probelm with `boost::static_vector`(which I use _a lot_ throughout my code).

**Comment by ericniebler** [comment]
As I suspected, it's a bug in Boost.Container. A pretty bad one, actually. So `ranges::is_range` is doing the right thing, `boost::container::vector` is not. The fix is [here](https://github.com/boostorg/container/pull/25).

**Comment by gnzlbg** [comment]
Thanks. I'll use the workaround till this is (hopefully) fixed in the next release. Good to know that Ion knows already about this.
