### ISSUE TITLE
Combinatoric views -- doesn't compile

### ISSUE THREAD

**Issue by beojan** [ericniebler/range-v3#1268]
I'm trying to make views that iterate over all k-combinations of a range using `view_facade`. My code (attached) does not compile, and the errors are attached. Am I doing something obviously wrong?

[combinations.hpp.txt](https://github.com/ericniebler/range-v3/files/3525067/combinations.hpp.txt)
[test.cpp.txt](https://github.com/ericniebler/range-v3/files/3525068/test.cpp.txt)
[errors.txt](https://github.com/ericniebler/range-v3/files/3525078/errors.txt)

**Comment by ericniebler** [comment]
There's two subtle problems with your cursor. First, by defaulting the copy and move constructors, you suppress the compiler-generated copy and move assignment operators, so your cursor type is neither `copyable` nor `movable`. Second, `std::reference_wrapper` is not default-constructable, so neither is your cursor.

Delete the lines where you default the copy/move ctors, and change `std::reference_wrapper` to `ranges::reference_wrapper` (or simply `const Rng*`) and all should be well. There are other problems in your code, but after those changes, you should be able to work through the problems yourself.

Also, consider first posting your code to stackoverflow and tag with `#range-v3`. You'll get better turn-around, and I like to keep range-v3's bug tracker for range-v3 bugs and feature requests.

Thanks.
