### ISSUE TITLE
not enough arguments for function-like macro invocation 'CPP_PP_DECL_DEF', etc on VS2019

### ISSUE THREAD

**Issue by danielmrussell** [ericniebler/range-v3#1272]
Cannot build. Concepts.hpp chokes the process hard with a plethora or non-sense error messages like this.

Please help. Thank you!

**Comment by ericniebler** [comment]
Are you building with MSVC's new experimental preprocessor, as described in range-v3's docs?

**Comment by CaseyCarter** [comment]
As Eric says: this is a consequence of compiling without `/experimental:preprocessor`.

**Comment by danielmrussell** [comment]
Thanks. I tried to add /permissive- as stated in the documentation for install (I do not see any mention of /experimental:preprocessor there). However, I used the /permissive- option and that didn't work, strangely, despite MS docs to the contrary. I am on the latest release of MSVC.

I'm curious as to why this is not in the CMakeLists.txt of Ranges library itself?

For anyone else that runs into this problem, here was my solution:
```
            add_subdirectory("range-v3")
            if(MSVC)
                target_compile_options(
                    meta
                    INTERFACE
                    "/experimental:preprocessor"
                )
                target_compile_options(
                    concepts
                    INTERFACE
                    "/experimental:preprocessor"
                )
                target_compile_options(
                    range-v3
                    INTERFACE
                    "/experimental:preprocessor"
                )
            endif()
```
