### ISSUE TITLE
views::filter is not lazy

### ISSUE THREAD

**Issue by dokai** [ericniebler/range-v3#1293]
It seems that introducing `ranges::views::filter` into a pipeline breaks assumptions on laziness. This does not seem to affect the correctness of the results of the pipeline but makes it difficult and counter-intuitive to reason about the underlying behavior and performance aspects of the pipeline.

Several other issues seem potentially related:  #1090, #1220, #1254,

For example (https://wandbox.org/permlink/bwXBCF7x5oLbStva),
```cpp
#include <range/v3/all.hpp>
#include <iostream>
#include <vector>

auto isEven = [](int n) {
  std::cerr << "-> isEven(" << n << ")" << std::endl;
  return n % 2 == 0;
};
auto triple = [](int n) {
 std::cerr << "-> triple(" << n << ")" << std::endl;
 return n * 3;
};

int main() {    
  std::vector<int> numbers = {1, 2, 3, 4};

  auto rng = numbers
    | ranges::views::filter(isEven, triple)
    | ranges::views::take(1);

  // expectation: predicate and projection functions to be called twice
  // observed: filter is not lazy, pred/proj called on all input elements
  std::cerr << "filter + take + materialize (vector)" << std::endl;
  auto res = rng | ranges::to<std::vector>;
    
  // the result itself is correct
  std::cerr << std::endl << "result: " << ranges::views::all(res) << std::endl;
  std::cerr << "result size: " << res.size() << " capacity: " << res.capacity() << std::endl;


  // expectation: pred/proj not called for the tail of the input elements due to `take(1)`
  // observed: loop causes pred/proj to be redundantly called on the tail of the input
  //           (and appears to use cached state to avoid the pred/proj calls for the
  //           first two elems of the input due to the previous run).
  std::cerr << std::endl << "Looping over filter + take" << std::endl;
  for (const auto v : rng) {
    std::cerr << "loop value: " << v << std::endl;
  }    
}
```
produces
```
filter + take + materialize (vector)
-> triple(1)
-> isEven(3)
-> triple(2)
-> isEven(6)
-> triple(3)
-> isEven(9)
-> triple(4)
-> isEven(12)
-> triple(3)
-> isEven(9)
-> triple(4)
-> isEven(12)

result: [2]
result size: 1 capacity: 1

Looping over filter + take
loop value: 2
-> triple(3)
-> isEven(9)
-> triple(4)
-> isEven(12)
```

**Comment by ericniebler** [comment]
You're seeing a few different things interacting here, the biggest of which is that `std::vector` tries very hard to to only perform a single allocation when constructed from a range. If the `vector` constructor is passed forward iterators, it will use `std::distance(begin, end)` to precompute the size of the vector. That's one traversal. Then the range is traversed a second time to initialize all the elements.

Had the range been input (and not forward), then that extra step would be skipped, and you'd see only one traversal in the `std::vector` case.

This, by the way, is one of the reasons why I would like to add a range adaptor that demotes a range's category to input. However, forcing `std::vector`'s constructor to use an exponential allocation strategy is not necessary a performance win over traversing the sequence twice. YMMV.

The other artifact you're seeing is that these invocations only appear on the first traversal:

```
-> triple(1)
-> isEven(3)
-> triple(2)
-> isEven(6)
```

The `filter` view has amortized O(1) complexity when calling `begin()`. The first time you call it, it scans forward in the sequence to find the first element that satisfies the predicate _and it caches that position_. Subsequent calls to `begin()` can simply use the cached position. This, incidentally, is why the `filter` view cannot abide being `const`-qualified.

Hope that clears it up.
