### ISSUE TITLE
Opt-in traits for forwarding-range detection

### ISSUE THREAD

**Issue by morinmorin** [ericniebler/range-v3#1319]
It would be easier to specialize opt-in traits than to (manually) write `begin`/`end` overloads for rvalues. Why not use opt-in traits as a forwarding-range detection mechanism?

With traits, *forward-range* concept (bikeshed: I prefer a more descriptive name like *range-with-outliving-iterators*) looks something like 
```
(is_lvalue_reference_v<R> && range<R>) || 
has_outliving_iterators<R>::value
```

Then, the library can provide `begin`/`end` overloads for rvalue forwarding-ranges.

**Comment by ericniebler** [comment]
Your personal preference aside, this ship has sailed. Non-member `begin`/`end` is how C++20 spells this.

**Comment by morinmorin** [comment]
OK, I've also realized that the traits mechanism needs some changes to C++20 ranges::begin and so that's a no-go.

For the naming, "range-with-outliving-iterators" is just an example and what I would like is a name that is visually different enough from "forward range" (assuming the name of exposition-only concepts can be changed in the future standard if there is a convincing name).
