### ISSUE TITLE
Calling equal algorithm with infinite ranges doesn't fail to compile in static_assert

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#132]
I'm trying to understand why calling the `ranges::equal` algorithm with infinite ranges doesn't fail to compile inside the static assert in:  https://github.com/ericniebler/range-v3/blob/master/test%2Falgorithm%2Fequal.cpp#L282

In this situation, the overload of `equal` taking 2 ranges is called. In that overload, even tho the `view::unbounded` is not a `SizedIterable` (it is an infinite range), the `ranges::distance(view::unbounded(p))` should be instantiated (it is a run-time if), see: https://github.com/ericniebler/range-v3/blob/master/include/range/v3/algorithm/equal.hpp#L111 . If it is instantiated, it should fail to compile because `view::unbounded(p)` is infinite.

In fact, if I just get that out of the `static_assert` and put the result on its own variable:

```c++
// this compiles fine:
static_assert(std::is_same<bool, decltype(ranges::equal({1, 2, 3, 4}, ranges::view::unbounded(p)))>::value, "");
// this fails to compile:
auto c = ranges::equal({1, 2, 3, 4}, ranges::view::unbounded(p));
```

So why doesn't it fail to compile inside the `static_assert`? (If I make `equal`, `distance`, ... `constexpr`, then it does fail to compile inside the `static_assert`).

**Comment by ericniebler** [comment]
`decltype` of a function call expression does not need to instantiate the function template. Merely looking at the function signature is sufficient for determining the expression type. `decltype` of a function call expression is a special case -- I argued for it in [n3233](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2011/n3233.html), and this tweak was actually the last change to make it into C++11.

I'm uncertain why adding constexpr changes things. Constexpr is a complex beast. I don't pretend to understand it.

**Comment by pfultz2** [comment]
> I'm uncertain why adding constexpr changes things. Constexpr is a complex beast. I don't pretend to understand it.

Its a bug. Most compilers(such as gcc and clang) are too eager to instantiate templates when using constexpr. I generally have to use lots of workarounds to get things to be sane using constexpr(and I have yet to find a workaround for constexpr fix point combinators).

**Comment by gnzlbg** [comment]
`constexpr` also implies `inline` I always thought it was related but haven't tested that yet.

**Comment by gnzlbg** [comment]
@pfultz2 can you share some of the workarounds you use for this?

**Comment by pfultz2** [comment]
Basically, you need to make it depend on a template parameter in order to delay the instantiation. Usually, I use [`identity`](http://pfultz2.github.io/Fit/doc/html/always/) or [`always`](http://pfultz2.github.io/Fit/doc/html/always/) to do that.

For `identity` I just use a default template parameter:

```cpp
template<class T>
struct foo
{
    T x;
    template<class U, class Id=decltype(identity)>
    constexpr auto sum(U y)
    {
        return Id()(this->x) + y;
    }
};
```

And with `always` the default template parameter is not necessary:
```cpp
template<class T>
struct foo
{
    T x;
    template<class U>
    constexpr auto sum(U y)
    {
        return always(this->x)(y) + y;
    }
};
```
 You can see where I use it in places like [here](https://github.com/pfultz2/Fit/blob/master/fit/by.h#L68). 

Of course, for your case, I dont know why you wouldn't use overloading/static assert instead of a runtime if, but I am not that familair with the code.

**Comment by gnzlbg** [comment]
Thank you @pfultz2 that was very useful. 

I had a case with a pure type computation where I could just move the code that shouldn't be eagerly instantiated into a different function, and then use `decltype` from within the constexpr function.  

```c++
template<...> auto not_constexpr_function(...) { ... }

template<A = decltype(not_constexpr_function(...))>
constexpr auto my_fun(...) {  ... }
```

**Comment by gnzlbg** [comment]
BTW I reported it on llvm bugs and it seems that clang and gcc ~~are~~ _will be_ doing the right thing since constexpr functions ~~are~~ _will be_ required to be instantiated in unevaluated contexts, see Richard Smith's answer here: https://llvm.org/bugs/show_bug.cgi?id=23135.

**Comment by ericniebler** [comment]
That sucks.

**Comment by gnzlbg** [comment]
I've been fighting with these all day. This semantic change sucks hard, and it is a huge pain to debug.

 You basically have no idea why code breaks. You know something, somewhere, got instantiated and failed, and a different branch was taken. And you know that _far away_ a type is not what you expect. I've been trying for an hour to find out what is broken with libc++ and I can only suspect that the decltype in `__invokable_imp` does something different due to `__invoke` being constexpr:

```c++
template <class _Fp, class ..._Args>
struct __invokable_imp
    : private __check_complete<_Fp>
{
    typedef decltype(
            __invoke(_VSTD::declval<_Fp>(), _VSTD::declval<_Args>()...)
                    ) type;
    static const bool value = !is_same<type, __nat>::value;
};
```
but there is no way to get a full backtrace "from main" so to speak, so it is a game of trying to make it fail in such a way that the compiler spits something useful, and dump types here and there and put static asserts here and there till one figures it out.

It took me an hour to find out why single view did not model the Iterable concept if I made one destructor of `variant_data` explicitly defaulted instead of declare it to `{}`. 

The errors one get do not point to the problem at all.

**Comment by ericniebler** [comment]
Sympathies. Honestly, I appreciate the effort you're putting in, but I have to wonder if it's worth it. It seems we (as a community) are still working out the kinks in `constexpr` and learning its limitations. The libc++ `__invokable` debacle has convinced me that we should leave `constexpr` alone until things settle a bit. I would be *extremely* hesitant to merge a big `constexpr` change knowing the headaches it's likely to cause.
