### ISSUE TITLE
Build failure with C++20 mode on Visual Studio 2019 16.3 Preview 4.0

### ISSUE THREAD

**Issue by 0x8000-0000** [ericniebler/range-v3#1326]
FAILED: src/CMakeFiles/pretty_grades.dir/pretty_grades.cpp.obj
C:\PROGRA~2\MIB055~1\2019\Preview\VC\Tools\MSVC\1423~1.281\bin\Hostx86\x86\cl.exe  /nologo /TP  -IC:\Users\fiucha\source\repos\cppcon-ranges\external\lib\ranges\include /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MDd   /W4 /WX /D_USE_MATH_DEFINES /permissive- /experimental:preprocessor /wd5105 -std:c++latest /showIncludes /Fosrc\CMakeFiles\pretty_grades.dir\pretty_grades.cpp.obj /Fdsrc\CMakeFiles\pretty_grades.dir\ /FS -c C:\Users\fiucha\source\repos\cppcon-ranges\src\pretty_grades.cpp
C:\Users\fiucha\source\repos\cppcon-ranges\external\lib\ranges\include\range/v3/view/tail.hpp(84): error C2760: syntax error: unexpected token '(', expected 'expression'
C:\Users\fiucha\source\repos\cppcon-ranges\external\lib\ranges\include\range/v3/view/tail.hpp(103): note: see reference to class template instantiation 'ranges::tail_view<Rng>' being compiled
C:\Users\fiucha\source\repos\cppcon-ranges\external\lib\ranges\include\range/v3/view/tail.hpp(84): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\fiucha\source\repos\cppcon-ranges\external\lib\ranges\include\range/v3/view/tail.hpp(84): error C2059: syntax error: '('
C:\Users\fiucha\source\repos\cppcon-ranges\external\lib\ranges\include\range/v3/view/tail.hpp(84): error C2059: syntax error: '('
ninja: build stopped: subcommand failed.

The same code builds fine with "-std:c++17" instead of "-std:c++latest" and runs.

**Comment by 0x8000-0000** [comment]
This happens with 04018bb2af0a2f5b962e5842b93ee2894c12de56

**Comment by CaseyCarter** [comment]
Are you sure it didn't start at d8ce45f1698931399fb09a322307eb95567be832? That commit notably put two non-primary-expressions in *requires-clause*s, and was part of #1311 which a range-v3 maintainer whose name rhymes with "Keebler" merged without CI completion.

**Comment by 0x8000-0000** [comment]
> Are you sure it didn't start at [d8ce45f](https://github.com/ericniebler/range-v3/commit/d8ce45f1698931399fb09a322307eb95567be832)? That commit notably put two non-primary-expressions in _requires-clause_s, and was part of #1311 which a range-v3 maintainer whose name rhymes with "Keebler" merged without CI completion.

No, I'm not sure :)  I haven't bisected it, just trying this out during a class and this is the revision I happened to have checked out yesterday.

Thank you for the quick fix.

**Comment by CaseyCarter** [comment]
> a range-v3 maintainer whose name rhymes with "Keebler" merged without CI completion.

I'm afraid I've wasted a really good jab here: Appveyor doesn't run VS previews, so our CI wouldn't have caught the incorrect Concepts syntax after all. Curses!

**Comment by ericniebler** [comment]
I didn't cancel any tests that hadn't already been run once. I'm immune to your jabs.
