### ISSUE TITLE
const range cannot be iterated over (on MSVC 2017/2019)

### ISSUE THREAD

**Issue by menuet** [ericniebler/range-v3#1332]
Hi,
Please pardon me if this is by design, but I find strange that if I create a const range, then I cannot iterate over it with a range loop.
Example:
```
std::vector<int> v{1, 2, 3, 4};

const auto rng = v | ranges::views::filter(
                            [](const auto& i) { return i % 2 == 0; });

for (const auto& i : rng)
    std::cout << i << ",";

```
The range-for loop emits this error when building with MSVC:
`error C2662: 'ranges::basic_iterator<ranges::adaptor_cursor<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,ranges::remove_if_view<Rng,ranges::logical_negate<Pred>>::adaptor>> ranges::view_facade<Derived,ranges::finite>::begin<Derived>(void)': cannot convert 'this' pointer from 'const ranges::filter_view<ranges::ref_view<std::vector<int,std::allocator<int>>>,algo::ut::____C_A_T_C_H____T_E_S_T____10::<lambda_dc5ea157b0a03520d3dd7d0d50270e4e>>' to 'ranges::view_facade<Derived,ranges::finite> &'`

If I replace the "const auto" by "auto", then it builds fine.
What is the rationale for this behavior ?

**Comment by h-2** [comment]
`view::filter` cannot be const-iterated. Many views cannot be const-iterated and some only conditionally. And if it does work it usually doesn't do what most people expect. I recommend never doing it. 

See also this thread: https://github.com/ericniebler/range-v3/issues/385

**Comment by menuet** [comment]
OK. Thank you very much.
I have read issue #385.
This helped me understand all the rationale behind this surprising behaviour (for a range newbie like me), especially why _begin_ and _end_ cannot be always const for all views.
I can see that I am the last of a long list of people falling in the trap :-)
I close my issue
