### ISSUE TITLE
CMake targets are not exported into a namespace

### ISSUE THREAD

**Issue by MichaelWJung** [ericniebler/range-v3#1342]
If I understand modern CMake practice correctly, exported targets should be in a namespace. A consumer of the library would then write something like the following in his CMakeLists.txt:
```
find_package(range-v3 REQUIRED)
add_executable(MyApp myapp.cpp)
target_link_libraries(MyApp
  PRIVATE
    range-v3::range-v3
)
```

For range-v3 this is currently not done, the exported targets will not be in a namespace. Is there a specific reason for this? I would love to see this changed.

To put the targets in a namespace, the following section would need to be changed in CMakeLists.txt:
```
install(EXPORT range-v3-targets FILE range-v3-config.cmake DESTINATION lib/cmake/range-v3)
```
to
```
install(EXPORT range-v3-targets NAMESPACE range-v3:: FILE range-v3-config.cmake DESTINATION lib/cmake/range-v3)
```

**Comment by ericniebler** [comment]
Would this break existing users? I know nothing about cmake.

**Comment by MichaelWJung** [comment]
The simple change from my post would no longer provide targets without a namespace, so yes, this would break existing users.

It is, however, easily possible to export the targets both with and without namespaces. I could provide a PR.

References:
Daniel Pfeifer recommends the pattern using namespaces in [his talk at C++Now 2017](https://youtu.be/bsXLMQ6WgIk?t=37m15s) ([slide](https://github.com/boostcon/cppnow_presentations_2017/blob/master/05-19-2017_friday/effective_cmake__daniel_pfeifer__cppnow_05-19-2017.pdf) 24ff.) It is also used in the [CMake reference for creating packages](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-packages).

**Comment by ericniebler** [comment]
Breaking users is <sad face>. So yes, it sounds like this PR needs a PR.
