### ISSUE TITLE
Unable to compile range-v3 with Qt 5.13.1 using CMake 

### ISSUE THREAD

**Issue by ankitthakar** [ericniebler/range-v3#1347]
Hello Team,

I just wanted to explore range-v3 library. Hence I decided to compile and use it.
My tool chain :- Qt 5.13.1 with MinGW using CMake
O.S. :- Windows 10

I just opened CMakeLists.txt file in Qt and tried to build it and it started to give me errors. 

![image](https://user-images.githubusercontent.com/10296218/66737232-04cd3b80-ee89-11e9-971f-7b82b0a3d8d2.png)

Any idea about this errors? Or Is it a bug???!!

**Comment by ankitthakar** [comment]
> Hello Team,
> 
> I just wanted to explore range-v3 library. Hence I decided to compile and use it.
> My tool chain :- Qt 5.13.1 with MinGW using CMake
> O.S. :- Windows 10
> 
> I just opened CMakeLists.txt file in Qt and tried to build it and it started to give me errors.
> 
> ![image](https://user-images.githubusercontent.com/10296218/66737232-04cd3b80-ee89-11e9-971f-7b82b0a3d8d2.png)
> 
> Any idea about this errors? Or Is it a bug???!!

Update :- When I disable the option to RANGE_V3_TESTS to OFF. It is successfully compiled and generated required outputs.

**Comment by ericniebler** [comment]
> My tool chain :- Qt 5.13.1 with MinGW using CMake

What is the compiler? Qt isn't a C++ compiler, is it? Neither is MinGW or CMake. Can you give me a self-contained repro?

**Comment by ankitthakar** [comment]
> > My tool chain :- Qt 5.13.1 with MinGW using CMake
> 
> What is the compiler? Qt isn't a C++ compiler, is it? Neither is MinGW or CMake. Can you give me a self-contained repro?

First of all, Yes, you are right Qt itself not a compiler, it's an IDE which supports multiple compilers. MinGW is a package to run gcc on windows system. the version which Qt 5.13.1 is providing with its installation is MinGW 7.3 which means it using gcc 7.3.0 (Please check https://doc.qt.io/qt-5/supported-platforms.html ).

**Comment by ilyapopov** [comment]
Strictly speaking, Qt is not an IDE either, it s a framework (collection of libraries). QtCreator is the IDE you are using.

**Comment by ankitthakar** [comment]
> Strictly speaking, Qt is not an IDE either, it s a framework (collection of libraries). QtCreator is the IDE you are using.

Yes, I agree, I wanted to tell the same thing. May be my bad language !!!

**Comment by ericniebler** [comment]
> which means it using gcc 7.3.0

Range-v3 is known to work on that compiler. Without more information, I don't have a way to address this issue. Closing this "no repro" for now. If you can give me more information, please do.
