### ISSUE TITLE
Is advance a customization point?

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#135]
I have mixed feelings about making `advance` a customization point, but e.g. `counted_cursor` uses ADL to define its own version of advance (which is nice). 

Anyhow if it is, it should be documented as such, so that others can hook their own versions of advance.

**Comment by anders-sjogren** [comment]
So, Eric also was hesitant about making e.g. for_each a customization point in https://github.com/ericniebler/range-v3/issues/83 . It might be obvious, but what is the downside of providing more customization points? If the semantics are well defined and a higher-performance implementation is available for a specific type, what's the downside of being able to express that implementation for other algorithms to use?

**Comment by gnzlbg** [comment]
Adding a customization point is like adding a new language keyword, so it should be held to the same standards.

In my opinion, advance is an algorithm, not a customization point, and should be treated as such. 
Having said that, it is heavily used by other algorithms (as opposed to, e.g., for each), so I can see how a more efficient implementation for a particular type could have a significant effect.

This is not true for `for_each`. There is not a single algorithm, view, or action, that uses `for_each` internally. That is, adding `for_each` as a customization point would not allow you to customize _anything_ within range-v3. 

You can provide your own  `my::for_each` that internally dispatches to an implementation for your type, and to `ranges::for_each` for anything else, and get the same effect. 

So for `for_each` the net win is minimal (if there is a win at all), and there is an easy "library solution", thus I think that adding a new language keyword (a customization point) is not worth it and I'm against it.

**Comment by anders-sjogren** [comment]
Thanks for the clarification. I see the point. However, there is clearly the case that a library writer (A) may write a generic library function `f(T& seq)` which uses `for_each(seq, ...)`, another library writer (B) may then write a class `S` which would benefit from a customized `for_each` (for example a segmented array), and a third programmer (C) may call `S s; f(s);`. 

If `for_each` would be customized, C would get an optimal implementation without even knowing it and the work of A and B would be totally decoupled. In essence the customization points form an extended interface, with default implementations.

I agree with the keyword analogy. It may just happen to be that a class contains an advance method with a different argument list or semantics. It should be possible to solve that using some other mechanism or calling conventions for customization points though, e.g. by not looking for `t.for_each` and `for_each(t` but `t.ranges_customized_for_each` and `ranges_customized_for_each(t`, or the like (cf. macro naming), or perhaps some other way.

**Comment by gnzlbg** [comment]
I see your point too. My proposed solution is an easy workaround for code you control; if someone calls `ranges::for_each` they will get a working but suboptimal implementation for your type. 

What you propose is an alternative, that only works for `for_each`, and that adds a new language keyword (the name is irrelevant, e.g. `for_each` vs `ranges_customized_for_each`). Don't fall in the politician's syllogism: _We must do something. This is something. Therefore, we must do this_. We are talking about the STL here, the solution must work with all algorithms and all types similar to yours. 

There might be a solution satisfying those criteria: segmented iterators. I don't think anybody knows if they really work. Even if they work, they might not be worth the trouble if they are not as fast as they should be. It is an open research question. This is the hard way out tho.

I'm busy with `constexpr` support right now, but I might toy with multi-dimensional/segmented iterators afterwards for vector, matrices, trees, `dynamic_bitset`... These are data-structures in which one typically wants to do parallel processing on, and I expect segmented iterators to play an even major role in a parallel STL world. I don't expect anything useful to come out of me looking into this tho.

**Comment by anders-sjogren** [comment]
> There might be a solution satisfying those criteria: segmented iterators.
Well, this was just one example. I bet there are plenty of other that cannot be implemented in terms of segments. The question is more general: Is there a way to use customization points to correctly and efficiently provide decoupling between algorithms and types (as outlined above). The main reason for using C++ is to gain optimal performance, so I think one should work hard to achieve that if possible, of course.

**Comment by gnzlbg** [comment]
> Is there a way to use customization points to correctly and efficiently provide decoupling between algorithms and types (as outlined above). 

I think that is the wrong question. The STL solves the "MxN problem" (M data structures + N algorithms result in NxM algorithm implementations). Making the algorithms customization points reintroduces that problem (allows one implementation per type, you can basically ditch iterator/range categories). The STL solves the problem with iterators, range-v3 solves it with iterators/ranges. So I think the right question is:

- Which iterator/range category allows you to write generic efficient algorithms for your data-structure and others like it? 

If none of the current categories allow that, why is that? Are they broken/not correct? Do we need new ones? etc. 

For example, I asked above: _why is the implementation of advance for counted iterator not covered by the current iterator categories?_

**Comment by anders-sjogren** [comment]
> I think that is the wrong question. The STL solves the "MxN problem" (M data structures + N algorithms result in NxM algorithm implementations). Making the algorithms customization points reintroduces that problem (allows one implementation per type, you can basically ditch iterator/range categories).

Well, not necessarily. If algorithms are coded in terms of other algorithms (e.g. using for_each when traversing), then it'd be sufficient to customize some of them to get increased performance in not only the ones customized, but also others. The non-optimized algorithms would just work as they are today. Thus, the customization points would introduce possibilities and not any additional requirements.

However, I understand that this is not the way STL currently works and since the customization would probably a bit of a hack, I'll just leave it.

Thanks for the clarifications and thoughts!

**Comment by ericniebler** [comment]
In range-v3, `advance` is a customization point. In my proposal to the committee, it is not. In the proposal, `advance` is overloaded for counted iterators, but ADL isn't used to find other overloads in users' namespaces.
