### ISSUE TITLE
views::c_str((char*)0) shouldn't model random_access_range

### ISSUE THREAD

**Issue by johelegp** [ericniebler/range-v3#1364]
The type of `views::c_str()` given a `const char*` argument models `random_access_range`, which is unexpected given that one doesn't know its size.

**Comment by CaseyCarter** [comment]
`random_access_range` doesn't refine `sized_range`, so a model of `random_access_range` need not know its size. To model `random_access_range` a range only needs to return a model of `random_access_iterator` from `begin`.

**Comment by johelegp** [comment]
Makes sense. Thank you.
