### ISSUE TITLE
How about making constructing iterator_range easier?

### ISSUE THREAD

**Issue by nanoric** [ericniebler/range-v3#1375]
Considering construct an iterator_range from two iterator.
```cpp
using Container = std::unordered_multimap<int, int>;
Container  m;
m.emplace(1,2);
m.emplace(1,3);
m.emplace(1,4);

// here!
auto bucket = m.bucket(1);
auto begini = m.begin(bucket);
auto endi = m.end(bucket);

// here! ugly: Even a old style for loop don't have to know the type of begini and endi.
for(auto i : ranges::iterator_range<Container::iterator/*for now, this is necessary, but ugly.*/>(
   /*make_pair is necessary too, the same ugly.*/std::make_pair(begini, endi))
{
...
}
// mabe the for-loop can be simplized to:
for(auto i: ranges::make_range(begini, endi))
{
....
}
```
Maybe when range library is fully merged into STL, this feature will be useless. Because no iterator will exist for that moment.
But for now, it will be useful. And, maybe, it will make people easier to convert old-style code to ranges based code.

**Comment by CaseyCarter** [comment]
> ```c++
> // maybe the for-loop can be simplified to:
> for(auto i: ranges::make_range(begini, endi))
> ```

No, but it can be simplified to `for(auto i: ranges::make_iterator_range(begini, endi))`.

Note that `iterator_range` is deprecated in range-v3 and replaced by `subrange`. I suggest trying `make_subrange` instead.
