### ISSUE TITLE
views::join not bi-directional

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#1418]
Currently `ranges::views::join` and `ranges::cpp20::views::join` return only an input range, but according the DS they should return bidirectional ranges if possible.

Maybe something to add to #802 ?

**Comment by johelegp** [comment]
It works:
https://github.com/ericniebler/range-v3/blob/f73ef2453f516ff8312c39d6db0daa52384fa7df/test/view/join.cpp#L174-L182
With the CPO too: https://godbolt.org/z/DjZqoi.
