### ISSUE TITLE
is_infinite should return either yes, no, or maybe

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/range-v3#142]
Some ranges are "maybe" infinite, like `view::ints | view::take_while(some_function)`. A Boolean `is_infinite` range is insufficient to catch this subtlety. Algorithms like `distance_compare` can be optimized for truly infinite ranges, but such an optimization is wrong for "maybe" infinite ranges.

See also: #74 #141

**Comment by gnzlbg** [comment]
Can `distance_compare` be implemented for "maybe" infinite ranges?

**Comment by morinmorin** [comment]
> Can distance_compare be implemented for "maybe" infinite ranges? 

The implementation just falls back to the ordinary (i.e. non-optimized) version for "maybe" infinite ranges, if `is_infinite_range` is fixed. So, no need to update `distance_compare`. (Of course, adding such test cases would be nice :) )

**Comment by gnzlbg** [comment]
But if the maybe infinite ranges are actually infinite, trying to compare their distances might never terminate right?

**Comment by morinmorin** [comment]
> trying to compare their distances by using the same technique as for finite ranges might never terminate, right?

No. If `rng` is not a truly infinite range, `distance_compare(rng, n)` takes 
* O(1) time if `rng` is `SizedIterable`;
* O(n) time (or, more correctly, O(n) increments) otherwise.

**Comment by gnzlbg** [comment]
If the range is "maybe infinite" it cannot be a `SizedIterable`, so if I understood it correctly now, a call to `distance_compare(rng, n)` doesn't attempt to compute the size of the range, but it increments its begin iterator at most `n` times while checking if the end of the range has been reached. Is that correct?

**Comment by morinmorin** [comment]
Correct.
