### ISSUE TITLE
range-v3 is not compiling with development version of Clang-11

### ISSUE THREAD

**Issue by keryell** [ericniebler/range-v3#1420]
Good news: a first version of the C++20 concepts landed recently into the development version of Clang-11. https://github.com/llvm/llvm-project/commit/67c608a9695496cfc9d3fdf9d0b12b554ac6b4df

Bad news: it breaks the compilation of range-v3. Actually it even crashes the Clang compiler.

I guess there is nothing to do but waiting for the Clang implementation to make progress but at the same time I need some C++2a features in my code. Unfortunately using `-std=c++2a` with Clang now enables the concepts.
Before, there was a `-fconcepts-ts` option to enable the concepts so I was expecting a new `-fno-concepts-ts` or `-fno-concepts` options. @saarraz : do you think it could be a useful option?

After trying various workaround to use range-v3 with C++2a, my simplest solution for now is
```
-std=c++2a -U__cpp_concepts
```
Amazing we can play with features macros like that... :-)

**Comment by CaseyCarter** [comment]
If you define `CPP_CXX_CONCEPTS` to `0`, range-v3 won't use Concepts despite the compiler claiming support.

**Comment by keryell** [comment]
This sounds an interesting macro to know.
But compiling with `-std=c++2a -DCPP_CXX_CONCEPTS=0` leads to:
```
clang++-11 -I ~/Xilinx/Projects/C++/range-v3/include -Wall -std=c++2a -DCPP_CXX_CONCEPTS=0 ranges.cpp  -lboost_thread -lboost_system -lboost_fiber -lboost_context -lpthread -o ranges
In file included from ranges.cpp:2:
In file included from /home/rkeryell/Xilinx/Projects/C++/range-v3/include/range/v3/all.hpp:17:
In file included from /home/rkeryell/Xilinx/Projects/C++/range-v3/include/range/v3/action.hpp:17:
In file included from /home/rkeryell/Xilinx/Projects/C++/range-v3/include/range/v3/action/action.hpp:19:
/home/rkeryell/Xilinx/Projects/C++/range-v3/include/meta/meta.hpp:2609:46: error: pack expansion does not contain any unexpanded parameter packs
        requires and_v<integral<invoke<C, L>>...>
                       ~~~~~~~~~~~~~~~~~~~~~~^
/home/rkeryell/Xilinx/Projects/C++/range-v3/include/meta/meta.hpp:2714:47: error: pack expansion does not contain any unexpanded parameter packs
        requires (integral<invoke<Fn, Ts>> && ...)
                  ~~~~~~~~~~~~~~~~~~~~~~~~    ^
2 errors generated.
```

**Comment by CaseyCarter** [comment]
> This sounds an interesting macro to know.
> But compiling with `-std=c++2a -DCPP_CXX_CONCEPTS=0` leads to:

Yes, sorry - I forgot that `meta` (which is a semi-independent library) doesn't use the same config macro. In fact, `meta` examines `__cpp_concepts` directly so its use of concepts can't be portably disabled.

You should continue using `-U__cpp_concepts` since Clang is happy with it, and hopefully someone will find time to smooth out clang's issues with range-v3 soon. (I know at least those two errors in `meta` have been reported.)

**Comment by ericniebler** [comment]
It works now.
