### ISSUE TITLE
Is there a way to efficiently rewrite this function as a ranges pipeline?

### ISSUE THREAD

**Issue by madmongo1** [ericniebler/range-v3#1421]
This function takes a reference to a vector of strings representing arguments for a linux `::execv` call.
The output is a `vector` of `char*` plus one terminating `nullptr`. The `char*` pointers point into the data of the input vector's strings.

The output range is always one element larger than the input range.

```
auto
transform_args(std::vector<std::string> &input)
-> std::vector<char *>
{
    using namespace ranges;

    auto result = std::vector<char*>();
    result.reserve(input.size() + 1);
    transform(input, back_inserter(result), data);
    push_back(result, nullptr);

    return result;
}
```

I can't figure out from the documentation whether it's possible to rewrite in terms of a single pipeline while eliminating the possibility of a reallocation.

Would you be able to provide guidance?

Many thanks.

**Comment by johelegp** [comment]
`| concat(single(nullptr))` might work for you: https://godbolt.org/z/boYUSY.

**Comment by madmongo1** [comment]
@johelegp this is returning some kind of proxy object, not a vector<char*>. what is the correct way to transform it to the correct return type?

**Comment by johelegp** [comment]
Using `ranges::to<vector>`: https://godbolt.org/z/tSn8QP.

**Comment by madmongo1** [comment]
Yep I see it now. Thanks.

https://godbolt.org/z/y3Lx-Y

**Comment by johelegp** [comment]
Ah, good job. I was trying to figure out why it doesn't compile.
