### ISSUE TITLE
What does yield_from do?

### ISSUE THREAD

**Issue by intractabilis** [ericniebler/range-v3#1427]
What does `yield_from` do? I see it in examples, but couldn't find it in any documentation besides that it is a `constexpr` of type `yield_from_fn`. All that documentation says about the latter is that it has `operator()`.

**Comment by ericniebler** [comment]
Maybe it should be called `yield_all`. It yields all the values from a given range in one go.

**Comment by intractabilis** [comment]
Thank you. What does it change if I remove it? I tried the following example with yield_from removed. It still produces the same result.

```
    auto vi =
        views::for_each(views::ints(1, 10), [](int i) {
            return yield_from(views::repeat_n(i, i));
        })
      | to<std::vector>();
```

**Comment by ericniebler** [comment]
`yield_from` is essentially the same as `views::all`. If it's a view already, it's a no-op. In the code above, it's a no-op.
