### ISSUE TITLE
Issue #946 regression test breaks with GCC 10 -std=c++20

### ISSUE THREAD

**Issue by jicama** [ericniebler/range-v3#1443]
libstdc++-v3/include/type_traits: In instantiation of ‘struct std::is_nothrow_destructible<main()::Data>’:

range-v3/include/range/v3/view/indirect.hpp:128:79:   recursively required from ‘constexpr ranges::view_interface<Derived, <anonymous> >::operator Container() const [with Container = const ranges::indirect_view<ranges::ref_view<std::vector<main()::Data*> > >; bool True = true; Derived = ranges::ref_view<std::vector<main()::Data*> >; ranges::cardinality Cardinality = ranges::finite]’

range-v3/include/range/v3/view/indirect.hpp:128:79:   required from ‘constexpr auto ranges::views::indirect_fn::operator()(Rng&&) const requires (viewable_range<Rng>) && (input_range<Rng>) && bool(readable<typename ranges::readable_traits<typename std::remove_cv<typename std::remove_reference<decltype(ranges::_::begin((declval<Rng&>)()))>::_t>::type>::value_type>) [with Rng = std::vector<main()::Data*>&]’

range-v3/include/range/v3/functional/invoke.hpp:134:34:   required by substitution of ‘template<class F, class ... Args> constexpr decltype ((F&&)(f)((Args&(ranges::invoke_fn::operator()::args))...)) ranges::invoke_fn::operator()(F&&, Args&& ...) const [with F = ranges::views::indirect_fn; Args = {std::vector<main()::Data*, std::allocator<main()::Data*> >&}]’

range-v3/include/range/v3/functional/concepts.hpp:31:9:   required from ‘constexpr auto ranges::views::view_closure_base_ns::operator|(Rng&&, ranges::views::view_closure<ViewFn>) [with Rng = std::vector<main()::Data*>&; ViewFn = ranges::views::indirect_fn]’

range-v3/test/view/indirect.cpp:58:48:   required from here

libstdc++-v3/include/type_traits:895:52: error: static assertion failed: template argument must be a complete class or an unbounded array

This doesn't look like a compiler bug to me.

**Comment by CaseyCarter** [comment]
> recursively required from ‘constexpr ranges::view_interface<Derived, >::operator Container() const
>
> This doesn't look like a compiler bug to me.

This is almost certainly yet another case of constraint recursion involving `view_interface`'s container conversion operators.

**Comment by ericniebler** [comment]
Can I delete those yet?

**Comment by ericniebler** [comment]
I've nuked the container conversion operators. This should be fixed on trunk now.
