### ISSUE TITLE
const group_by view issue

### ISSUE THREAD

**Issue by voivoid** [ericniebler/range-v3#1446]
Not sure if it's an issue, nevertherless, please consider the following code:

```
#include "range/v3/view/group_by.hpp"
#include <string>

int main() {
    std::string s;
    const auto r = s | ranges::views::group_by( std::equal_to<char>{} );
    for( auto x : r ) {
    }
}
```

The code compiled fine before the latest group_by fix c359d312a70ad33a39c486e88dda879e976ae771

Now both clang9 and gcc9.2 fail with "error: no matching member function for call to 'begin'"

By the way can you please advise some docs describing range-v3 range const semantics?

**Comment by johelegp** [comment]
See "View const-ness" at https://ericniebler.github.io/range-v3/#tutorial-views. This behavioural change was done to fix a bug.

**Comment by ericniebler** [comment]
What @johelegp said. This is by design. A great many view types will not suffer to be `const`-qualified because they are stateful. `group_by` now falls into that category.
