### ISSUE TITLE
C7608: atomic constraint should be a constant expression when using ranges::to_vector

### ISSUE THREAD

**Issue by Guekka** [ericniebler/range-v3#1450]
When I compile my code, it stops with the error C7608.
Here's a relevant snippet:
```cpp
#include "json/single_include/nlohmann/json.hpp"
#include "range-v3/include/range/v3/all.hpp"

class myClass
{
private:
    nlohmann::json json_;

public:
    auto getJSON() const { return json_; }
};

int main()
{
    std::map<int, myClass> patterns_;
    auto getJSON = [](const auto &item) { return item.getJSON(); }; //Returns a nlohmann::json
    namespace rv = ranges::views;
    std::vector<nlohmann::json> jsons = patterns_ | rv::values | rv::transform(getJSON)
                                        | ranges::to_vector;
    return 0;
}

```

Compiler output:

    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(228): error C7608: atomic constraint should be a constant expression
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(243): note: see reference to variable template 'bool convertible_to_cont_cont_impl_frag_<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> &,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(257): note: see reference to variable template 'bool convertible_to_cont_cont_impl_<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> &,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(268): note: see reference to variable template 'bool convertible_to_cont_cont_impl_<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> &,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(278): note: see reference to variable template 'bool convertible_to_cont_cont<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> &,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(296): note: see reference to variable template 'bool convertible_to_cont_cont<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> &,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(365): note: see reference to variable template 'bool convertible_to_cont_and_not_cont_cont<meta::id<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> &>' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(228): note: see reference to variable template 'bool invocable<ranges::detail::to_container::fn<meta::id<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> > >,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> &>' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(243): note: see reference to variable template 'bool convertible_to_cont_cont_impl_frag_<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer>,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(257): note: see reference to variable template 'bool convertible_to_cont_cont_impl_<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer>,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(268): note: see reference to variable template 'bool convertible_to_cont_cont_impl_<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer>,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(278): note: see reference to variable template 'bool convertible_to_cont_cont<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer>,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(296): note: see reference to variable template 'bool convertible_to_cont_cont<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer>,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(365): note: see reference to variable template 'bool convertible_to_cont_and_not_cont_cont<meta::id<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(228): note: see reference to variable template 'bool invocable<ranges::detail::to_container::fn<meta::id<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> > >,nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(243): note: see reference to variable template 'bool convertible_to_cont_cont_impl_frag_<ranges::transform_view<ranges::transform_view<ranges::ref_view<std::map<unsigned int,CAO::PatternSettings,std::less<unsigned int>,std::allocator<std::pair<unsigned int const ,CAO::PatternSettings> > > const >,ranges::detail::get_second>,`CAO::PatternMap::getUnifiedJSON'::`2'::<lambda_1> > &,std::vector<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer>,std::allocator<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> > > >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(257): note: see reference to variable template 'bool convertible_to_cont_cont_impl_<ranges::transform_view<ranges::transform_view<ranges::ref_view<std::map<unsigned int,CAO::PatternSettings,std::less<unsigned int>,std::allocator<std::pair<unsigned int const ,CAO::PatternSettings> > > const >,ranges::detail::get_second>,`CAO::PatternMap::getUnifiedJSON'::`2'::<lambda_1> > &,std::vector<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer>,std::allocator<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> > > >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(268): note: see reference to variable template 'bool convertible_to_cont_cont_impl_<ranges::transform_view<ranges::transform_view<ranges::ref_view<std::map<unsigned int,CAO::PatternSettings,std::less<unsigned int>,std::allocator<std::pair<unsigned int const ,CAO::PatternSettings> > > const >,ranges::detail::get_second>,`CAO::PatternMap::getUnifiedJSON'::`2'::<lambda_1> > &,std::vector<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer>,std::allocator<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> > > >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(278): note: see reference to variable template 'bool convertible_to_cont_cont<ranges::transform_view<ranges::transform_view<ranges::ref_view<std::map<unsigned int,CAO::PatternSettings,std::less<unsigned int>,std::allocator<std::pair<unsigned int const ,CAO::PatternSettings> > > const >,ranges::detail::get_second>,`CAO::PatternMap::getUnifiedJSON'::`2'::<lambda_1> > &,std::vector<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer>,std::allocator<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> > > >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(296): note: see reference to variable template 'bool convertible_to_cont_cont<ranges::transform_view<ranges::transform_view<ranges::ref_view<std::map<unsigned int,CAO::PatternSettings,std::less<unsigned int>,std::allocator<std::pair<unsigned int const ,CAO::PatternSettings> > > const >,ranges::detail::get_second>,`CAO::PatternMap::getUnifiedJSON'::`2'::<lambda_1> > &,std::vector<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer>,std::allocator<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer> > > >' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(365): note: see reference to variable template 'bool convertible_to_cont_and_not_cont_cont<ranges::detail::from_range<std::vector>,ranges::transform_view<ranges::transform_view<ranges::ref_view<std::map<unsigned int,CAO::PatternSettings,std::less<unsigned int>,std::allocator<std::pair<unsigned int const ,CAO::PatternSettings> > > const >,ranges::detail::get_second>,`CAO::PatternMap::getUnifiedJSON'::`2'::<lambda_1> > &>' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include/libs/json/single_include/nlohmann/json.hpp(22646): note: see reference to class template instantiation 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>' being compiled
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\filesystem(2087): note: see reference to class template instantiation 'std::chrono::time_point<std::filesystem::_File_time_clock,std::chrono::duration<std::chrono::system_clock::rep,std::chrono::system_clock::period>>' being compiled
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xstring(1743): note: see reference to class template instantiation 'std::basic_string_view<wchar_t,std::char_traits<wchar_t>>' being compiled
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(228): error C2131: expression did not evaluate to a constant
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(228): note: failure was caused by a read of an uninitialized symbol
    C:\IT\Code_perso\Cathedral_Assets_Optimizer\include\libs\range-v3\include\range/v3/range/conversion.hpp(228): note: see usage of 'ranges::invocable<ranges::detail::to_container::fn<meta::id<nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>&>'

[Here](https://drive.google.com/open?id=18Rpy7yMZeSHw9klOoMBHV4tHxyFg4tUt)'s the full project (required libs and CMake file)

The compiler used is MSVC 32 bits 16.5 (latest) with options ``/experimental:preprocessor /std:c++latest /permissive-``

**Comment by ericniebler** [comment]
I wonder if you would be willing to try the latest from trunk? I just made some msvc portability improvements in #1449 two days ago that might fix this.

**Comment by Guekka** [comment]
That was fast, thank you
It partially works. It compiles and works correctly when compiling with `std:c++17`, but doesn't with `std:c++latest`
I'm personally perfectly fine with that, since I use C++17
I'd love to be able to give some code, but I do not understand enough the issue to be able to reproduce it.

**Comment by ericniebler** [comment]
Please give me some self-contained code that reproduces the error.

**Comment by ericniebler** [comment]
I was able to reproduce the error using the .7z file you provided. It no longer repros on trunk. Closing as fixed.
