### ISSUE TITLE
ranges::actions::sort error: use of deleted function with gcc 9.2

### ISSUE THREAD

**Issue by MartinJewski** [ericniebler/range-v3#1457]
I tried running the following code (gcc 9.2):

> 
>     std::vector<int> f_mycontainer{99,2,5,2,0,4,5,2,5,11,99};
>     auto a = f_mycontainer | ranges::actions::sort | ranges::actions::drop(5); //ERROR
>     auto b = ranges::actions::drop(f_mycontainer, 5); //OK
>     auto c = ranges::actions::sort(f_mycontainer); //OK

It throws the following error message:

> error: use of deleted function ‘constexpr concepts::return_t<Rng, typename std::enable_if<(range<Rng> && concepts::detail::CPP_true(concepts::detail::Nil{})), void>::type> ranges::actions::action_closure_base_ns::operator|(Rng&, const ranges::actions::action_closure<ActionFn>&) [with Rng = std::vector<int>; ActionFn = ranges::actions::sort_fn; concepts::return_t<Rng, typename std::enable_if<(range<Rng> && concepts::detail::CPP_true(concepts::detail::Nil{})), void>::type> = std::vector<int>]’
>   200 |     auto a = f_mycontainer | ranges::actions::sort | ranges::actions::drop(5); //ERROR

**Comment by ericniebler** [comment]
Actions do not support piping from an lvalue container. Do this instead:

```c++
auto a = std::move(f_mycontainer) | ranges::actions::sort | ranges::actions::drop(5); //ERROR
```
