### ISSUE TITLE
Range_v3 failed due to error C2672 C2182 on MSVC + /std:c++17

### ISSUE THREAD

**Issue by QuellaZhang** [ericniebler/range-v3#1458]
Recently after we updated range-v3 to latest source code, it failed to build due to lots of errors under /std:c++17, and we verified it build successfully on /std:c++latest. I attached the build log.

**Steps to reproduce the behavior:**

1. git clone https://github.com/ericniebler/range-v3 D:\Range-v3\src
2. Open a VS 2017 x86 command prompt as admin and browse to D:\Range-v3
3. set CL=/std:c++17 /wd5105 /permissive- /experimental:newLambdaProcessor /D_WINSOCKAPI_ %CL%
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DCMAKE_BUILD_TYPE=Release ..\src
6. pop
7. pushd build_x86
8. msbuild Range-v3.sln /p:Configuration=Release /p:Platform=win32 /m /t:Rebuild

**build log:** [rang_v3_build.log](https://github.com/ericniebler/range-v3/files/4408134/rang_v3_build.log)

**error:**
F:\gitP\ericniebler\range-v3\example\is_sorted.cpp(30): error C2672: 'operator __surrogate_func': no matching overloaded function found
F:\gitP\ericniebler\range-v3\example\is_sorted.cpp(30): error C2893: Failed to specialize function template
F:\gitP\ericniebler\range-v3\include\concepts/concepts.hpp(1122): error C2182: 'abstract declarator': illegal use of type 'void'
F:\gitP\ericniebler\range-v3\include\concepts/concepts.hpp(1124): error C2182: 'abstract declarator': illegal use of type 'void'
F:\gitP\ericniebler\range-v3\include\concepts/concepts.hpp(1125): error C2182: 'abstract declarator': illegal use of type 'void'

**Comment by ericniebler** [comment]
Thanks for the report. As stated in the readme and in the docs, the supported compilers do not include VS2017,
