### ISSUE TITLE
MSVC compiler error if an std::bind predicate is used

### ISSUE THREAD

**Issue by voivoid** [ericniebler/range-v3#1462]
Hi! MSVC fails to compile the following code ( while gcc and clang have no problems with it )

```cpp
#include "range/v3/all.hpp"
#include <vector>
#include <functional>

int f(int x)
{
  return x;
}

void test()
{
  std::vector<int> v;
  /* OK */ ranges::max( v | ranges::views::transform( &f ) );
  /* OK */ ranges::max( v | ranges::views::transform( [](int n){ return f(n); } ) );
  /* ERROR */ ranges::max( v | ranges::views::transform( std::bind( &f, std::placeholders::_1 ) ) );
}
```

Tested with range-v3 master and MSVC 14.25 ( but almost sure previous MSVC versions have the same behavior )

**Comment by ericniebler** [comment]
Just tested with the latest MSVC, and it works. A lot has changed in range-v3 in the past few weeks, and I'm guessing one of the recent changes fix it.
