### ISSUE TITLE
rv::reverse after rv::group_by fails?

### ISSUE THREAD

**Issue by codereport** [ericniebler/range-v3#1471]
https://godbolt.org/z/eQ9aeM

```cpp
    std::vector v = {1,1,3,3,5};

    auto x = v | rv::chunk(3) | rv::reverse; // SUCCEEDS
    auto y = v | rv::group_by(std::equal_to{}) | rv::reverse; // FAILS
```

Maybe this isn't a bug - but I don't see why one anamorphic function (`chunk`) would work and another (`group_by`) would fail. So my guess is it is a bug.

**Comment by BRevzin** [comment]
I don't think `group_by` can yield a bidirectional view (which `reverse` requires). 

Basically, consider like `<` as the predicate and `[1, 6, 5]` as the vector. `group_by` from the front would yield `[[1, 6, 5]]` but if you start from the back - how do you get there without somehow getting `[[1, 6], [5]]`? Only way would be to actually produce the whole range first:

```cpp
auto y_tmp = v | rv::group_by(std::equal_to{}) | to<std::vector>();
auto y = y_tmp | rv::reverse;
```

**Comment by ericniebler** [comment]
Barry has the answer. Thanks, @BRevzin!
