### ISSUE TITLE
all_t alias not in cpp20 namespace

### ISSUE THREAD

**Issue by rrahn** [ericniebler/range-v3#1477]
Hi, I am just wondering why `all_t` was not yet adopted to the ranges::cpp20 namespace. It seems the standard defines now this transformation type trait in favour of all_view.
Is that on purpose or not yet updated? 
If so I can also make a PR for this.

Thanks a lot

**Comment by marehr** [comment]
I think I also encountered those discrepancies:

* `safe_range` -> `borrowed_­range` (https://eel.is/c++draft/range.range#5)
* `enable_safe_range` -> `enable_borrowed_range` 
* ranges `basic_istream_view` only has one template argument, standard requires three (https://eel.is/c++draft/range.istream.view#:stream-extractable)
