### ISSUE TITLE
Is it possible to memoize the result of the projection within min_element and related algorithms?

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#148]
The motivation comes from [this reddit post](http://www.reddit.com/r/cpp/comments/36sqtq/more_efficient_interface_for_algorithms_taking_a/).

The aim is to halve the number of projection computations (from ~2N to ~N, the asymptotic complexity remains the same).

On the specification of `min_element` in D4382 I found:

> complexity: Exactly `max((last - first) - 1, 0)` applications of the corresponding comparison function and projection.

However, the current implementation executes the projection at most `2(last - first)` times:

```c++
         template<typename I, typename S, typename C = ordered_less, typename P = ident,
                CONCEPT_REQUIRES_(ForwardIterator<I>() && IteratorRange<I, S>() &&
                    IndirectCallableRelation<C, Project<I, P>>())>
            I operator()(I begin, S end, C pred_ = C{}, P proj_ = P{}) const
            {
                auto && pred = as_function(pred_);
                auto && proj = as_function(proj_);
                if(begin != end)
                    for(auto tmp = next(begin); tmp != end; ++tmp) // N times
                        if(pred(proj(*tmp), proj(*begin))) // 2 calls to proj here -> 2N
                            begin = tmp;
                return begin;
            }
```

Would it be possible to use a different implementation like the following at least for some types?

```c++
         template<typename I, typename S, typename C = ordered_less, typename P = ident,
              typename V = iterator_value_type_t<I>, typename R = iterator_reference_t<I>,
                CONCEPT_REQUIRES_(ForwardIterator<I>() && IteratorRange<I, S>() &&
                    IndirectCallableRelation<C, Project<I, P>>() && CopyConstructible<V, R>() && 
                    CopyAssignable<V, R>()
            )>
            I operator()(I begin, S end, C pred_ = C{}, P proj_ = P{}) const
            {
                auto && pred = as_function(pred_);
                auto && proj = as_function(proj_);
                if(begin != end) {
                    V memoized(proj(*begin));  // Is MoveConstructible enough?
                    for(auto tmp = next(begin); tmp != end; ++tmp) {                       
                        if(pred(proj(*tmp), memoized)) {
                           begin = tmp;
                           memoized = proj(*begin);  // Is MoveAssignable enough?
                        }
                    }
                }
                return begin;
            }
```

I've specified that the iterator value type must be copy constructible and copy assignable to try to support proxy iterators but this is overly restrictive and won't work with e.g. unique pointers. 

If projections are allowed to have side-effects these kind of optimizations are not possible at all. 
I haven't found any comments about the semantics of projections neither in [N4128](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4128.html#algorithms-should-take-invokable-projections) nor in [D4382](http://boost-sandbox.sourceforge.net/std/wg21/D4382.pdf). In the later I found only the syntactic requirements and the algorithmic complexities. To me it is not clear if an STL2 implementation can memoize the result of a projection, or if a projection has to be invoked on "every iterator dereference". The algorithmic complexities indicate when and how a user can rely on the number of projection invocations tho.

**Comment by CaseyCarter** [comment]
N4382 [projected.indirectcallables] defines `Projected<I, Proj>`. It requires `RegularFunction<FunctionType<Proj>, ValueType<I>>`, so projections may have side effects but not side effects that affect the result of the projection.

The additional constraints would need to apply to the result type of the projection, not to the value type of the iterator. i.e.,
```
template<typename I, typename S, typename C = ordered_less, typename P = ident,
    CONCEPT_REQUIRES_(ForwardIterator<I>() && IteratorRange<I, S>() &&
        IndirectCallableRelation<C, Project<I, P>>() &&
        MoveConstructible<iterator_value_t<Project<I, P>>>() && 
        MoveAssignable<iterator_value_t<Project<I, P>>>()
    )>
I operator()(I begin, S end, C pred_ = C{}, P proj_ = P{}) const
{
    auto && pred = as_function(pred_);
    auto && proj = as_function(proj_);
    if(begin != end) {
        auto memoized = proj(*begin);
        for(auto tmp = next(begin); tmp != end; ++tmp) {
            auto&& val = proj(*tmp);
            if(pred(val, memoized)) {
                begin = tmp;
                memoized = std::move(val);
            }
        }
    }

    return begin;
}
```
In addition to the stronger constraint, this algorithm has a different complexity specification: exactly max(end - begin - 1, 0) calls of the predicate, (end - begin) calls of the projection, 1 move construction, and at most (end - begin) move assignments of the projection's result type. It may be a pessimization vs. the less constrained algorithm if move assignment of the projection result is more expensive than a projection call, so it's not a pure optimization (e.g., identity projection with a value type of `std::array<double, 7823749>`). I think it should have a different name if it's not a pure optimization.

**Comment by gnzlbg** [comment]
> I think it should have a different name if it's not a pure optimization.

I agree, and you just showed that it is not a pure optimization.

>  identity projection with a value type of std::array<double, 7823749>

Good example that gives us the two extreme cases:

"cheap projection + expensive to move" and "expensive projection + cheap to move".

For me "cheap projection + expensive to move" is a reasonable default since I don't use projections that often.  I think that being able to choose which implementation to use is something desirable not only for `min_element` but also for a bunch of other algorithms (at least max and minmax element). 

I can think of a couple of ways to choose the implementation:

- have a trait, to specify the default operation for each type (optional),
- let the memoized version be a member function of the algorithm (my favorite): 
  
  `auto i = min_element.memoized(rng, std::plus<>{}, proj);`,

- use a tag to choose with version of the algorithm to use,
- use a completely different name for the algorithm.

**Comment by ericniebler** [comment]
> ```c++
> auto memoized = proj(*begin);`
> ```

Actually, this creates the potential for dangling references. It would need to be written as:

```c++
auto && x = *begin;
auto && memo = proj( (decltype(x) &&) x );
```

Without a deep think about this, my gut tells me that we should write the algorithm constraints and complexity guarantees generally enough so that it allows either implementation.

I'm rather against all the options Gonzalo lists above. Projections should be totally ignorable and not needlessly bloat the interface.

**Comment by vlovich** [comment]
Would it be possible to provide a memoized range adaptor instead?

It seems like it would be more composable (all of the comparison algorithms such as max_element, minmax_element, sort, etc would be able to take advantage of this) & 
that way I don't think it even needs to be move-constructible or anything since the range would just store it internally (http://lists.boost.org/Archives/boost/2012/05/193457.php).

This also puts the user in control to know if it makes sense to memoize or not depending on their individual performance requirements.

**Comment by CaseyCarter** [comment]
I can imagine `auto && foo = proj(*begin);` dangling, e.g. if `*begin` is an rvalue and `proj` returns a reference to a member, but not `auto foo = proj(*begin);`. I do in general think we should support projections that return references to non-movable objects; useful objects may have non-movable members:
```
auto joiner = [](std::thread& t){ if (t.joinable()) t.join(); };
struct A { std::thread t; };
std::vector<A> some_objects(42);
// ...
ranges::for_each(some_objects, joiner, &A::t);
```
...and it's just occurred to me that memoization needs to copy in general so the algorithms don't steal the contents of the range ;)

**Comment by gnzlbg** [comment]
> Without a deep think about this, my gut tells me that we should write the algorithm constraints and complexity guarantees generally enough so that it allows either implementation.

One way to do this is to leave the projection out of the specification of the algorithmic complexity: 

> complexity: Exactly max((last - first) - 1, 0) applications of the corresponding comparison function ~~and projection~~. 

This allows both implementations, makes the specification of the algorithm "easier" and gives more leeway to the implementation. However, can the implementation really make use of this leeway? There is no way to tell if a projection is cheap or expensive, or if moving a type is cheap of expensive. Since there is no implementation that is good for all cases, doing this doesn't solve the original problem.

> I do in general think we should support projections that return references to non-movable objects; useful objects may have non-movable members

+ 1

**Comment by ericniebler** [comment]
> One way to do this is to leave the projection out of the specification of the algorithmic complexity

A better solution is to put an upper bound on the number of times the projection is called.

> Since there is no implementation that is good for all cases, doing this doesn't solve the original problem.

Not all problems are worth solving.

**Comment by gnzlbg** [comment]
> A better solution is to put an upper bound on the number of times the projection is called.

Indeed. Allowing the projection to be called at most 2(last - first) times permits both implementations.

> Not all problems are worth solving.

But some problems are worth knowing about :P 

I am on Casey's side here: these are two different algorithms with two different complexity guarantees. 

- I would like to avoid an explosion in the number of algorithms,
- I want to know which algorithm is implemented (otherwise we just made OP's problem worse, now he needs 2 algorithms to get reliable behavior instead of one), and
- I don't want memoization by default since the most common projection (identity) is a no op (don't read this issue's title please :P).

So I'd rather state "projections should be cheap" explicitly by requiring _exactly_ 2(last - first) invocations of the projection, forbidding memoization. 

Giving leeway to implementations here to chose memoization by default is just allowing them to do what I consider to be the wrong thing.

**Comment by gnzlbg** [comment]
Shall we close this issue? Memoization of the projection should be left to a different algorithm, and as Eric said: 

> A better solution is to put an upper bound on the number of times the projection is called.

**Comment by ericniebler** [comment]
Closing this, will use #198 as a placeholder for a general review of the algorithm complexity wrt #'s of projection invocation.
