### ISSUE TITLE
gcc --std=c++2a: zip view has problems with constness 

### ISSUE THREAD

**Issue by marehr** [ericniebler/range-v3#1480]
```c++
#include <algorithm>
#include <ranges>
#include <vector>

#include <range/v3/view/zip.hpp>

int main()
{
    // removing one const works again
    std::vector<char> const first_sequence{};
    std::vector<char> const second_sequence{};

    auto zip_view = ranges::views::zip(first_sequence, second_sequence);
    auto fn = [&] ([[maybe_unused]] auto && ch)
    {
    };
    std::ranges::for_each(zip_view, fn);
}
```

https://godbolt.org/z/kixrtN

I guess this has something to do with the missing overloads of `std::common_type`.

**Comment by ericniebler** [comment]
> I guess this has something to do with the missing overloads of `std::common_type`.

... and `std::common_reference`, right. There are lots of problems with using range-v3 with `std::ranges`, now that such implementations are actually a thing.
