### ISSUE TITLE
`set_intersection` w/o sorting should be harder

### ISSUE THREAD

**Issue by DerekTBrown** [ericniebler/range-v3#1484]
I recently encountered a strange condition when using `views::set_intersection` together with `std::unordered_map`:

**Repro:**
```cpp
TEST(RangesTest, IntersectWithUnorderedMap) {
  std::unordered_map<int32_t, std::string> mapOfValues = {
    {1, "1"},
    {2, "2"},
    {3, "3"},
    {4, "4"}
  };
  std::set<int32_t> setOfValues = {4,3,2,1};

  auto intersect = ranges::views::set_intersection(
    mapOfValues | ranges::views::keys, setOfValues) | ranges::to_vector;
  for(const auto& v : intersect){
    LOG(ERROR) << v;
  }
  EXPECT_EQ(intersect.size(), 4);
}
```

**Output:**

```
FAILURE
>       Expected: intersect.size()
>       Which is: 1
> To be equal to: 4
```

After reviewing the notes, I realized that `set_intersection` requires sorted ranges as input, which isn't something (at least I would have assumed).  Is there a way of adding a sorted "trait" to ranges, to give a compiler warning against this sort of thing?

**Comment by ericniebler** [comment]
I'm afraid not. The `std::set_*` algorithms have the same precondition. You really just need to know about it.
