### ISSUE TITLE
Const 'for_each' results does not define begin

### ISSUE THREAD

**Issue by FunMiles** [ericniebler/range-v3#1488]
I have been using range-v3 with general delight.
But yesterday I hit a strange cascading error message in a fairly complex composition of views.
I reduced it to a very simple issue. The result of a for_each, cannot be iterated upon when it is viewed as constant. Here is a really short example. C++17 on Mac OS 10.15.4 using either of the latest Apple clang++ or g++ 9.

I believe this is a bug. Am I wrong?

    #include <iostream>
    #include <range/v3/all.hpp>
    #include <string_view>

    std::string_view sub(const std::string &s, int i)
    {
	return {s.data() + i, 2};
    }

    int main()
    {
	using namespace ranges;
	std::vector n{3, 2, 5};

	std::string s{"Hello World!"};

	auto sr = views::for_each(n, [&](int i) { return sub(s, i); });
	for (auto i : sr)  // Compiles and works as expected
		std::cout << ' ' << i;
        std::cout << std::endl;

	const auto src = views::for_each(n, [&](int i) { return sub(s, i); });
	for (auto i : src)  // Will not compile, saying that no begin(...) exists
		std::cout << ' ' << i;

	std::cout << std::endl;

	return 0;
    }

**Comment by ericniebler** [comment]
It's not a bug. Many views are not const-iterable. Think of a view as an algorithm turned inside-out, so that the consumer steps the algorithm forward by advancing iterators. Many algorithms need mutable state in order to do their work. `views::for_each` is one such. The mutable state is stored in the view, and advancing the iterator mutates the state. Therefore, `views::for_each` is not const-iterable.

**Comment by FunMiles** [comment]
Shouldn't the state be stored in the iterator instead?
If the state is in the view, then the iterator shouldn't be copiable since you could have two iterators, increment one and mutating the view, invalidating the other iterator or invalidating the way a user think of that iterator. 
Yet the iterator can be copied and you can also call `begin()` more than once.
A quick test with the example above seems to indicate that the state of the view is not mutated.

**Comment by FunMiles** [comment]
@ericniebler can you answer the question about why the state is not in the iterator?
It seems to me that having the state in the view destroys the classical semantical understanding of an iterator that needs to be used in algorithm that need to keep an iterator in a back-state.
