### ISSUE TITLE
views::generate_n triggers -Wunused-result

### ISSUE THREAD

**Issue by invexed** [ericniebler/range-v3#1512]
I am attempting to use ```views::generate_n``` with a function declared with the ```nodiscard``` attribute, but the following member function in ```generate_n_view::cursor``` triggers ```-Wunused-result```:

```cpp
void next()
{
    RANGES_EXPECT(0 != rng_->n_);
    if(rng_->val_)
        rng_->val_.reset();
    else
        rng_->gen_();
    --rng_->n_;
}
```

What is the rationale behind discarding the result? i.e. ```rng_->gen_();```

**Comment by ericniebler** [comment]
> What is the rationale behind discarding the result? i.e. `rng_->gen_();`

That gets executed if the `generate` view's iterator is incremented twice without an intervening dereference. A value is generated and discarded.

This expression should be cast to `void` to avoid the warning. Thanks for the report.
