### ISSUE TITLE
iota range-check only for random-access iterators

### ISSUE THREAD

**Issue by kaba2** [ericniebler/range-v3#1513]
I am triggering this check from iota.hpp:431:

    check_bounds_(meta::bool_<totally_ordered_with<From, To>>{});

My iterators are bidirectional (not random access), and they are totally ordered. However, their ordering (in terms of <) is not related to whether one precedes another (in terms of ++). 

Background: my iterator wraps a pointer to a node in a tree-like data structure. The ordering is inherited from these pointers. The ordering operators are there so that I can use the iterators easily as keys in std::set and others. 

I don't expect non-random-access iterators to have any correspondence between the ordering given by the operators and the ordering given by the ++sequence.

Could it be changed so that this check is done only when the iterators are in addition random access?

**Comment by marehr** [comment]
Can you give a small example?

**Comment by ericniebler** [comment]
I am conflicted about this bug report. I'm inclined to say, "don't do that." If your bidirectional iterator provides relational operators, but they don't satisfy the semantic requirements that iterator-based algorithms expect, then at the very least that seems like asking for trouble.

> The ordering operators are there so that I can use the iterators easily as keys in std::set and others.

This seems like an excellent place to use a custom comparison function (2nd template parameter) to `std::set`.

Closing this "won't fix".
