### ISSUE TITLE
single view + transform view = to much const?

### ISSUE THREAD

**Issue by rrahn** [ericniebler/range-v3#1519]
Hi I ran into the following problem with the ranges library (also with the current gcc implementation).
 The following code emits the static assert even though I would expect not to:

```cpp
#include <concepts>
#include <range/v3/view/transform.hpp>
#include <range/v3/view/single.hpp>
#include <vector>

auto transform_v = [] (auto && v)
{
    static_assert(std::same_as<decltype(v), int &>);
    return v;
};

using range_t = decltype(ranges::views::single(0));  // falsely calls const qualified begin somewhere in stack
// using range_t = std::vector<int>; // OK, everyting as expected.
using transformed_view_t = decltype(std::declval<range_t &>() | ranges::views::transform(transform_v));
using ref_t = std::ranges::range_reference_t<transformed_view_t>;
```

This happens on the current trunk version of ranges v3 library.
Here is the godbolt link: https://godbolt.org/z/rMzfmi

Am I overlooking something?

**Comment by johelegp** [comment]
It works fine without the metaprogramming: https://godbolt.org/z/PuQyqr. I wonder what's going on.

**Comment by ericniebler** [comment]
It works if you specify the return type of the lambda. https://godbolt.org/z/eRv2Wj

The `transform` view has `const` and non-`const` overloads, and during overload resolution, the compiler checks the callability of the lambda with both `int&` and `int const&`. If you don't declare the lambda's return type, the compiler must deduce the return type by instantiating the body of the lambda. That's where you run into trouble.

**Comment by rrahn** [comment]
Many thanks for clarifying. This also makes sense. But what I don't get is why it does work if the `range_t` is a `std::vector<int>`. Should that not also trigger the check with `int const &`?

**Comment by ericniebler** [comment]
When you use a `vector<int>&` in a range pipeline, it gets converted into a `ref_view<vector<int>>`, which has pointer-like semantics. That is, it has shallow `const`. Whether a `ref_view` is `const` or non-`const`, its reference type is the same: `int&`. In contrast, a `single_view<int>` has deep `const`, because it stores the `int` by value.
