### ISSUE TITLE
Test failure with GCC 10.2.0

### ISSUE THREAD

**Issue by mymedia2** [ericniebler/range-v3#1545]
I tried to build and run auto-tests of recently released version 0.11.0, but an error occurred. Would you please look at this issue?

I noticed #1491, but the `RANGES_PREFER_REAL_CONCEPTS=OFF` CMake varible does not help :disappointed:. Build with GCC 9.3.0 goes fine.

[full build log](https://github.com/ericniebler/range-v3/files/5045035/range-v3_0.11.0-1.rc1_amd64.build.txt)

```
In file included from /tmp/tmp.UHSwF4F4qi/include/range/v3/range/concepts.hpp:37,
                 from /tmp/tmp.UHSwF4F4qi/include/range/v3/action/concepts.hpp:23,
                 from /tmp/tmp.UHSwF4F4qi/include/range/v3/range/conversion.hpp:23,
                 from /tmp/tmp.UHSwF4F4qi/test/view/chunk.cpp:16:
/tmp/tmp.UHSwF4F4qi/include/range/v3/iterator/concepts.hpp: In instantiation of 'constexpr const bool ranges::forward_iterator<ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor> >':
/tmp/tmp.UHSwF4F4qi/include/range/v3/range/concepts.hpp:90:5:   required by substitution of 'template<class T, bool CPP_true, typename std::enable_if<(forward_iterator<decltype (ranges::{anonymous}::begin(declval<Rng&>()))> && CPP_true), int>::type <anonymous> > char (& ranges::forward_range__concept_(concepts::detail::tag<T>*))[1] [with T = ranges::chunk_view_<debug_input_view<const int>, false>; bool CPP_true = true; typename std::enable_if<(forward_iterator<decltype (ranges::{anonymous}::begin(declval<Rng&>()))> && CPP_true), int>::type <anonymous> = <missing>]'
/tmp/tmp.UHSwF4F4qi/include/range/v3/range/concepts.hpp:96:27:   required from 'constexpr const bool ranges::forward_range<ranges::chunk_view_<debug_input_view<const int>, false> >'
/tmp/tmp.UHSwF4F4qi/include/range/v3/view/interface.hpp:180:9:   required by substitution of 'template<bool True, bool CPP_true, typename std::enable_if<(True && CPP_true), int>::type <anonymous>, typename std::enable_if<((! ranges::detail::has_fixed_size_<ranges::finite>) && CPP_true), int>::type <anonymous>, typename std::enable_if<(forward_range<typename ranges::detail::dependent_<<anonymous> >::invoke<ranges::chunk_view_<debug_input_view<const int, true>, false> > > && CPP_true), int>::type <anonymous> > constexpr bool ranges::view_interface<ranges::chunk_view_<debug_input_view<const int>, false>, ranges::finite>::empty<True, CPP_true, <anonymous>, <anonymous>, <anonymous> >() [with bool True = true; bool CPP_true = true; typename std::enable_if<(True && CPP_true), int>::type <anonymous> = <missing>; typename std::enable_if<((! ranges::detail::has_fixed_size_<ranges::finite>) && CPP_true), int>::type <anonymous> = <missing>; typename std::enable_if<(forward_range<typename ranges::detail::dependent_<<anonymous> >::invoke<ranges::chunk_view_<debug_input_view<const int, true>, false> > > && CPP_true), int>::type <anonymous> = <missing>]'
/tmp/tmp.UHSwF4F4qi/include/range/v3/range/primitives.hpp:258:86:   required by substitution of 'template<class R> static constexpr decltype ((bool)((R&&)(r).empty())) ranges::_empty_::fn::impl_(R&&, ranges::detail::priority_tag<2>) [with R = const ranges::chunk_view_<debug_input_view<const int>, false>&]'
/tmp/tmp.UHSwF4F4qi/include/range/v3/range/primitives.hpp:288:42:   required by substitution of 'template<class R> constexpr decltype (ranges::_empty_::fn::impl_((R&&)(r), (ranges::detail::priority_tag<2>)(<brace-enclosed initializer list>()))) ranges::_empty_::fn::operator()(R&&) const [with R = const ranges::chunk_view_<debug_input_view<const int>, false>&]'
/tmp/tmp.UHSwF4F4qi/include/range/v3/view/interface.hpp:81:9:   required by substitution of 'template<class ... As> char (& ranges::detail::_can_empty__requires_(concepts::detail::tag<As ...>*, decltype (& _can_empty__requires_test_<As ...>)))[1] [with As = {const ranges::chunk_view_<debug_input_view<const int, true>, false>}]'
/tmp/tmp.UHSwF4F4qi/include/range/v3/view/interface.hpp:88:13:   required from 'constexpr const bool ranges::detail::can_empty_<const ranges::chunk_view_<debug_input_view<const int>, false> >'
/tmp/tmp.UHSwF4F4qi/include/range/v3/view/interface.hpp:211:9:   required by substitution of 'template<bool True, bool CPP_true, typename std::enable_if<((True && can_empty_<const typename ranges::detail::dependent_<<anonymous> >::invoke<ranges::chunk_view_<debug_input_view<const int, true>, false> > >) && CPP_true), int>::type <anonymous> > constexpr ranges::view_interface<ranges::chunk_view_<debug_input_view<const int>, false>, ranges::finite>::operator bool<True, CPP_true, <anonymous> >() const [with bool True = true; bool CPP_true = true; typename std::enable_if<((True && can_empty_<const typename ranges::detail::dependent_<<anonymous> >::invoke<ranges::chunk_view_<debug_input_view<const int, true>, false> > >) && CPP_true), int>::type <anonymous> = <missing>]'
/tmp/tmp.UHSwF4F4qi/include/range/v3/view/chunk.hpp:341:40:   required from 'constexpr ranges::chunk_view_<Rng, false>::outer_cursor::inner_view ranges::chunk_view_<Rng, false>::outer_cursor::read() const [with Rng = debug_input_view<const int>]'
/tmp/tmp.UHSwF4F4qi/include/range/v3/detail/range_access.hpp:107:31:   required from 'static constexpr decltype (pos.read()) ranges::range_access::read(const Cur&) [with Cur = ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor; decltype (pos.read()) = ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor::inner_view]'
/tmp/tmp.UHSwF4F4qi/include/range/v3/iterator/basic_iterator.hpp:599:38:   required from 'constexpr concepts::return_t<typename ranges::detail::iterator_associated_types_base_<Cur, (bool)(readable_cursor<Cur>)>::const_reference_t, typename std::enable_if<((readable_cursor<Cur> && (! is_writable_cursor_v<Cur>)) && CPP_true_fn(concepts::detail::Nil{})), void>::type> ranges::basic_iterator<Cur>::operator*() const [with bool (& CPP_true_fn)(concepts::detail::xNil) = concepts::detail::CPP_true_fn; Cur = ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor; concepts::return_t<typename ranges::detail::iterator_associated_types_base_<Cur, (bool)(readable_cursor<Cur>)>::const_reference_t, typename std::enable_if<((readable_cursor<Cur> && (! is_writable_cursor_v<Cur>)) && CPP_true_fn(concepts::detail::Nil{})), void>::type> = ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor::inner_view; typename std::enable_if<((readable_cursor<Cur> && (! is_writable_cursor_v<Cur>)) && CPP_true_fn(concepts::detail::Nil{})), void>::type = void; typename ranges::detail::iterator_associated_types_base_<Cur, (bool)(readable_cursor<Cur>)>::const_reference_t = ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor::inner_view]'
/tmp/tmp.UHSwF4F4qi/include/range/v3/iterator/access.hpp:115:18:   required by substitution of 'template<class I, class, class R> constexpr decltype (static_cast<ranges::aux::move_t<R> >(ranges::aux::{anonymous}::move((* i)))) ranges::_iter_move_::fn::operator()(I&&) const [with I = const ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor>&; <template-parameter-1-2> = void; R = ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor::inner_view]'
/tmp/tmp.UHSwF4F4qi/include/range/v3/iterator/traits.hpp:54:49:   required by substitution of 'template<class I, bool CPP_true, typename std::enable_if<(same_as<ranges::detail::iter_reference_t_<const I, decltype (* declval<const I&>()), decltype (* declval<const I&>())&>, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&> > && CPP_true), int>::type <anonymous>, typename std::enable_if<(same_as<ranges::detail::iter_rvalue_reference_t<const I, ranges::detail::iter_reference_t_<const I, decltype (* declval<const I&>()), decltype (* declval<const I&>())&>, decltype (ranges::{anonymous}::iter_move(declval<const I&>())), decltype (ranges::{anonymous}::iter_move(declval<const I&>()))&>, ranges::detail::iter_rvalue_reference_t<I, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>, decltype (ranges::{anonymous}::iter_move(declval<I&>())), decltype (ranges::{anonymous}::iter_move(declval<I&>()))&> > && CPP_true), int>::type <anonymous>, typename std::enable_if<(common_reference_with<ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>&&, typename ranges::indirectly_readable_traits<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>::value_type&> && CPP_true), int>::type <anonymous>, typename std::enable_if<(common_reference_with<ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>&&, ranges::detail::iter_rvalue_reference_t<I, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>, decltype (ranges::{anonymous}::iter_move(declval<I&>())), decltype (ranges::{anonymous}::iter_move(declval<I&>()))&>&&> && CPP_true), int>::type <anonymous>, typename std::enable_if<(common_reference_with<ranges::detail::iter_rvalue_reference_t<I, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>, decltype (ranges::{anonymous}::iter_move(declval<I&>())), decltype (ranges::{anonymous}::iter_move(declval<I&>()))&>&&, const typename ranges::indirectly_readable_traits<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>::value_type&> && CPP_true), int>::type <anonymous> > char (& ranges::readable__concept_(concepts::detail::tag<T>*))[1] [with I = ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor>; bool CPP_true = true; typename std::enable_if<(same_as<ranges::detail::iter_reference_t_<const I, decltype (* declval<const I&>()), decltype (* declval<const I&>())&>, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&> > && CPP_true), int>::type <anonymous> = <missing>; typename std::enable_if<(same_as<ranges::detail::iter_rvalue_reference_t<const I, ranges::detail::iter_reference_t_<const I, decltype (* declval<const I&>()), decltype (* declval<const I&>())&>, decltype (ranges::{anonymous}::iter_move(declval<const I&>())), decltype (ranges::{anonymous}::iter_move(declval<const I&>()))&>, ranges::detail::iter_rvalue_reference_t<I, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>, decltype (ranges::{anonymous}::iter_move(declval<I&>())), decltype (ranges::{anonymous}::iter_move(declval<I&>()))&> > && CPP_true), int>::type <anonymous> = <missing>; typename std::enable_if<(common_reference_with<ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>&&, typename ranges::indirectly_readable_traits<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>::value_type&> && CPP_true), int>::type <anonymous> = <missing>; typename std::enable_if<(common_reference_with<ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>&&, ranges::detail::iter_rvalue_reference_t<I, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>, decltype (ranges::{anonymous}::iter_move(declval<I&>())), decltype (ranges::{anonymous}::iter_move(declval<I&>()))&>&&> && CPP_true), int>::type <anonymous> = <missing>; typename std::enable_if<(common_reference_with<ranges::detail::iter_rvalue_reference_t<I, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>, decltype (ranges::{anonymous}::iter_move(declval<I&>())), decltype (ranges::{anonymous}::iter_move(declval<I&>()))&>&&, const typename ranges::indirectly_readable_traits<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>::value_type&> && CPP_true), int>::type <anonymous> = <missing>]'
/tmp/tmp.UHSwF4F4qi/include/range/v3/iterator/concepts.hpp:155:9:   required from 'constexpr const bool ranges::indirectly_readable<ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor> >'
/tmp/tmp.UHSwF4F4qi/include/range/v3/iterator/concepts.hpp:329:9:   required from 'constexpr const bool ranges::input_iterator<ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor> >'
/tmp/tmp.UHSwF4F4qi/include/range/v3/range/concepts.hpp:82:5:   required by substitution of 'template<class T, bool CPP_true, typename std::enable_if<(input_iterator<decltype (ranges::{anonymous}::begin(declval<Rng&>()))> && CPP_true), int>::type <anonymous> > char (& ranges::input_range__concept_(concepts::detail::tag<T>*))[1] [with T = ranges::chunk_view<debug_input_view<const int> >; bool CPP_true = true; typename std::enable_if<(input_iterator<decltype (ranges::{anonymous}::begin(declval<Rng&>()))> && CPP_true), int>::type <anonymous> = <missing>]'
/tmp/tmp.UHSwF4F4qi/include/range/v3/range/concepts.hpp:88:21:   required from 'constexpr const bool ranges::input_range<ranges::chunk_view<debug_input_view<const int> > >'
/tmp/tmp.UHSwF4F4qi/test/view/chunk.cpp:41:9:   required from here
/tmp/tmp.UHSwF4F4qi/include/range/v3/iterator/concepts.hpp:334:9: error: the value of 'ranges::input_iterator<ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor> >' is not usable in a constant expression
  334 |         input_iterator<I> &&
      |         ^~~~~~~~~~~~~~~~~
/tmp/tmp.UHSwF4F4qi/include/range/v3/iterator/concepts.hpp:327:17: note: 'ranges::input_iterator<ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor> >' used in its own initializer
  327 |     CPP_concept input_iterator =
      |                 ^~~~~~~~~~~~~~
```

**Comment by manujinda** [comment]
Build fails with GCC 10.2.0 with and without  -DRANGES_PREFER_REAL_CONCEPTS=off flag for cmake.

`[ 72%] Building CXX object test/view/CMakeFiles/view.chunk.dir/chunk.cpp.o
In file included from /Users/manujinda/Downloads/range-v3/include/range/v3/range/concepts.hpp:37,
                 from /Users/manujinda/Downloads/range-v3/include/range/v3/action/concepts.hpp:23,
                 from /Users/manujinda/Downloads/range-v3/include/range/v3/range/conversion.hpp:23,
                 from /Users/manujinda/Downloads/range-v3/test/view/chunk.cpp:16:
/Users/manujinda/Downloads/range-v3/include/range/v3/iterator/concepts.hpp: In instantiation of 'constexpr const bool ranges::forward_iterator<ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor> >':
/Users/manujinda/Downloads/range-v3/include/range/v3/range/concepts.hpp:90:5:   required by substitution of 'template<class T, bool CPP_true, typename std::enable_if<(forward_iterator<decltype (ranges::{anonymous}::begin(declval<Rng&>()))> && CPP_true), int>::type <anonymous> > char (& ranges::forward_range__concept_(concepts::detail::tag<T>*))[1] [with T = ranges::chunk_view_<debug_input_view<const int>, false>; bool CPP_true = true; typename std::enable_if<(forward_iterator<decltype (ranges::{anonymous}::begin(declval<Rng&>()))> && CPP_true), int>::type <anonymous> = <missing>]'
/Users/manujinda/Downloads/range-v3/include/range/v3/range/concepts.hpp:96:27:   required from 'constexpr const bool ranges::forward_range<ranges::chunk_view_<debug_input_view<const int>, false> >'
/Users/manujinda/Downloads/range-v3/include/range/v3/view/interface.hpp:180:9:   required by substitution of 'template<bool True, bool CPP_true, typename std::enable_if<(True && CPP_true), int>::type <anonymous>, typename std::enable_if<((! ranges::detail::has_fixed_size_<ranges::finite>) && CPP_true), int>::type <anonymous>, typename std::enable_if<(forward_range<typename ranges::detail::dependent_<<anonymous> >::invoke<ranges::chunk_view_<debug_input_view<const int, true>, false> > > && CPP_true), int>::type <anonymous> > constexpr bool ranges::view_interface<ranges::chunk_view_<debug_input_view<const int>, false>, ranges::finite>::empty<True, CPP_true, <anonymous>, <anonymous>, <anonymous> >() [with bool True = true; bool CPP_true = true; typename std::enable_if<(True && CPP_true), int>::type <anonymous> = <missing>; typename std::enable_if<((! ranges::detail::has_fixed_size_<ranges::finite>) && CPP_true), int>::type <anonymous> = <missing>; typename std::enable_if<(forward_range<typename ranges::detail::dependent_<<anonymous> >::invoke<ranges::chunk_view_<debug_input_view<const int, true>, false> > > && CPP_true), int>::type <anonymous> = <missing>]'
/Users/manujinda/Downloads/range-v3/include/range/v3/range/primitives.hpp:258:86:   required by substitution of 'template<class R> static constexpr decltype ((bool)((R&&)(r).empty())) ranges::_empty_::fn::impl_(R&&, ranges::detail::priority_tag<2>) [with R = const ranges::chunk_view_<debug_input_view<const int>, false>&]'
/Users/manujinda/Downloads/range-v3/include/range/v3/range/primitives.hpp:288:42:   required by substitution of 'template<class R> constexpr decltype (ranges::_empty_::fn::impl_((R&&)(r), (ranges::detail::priority_tag<2>)(<brace-enclosed initializer list>()))) ranges::_empty_::fn::operator()(R&&) const [with R = const ranges::chunk_view_<debug_input_view<const int>, false>&]'
/Users/manujinda/Downloads/range-v3/include/range/v3/view/interface.hpp:81:9:   required by substitution of 'template<class ... As> char (& ranges::detail::_can_empty__requires_(concepts::detail::tag<As ...>*, decltype (& _can_empty__requires_test_<As ...>)))[1] [with As = {const ranges::chunk_view_<debug_input_view<const int, true>, false>}]'
/Users/manujinda/Downloads/range-v3/include/range/v3/view/interface.hpp:88:13:   required from 'constexpr const bool ranges::detail::can_empty_<const ranges::chunk_view_<debug_input_view<const int>, false> >'
/Users/manujinda/Downloads/range-v3/include/range/v3/view/interface.hpp:211:9:   required by substitution of 'template<bool True, bool CPP_true, typename std::enable_if<((True && can_empty_<const typename ranges::detail::dependent_<<anonymous> >::invoke<ranges::chunk_view_<debug_input_view<const int, true>, false> > >) && CPP_true), int>::type <anonymous> > constexpr ranges::view_interface<ranges::chunk_view_<debug_input_view<const int>, false>, ranges::finite>::operator bool<True, CPP_true, <anonymous> >() const [with bool True = true; bool CPP_true = true; typename std::enable_if<((True && can_empty_<const typename ranges::detail::dependent_<<anonymous> >::invoke<ranges::chunk_view_<debug_input_view<const int, true>, false> > >) && CPP_true), int>::type <anonymous> = <missing>]'
/Users/manujinda/Downloads/range-v3/include/range/v3/view/chunk.hpp:341:40:   required from 'constexpr ranges::chunk_view_<Rng, false>::outer_cursor::inner_view ranges::chunk_view_<Rng, false>::outer_cursor::read() const [with Rng = debug_input_view<const int>]'
/Users/manujinda/Downloads/range-v3/include/range/v3/detail/range_access.hpp:107:31:   required from 'static constexpr decltype (pos.read()) ranges::range_access::read(const Cur&) [with Cur = ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor; decltype (pos.read()) = ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor::inner_view]'
/Users/manujinda/Downloads/range-v3/include/range/v3/iterator/basic_iterator.hpp:599:38:   required from 'constexpr concepts::return_t<typename ranges::detail::iterator_associated_types_base_<Cur, (bool)(readable_cursor<Cur>)>::const_reference_t, typename std::enable_if<((readable_cursor<Cur> && (! is_writable_cursor_v<Cur>)) && CPP_true_fn(concepts::detail::Nil{})), void>::type> ranges::basic_iterator<Cur>::operator*() const [with bool (& CPP_true_fn)(concepts::detail::xNil) = concepts::detail::CPP_true_fn; Cur = ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor; concepts::return_t<typename ranges::detail::iterator_associated_types_base_<Cur, (bool)(readable_cursor<Cur>)>::const_reference_t, typename std::enable_if<((readable_cursor<Cur> && (! is_writable_cursor_v<Cur>)) && CPP_true_fn(concepts::detail::Nil{})), void>::type> = ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor::inner_view; typename std::enable_if<((readable_cursor<Cur> && (! is_writable_cursor_v<Cur>)) && CPP_true_fn(concepts::detail::Nil{})), void>::type = void; typename ranges::detail::iterator_associated_types_base_<Cur, (bool)(readable_cursor<Cur>)>::const_reference_t = ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor::inner_view]'
/Users/manujinda/Downloads/range-v3/include/range/v3/iterator/access.hpp:115:18:   required by substitution of 'template<class I, class, class R> constexpr decltype (static_cast<ranges::aux::move_t<R> >(ranges::aux::{anonymous}::move((* i)))) ranges::_iter_move_::fn::operator()(I&&) const [with I = const ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor>&; <template-parameter-1-2> = void; R = ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor::inner_view]'
/Users/manujinda/Downloads/range-v3/include/range/v3/iterator/traits.hpp:54:49:   required by substitution of 'template<class I, bool CPP_true, typename std::enable_if<(same_as<ranges::detail::iter_reference_t_<const I, decltype (* declval<const I&>()), decltype (* declval<const I&>())&>, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&> > && CPP_true), int>::type <anonymous>, typename std::enable_if<(same_as<ranges::detail::iter_rvalue_reference_t<const I, ranges::detail::iter_reference_t_<const I, decltype (* declval<const I&>()), decltype (* declval<const I&>())&>, decltype (ranges::{anonymous}::iter_move(declval<const I&>())), decltype (ranges::{anonymous}::iter_move(declval<const I&>()))&>, ranges::detail::iter_rvalue_reference_t<I, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>, decltype (ranges::{anonymous}::iter_move(declval<I&>())), decltype (ranges::{anonymous}::iter_move(declval<I&>()))&> > && CPP_true), int>::type <anonymous>, typename std::enable_if<(common_reference_with<ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>&&, typename ranges::indirectly_readable_traits<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>::value_type&> && CPP_true), int>::type <anonymous>, typename std::enable_if<(common_reference_with<ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>&&, ranges::detail::iter_rvalue_reference_t<I, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>, decltype (ranges::{anonymous}::iter_move(declval<I&>())), decltype (ranges::{anonymous}::iter_move(declval<I&>()))&>&&> && CPP_true), int>::type <anonymous>, typename std::enable_if<(common_reference_with<ranges::detail::iter_rvalue_reference_t<I, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>, decltype (ranges::{anonymous}::iter_move(declval<I&>())), decltype (ranges::{anonymous}::iter_move(declval<I&>()))&>&&, const typename ranges::indirectly_readable_traits<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>::value_type&> && CPP_true), int>::type <anonymous> > char (& ranges::readable__concept_(concepts::detail::tag<T>*))[1] [with I = ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor>; bool CPP_true = true; typename std::enable_if<(same_as<ranges::detail::iter_reference_t_<const I, decltype (* declval<const I&>()), decltype (* declval<const I&>())&>, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&> > && CPP_true), int>::type <anonymous> = <missing>; typename std::enable_if<(same_as<ranges::detail::iter_rvalue_reference_t<const I, ranges::detail::iter_reference_t_<const I, decltype (* declval<const I&>()), decltype (* declval<const I&>())&>, decltype (ranges::{anonymous}::iter_move(declval<const I&>())), decltype (ranges::{anonymous}::iter_move(declval<const I&>()))&>, ranges::detail::iter_rvalue_reference_t<I, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>, decltype (ranges::{anonymous}::iter_move(declval<I&>())), decltype (ranges::{anonymous}::iter_move(declval<I&>()))&> > && CPP_true), int>::type <anonymous> = <missing>; typename std::enable_if<(common_reference_with<ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>&&, typename ranges::indirectly_readable_traits<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>::value_type&> && CPP_true), int>::type <anonymous> = <missing>; typename std::enable_if<(common_reference_with<ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>&&, ranges::detail::iter_rvalue_reference_t<I, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>, decltype (ranges::{anonymous}::iter_move(declval<I&>())), decltype (ranges::{anonymous}::iter_move(declval<I&>()))&>&&> && CPP_true), int>::type <anonymous> = <missing>; typename std::enable_if<(common_reference_with<ranges::detail::iter_rvalue_reference_t<I, ranges::detail::iter_reference_t_<R, decltype (* declval<R&>()), decltype (* declval<R&>())&>, decltype (ranges::{anonymous}::iter_move(declval<I&>())), decltype (ranges::{anonymous}::iter_move(declval<I&>()))&>&&, const typename ranges::indirectly_readable_traits<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>::value_type&> && CPP_true), int>::type <anonymous> = <missing>]'
/Users/manujinda/Downloads/range-v3/include/range/v3/iterator/concepts.hpp:155:9:   required from 'constexpr const bool ranges::indirectly_readable<ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor> >'
/Users/manujinda/Downloads/range-v3/include/range/v3/iterator/concepts.hpp:329:9:   required from 'constexpr const bool ranges::input_iterator<ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor> >'
/Users/manujinda/Downloads/range-v3/include/range/v3/range/concepts.hpp:82:5:   required by substitution of 'template<class T, bool CPP_true, typename std::enable_if<(input_iterator<decltype (ranges::{anonymous}::begin(declval<Rng&>()))> && CPP_true), int>::type <anonymous> > char (& ranges::input_range__concept_(concepts::detail::tag<T>*))[1] [with T = ranges::chunk_view<debug_input_view<const int> >; bool CPP_true = true; typename std::enable_if<(input_iterator<decltype (ranges::{anonymous}::begin(declval<Rng&>()))> && CPP_true), int>::type <anonymous> = <missing>]'
/Users/manujinda/Downloads/range-v3/include/range/v3/range/concepts.hpp:88:21:   required from 'constexpr const bool ranges::input_range<ranges::chunk_view<debug_input_view<const int> > >'
/Users/manujinda/Downloads/range-v3/test/view/chunk.cpp:41:9:   required from here
/Users/manujinda/Downloads/range-v3/include/range/v3/iterator/concepts.hpp:334:9: error: the value of 'ranges::input_iterator<ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor> >' is not usable in a constant expression
  334 |         input_iterator<I> &&
      |         ^~~~~~~~~~~~~~~~~
/Users/manujinda/Downloads/range-v3/include/range/v3/iterator/concepts.hpp:327:17: note: 'ranges::input_iterator<ranges::basic_iterator<ranges::chunk_view_<debug_input_view<const int>, false>::outer_cursor> >' used in its own initializer
  327 |     CPP_concept input_iterator =
      |                 ^~~~~~~~~~~~~~
make[2]: *** [test/view/CMakeFiles/view.chunk.dir/chunk.cpp.o] Error 1
make[1]: *** [test/view/CMakeFiles/view.chunk.dir/all] Error 2
make: *** [all] Error 2`

**Comment by ericniebler** [comment]
After some changes I made today, it now works with `RANGES_PREFER_REAL_CONCEPTS=ON`, but still fails with `RANGES_PREFER_REAL_CONCEPTS=OFF`.
