### ISSUE TITLE
msvc 2019 no operator '|' matches these operands

### ISSUE THREAD

**Issue by imamushroom** [ericniebler/range-v3#1567]
I want to convert an `array<double*>` to a `vector<double>` so that I can do a `ranges::views::concat` on two vectors of the same type but I'm having difficulty doing this.

I have the following code:
```c++
#include <range/v3/all.hpp>
#include <array>

static constexpr auto max_elements = 2000;

struct PriceInfo
{
    std::array<double*, max_elements> prices;
};

auto main() -> int
{
    auto a = std::array<double,3>{1.0, 2.0, 3.0};
    PriceInfo* const buf = nullptr;
    buf->prices[0] = &a[0];
    buf->prices[1] = &a[1];
    buf->prices[2] = &a[2];
    const PriceInfo* const buf_prices = buf;
    const auto vec = buf_prices->prices 
                   | ranges::views::indirect 
                   | ranges::to_vector;
}
```

When I compile I'm getting the following errors and I don't understand why as I believe my code is correct, at least it compiles errorfree under gcc.

```
Error (active) E0349 no operator "|" matches these operands
operands types are: const std:array<double*, 2000U> | const ranges::views:views_closure<ranges::views:indirect_fn>
```

How do I fix this error please?

Godbolt play area: https://godbolt.org/z/K1aWq6

**Comment by CaseyCarter** [comment]
> How do I fix this error please?

The "E" in E3049 indicates this is an error message from IntelliSense (the compiler-like thing in Visual Studio that decides where to draw squiggles in your source), not from the "real" compiler. The lack of "CXXXX" messages indicates that this program _is_ compiling successfully.

I suggest you [file an issue over at Developer Community](https://developercommunity.visualstudio.com/content/problem/post.html?space=62) for the IntelliSense bug.

**Comment by ericniebler** [comment]
Thanks Casey.
