### ISSUE TITLE
[Q] views::remove_if pred invoked more times

### ISSUE THREAD

**Issue by silverqx** [ericniebler/range-v3#1591]
Hi, I want to ask if is normal that a predicate called by `views::remove_if` is invoked more times for one element in the container.

```
QVector<int> a {4};
QVector<int> b {1, 2, 3, 4};

auto rng = b | ranges::views::remove_if([&a](auto value)
{
    auto contains = a.contains(value);
    qDebug() << value << ":" << contains;
    return contains;
});

auto final = a + ranges::to<QVector<int>>(rng);
qDebug() << final;
```

Output:
```
1 : false
2 : false
3 : false
4 : true
2 : false
3 : false
4 : true
QVector(4, 1, 2, 3)
```

Another case is that if the `views::remove_if` predicate returns true for every element, then the predicate is `called == container.size()`, in other words, is called the same times as the count of elements in the container.

I'm asking because I would expect that predicate will be called as many times as items in the container in every case.

Thank you for your clarification. 🙏

**Comment by ericniebler** [comment]
I suspect this behavior is caused by the QVector constructor. It probably traverses the range once to compute the size, does a single allocation, then traverses the range a second time to fill the vector.

**Comment by silverqx** [comment]
I tried it now with std::vector and it behaves the same way, of course, optimal would be to invoke pred only once for every item.

**Comment by johelegp** [comment]
`remove_if` is a forward but not random access range, so the vectors must be calculating their size first to preallocate memory before copying the elements.

**Comment by silverqx** [comment]
> `remove_if` is a forward but not random access range, so the vectors must be calculating their size first to preallocate memory before copying the elements.

Thx for the clarification, from your answers it seems that this behavior is desirable and remove_if works like it should.
