### ISSUE TITLE
drop_last - source range with fewer elements than to be dropped

### ISSUE THREAD

**Issue by szilardszaloki** [ericniebler/range-v3#1598]
Shouldn't `drop_last` produce an empty range if the source range has fewer elements than to be dropped?
(_"Given a source range and an integral count, return a range consisting of all but the last count elements from the source range, or an empty range if it has fewer elements."_ - https://ericniebler.github.io/range-v3/index.html#autotoc_md8)
```
for (std::vector one{ 1 }; auto i : one | ranges::views::drop_last(2)) {
    std::cout << i;
}
```
drop_last.hpp(53): `RANGES_EXPECT(initial_size >= n);`
https://godbolt.org/z/81Kvs8

**Comment by JohelEGP** [comment]
@ericniebler This can be closed.
