### ISSUE TITLE
Should the deprecated random_shuffle be removed?

### ISSUE THREAD

**Issue by rhalbersma** [ericniebler/range-v3#160]
Now that range-v3 itself does not use `random_shuffle` anywhere in its implementation and unit tests, it is possible to remove `algorithm::random_shuffle` from range-v3. 

One argument against this would be that `std::random_shuffle` is only deprecated from C++14 and beyond. On the other hand, the recommended migration route of `std::shuffle` is already available in C++11. This migration is also fully supported in range-v3 via both an algorithm and an action, whereas `random_shuffle` is only half-heartedly supported (no action, only an algorithm). 

So it seems that range-v3 could safely remove `random_shuffle` without too much pain on either its C++11 or it C++14 users.

**Comment by ericniebler** [comment]
I actually don't understand why the committee chose to deprecate `random_shuffle` instead of requiring it to use a random number generator that doesn't suck, like `mt19937` seeded with `random_device`. It's a useful wrapper. I see no reason to remove it, but perhaps I'm missing something.

**Comment by rhalbersma** [comment]
The committee not just deprecated `random_shuffle`, but, based on [N4190](https://isocpp.org/files/papers/N4190.txt), the current working paper actually *removes* it altogether, see [diff.cpp14.depr] in [N4296](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf): 

>The class templates auto_ptr, unary_function, and binary_function, **the function templates     random_shuffle**, and the function templates (and their return types) ptr_fun, mem_fun, mem_fun_ref, bind1st, and bind2nd **are not defined**.

A C++11/14/17 library should then follow suit and remove them as well.

But I agree that wrapping the generator is convenient. AFAICS, the wrapping `random_shuffle` overload that you define already uses a uniform random generator. So couldn't that be simply ported to a new wrapping `shuffle` overload? That could then be part of a future committee proposal or STL2.

**Comment by CaseyCarter** [comment]
Thread-safety. It's too late to change `random_shuffle` to either (a) use a `mutex` and a global engine, or (b) use a `thread_local` engine. Either choice is a breaking change. As is changing the engine: it would break reproducability of results. [N4316](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4316.html) provides an overload of `shuffle` that uses a `thread_local` engine to provide the same interface that `random_shuffle` did.

**Comment by rhalbersma** [comment]
It appears that N4316 did not make it into the in-progress working draft [N4527](https://github.com/cplusplus/draft/blob/master/papers/n4527.pdf)

**Comment by CaseyCarter** [comment]
IIRC, LEWG voted to forward the paper to LWG after we fiddled with it a bit. I don't know if LWG got around to it or not, their were some wording (grammatical) issues.

**Comment by rhalbersma** [comment]
So, should we rename the useful wrapping `random_shuffle` overload to `shuffle` and remove the former (and hope the committee catches up with it)?

**Comment by ericniebler** [comment]
Looks like the committee is already working on it. See [n4531](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4531.html). We should track this.

**Comment by rhalbersma** [comment]
[N4531 has been accepted for LibFundamentals V2](https://www.reddit.com/r/cpp/comments/3q4agc/c17_progress_update_oct_2015/)
