### ISSUE TITLE
ranges::max behavior seems to be wrong with custom compare

### ISSUE THREAD

**Issue by hewillk** [ericniebler/range-v3#1623]
Hey, in the following example, I think the return value of `ranges::max` should be `1`, correct me if i am wrong.

https://godbolt.org/z/rq6oasbea

```
#include <algorithm>
#include <range/v3/algorithm.hpp>

struct Comp {
  constexpr bool operator()(auto, auto) const { return true; };
} cmp;

static_assert(        std::max(0, 1, cmp) == 1);
static_assert(std::ranges::max(0, 1, cmp) == 1);
static_assert(     ranges::max(0, 1, cmp) == 0);
```

**Comment by roibarkan** [comment]
I believe that both std::max() and std::ranges::max() are technically undefined behavior when the comparator isn't a strict-weak-ordering relation
