### ISSUE TITLE
Ranges do not work with C++17 end sentinels

### ISSUE THREAD

**Issue by dchansen** [ericniebler/range-v3#1626]
In c++17, `end()` is allowed to return a sentinel which must be equality comparable to the iterator returned by `begin()`.
This is not accurately modelled by range-v3, and such a class does not meet the `range` concept when compiled under C++17. Note that it works as expected under C++20.

[Godbolt link](https://godbolt.org/z/n965bE9zd)

**Comment by dvirtz** [comment]
you're missing the reverse order comparators:
https://godbolt.org/z/c9bYGEx77

**Comment by dchansen** [comment]
You're absolutely right. Why aren't they needed in c++20?

**Comment by dvirtz** [comment]
The compiler now generates them for you. See
https://brevzin.github.io/c++/2019/07/28/comparisons-cpp20/#reversing-primary-operators
