### ISSUE TITLE
strongly against standardisation of the current `views::group_by`

### ISSUE THREAD

**Issue by huixie90** [ericniebler/range-v3#1637]
views::group_by seems to be on the plan for c++23 according to this paper.
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2214r0.html

However, I think there are two problems with this view:
1. naming
2. which elements the predicate is evaluated against.

First issue, naming.
"group_by", by its name, suggests that it takes a unary key function. For example, group the students by their age. I'd expect something like
```
for (const auto&[age, group] : students | group_by(&student::age)){
   // ...
}
```
Here are examples of some libraries of other programming languages
Java  [`Collectors.GroupingBy`](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#groupingBy-java.util.function.Function-)
Python [`itertools.groupby`](https://docs.python.org/3/library/itertools.html#itertools.groupby)

Those group_by functions take unary key function. 

However, range-v3 `group_by` takes a binary predicate. The idea is to group a sequence of elements. If the two elements satisfy the predicate, they will be grouped together
My suggestion is to rename it to `views::group_if`

```
for (const auto group : elements | group_if(std::equal_to{})){
  // ...
}
```

Second issue, which elements the predicate is evaluated against.
In range-v3 implementation, the binary predicate is evaluate between the first element in the group and the current element. But I'd expect the predicate is evaluated between adjacent elements, i.e. the previous element and the current element. For operations that are transitive, e.g. `equal_to`,  it doesn't really matter. Because, if the first element in the group equals to the current element, the previous element also equals to the current element. But for operators that are not transitive, this is problematic. For example, I'd like to find groups that have increasing numbers

```
    std::vector v{10,15,19, 6,9,8};
    for(const auto group : v | ranges::views::group_by(std::less{})){
        for (const auto i : group){
            std::cout << i  << ' ';
        }
        std::cout << '\n';
    }
```
I'd expect the output to be
10 15 19
6 9
8

But the output is
10 15 19
6 9 8

[godblot](https://godbolt.org/z/KejjcbfW9)

**Comment by huixie90** [comment]
I sent a pull request to change the group_by view to evaluate predicates on adjacent elements
https://github.com/ericniebler/range-v3/pull/1647

**Comment by huixie90** [comment]
> That would be a silent breaking change. I would rather we provide a better view with a better name and deprecate views::group_by.

Hmm if the version proposed to the standard is adjacent version, I think it is a good idea to update range-v3 even it is a breaking change. Anyway, I think the majority use case is the case where predicate is transitive (e.g. , equal_to) where it doesn’t t matter which element was compared against. I can hardly think of a real use case where the predicate needs to be called with the first element in the group.  

Another approach is to use a different name. What do you think about ‘group_if’

**Comment by huixie90** [comment]
> That would be a silent breaking change. I would rather we provide a better view with a better name and deprecate views::group_by.

@ericniebler  what about `adjacent_group`  (or `adjacent_group_if`)? It does what it says, i.e. group adjacent items.  the original name `group_by` might give an impression that it does the dictionary thing where order of elements doesn't matter (especially if we support unary key function version). For example, one might think the algorithm might group `A B A` into `A A` and `B`. 

regarding the binary predicate vs unary key function, yes I realise that binary predicate is a more generic form. One can easily create a binary predicate from a unary key function 
`const auto pred = std::equal_to<>{} ^ boost::hana::on ^ my_key_fn;`

**Comment by ericniebler** [comment]
@codereport can you chime in here? I think you were in favor of the name `chunk_by`?

**Comment by codereport** [comment]
There is a [section in the "A Plan for C++23 Ranges" (P2214)](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2214r0.html#the-group_by-family) that talks about the `group_by` family. The consensus at the moment is that we will be going with:

* `chunk_by` (takes a binary predicate && compares adjacent elements)
* `chunk_on` (takes a unary transform)

___

From the paper:

> In Haskell, the second 1 starts a new group because we’re comparing it with its previous element and 3 <= 1 is false. But in range-v3, the second 1 does not start a new group because we’re comparing it with the first element of the group, and 1 <= 1 is true. **We think the Haskell/Elixir/D choice is more familiar and more useful.**

and also

> Given the time and bandwidth pressure, we think the top priority is the binary group_by and the unary form, while still very useful, should be a Tier 2 addition. As far as naming goes, there two approaches we could take:
>- group_by takes a binary predicate and either group_on or group_by_key takes a unary transform.
>- **chunk_by takes a binary predicate and chunk_on takes a unary transform.**

There isn't a paper currently for this but there was a recent discussion and agreement in the `#include` discord algorithm channel on July 5, 2021. I hope Sy is ok with me posting this here:

![image](https://user-images.githubusercontent.com/36027403/129988243-91f41a83-c972-43a7-a6ec-d4e0206d3a63.png)

**Comment by huixie90** [comment]
@ericniebler , I've sent another PR which follows Conor's @codereport  suggestion to use the name `chunk_by`
https://github.com/ericniebler/range-v3/pull/1648

regarding `chunk_on`, what would the resultant range look like? Is it just  [[T]] or [Key, [T]] ?
If it is just [[T]], then we don't need to implement anything
```
chunk_on(key_fn) == chunk_by(hana::on(equal_to, key_fn))
```

**Comment by codereport** [comment]
@huixie90 That is exactly correct. A simple Haskell impl would be:

```hs
import Data.List.HT (groupBy)
import Data.Function (on)

chunkOn keyFn = groupBy ((==) `on` keyFn)
chunkOn even [2, 4, 1, 3, 5, 6] -- [[2,4],[1,3,5],[6]]
```

**Comment by Aster89** [comment]
Fyi, the "ambiguity" about which elements the predicate is evaluated against (current and previous vs current and first)  [is also in Haskell](https://stackoverflow.com/questions/64248500/groupby-like-function-such-that-the-binary-predicate-holds-between-consecutive-e), but there they didn't create a function with a different name, just a namesake in another package.
```haskell
λ> Data.List.groupBy (\x y -> y - x == 1) [1,2,3,7,8,9] -- pred evaluated vs first
[[1,2],[3],[7,8],[9]]
λ> Data.List.GroupBy.groupBy (\x y -> y - x == 1) [1,2,3,7,8,9] -- pred evaluated vs previous
[[1,2,3],[7,8,9]]
```

**Comment by ericniebler** [comment]
> regarding chunk_on, what would the resultant range look like? Is it just [[T]] or [Key, [T]] ?

I think `[[T]]` is right. If other languages did it different, it would give me pause, though.

**Comment by BRevzin** [comment]
> > regarding chunk_on, what would the resultant range look like? Is it just [[T]] or [Key, [T]] ?
> 
> I think `[[T]]` is right. If other languages did it different, it would give me pause, though.

Swift does `[[T]]`. 

But D, Python, and Rust all do `[(Key, [T])]`.  This seems like the more useful behavior, especially if calculating the key is expensive.
