### ISSUE TITLE
Macro for inline variables?

### ISSUE THREAD

**Issue by rhalbersma** [ericniebler/range-v3#167]
Should the `constexpr` reference trickery for global function objects be wrapped inside a macro, like this?

    #define RANGES_INLINE_DEFAULTED_VARIABLE(var, type)     \  
    namespace                                               \          
    {                                                       \
        constexpr auto&& var = static_const<type>::value;   \
    }                                                       \

This macro can be called like e.g. `RANGES_INLINE_DEFAULTED_VARIABLE(join, view<join_fn>)` in `ranges/v3/view/join.hpp`, and similarly for the other views and actions. 

Apart from keeping the current implementation magic in one place, this has the added benefit of making it easier for future upgrades to [N4424](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4424.pdf) style `inline` variables, for which the macro would then delegate to 

    inline constexpr auto var = type{};

**Comment by ericniebler** [comment]
I don't like macros and try to use them as sparingly as possible. If we get inline variables (or better, if the ODR is changed so that a `constexpr` global does the right thing), then I'll just change the code and be done with it.
