### ISSUE TITLE
Formally cut a new release

### ISSUE THREAD

**Issue by offbynull** [ericniebler/range-v3#1694]
The last release was 0.11.0 in 2020. It looks like many changes/fixes have come in since then. Would it be possible to cut a new release? Maybe 0.11.1 or 0.12.0? Many of us use range-v3 through a dependency manager like conan, which as far as I'm aware supplies "official" releases only.

**Comment by ericniebler** [comment]
> Is there a formal(ish?) list of todos that are pending before a new release is made?

A summary of the changes since the last release, for the release notes.

Fwiw, I agree it's long past time for a new release.

**Comment by david-fong** [comment]
(I know there's the git way to view commit ranges) [Here's a github link](https://github.com/ericniebler/range-v3/search?o=desc&q=committer-date%3A%3E2020-08-06&s=committer-date&type=commits) if anyone's interested in seeing commits after the date of the 0.11.0 release via github.

**Comment by ericniebler** [comment]
Version 0.12.0 released today.
