### ISSUE TITLE
Improvements to algorithms that throw away information

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#171]
`binary_search`, [`contains`](http://www.reddit.com/r/cpp/comments/31167m/c17s_stl_what_do_you_want_it_to_have/cpxmyj1), `is_partitioned`, `is_sorted`, `is_heap`  are very ergonomic algorithms that just return a `bool` if the range contains a particular element. 

OTOH they are not as useful as `find/find_if/...`, `lower_bound/upper_bound/...`, `is_sorted_until`, `is_heap_until` because they throw away information. One can even argue that `binary_search` and `contains` might encourage encourage bad performance and even quadratic algorithms. 

If they were to return an `optional<Iterator>` instead, we could have the cake and eat it too:

```c++
template<typename I, typename S, typename V2, typename C = ordered_less,
      typename P = ident,
      CONCEPT_REQUIRES_(IteratorRange<I, S>() && BinarySearchable<I, V2, C, P>())>
optional<I> binary_search(I begin, S end, V2 const &val, C pred = C{}, P proj = P{}) {
    begin = lower_bound(std::move(begin), end, val, pred, proj);
    auto &&ipred = as_function(pred);
    auto &&iproj = as_function(proj);
    return begin != end && !ipred(val, iproj(*begin))? optional<I>{begin} : optional<I>{};
}
```

This is probably a breaking change, but a minor one since `optional` has an `explicit operator bool()`. 

I went through the library and the following algorithms might benefit from returning an `optional`:
- `binary_search`
- `is_partitioned`
- `is_sorted` (making it equivalent to `is_sorted_until`)
- `is_heap` (making it equivalent to `is_heap_until`)

**Comment by ericniebler** [comment]
There already are algorithms to use if you want to know the actual position. lower-/upper_bound, partition_point, is_sorted_until, is heap_until. We don't need to change these algorithms.

**Comment by gnzlbg** [comment]
> There already are algorithms to use if you want to know the actual position.

But there isn't an algorithm that computes if an element is in a sequence (in the spirit of `binary_search`, that is, returning a `bool`). It is possible to write one and make it return a `bool`, but `optional` provides an alternative worth considering, and would make this algorithm unnecessary.

**Comment by ericniebler** [comment]
I already answered this. Use either lower_bound or upper_bound.
