### ISSUE TITLE
Problem when sort a zip-view?

### ISSUE THREAD

**Issue by dangdkhanh** [ericniebler/range-v3#1727]
Hi, from this [post ](https://stackoverflow.com/a/30419985/14155740)
I get an error when compiling as upload image (has it changed on newer version?)

![image](https://user-images.githubusercontent.com/99936463/180504028-e3ca34e0-f4be-424b-bcf5-856c94d1b701.png)

Another issue is whether I can write predicate as a lambda? because I have some external parameters
Something like this:
```
sort(zipped, [](auto &&a, auto &&b) {
//...
}
```
Unfortunately, this code also fails to compile.
How do I fix them?

Thanks you.

**Comment by brevzin** [comment]
As with the last time, please provide a [minimal and reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in code, not as a screenshot. 

My best guess as to what your code is [compiles and runs fine](https://godbolt.org/z/6hMaaYenn).

**Comment by dangdkhanh** [comment]
Hi @brevzin ,
Sorry, I tried it and it actually works despite the red warning appearing.
The error I got turned out to be from another location.
This is exactly what I expected. 

Thank you.
