### ISSUE TITLE
GCC and std=c++20 flag, ambiguous

### ISSUE THREAD

**Issue by LeHibou2** [ericniebler/range-v3#1735]
Hi,

How can I get rangev3 to work with gcc 12.2 and the std=c++20 flag?

I cannot decrease the standard requirement and I need the cyclic view.
I am willing to dump the std::ranges in favor of v3.

Please have a look at the issue I am talking about:
[godbolt link](https://godbolt.org/z/Trb7c5o5E)

Thanks

**Comment by dvirtz** [comment]
As you can see in the compiler output, there's an ambiguity between `std::ranges` and (range-v3) `::ranges` namespaces.
If you drop the `using namespace std;` statement it will unambiguously choose range-v3's namespace.
https://godbolt.org/z/5rac63M5G

**Comment by LeHibou2** [comment]
Thanks, 
So no way to keep the `using namespace std`?
No workaround?

**Comment by dvirtz** [comment]
The other solution is to fully qualify `using namespace ::ranges;`
https://godbolt.org/z/5d1fT7E7r

**Comment by LeHibou2** [comment]
Great, thank you !
