### ISSUE TITLE
different result for range move with std

### ISSUE THREAD

**Issue by LeHibou2** [ericniebler/range-v3#1740]
Hi,
Is the result difference expected?

[godbolt](https://godbolt.org/z/q4Moq67Y6)

Cheers

**Comment by JohelEGP** [comment]
No. It's a bug.

**Comment by JohelEGP** [comment]
A bug in your code. See https://en.cppreference.com/w/cpp/algorithm/ranges/move.
> The behavior is undefined if result is within the range [first, last).

**Comment by LeHibou2** [comment]
Right, missed that one thanks!
