### ISSUE TITLE
chunk, but forcing stride?

### ISSUE THREAD

**Issue by LumiereDeLOmbre** [ericniebler/range-v3#1744]
Hi,

```
auto vector<int> container {0,1,2,3,4};
auto a = container | ::ranges::views::cycle | ::ranges::views::chunk(2);
```

gives [0,1], [2,3] and so on.

I need [0,1], [1,2], [2,3] and so on.

What is the cleanest way to do that?
Thanks,

**Comment by JohelEGP** [comment]
https://eel.is/c++draft/range.slide#overview-example-1

**Comment by LumiereDeLOmbre** [comment]
@JohelEGP thanks, and you are right about the section. That's a misfit.
