### ISSUE TITLE
bug: some easy operator to change the data-vector

### ISSUE THREAD

**Issue by JWleo** [ericniebler/range-v3#1769]
**gcc version :8.5.0
os: centos7
rangev3 version:newest(0.12.0)**

**picture #1: the code just like below**
![range_bug](https://user-images.githubusercontent.com/32316654/219319560-a9d97bfd-62db-4cab-bde3-b6da15a6fde2.PNG)

**picture #2:the result is from upper code.**
![range-result](https://user-images.githubusercontent.com/32316654/219319576-48a2262c-4699-4e0b-92bf-6d59bab4d745.PNG)

**the easy operator:obj += 100;
the action changes the size of array-data.
origin_array:[3,6,9];
changed_array:[103].**

**Comment by brevzin** [comment]
Please don't submit issues as images, submit them as text. Also some actual description of what the issue would help. 

Yes, mutating a `filter` while you're iterating over it will break the behavior of that `filter` if you attempt to reuse it. Don't do that.
