### ISSUE TITLE
C++23's range_adaptor_closure equivalent

### ISSUE THREAD

**Issue by stripe2933** [ericniebler/range-v3#1804]
Hello, is there any equivalent for C++23's `range_adaptor_closure`? It would be good to make user defined class inherits its CTRP parent so that reduce boilerplate for `operator|`.

**Comment by brevzin** [comment]
range-v3 has one, it just looks a little different. You can see the description [in the paper](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2387r3.html#range-v3). 

Basically you write:

```cpp
namespace ranges::views {
  struct join_view_fn {
    template <viewable_range R>
        requires /* ... */
    constexpr auto operator(R&& r)
        -> join_view<all_t<R>>;
  };

  // for user consumption
  inline constexpr view_closure<join_view_fn> join{};
}
```

instead of:

```cpp
namespace ranges::views {
  struct join_view_fn : range_adaptor_closure<join_view_fn> {
    template <viewable_range R>
        requires /* ... */
    constexpr auto operator(R&& r)
        -> join_view<all_t<R>>;
  };

  // for user consumption
  inline constexpr join_view_fn join{};
}
```

**Comment by stripe2933** [comment]
Thank you for your answer.
