### ISSUE TITLE
Is there an approach to concat 2 vector?

### ISSUE THREAD

**Issue by dangdkhanh** [ericniebler/range-v3#1820]
Hi,
Is there an efficient way to concatenate 2 vectors but in element order with range-v3?
vector v1{1,2,3};
vector v2{4,5,6};
output : {1,4,2,5,3,6};

Thanks you!

**Comment by brevzin** [comment]
The calendar example has an `interleave_view` which is what you're looking for, but nothing in the library proper: https://github.com/ericniebler/range-v3/blob/53c40dd628450c977ee1558285ff43e0613fa7a9/example/calendar.cpp#L189-L251

**Comment by dangdkhanh** [comment]
Hi @brevzin ,
Thank you. I missed it.
