### ISSUE TITLE
BinarySearchable too strict

### ISSUE THREAD

**Issue by blindley** [ericniebler/range-v3#185]
The binary search based functions all require the `BinarySearchable` concept, which requires all 6 comparison operators (due to `BinarySearchable` requiring the searched value type to be `TotallyOrdered`), even if you use a custom comparison predicate. So, this simple example doesn't compile:

    struct my_int {
        int value;
    };

    bool compare(my_int lhs, my_int rhs) {
        return lhs.value < rhs.value;
    }

    int main() {
        std::vector<my_int> vec;
        ranges::lower_bound(vec, my_int{10}, compare);
    }

I would expect that if you can sort a range, you should be able to binary search it using the same predicate you sorted by.

**Comment by ericniebler** [comment]
The constraints on `lower_bound` and `upper_bound` were copied directly from the N3351, but it seems to be a mistake there. Thanks for the report.
