### ISSUE TITLE
Output algorithms (copy, fill_n, etc...) don't work with standard output iterators.

### ISSUE THREAD

**Issue by blindley** [ericniebler/range-v3#189]
#include <iterator>
    #include <vector>
    #include <range/v3/all.hpp>

    int main() {
        std::vector<int> vec;
        ranges::fill_n(std::back_inserter(vec), 0, 0);
    }

This fails to compile with:

    .../range/v3/utility/concepts.hpp:731:15: error: no type named 'type' in 'struct std::enable_if<false, int>'
         >::type = 0
         \
                   ^
    .../range/v3/algorithm/fill_n.hpp:34:17: note: in expansion of macro 'CONCEPT_REQUIRES_'
                     CONCEPT_REQUIRES_(WeakOutputIterator<O, V>())>
                     ^

The algorithm works fine with forward iterators or better.

**Comment by ericniebler** [comment]
This is by design. Std::back_insert_iterator does not model the Iterator concept of range-v3. Use ranges::back_inserter instead.
