### ISSUE TITLE
Make view::join single_pass for input ranges only?

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#191]
Right now `view::join` iterators are always [`single_pass`](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/view/join.hpp#L98). 

As a consequence:

```c++
auto rng = view::iota(0, 4) | view::transform([](auto&& i) { return view::iota(i, i * 2); })
                            | view::join;

static_assert(ForwardRange<decltype(rng)>{}, "rng is not even a forward range :( :(");
```

~~Is this intended (that is, are `join` views _always_ single pass)? Or would it make sense to compute `single_pass` for `view::join` as follows instead:~~

~~`using single_pass = SinglePass<range_iterator_t<Rng>>;`~~

~~I would expect `rng` above to model `BidirectionalRange`, which it does if `single_pass` in the adaptor is defined as proposed.~~

EDIT: it seems that this is the intended behavior.

**Comment by ericniebler** [comment]
It is. The join view must maintain mutable state in the view object itself. As such, it's single-pass.

**Comment by gnzlbg** [comment]
IIUC it maintains "a view of the current sub-range being traversed" (`cur_`) in the view object itself. 

I am asking myself why this is maintained in the range and not in the iterator. Is it to make the iterator thinner? Or maybe there is a case in which this view cannot be maintained inside the iterator?

**Comment by ericniebler** [comment]
What happens when you copy a `view::join` iterator? Then the two iterators have two different copies of the sub-range currently being traversed. That doesn't work. Iterators need to point into the *same* range object.

**Comment by gnzlbg** [comment]
I was thinking that they could hold an iterator into the range of ranges.

So the view::join has the range of ranges, and the view::join::iterators have two iterators, one into the view of ranges, which denotes a particular range, and one into an element of that range. 

Spelling this out loud sounds complicated.

**Comment by ericniebler** [comment]
It doesn't work unless the outer inner returns by lvalue reference. (There's a comment in the code to that effect, I believe. Yep, [here](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/view/join.hpp#L155).) If the reference type of the range-of-ranges is an rvalue, then you need to save the temporary range somewhere until you have iterated over it.

**Comment by gnzlbg** [comment]
Ah crap, good point. My example above can never work then because no matter where we store that temporary range we run into problems:

- if it is stored in the view::join, then it cannot be multi pass because different iterators will try to modify it,
- if it is stored in the iterator, different iterators to the "same element" will point into different ranges.

Reality strikes again.

**Comment by gnzlbg** [comment]
@ericniebler I think the following issue is related to this:   

```c++
 auto r = view::ints(0, 6)
               | view::transform([](auto&& i) { return view::ints(i, i + 2); })
               | view::join | view::filter([](auto&& i) { return i % 4 == 0; });
    std::cout << "d1: " << distance(r) << std::endl;  // 6
    std::cout << "d2: " << distance(r) << std::endl;  // 9
    std::cout << "d3: " << distance(r) << std::endl;  // 9
```

That is just a ~"minimal example" but when returning ranges from functions and chaining them with views one might forget that some ranges are single pass and do stuff like this. 

It would be nice if the code above would work as expected, but since from what I recall from this discussion that cannot work, it would be nice if at least a run-time assertion could be triggered when one tries to iterate multiple times over a single pass range.

**Comment by anders-sjogren** [comment]
I strongly agree that code such as the above should either work or at least throw a runtime error when it doesn't. Otherwise, it seems to be seriously bug prone to use in real world settings, even for one interested in the details, and not to mention the less C++ savvy. And that applies even more since the code looks so simple and elegant, and comprehensible.

**Comment by CaseyCarter** [comment]
> ...it would be nice if we could assert on `SinglePass` and/or `InputRanges` being iterated multiple times.

Eric and I had [a discussion about equality preservation of `begin(range)` and `end(range)`](https://github.com/ericniebler/stl2/issues/101) a while back that concluded in the decision that `begin(range)` is only required to preserve equality when the range's iterator type satisfies `ForwardIterator`. Consequently, the behavior of repeated calls of `begin(range)` is not defined for input and output (single-pass) ranges. I think it would be appropriate for single-pass ranges to detect repeated calls to `begin` and explode if there is no overhead added to `NDEBUG` compiles.

**Comment by ericniebler** [comment]
@CaseyCarter I was thinking the same thing.
