### ISSUE TITLE
Should we enable -Wshadow?

### ISSUE THREAD

**Issue by rhalbersma** [ericniebler/range-v3#195]
Most algorithm function objects currently shadow the `begin()` and `end()` functions in their `operator()` function parameters `begin` and `end`. This will trigger `-Wshadow` on Clang (currently avoided in CMakeLists.txt through `-Wno-shadow`). Even though the warning is not signalling an error, it still obfuscates the code IMO. Better parameter names would be `first` and `last`. Clearing all this up is rather elaborate, so hence this issue to inquire whether I should undertake this cleanup.

**Comment by gnzlbg** [comment]
This was also discussed in #2 .

**Comment by rhalbersma** [comment]
Yeah, sorry, I should have searched the archive first. Let's focus the discussion to shadowing only here. Both libc++ and libstdc++ don't shadow `begin`/`end` (and it would surprise me if MSVC wouldn't do the same) and `first`/`last` is much easier on the eyes. For one, it's how all STL documentation has named its parameters as well. Plus, if (when?) range-v3 is standardized, the STL implementors will have to go through the cleanup as well. Dito for `size` parameters which could be renamed to `n`. Note that this is something else than postfixing ugly underscores to names as proposed in #2 .

**Comment by ericniebler** [comment]
Shadow warnings don't concern me. If someone submitted a patch that replaced locals `begin`/`end` with `first`/`last`, I would accept it. No strong feelings about `size` --> `n`.

**Comment by ericniebler** [comment]
No patch appears to be forthcoming. Closing this.
