### ISSUE TITLE
operator_brackets_proxy does not behave like a range when it should

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#197]
Example:

```c++
// this works:
auto rng = view::iota(0, 10) | view::chunk(2);
static_assert(RandomAccessRange<decltype(rng)>{}, ""); 
RANGES_FOR(auto inner_rng, rng) {
      static_assert(RandomAccessRange<decltype(inner_rng)>{}, "");
      RANGES_FOR(auto i, inner_rng) { 
          std::cout << i << std::endl; 
       }
 }
// but this fails:
static_assert(RandomAccessRange<decltype(rng[0])>{}, ""); 
assert(rng[0][0] == 0);  // fails to compile
```

This is not a major issue but was unexpected.  If `rng` is a random access range of random access ranges I expected:

- `rng[0]` to return a random access range, and
-  to be able to index `rng` like this: `rng[a][b]...`.

**Comment by ericniebler** [comment]
There is no requirement at the moment that `RandomAccessRange` even have an `op[]`. And for `RandomAccessIterator` the only requirement is (or rather, *should be*) that `i[n]` share a common reference with `ValueType<I> &`. So from a generic programming perspective, you can't rely on this.

From a practical standpoint, it's possible that `view_interface` could provide something like this as a convenience. And `operator_brackets_proxy` needs work anyway. I'll keep it in mind.

**Comment by gnzlbg** [comment]
Don't misunderstand me, I'm not volunteering to fix this. Im just saying,
my expectations we're not fulfilled in a way that was surprising. I
understood what was going on "fast enough" and was able to keep on working
without any major problem. I just thought maybe there would be a way to
improve "ergonomics" and thought it was worth mentioning it.

If fixing this requires extending a concept like requiring that
RandomAccessRange to provide operator[] I would say that is a pretty strong
requirement worth a couple of showers. Without much thought, why shouldn't
it provide it?

**Comment by gnzlbg** [comment]
From issue #203 it seems that `RandomAccessRange` should not require `operator[]`. The following example is better: 

```c++
  auto rng = view::iota(0, 10) | view::chunk(2);
  static_assert(RandomAccessRange<decltype(rng)>{}, "works");
  static_assert(RandomAccessRange<decltype(at(rng, 0))>{}, "fails"); 
  assert(at(at(rng, 0), 0) == 0);  // fails to compile
```

**Comment by ericniebler** [comment]
I've killed off `operator_brackets_proxy`.
