### ISSUE TITLE
Should RandomAccessRange provide operator[] ?

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#203]
Why? / Why not?

I've found following precedence for both cases:

- range-v3: does not require it but some ranges like [`view_interface`](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/view_interface.hpp) do provide it.

- Boost.Range: [`RandomAccessRange`](http://www.boost.org/doc/libs/1_58_0/libs/range/doc/html/range/concepts/random_access_range.html) does not require it, but some ranges like [`iterator_range`](http://www.boost.org/doc/libs/1_58_0/libs/range/doc/html/range/reference/utilities/iterator_range.html) do provide it.

- [D RandomAccessRange](http://dlang.org/phobos/std_range_primitives.html#isRandomAccessRange) does require it (`opIndex` is equivalent to `operator[]`). 

The only advantage I see for having an `operator[]` in the `RandomAccessRange` concept is better ergonomics. Users will try to transfer their knowledge from iterators and containers to ranges. Both `RandomAccessIterator`s and containers with `RandomAccessIterator`s provide `operator[]`.

Adding this to `RandomAccessRange` would add a bit of redundancy since we already have the non-member non-friend `ranges::at` for this purpose. 

The killer question is:

- Is there any `RandomAccessRange` range for which `operator[]` cannot be provided ? 

I couldn't think of any, but if such a range exist then the answer is a clear "No, `RandomAccessRange` should not provide `operator[]`".

Note: this is related to issue #197 .

**Comment by pfultz2** [comment]
> Is there any RandomAccessRange range for which operator[] cannot be provided ? 

The `operator[]` is only allowed to be overloaded using a member function. So this would exclude any range where the class can't be change(such as for third party libraries).

**Comment by gnzlbg** [comment]
> The operator[] is only allowed to be overloaded using a member function. So this would exclude any range where the class can't be change(such as for third party libraries).

Yes, ideally `operator[]` could be provided as a non-member non-friend and be just equivalent to `ranges::at` but this is not how things are.

**Comment by rhalbersma** [comment]
With universal function call syntax on the horizon, `range::at` would become equivalent to a member function `at`. I'd prefer to use `operator[]` for fast unchecked access, and `at` for throwing access, just as for `vector`. 

If overloading `operator[]` is relaxed, then UFCS will also solve the problem @pfultz2 alludes in the sense that `rng[n]` becomes equivalent to `operator[n](rng)` for a non-member index operator (so that it can be retro-fitted on legacy classes).

**Comment by gnzlbg** [comment]
> If overloading operator[] is relaxed to non-member functions

This would require a new proposal.

> I'd prefer to use operator[] for fast unchecked access, and at for throwing access, just as for vector.

Makes sense to me. This is also the case for `array`, `basic_string`, `map`, `unordered_map`, `deque`.

**Comment by rhalbersma** [comment]
>D RandomAccessRange does require it (opIndex is equivalent to operator[]).

BTW, is there (or if no, should there be) a dictionary table of the functionality and naming of D's ranges and `ranges-v3`? Could serve both as a quick doc and as a  TODO for missing functionality.

**Comment by pfultz2** [comment]
> D RandomAccessRange does require it (opIndex is equivalent to operator[]).

Also, D requires it because it uses no iterators, so its necessary for random access, whereas for ranges in C++ its not necessary ever as it can be implemented on top of iterators.

**Comment by CaseyCarter** [comment]
If we define `range[n]` as equivalent to `*(range.begin() + n)`, any random access range *can* provide constant-time `[]`. It would be trivial to add a default implementation to `view_facade`. The question of whether every random access range *should* provide `[]` comes down to safety. Random access containers always know their size, and can therefore assert the precondition that `n` is less than that size. For random access ranges that do not model SizedRange (or are not infinite) that is not always the case.

I think favoring speed and utility over safety is at the core of C++, so I would be fine with requiring `[]` for random access ranges. If we relax the complexity requirement to amortized constant time a range implementation could provide a debug mode that asserts the precondition by tracking the highest known valid index (that could also be added to `view_facade`, but would be less trivial).

**Comment by pfultz2** [comment]
> Random access containers always know their size, and can therefore assert the precondition that n is less than that size.

Size for random access ranges can always be computed in constant time.

> so I would be fine with requiring [] for random access ranges.

But then we exclude the ability for some classes to be random access ranges because `operator[]` must always be a member function. 

A better solution would be to use concept maps with a defaulted `operator[]`. Then the user doesn't have to redefine `operator[]` everytime, and for cases where there can be a speed improvement, an explicit concept map can be used to override it.

**Comment by gnzlbg** [comment]
> A better solution would be to use concept maps with a defaulted `operator[]`

IIRC Andrew said that we are not getting concept maps any time soon.

**Comment by CaseyCarter** [comment]
> Size for random access ranges can always be computed in constant time.

That is not the case in the design of range-v3 / the Ranges proposal. A range whose iterator type is a RandomAccessIterator is a RandomAccessRange, but such ranges whose sentinel type differs from their iterator type do not necessarily model SizedRange. Since the comparison of iterator and sentinel can compute an arbitrary function, there's not necessarily a way to know a priori the size of the range.

**Comment by pfultz2** [comment]
> IIRC Andrew said that we are not getting concept maps any time soon.

Which is unfortunate, so the only other solution is to use ADL free functions. The `ranges::at` could provide a default that can be overridden using an ADL `ranges_at` function, something like this:

```cpp
FIT_STATIC_LAMBDA_FUNCTION(at) = fit::conditional(
    [](auto&& range, auto n) -> decltype(ranges_at(range, n)) { return ranges_at(range, n); },
    [](auto&& range, auto n) -> decltype(auto) { return *(range.begin() + n); }
);
```

So this would allow customizing `ranges::at` for improved performance and safety for certain ranges, but its not necessary that the user customize it everytime.

However, I don't think its feasible to require `operator[]` without support for concept mapping.

**Comment by ericniebler** [comment]
`RandomAccessRange` should *not* require `operator[]`. Today, it is possible to nonintrusively make a type model `RandomAccessRange` by overloading `begin`/`end` for it. But `operator[]` must be a member function. Requiring that makes it impossible to nonintrusively make a type model `RandomAccessRange`.

**Comment by pfultz2** [comment]
> Writing a view adaptor to add [] to a broken range should be trivial.

Its only trivial at the top level.

**Comment by ericniebler** [comment]
@CaseyCarter 
> If we define `range[n]` as equivalent to `*(range.begin() + n)`, any random access range can provide constant-time `[]`. It would be trivial to add a default implementation to `view_facade`.

- `view_facade` already inherits `op[]` from `view_interface`
- The correct implementation is `begin(rng)[n]`, not `*(rng.begin() + n)`. For `RandomAccessIterator`, `op[]` is allowed to return a proxy. `rng[n]` should respect that and also return a proxy (which is what `view_interface` does.

**Comment by CaseyCarter** [comment]
> `rng[n]` should respect that and also return a proxy (which is what `view_interface` does).

If `begin(rng)[n]` returns a proxy, `*(begin(rng) + n)` is likely also a proxy: `begin(rng)[n]` is required to be equal to `*(begin(rng) + n)` by [random.access.iterators]/2.11.

**Comment by gnzlbg** [comment]
For me this issue is settled. 

With the current language an `operator[]` cannot be provided generically for _all_ `RandomAccessRange`s. 

I think @rhalbersma raised a valid point in that `ranges::at` is too similar to the `::at` member functions which perform checked access. From a consistency point-of-view, I think it makes sense for `ranges::at` to also perform checked access, and to have a different utility for performing unchecked access in generic code (e.g. `ranges::index` anybody?).  

Anyhow the generic way of indexing a `RandomAccessRange` right now in generic code is to use `ranges::at`. Some `RandomAccessRange`s might provide `operator[]`, which is nice, but not required, and generic code cannot rely on this. Hopefully when we get concepts little the compiler will reject generic code that relies on `operator[]`.
