### ISSUE TITLE
Something screwy on travis-ci

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/range-v3#205]
https://travis-ci.org/ericniebler/range-v3/jobs/72931081

**Comment by gnzlbg** [comment]
Seems like llvm moved "trunk" to clang-3.8 in their repo. I'll see what I can do.

**Comment by CaseyCarter** [comment]
I believe this is fixed by #218.

**Comment by ericniebler** [comment]
Reopened since travis is broken again.

**Comment by CaseyCarter** [comment]
I think [Travis ~~just hates you~~ is subject to transient errors](https://travis-ci.org/CaseyCarter/range-v3/builds/86432603).

**Comment by julian-becker** [comment]
Will have a closer look at it later. Looks indeed as if the Travis build environment is subject to some unreasonable changes. Maybe there is a way around these spooky failures somehow.

**Comment by ericniebler** [comment]
> I think Travis ~~just hates you~~

I've long suspected that. It's mutual at this point.

**Comment by ericniebler** [comment]
Closing this since travis seems to be behaving itself. I'm curious why it's so flakey, though.

**Comment by CaseyCarter** [comment]
> I'm curious why it's so flakey, though.

The most common transient errors we get are failures to retrieve clang packages from the repository, which I've always assumed are caused by downtime at the server end. This last one (the build you linked) is similar:

```
$ if [ -n "$CLANG_VERSION" ]; then sudo CXX=$CXX CC=$CC ./install_libcxx.sh; fi
svn: OPTIONS of 'http://llvm.org/svn/llvm-project/libcxx/trunk': could not connect to server (http://llvm.org)
mkdir: cannot create directory `libcxx/build': No such file or directory
./install_libcxx.sh: line 7: cd: libcxx/build: No such file or directory
make: *** libcxx/build: No such file or directory.  Stop.
cp: cannot stat `libcxx/build/lib/libc++.so.1.0': No such file or directory
cp: cannot stat `libcxx/build/include/c++/v1': No such file or directory
```

Subversion failed to contact llvm.org to download libcxx.
