### ISSUE TITLE
Rename view::for_each to view::flat_map or view::flat_transform

### ISSUE THREAD

**Issue by kryptan** [ericniebler/range-v3#207]
In many other languages this function is called `flat map`:
Java `flatMap` - https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#flatMap-java.util.function.Function-
Scala - `flatMap`: https://twitter.github.io/scala_school/collections.html#flatMap
Ruby -`flat_map`: http://apidock.com/ruby/Enumerable/flat_map
Rust - `flat_map`: https://doc.rust-lang.org/core/iter/trait.Iterator.html#method.flat_map
Swift - `flatMap`: http://swiftdoc.org/func/flatMap/
and there are many others...

Of course you can find other languages where it is named differently but flat map is the most popular name. I think that `for_each` is very confusing name for this function. Using established name will make programmer's life easier.

Since `map` is named `transform` the other alternative is `flat_transform` but I would prefer to rename `transform` to `map` to match widespread convention.

**Comment by gnzlbg** [comment]
This is Sparta! I mean... C++... the STL made a different choice decades
ago and this is a STL 2.0 implementation. I don't know if I would be fine
with aliases, but renaming these is a too large non-backwards compatible
change.

Having said this, I would prefer this too, but this ship sailed long ago.

On Friday, August 7, 2015, kryptan <notifications@github.com> wrote:

> In many other languages this function is called flat map:
> Java flatMap -
> https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#flatMap-java.util.function.Function-
> Scala - flatMap:
> https://twitter.github.io/scala_school/collections.html#flatMap
> Ruby -flat_map: http://apidock.com/ruby/Enumerable/flat_map
> Rust - flat_map:
> https://doc.rust-lang.org/core/iter/trait.Iterator.html#method.flat_map
> Swift - flatMap: http://swiftdoc.org/func/flatMap/
>
> Of course you can find other languages where it is named differently but
> flat map is the most popular name. I think that for_each is very
> confusing name for this function. Using established name will make
> programmer's life easier.
>
> Since map is named transform the other alternative is flat_transform but
> I would prefer to rename transform to map to match widespread convention.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ericniebler/range-v3/issues/207>.
>


-- 
Dipl.-Ing. Gonzalo Brito Gadeschi
Institute of Aerodynamics and Chair of Fluid Mechanics
RWTH Aachen University
Wuellnerstraße 5a
D-52062 Aachen
Germany
Phone: ++49-(0)241-80-94821
Fax: ++49-(0)241-80-92257
E-mail:  g.brito@aia.rwth-aachen.de
Internet: www.aia.rwth-aachen.de

**Comment by kryptan** [comment]
@gnzlbg, this may be true for `transform` but there is no such `for_each` in STL. There is different `for_each` in STL but it is just the usual `for_each` which simply executes one function for each element without concatenating results.

**Comment by ericniebler** [comment]
```c++
view::for_each( some_range, [](auto i) {
    return yield_if( some-condition, i );
});
```

The mental model is iteration over all the element in a range, doing something and yielding new elements to produce a new range. In that sense, it *is* a for-each loop.

I'm not changing the name. Simply, no.
