### ISSUE TITLE
associated type size_type does not use the ::size_type member type

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#209]
Is this intended? If so, what is the rationale?

**Comment by ericniebler** [comment]
It's not clear to me that it should use `size_type`. Size `size_type` is not (currently) part of any concept, there is no way of knowing that a nested `size_type` has any relationship to `difference_type`. The current method of simply making `difference_type` unsigned ensures the proper relationship.

**Comment by gnzlbg** [comment]
It was a while ago but I remember I found this behavior surprising (IIRC for libc++ std::vector on my system the ::size_type member had a different type). I always thought of associated types as customization points but maybe they aren't and I got it wrong.

**Comment by ericniebler** [comment]
`size_type` is an associated type only in the sense that `size` returns the size of a `SizedRange`, and `size_type` should name that type. So I think that is the correct direction to take for this type.

**Comment by gnzlbg** [comment]
This was fixed in 41682f70723bda6472772157c820f1ec199f419b but not closed.

**Comment by ericniebler** [comment]
Thanks!
