### ISSUE TITLE
Fails to compile under C++1y mode of GCC 4.9.2 with libstdc++ version 20150327 (libstdc++.so.6.0.20)

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#210]
I create a new file `test.cpp` in the root directory of a fresh range-v3 clone that only contains the following:

~~~~~.cpp
#include <range/v3/core.hpp>

~~~~~

This compiles cleanly with any of:

    clang++ -std=c++11 -stdlib=libc++ -isystem include test.cpp -c
    clang++ -std=c++1y -stdlib=libc++ -isystem include test.cpp -c
    g++     -std=c++11                -isystem include test.cpp -c

...but fails with...

    g++     -std=c++1y                -isystem include test.cpp -c

~~~~~
In file included from include/range/v3/core.hpp:17:0,
                 from test.cpp:1:
include/range/v3/begin_end.hpp:40:24: error: ‘std::rbegin’ has not been declared
             using std::rbegin;
                        ^
include/range/v3/begin_end.hpp:41:24: error: ‘std::rend’ has not been declared
             using std::rend;
                        ^
In file included from include/range/v3/view_facade.hpp:24:0,
                 from include/range/v3/core.hpp:21,
                 from test.cpp:1:
include/range/v3/utility/basic_iterator.hpp:374:22: error: ‘constexpr const T& ranges::v3::basic_mixin<Cur>::get() const’ cannot be overloaded
             T const &get() const noexcept
                      ^
include/range/v3/utility/basic_iterator.hpp:368:16: error: with ‘constexpr T& ranges::v3::basic_mixin<Cur>::get() const’
             T &get() noexcept
                ^
include/range/v3/utility/basic_iterator.hpp:396:22: error: ‘constexpr const S& ranges::v3::basic_sentinel<S>::end() const’ cannot be overloaded
             S const &end() const noexcept
                      ^
include/range/v3/utility/basic_iterator.hpp:391:16: error: with ‘constexpr S& ranges::v3::basic_sentinel<S>::end() const’
             S &end() noexcept
                ^
include/range/v3/utility/basic_iterator.hpp:440:47: error: ‘constexpr const Cur& ranges::v3::basic_iterator<Cur, S>::pos() const’ cannot be overloaded
             RANGES_CXX14_CONSTEXPR Cur const &pos() const noexcept
                                               ^
include/range/v3/utility/basic_iterator.hpp:436:41: error: with ‘constexpr Cur& ranges::v3::basic_iterator<Cur, S>::pos() const’
             RANGES_CXX14_CONSTEXPR Cur &pos() noexcept
                                         ^
~~~~~

Context
-------

 * ***Compiler*** : GCC Ubuntu 4.9.2-10ubuntu13
 * ***Stdlib*** : GNU libstdc++ version 20150327 (/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.20)
 * ***OS*** : Ubuntu 15.04
 * ***Kernel*** : 3.19.0-25-generic #26-Ubuntu SMP Fri Jul 24 21:17:31 UTC 2015 x86_64

**Comment by CaseyCarter** [comment]
The preliminary support for C++14 in the GCC 4.9 series is not sufficient for range-v3's usage of C++14. You will have to either get a GCC 5 series compiler, or stick with -std=c++11.

**Comment by tonyelewis** [comment]
Thanks for the response. That sounds sensible to me and reflects what I've seen. In that case, please may I suggest adding a few words to that effect in the [Supported Compilers section of the main README.md](https://github.com/ericniebler/range-v3#supported-compilers)? Perhaps: "(C++14 support requires at least GCC v5.1)" after "GCC 4.9.0"?

**Comment by gnzlbg** [comment]
C++14 support requires clang >= 3.5.

Is GCC > 4.9 supported at all? Last time I tried GCC 5.1 had a couple of
ICEs while compiling the test suite.

If so the readme should be updated.

**Comment by CaseyCarter** [comment]
5.2 compiles everything except constexpr-core, which IIUC is not a "real" test so much as an attempt to determine how much of the library could be `constexpr`-ized.

My vague recollection of 5.1 working months ago was very much wrong. 5.1 needs a meta patch (https://github.com/ericniebler/meta/pull/30)  to even compile with C++11. Except on Travis, apparently, where [even with the patch 5.1 won't build all tests without `NDEBUG` defined](https://travis-ci.org/CaseyCarter/range-v3/builds/83228659). 

6.0 *was* working with C++14, again with the exception of constexpr-core, until the implementation of fold expressions last week [broke everything](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67810).

**Comment by octoploid** [comment]
The only thing that ICEs with gcc-5 branch is the calendar.cpp example.
See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60153
