### ISSUE TITLE
Do we actually need projections?

### ISSUE THREAD

**Issue by ldionne** [ericniebler/range-v3#211]
I haven't looked at all the algorithms that use projections, but I think it might be possible to replace additional projection arguments by the following combinator:

```c++
#include <utility>

template <typename Projection, typename F>
struct on_fn {
    Projection const& projection;
    F const& f;
    template <typename ...X>
    constexpr decltype(auto) operator()(X&& ...x) const {
        return f(projection(std::forward<X>(x))...);
    }
};

template <typename Projection, typename F>
constexpr on_fn<Projection, F> on(Projection const& projection, F const& f) {
    return {projection, f};
}
```

With this, one can use `on(projection, predicate)` as a predicate instead of passing an additional projection argument:

```c++
#include <range/v3/algorithm/any_of.hpp>
#include <range/v3/algorithm/sort.hpp>
#include <functional>
#include <vector>

struct Person {
    int age;
};

int main() {
    std::vector<Person> persons;
    auto age = [](Person const& p) { return p.age; };

    // both are equivalent
    ranges::sort(persons, std::less<>{}, age);
    ranges::sort(persons, on(age, std::less<>{}));

    // also works for unary predicates:
    auto large = [](int n) { return n > 50; };
    ranges::any_of(persons, large, age);
    ranges::any_of(persons, on(age, large));
}
```

Note that the name comes from [Haskell's `on`][1]. The name becomes very obvious when used with infix application:

```c++
ranges::sort(persons, std::less<>{} `on` age);
```

If this turns out to be correct and all algorithms taking projections can be implemented this way, it would simplify the interface to get rid of the facultative projection argument. I'm not too familiar with algorithms taking projections though, so I might be missing something obvious.

[1]: https://hackage.haskell.org/package/base-4.8.1.0/docs/Data-Function.html#v:on

**Comment by pfultz2** [comment]
I agree, I think separating out the projections would be a much simpler approach.

**Comment by ericniebler** [comment]
It's not possible in general since some predicates are symmetric and some
are asymmetric. Consider a call to lower_bound that searches for a string
in a range of employees using a projection to get the last name. Only one
argument to the predicate needs to be projected. Your combinator would do
the wrong thing.

**Comment by pfultz2** [comment]
> Your combinator would do the wrong thing.

I believe `hana::compose` could be used for asymmetrical projections. However, that may not be the clearest to the user. A better choice would have been not to have asymmetrical predicates at all, and `std::lower_bound` would take either a value or a predicate(not both a value and compare function), but its much too late to change that now.

**Comment by ldionne** [comment]
For asymmetrical predicates, would the following work?

```c++
template <typename Projection, typename Predicate>
struct asymmetrical_on_fn {
    Projection const& projection;
    Predicate const& predicate;

    template <typename T, typename U>
    constexpr auto operator()(T&& t, U&& u) const -> decltype(
        predicate(projection(std::forward<T>(t)), std::forward<U>(u))
    ) {
        return predicate(projection(std::forward<T>(t)), std::forward<U>(u));
    }

    template <typename T, typename U>
    constexpr auto operator()(T&& t, U&& u) const -> decltype(
        predicate(std::forward<T>(t), projection(std::forward<U>(u)))
    ) {
        return predicate(std::forward<T>(t), projection(std::forward<U>(u)));
    }
};

template <typename Projection, typename Predicate>
constexpr asymmetrical_on_fn<Projection, Predicate>
asymmetrical_on(Projection const& projection, Predicate const& predicate) {
    return {projection, predicate};
}
```

Then, 

```c++
#include <range/v3/algorithm/lower_bound.hpp>
#include <functional>
#include <vector>

struct Person {
    int age;
};

int main() {
    std::vector<Person> persons;
    auto age = [](Person const& p) { return p.age; };

    // both are equivalent
    ranges::lower_bound(persons, 10, std::less<>{}, age);
    ranges::lower_bound(persons, 10, asymmetrical_on(age, std::less<>{}));
}
```

At a glance, it seems like projections are somewhat orthogonal to the range library itself, and hence they shouldn't clutter the interface, especially if they are seldom used (which I would suspect in a real codebase, but can't be sure). On the other hand, perhaps this whole attempt to remove projections is wrong and that functionality can't be obtained in another way.

At any rate, if there is interest to try to remove the projections and see what that gives, here are some thoughts that might help:

1. For symmetrical algorithms like `any_of` and `sort`, the `on` combinator proposed above will do the trick just fine.

2. For some asymmetrical algorithms like `count`, we can use the normal algorithm on a transformed view instead of a projection.

3. For some asymmetrical algorithms like `find`, we can use the `find_if` version instead of providing a projection.

4. For other asymmetrical algorithms, the above `asymmetrical_on` combinator might do the trick. One could also consider modifying these algorithms so that they are not asymmetrical anymore, or still accept a projection but consider this as a special case. There only seems to be a few of these algorithms.

**Comment by ericniebler** [comment]
To be sure, yes we can make do without projections. We have for 20 years. Some like you feel they are unnecessary clutter. Others see them as a huge step forward. I'm somewhere in the middle. I have occasionally found then useful and safely ignorable the rest of the time.

Another way to look at them: they are an experiment. A TS is a good time for experimentation. I'm not inclined to take them out until experience shows they are more trouble than they are worth.

**Comment by ldionne** [comment]
That's fine by me!

**Comment by sean-parent** [comment]
A post close comment -

It is very valuable to have symmetry with lower_bound and sort - logically
the comparison must be the same.  Projections do that - solutions with "on"
(which I like the general idea of) have the problem of also requiring some
kind of bind or lambda for lower_bound and even with a predicate form is
asymmetric with sort. i.e.

sort(r, on(less<>(), &name::last));
lower_bound(r, bind(on(less<>(), &name::last), _1, value));

or

lower_bound(r, [&](const auto& x) { return x.last < value; });

Compare with:

sort(r, less<>(), &name::last);
lower_bound(r, value, less<>(), &name::last);

In my experience (and we have a lot of experience with projections as they
have been in ASL for many years), the projection functions are much less
error prone - and I spend far less time answering the "how do I..."
questions.

**Comment by ldionne** [comment]
I personnally find that 

```c++
lower_bound(r, [&](auto const& x) { return x.last < value; })
```

is the easiest to read, but that's arguably a matter of taste. The description of the algorithm also becomes

```c++
template<class ForwardIt, class Predicate>
ForwardIt lower_bound(ForwardIt first, ForwardIt last, Predicate const& is_below_bound);
```

which I find at least as clear as the signature in the current standard. The downside of using projections is that you end up putting them everywhere, even in cases where `on` would be vastly sufficient, like `any_of`. IMHO, the symmetry between `sort` and `lower_bound` when using projections, even though nice, is not sufficient to mandate such an important design choice.

On the other hand, I do not have the experience that you have with projections, and part of this is personal preference anyways. Hence, I find it justifiable to give projections a chance in the TS, and I hold no grudge against Eric for it :-). However, I do think that the alternative of using `on` and slightly modifying algorithms like `lower_bound` should be known to the public, so that people are at least aware of this design choice.

**Comment by ericniebler** [comment]
For the record, I like `on ` and think it's an important functional combinator. My Meta library provides it for type computation, and I'd like to see it in `<functional>` some day.
