### ISSUE TITLE
view::iota::iota_minus overflows for unsigned integers

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#215]
[`iota_minus`](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/view/iota.hpp#L146) is defined for unsigned integers as follows:

```c++
template<typename Val, CONCEPT_REQUIRES_(UnsignedIntegral<Val>())>
iota_difference_t<Val> iota_minus(Val const &v0, Val const &v1)
{
    using D = iota_difference_t<Val>;
    return (D) (v0 - v1);
}
```

which overflows if `v1` is greater than `v0` (e.g. for `view::iota(unsigned{0}, unsigned{1})` the call to `iota_minus` returns `std::numeric_limits<unsigned>::max()`). Unsigned integer overflow is perfectly defined behavior, but from what I understood this seems not to be the intent of `iota_minus`. 

I am not well versed in unsigned arithmetic but

`return static_cast<D>(v0) - static_cast<D>(v1);`

should avoid the unintended overflow, and 

`return v0 < v1? - static_cast<D>(v1 - v0) :  static_cast<D>(v0 - v1);`

should also allow differencing numbers that are not representable with `iota_difference_t<Val>`. 

Maybe there is a better way. Ideas?

**Comment by ericniebler** [comment]
Fixed in 92ea424
