### ISSUE TITLE
Support for VS2015

### ISSUE THREAD

**Issue by akrohit** [ericniebler/range-v3#217]
VS2015 does not seem to be currently supported. Any plans for the same?

**Comment by gnzlbg** [comment]
Probably when MSVC adds support for expression SFINAE it might be worth to look into it, although there might be other issues like two-phase lookup :/

See also, https://github.com/ericniebler/meta/issues/23 (range-v3 depends on meta).

**Comment by ericniebler** [comment]
No plans. VC++ is too broken. See also #78.
