### ISSUE TITLE
Feature suggestion: max_element_value() and min_element_value()

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#232]
Suggestion
----

Add two convenience functions, `max_element_value()` and `min_element_value()`, that return the result of dereferencing the return values from `max_element()` and `min_element()` respectively.

Eg: `max_element_value( std::vector<int>{ 3, 5, 7, 9 } )` returns `9`.

Potential Benefits
----
 * **Simple, expressive syntax for a common task**
 * **Acceptance of an rvalue for the range argument** The range can reasonably expire by the end of the function call because the function returns a dereferenced value, not an iterator. This prevents callers that only want the final value from facing needless `dangling` problems and from having to save a temporary range in a named variable.
 * **In particular, acceptance of composed range-v3 views for the range argument**
 * **In particular, the ability to take any (part of) the projection that should be applied to the final value and put it into a ` | view::transform( ... )` suffix of the range argument** This avoids having to needlessly duplicate that transformation in the projection and in the result-handling.

Illustration of benefits
----

Finding the maximum value, mod 10, of the first three `nums` can be achieved with clean, natural syntax:

~~~~~.cpp
ranges::max_element_value(
	nums
		| ranges::view::take( 3 )
		| ranges::view::transform(
			[] (const auto &x) { return ( x % 10 ); }
		)
);
~~~~~

(Whereas using `*ranges::max_element()` would give `dangling` compiler errors, which would require saving the modified range into a temporary, named variable.)

Potential Issues
----
 * Might there be problems if an rvalue range returns a value by non-const reference and the caller takes it by non-const reference and then tries to use it after its owning ranges has expired?
   * Should the function always return by value to avoid this?
   * Or ensure any returned reference is a const reference?
 * Is it worth also adding a minmax_element_value() that returns a pair of values?

Possible Implementation
------

~~~~~.cpp
#include <range/v3/core.hpp>
#include <range/v3/algorithm/max_element.hpp>
#include <range/v3/utility/functional.hpp>

#include <utility>

namespace ranges {
    inline namespace v3 {

    	/// \brief Return the value of the max_element of the specified range
    	///
    	/// The value is returned without the projection function applied
    	///
    	/// This does not std::forward<> the range because if it's an rvalue,
    	/// max_element() would worry about `dangling` problems but this
    	/// function knows the range will live long enough to return the final value
		template <typename Rng,
		          typename C = ::ranges::v3::ordered_less,
		          typename P = ::ranges::v3::ident>
		auto max_element_value(const Rng  &rng,        ///< The range from which the max element value should be calculated
		                       C         &&pred = C{}, ///< The predicate to determine which of two elements is less (default: ranges::v3::ordered_less())
		                       P         &&proj = P{}  ///< The projection function to apply to elements before comparison
		                       ) -> decltype( *::ranges::v3::max_element( rng, std::forward<C>( pred ), std::forward<P>( proj ) ) ) {
			return *::ranges::v3::max_element(
				rng,
				std::forward<C>( pred ),
				std::forward<P>( proj )
			);
		}
	}
}
~~~~~

**Comment by CaseyCarter** [comment]
We already have these algorithms in the Ranges TS with names `min` and `max`. I didn't realize they weren't implemented in range-v3, so I've ported the implementations over from [cmcstl2](https://github.com/CaseyCarter/cmcstl2).

**Comment by ericniebler** [comment]
Great, thanks Casey. I'll merge as soon as the tests pass.
