### ISSUE TITLE
Mom, Travis-CI is hating on me again!

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/range-v3#235]
https://travis-ci.org/ericniebler/range-v3/builds/89329436

**Comment by CaseyCarter** [comment]
[Found the bug](https://github.com/ericniebler/range-v3/pull/237).

Incidentally, I strongly dislike the header-checking feature of CMakeLists.txt. It greatly slows down the speed of changing build configuration, which is a mild annoyance, and it makes it impossible to debug header file issues on Travis.

**Comment by ericniebler** [comment]
Agreed

**Comment by gnzlbg** [comment]
This annoyed me infinitely too.

I still prefer Boost.Hana solution, which basically just add a target `make
headers` that you have to explicitly call to build all the headers.
