### ISSUE TITLE
Undefined behavior in sized_range

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/range-v3#239]
`sized_range` as defined in range.hpp uses a clever technique to defend its class invariant despite exposing public data members: the data members are declared `const`, and mutating operations cast away member constness. This is formally undefined behavior per [dcl.type.cv]/4.

**Comment by ericniebler** [comment]
I think it's possible to have public `const` data members in a mutable struct. Consider:

```c++
template<typename F, typename S>
struct pair_data
{
    union
    {
        F non_const_first_;
        F const first;
    };
    union
    {
        S non_const_second_;
        S const second;
    };
};

template<typename F, typename S>
struct pair : private pair_data<F, S>
{
    using pair_data<F, S>::first;
    using pair_data<F, S>::second;
    pair() : pair_data<F, S>{} {}
    pair(F f, S s) : pair_data<F, S>{f, s} {}
    ~pair()
    {
        first.~F();
        second.~S();
    }
};

int main()
{
    pair<int, float> f{1, 3.14f};
    std::cout << f.first << ' ' << f.second << '\n';
    // ++f.first; // ERROR: first is const
}
```

**Comment by CaseyCarter** [comment]
This has UB due to accessing an inactive union member.

**Comment by gnzlbg** [comment]
IIUC what @CaseyCarter points out is that UB results from doing something like:

```c++
++const_cast<int&>(f.first); // UB because first is const
```

2. Aggregate initialization of the union is initializing the `first_` data member. In your example, `first` is thus not active, and reading from it is UB as well.

**Comment by ericniebler** [comment]
Humbug.

**Comment by CaseyCarter** [comment]
> In your example, first is thus not active, and reading from it is UB as well.

Jinx!

**Comment by gnzlbg** [comment]
timing :D

**Comment by CaseyCarter** [comment]
> Humbug.

On the bright side, you didn't invest the time to write all the silliness necessary make this work with non-trivial types.

**Comment by CaseyCarter** [comment]
> Which may actually be impossible - you can't have constructors/destructors for anonymous unions.

Derp. You can have constructors/destructors for a union-like class though:

```c++
template<typename F, typename S>
struct pair_data
{
    union
    {
        F non_const_first_;
        F const first;
    };
    union
    {
        S non_const_second_;
        S const second;
    };
    pair_data()
    : non_const_first_{}, non_const_second_{} {}
    template <class FF, class SS>
    pair_data(FF&& f, SS&& s)
    : non_const_first_{(FF&&)f},
      non_const_second_{(SS&&)s} {}
    ~pair_data() {
        non_const_first_.~F();
        non_const_second_.~S();
    }
};
```
