### ISSUE TITLE
[Question] Why use a v3/ subdirectory

### ISSUE THREAD

**Issue by ldionne** [ericniebler/range-v3#246]
This is a question, not an actual issue.

I'm wondering why the whole library is provided in a `range/v3/` directory, rather than just using `range/`. This question is related to [my post](http://thread.gmane.org/gmane.comp.lib.boost.devel/264195) on the Boost mailing list.

**Comment by ericniebler** [comment]
Because my original intent was to put this library in Boost alongside Boost.Range.

**Comment by ldionne** [comment]
Ok. In general, would you recommend putting libraries in a subdirectory like `v1`, and changing that directory when the major version changes? Along with inline namespaces, this might enable two incompatible versions of the library to cohabit within the same codebase?

I'm looking for best practices for [Hana](https://github.com/boostorg/hana).

Also, out of curiosity, do you still plan on submitting range-v3 to Boost?

**Comment by ericniebler** [comment]
Regarding the directory, it could very well make sense to do something like that, along with some forwarding headers at the root for people who just want the latest. I haven't thought through the implications of that, though.

I don't have a reason not to put range-v3 in Boost. It's just a matter of (lack of) time.

**Comment by ldionne** [comment]
> Regarding the directory, it could very well make sense to do something like that, along with some forwarding headers at the root for people who just want the latest. I haven't thought through the implications of that, though.

Ok, thanks. I think it would be too cumbersome to provide all of these forwarding headers, so I don't think I'm going to do it for Hana. But for a library more ABI-involved than Hana, perhaps it would be worth it to support multiple simultaneous versions. IDK.

> I don't have a reason not to put range-v3 in Boost. It's just a matter of (lack of) time.

Thanks for the answers!
