### ISSUE TITLE
Calling zip with 2 arguments will result in a pair instead of a tuple

### ISSUE THREAD

**Issue by MaikKlein** [ericniebler/range-v3#248]
Calling zip with 2 arguments will result in a pair instead of a tuple. Don't you think it would be more general to also use a tuple for 2 elements?

**Comment by ericniebler** [comment]
I feel that a `pair` is more useful and less surprising in the common case of zipping two sequences together. If you want to handle this genetically, you can use `std::get` and `std::tuple_element` on the `pair`s.
