### ISSUE TITLE
Using `concat` over a zipped range

### ISSUE THREAD

**Issue by MaikKlein** [ericniebler/range-v3#249]
```
    vector<int> iv1 = {1,2,3};
    vector<int> iv2 = {1,2,3};

    vector<float> fv1 = {4,5,6};
    vector<float> fv2 = {4,5,6};

    vector<double> dv1 = {7,8,9};
    vector<double> dv2 = {7,8,9};

    auto r1 = ranges::view::zip(ranges::view::all(iv1),ranges::view::all(fv1),ranges::view::all(dv1));
    auto r2 = ranges::view::zip(ranges::view::all(iv2),ranges::view::all(fv2),ranges::view::all(dv2));
    auto r3 = ranges::view::concat(r1, r2);
    for(auto i: r3){
      //..
    }
```
Would this be possible? 

I mean I could probably concat first and then zip but this would be much nicer to use for my current problem.

**Comment by ericniebler** [comment]
It works today, AFAICT, but it does emit warnings about comparing `double`s for equality. Are you seeing something different?

**Comment by CaseyCarter** [comment]
This blows up for me in `concat_view::cursor::get`. `get` wants to call `unique_variant` which needs to default-initialize a `variant<common_pair<int&, float&>>`, which is obviously not possible.

**Comment by MaikKlein** [comment]
This is my error message

https://gist.github.com/MaikKlein/b9f83080c69adaab3161

**Comment by CaseyCarter** [comment]
> This is my error message

Interesting. Different line, same issue; `variant<common_tuple<bunch of references>>` having no default constructor. This one's in `variant::apply(...) const`.

**Comment by MaikKlein** [comment]
Probably because I am using 3 elements which results in a tuple and not a pair.

**Comment by ericniebler** [comment]
Looks like I broke this code in eb7707. Thanks for catching it.
