### ISSUE TITLE
Heterogeneous ranges?

### ISSUE THREAD

**Issue by MaikKlein** [ericniebler/range-v3#251]
Do you think it would be possible to implement heterogeneous ranges (tuple etc)? I either have to reimplement it myself or use a 3rd party metaprogramming library. It would be nice if this could be unified.

**Comment by ericniebler** [comment]
What you're describing is not a Range as range-v3 defines it. If you are looking for algorithms that work on heterogeneous sequences, I recommend Boost.Fusion.
