### ISSUE TITLE
View interface's insertion operator fails to compile on ostringstream

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#252]
The following example fails to compile on both Clang and GCC. It looks like the view interface's insertion operator deduces its `Stream` type as `basic_ostringstream<char>` and then can't bind its return type of `basic_ostringstream<char> &` to the `basic_ostream<char>` that's returned by `basic_ostringstream<char>`'s `operator<<()`.

~~~~~.cpp
#define RANGES_SUPPRESS_IOTA_WARNING

#include <range/v3/all.hpp>

#include <iostream>
#include <sstream>

int main() {
        const auto nums = ranges::view::iota( 0, 10 );
        std::ostringstream out_ss;
        out_ss << nums;
        std::cerr << out_ss.str() << "\n";
}
~~~~~

One possible solution would be to separate the return into its own statement (`return sout;`) rather than returning the result of insertion operator on `sout`. There are a few occurrences of this.

**Comment by ericniebler** [comment]
Wow, great issue. Thanks.

**Comment by tonyelewis** [comment]
> Wow, great issue. Thanks.

Thanks for these kind words that brighten my day. Thanks also for applying a fix so remarkably quickly.
