### ISSUE TITLE
Taking distance() of const ref to view::remove_if fails to compile

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#254]
Taking the `distance()` of a const-lvalue-reference to a `view::remove_if` fails to compile under both GCC and Clang because it attempts to calculate a type using `ranges::range_difference_t<T>`, which fails as illustrated in this example:

~~~~~.cpp
#include <range/v3/all.hpp>

int main() {
	int rg[] = { 1, 2, 3, 4, 5 };

	// This     const view::tail      is fine
	const auto const_tail_view        = rg | ranges::view::tail;
	using      const_tail_view_diff_t = ranges::range_difference_t< decltype( const_tail_view ) >;

	// This non-const view::remove_if is fine
	      auto even_view              = rg | ranges::view::remove_if( [] (const int &i) { return ( i % 2 == 0 ); } );
	using      even_view_diff_t       = ranges::range_difference_t< decltype( even_view ) >;

	// This     const view::remove_if fails to compile
	const auto const_even_view        = rg | ranges::view::remove_if( [] (const int &i) { return ( i % 2 == 0 ); } );
	using      const_even_view_diff_t = ranges::range_difference_t< decltype( const_even_view ) >;

	return 0;
}
~~~~~

My understanding is that this attempts to compute the type of `begin(std::declval<T&>())`, which leads to a failed instantiation of the `begin_fn::operator()()` template, which then fails because neither private `impl()` function can be used.

I've found that this problem occurs with both `view::remove_if` and `view::drop_while` but not with:
 * `view::adjacent_remove_if`
 * `view::chunk`
 * `view::delimit`
 * `view::drop`
 * `view::replace`
 * `view::reverse`
 * `view::slice`
 * `view::stride`
 * `view::tail`
 * `view::take`
 * `view::take`
 * `view::take_exactly`
 * `view::take_while`

**Comment by CaseyCarter** [comment]
This is by design: some views have mutable state; iterating over them modifies that state. `remove_if_view<...>`, for example, is a `Range` - but `const remove_if_view<...>` is not.

**Comment by tonyelewis** [comment]
Thanks for your helpful explanation.

I write the following with all the humility that comes with knowing that:
 * you guys have written an amazing ranges library and really know what you're doing
 * I haven't and really don't

Still, FWIW, my feeling as a user of the library is that it's pretty reasonable to expect a `const view::remove_if` (or any other `const` view) to be a valid range. Particularly since that seems to be fine for many other views, not least the rather similar `view::adjacent_remove_if`.

Am I correct that `view::remove_if`'s mutable state is needed so that it can cache the iterator to the first non-removed element in `optional<range_iterator_t<Rng>> begin_`? If so:
 * Do you think it would be possible to const-overload so that a `const view::remove_if` works but just doesn't cache the begin iterator? In more detail, something like: make adaptor into a template and then const-overload `begin_adaptor()` / `end_adaptor()` to return either `adaptor<remove_if_view>` or `adaptor<const remove_if_view>` and prevent the latter from attempting to cache. Would it be helpful for me to have a go at that (no problem at all if not)?
 * But actually, I'd vote for dropping `view::remove_if`'s caching for a few reasons:
   * I think it's reasonable for the benefits of lazy views to come with the expectation of the following cost: *multiple iterations incur multiple computations*.
   * I fear such caching could cause problems if the correct starting position changes between the first iteration and successive iterations (if, say, the underlying range changes or other state that's accessed by the predicate changes). On successive iterations, might the view perpetually skip blindly past the initial elements it rejected on the first pass even if they now fail the remove predicate? That seems to undermine the idea of it being a view of the underlying range.
   * Users with strong reasons to avoid repeatedly iterating through the start of a `view::remove_if` can always cache the result of `begin()` themselves.
   * Or, If it's important that range-v3 views provide users with this sort of caching, perhaps it could be made into a more explicit choice using a separate `view::cached_begin` that explicitly caches the result of its wrapped range's begin(). The documentation could be very explicit that this is the one view that mustn't be `const`. Again, would it be helpful for me to have a go at that (no problem at all if not)?

**Comment by ericniebler** [comment]
Calling `begin` on a Range should be amortized constant time. Otherwise it becomes close to impossible to reason about the algorithmic complexity of range compositions.

**Comment by tonyelewis** [comment]
Just to follow up on the point about potential correctness problems of caching...

The following example shows an inconsistent behaviour between `view::adjacent_remove_if`, which continues to provide an accurate view of its underlying range after that range gets changed, and `view::remove_if`, which ignores the changes that occur before the location of its cached begin :

~~~~~.cpp
#include <range/v3/all.hpp>

#include <iostream>
#include <vector>

int main() {
	std::vector<int> nums = {   1, 1, 1, 1, 1, 1,   2, 2, 2, 2, 2, 2   };

	auto rng_ri  = nums | ranges::view::remove_if         ( [] (const size_t &x                 ) { return x <= 1; } );
	auto rng_ari = nums | ranges::view::adjacent_remove_if( [] (const size_t &x, const size_t &y) { return x <= 1; } );

	std::cerr << "ranges::view::remove_if          before : " << rng_ri  << "\n";
	std::cerr << "ranges::view::adjacent_remove_if before : " << rng_ari << "\n";

	nums                  = {   3, 3, 3, 3, 3, 3,   2, 2, 2, 2, 2, 2   };

	std::cerr << "ranges::view::remove_if          after  : " << rng_ri  << "\n";
	std::cerr << "ranges::view::adjacent_remove_if after  : " << rng_ari << "\n";

	return 0;
}
~~~~~

Output:
~~~~~
ranges::view::remove_if          before : [2,2,2,2,2,2]
ranges::view::adjacent_remove_if before : [1,2,2,2,2,2]
ranges::view::remove_if          after  : [2,2,2,2,2,2]
ranges::view::adjacent_remove_if after  : [3,3,3,3,3,3,2,2,2,2,2,2]
~~~~~

**Comment by tonyelewis** [comment]
> Calling `begin` on a Range should be amortized constant time. Otherwise it becomes close to impossible to reason about the algorithmic complexity of range compositions.

That does sound like a problem. That said, the first iteration (which I'd guess is often the only iteration) over a `view::remove_if` manages with a potentially linear time `begin` call. Also, `view::adjacent_remove_if` doesn't seem to cache so I guess it always has a potentially linear time `begin` call. Given that, is it a bigger problem for `view::remove_if` from the second pass onwards?

Apologies if this response is irrelevant. Thanks for taking the time to reply.

**Comment by gnzlbg** [comment]
@tonyelewis  maybe you should consider that `view::remove_if` is a _statefull range algorithm_, where each call can potentially modify its state, just like the new search algorithms in C++17 (e.g. Boyer-Moore). If you make it `const` the algorithm cannot modify its state and hence it cannot work. There are a lot of statefull range algorithms in range-v3 and they are very useful.

It is possible to write a `view::stateless_remove_if` algorithm that doesn't require state. Being able to make it `const` is desirable, but I would never trade amortized constant time begin just for that.

The error messages one gets when trying to use a `const view::remove_if` are puzzling though. I don't know how hard it would be to improve that.

**Comment by CaseyCarter** [comment]
> you guys have written an amazing ranges library and really know what you're doing

I've contributed a patch here and there, but I don't take credit for rv3. It's Eric's baby.

> I fear such caching could cause problems if the correct starting position changes between the first iteration and successive iterations

We haven't nailed down hard semantics for views yet since they haven't made it into the TS. I'm reasonably sure that when we do, it'll be the case that any modification to the structure of the underlying range will invalidate the view. A view is basically a pointer that denotes a range of elements instead of just one - anything that would invalidate a pointer or iterator into a range should also invalidate a view of that range.

> Calling begin on a Range should be amortized constant time.

Calling `++` on an Iterator should be constant time as well, and `remove_if_view`'s iterators don't provide that guarantee. (Yes, I'm arguing both sides.) The argument for caching would be stronger if the view cached *all* iterators that don't satisfy its predicate instead of only the first such iterator. Doing so would be incredibly heavy-weight but provide random access and amortized constant time for all iterator operations. Perhaps `remove_if_view` should be light-weight single-pass range to avoid pathological performance for multi-pass algorithms combined with sparse data sets, and users who want multi-pass and/or bidirectional/random access should be encouraged to either filter their data into a vector or use a heavier-weight filtering view with full caching?

**Comment by CaseyCarter** [comment]
Out of curiosity, why would one bother to declare a view `const`? To prevent inadvertent assignment?

**Comment by tonyelewis** [comment]
Thanks to all for taking the time to engage with my comments.

So, as I understand, the "in general" constraints incurred by this sort of caching in views include:
 * After the start of the first pass, a view's underlying range cannot be modified. In particular: changing an underlying vector's elements can give errors; enlarging an underlying vector causes undefined behaviour.
 * After the start of the first pass, a view's predicate must be deterministic, ie must always give the same answer for the same inputs, else there might be (difficult-to-spot) errors.
 * The iterator that a view's underlying range provides for the first pass must remain valid for future passes. Is this generally required of ranges?
 * Views may not be `const` (which could otherwise be used for preventing inadvertent assignment and make code more expressive/readable)

Is that correct? And the benefit is:
 * From the second pass onwards, the `begin` call is constant time.

I propose: let the user make this choice for themselves by leaving this sort of caching out of views but letting users opt-in with a `view::cached_begin`. Then users that want a constant time `begin` from the second pass onwards can use append a `[...] | view::cached_begin`, which can be explicitly documented as incurring the above costs.

I think those costs make views substantially less powerful than they would otherwise be. I'm guessing that many C++ coders' intuition about a lazy range view would be that it could handle changes to the underlying range and/or predicate results between passes and that this could be really useful.

Casey: I take your point about a view being invalidated like an iterator/pointer is invalidated, but then unlike an iterator/pointer, it doesn't *have* to be that way: unlike a dumb `vector::iterator`, a view doesn't *have* to be invalidated by a `push_back()` on the `vector` because it knows about the higher level of abstraction of the range.

Anyway, if you all still disagree with me, please may I suggest:
 * it probably makes sense for other similar views like `view::adjacent_remove_if` to be consistent with `view::remove_if`
 * when this is being nailed down for a TS, I propose it'd be worth explicitly raising this high-level conception of what a view should be for discussion amongst the decision makers.

Anyway, thanks. :-)

**Comment by CaseyCarter** [comment]
These:

> * After the start of the first pass, a view becomes unusable if its underlying range is modified. In particular: using a view after changing its underlying vector's elements can give errors; using a view after enlarging its underlying vector causes undefined behaviour.
* After the start of the first pass, a view's predicate must be deterministic, ie must always give the same answer for the same inputs, else there might be (difficult-to-spot) errors in future passes.
* The iterator that a view's underlying range provides for the first pass must remain valid for future passes. Is this generally required of ranges?

Are general requirements of multi-pass ranges that follow from the semantics of forward iterators. It's necessary that multiple passes over the same range exhibit the same behavior - the same sequence of iterator values denoting the same elements - for multipass algorithms to make sense. `search`, for example, makes multiple passes over subranges of the "haystack" range looking for a match to the contents of the "needle" range. If the content of the ranges may change from pass to pass, `search` can't guarantee that its result is the first occurrence of the "needle" in the "haystack."

This:
> * From the second pass onwards, the `begin` call is constant time.

Is a general requirement of ranges: both `begin` and `end` are required to have amortized constant time complexity to support reasoning about the complexity of algorithms and range compositions. That is, for roughly the same reasons that the standard library requires iterator operations to have constant time complexity.

This:
> * Views may not be `const` (which could otherwise be used to prevent inadvertent assignment and to make code more expressive/readable)

Is a consequence of a view caching mutable state when necessary to meet the semantic requirements above and simultaneously meeting to the general standard library requirement that `const` means data-race-free. Whether to make the operation non-`const` or to provide internal synchronization of the mutable state is an engineering choice. range-v3 chooses to expose mutability so that users who don't need synchronization don't pay for it. (This is unfortunately inconsistent with the semantics of `begin` and `end` on containers which are always data-race-free whether `const` or not.)

> I think those costs make views substantially less powerful than they would otherwise be. I'm guessing that many C++ coders' intuition about a lazy range view would be that it could handle changes to the underlying range and/or predicate results between passes and that this could be really useful.

I agree that this would be a useful abstraction; views are not that abstraction. A function object that stamps out views on demand comes close:
```c++
const auto even_view_of = [](auto&& rng) {
  return view::remove_if(forward<decltype(rng)>(rng), [](auto&& v){ return v % 2 != 0; });
};
std::vector<int> vec = {...};
do_stuff_with(even_view_of(vec));
change_contents_of(vec);
do_stuff_with(even_view_of(vec));
```

**Comment by tonyelewis** [comment]
> Are general requirements of multi-pass ranges that follow from the semantics of forward iterators. It's necessary that multiple passes over the same range exhibit the same behavior - the same sequence of iterator values denoting the same elements - for multipass algorithms to make sense. `search`, for example, makes multiple passes over subranges of the "haystack" range looking for a match to the contents of the "needle" range. If the content of the ranges may change from pass to pass, `search` can't guarantee that its result is the first occurrence of the "needle" in the "haystack."

Are you arguing that the existence of multipass algorithms prohibits us from allowing ranges to change between passes? If so, I'd suggest `vector` is a counter-example: true, a `vector` must remain consistent between calls to `search` and, true, it mustn't change size whilst something's iterating over it, but we're used to those sorts of conditions and they certainly don't prohibit us changing a `vector` between passes. I'd argue that the semantics for the range `vector` can apply just as well to the range `vector | view::remove_if` : change is fine, so long as not done between calls to multipass algorithms or during an iteration.

> Is a general requirement of ranges: both `begin` and `end` are required to have amortized constant time complexity to support reasoning about the complexity of algorithms and range compositions. That is, for roughly the same reasons that the standard library requires iterator operations to have constant time complexity.

Is this a strict requirement? If it is, then doesn't that mean that all ranges that have to search for their first position (including `[...] | view::remove_if` and `[...] | view::adjacent_remove_if`) must do so in their constructor rather than having a worse-than-constant time `begin` (that then caches its result in case it gets called again)? Or if it's just an *often really useful* requirement, then wouldn't it be OK to provide a `view::cached_begin` that people can wrap around their other views whenever they need to be able to reason about their complexity?

Out of interest: does it also cause problems for complexity reasoning if comparison with the sentinel is potentially worse-than-constant time, as I'd imagine is the case with `view::drop_while`?

Anyway - thanks very much again for having taken the time to respond to my thoughts. It's much appreciated. I hope I haven't been *too* annoying. :-)

**Comment by tonyelewis** [comment]
So to wrap-up...

Though I personally still prefer the stateless, open-to-underlying-change conception of views, your patient explanations have given me a much clearer understanding of your very good reasons for preferring the stateful, open-to-complexity-reasoning conception. Thanks very much for taking the time.

As we've discussed, this latter conception implies that range-v3 views can be invalidated in ways that might not be trivially obvious to everyone. Given that, please may I suggest adding a clear disclaimer to the top of the documentation about views? In the same way that everyone using `std::vector` should know when its iterators get invalidated, I suggest everyone using range-v3 views should know when they get invalidated.

I suggest something like the following at the top of the section about views. How do you guys feel about this? Shall I add it and issue a pull-request?


View Invalidation
-----------------

A range-v3 view and its iterators are invalidated if:
 * the underlying range's element values change,
 * the underlying range's iterators are invalidated or
 * any supplied Callables stop guaranteeing determinism (so then calls on identical inputs risk giving different results).

This allows range-v3 view to cache results and iterators between passes.

For example, though the following is OK:

~~~~~.cpp
const auto int_is_even           = [] (const int &x) { return ( x % 2 == 0 ); };

auto       nums                  = std::vector<int>{ 1, 2, 3, 4 };
auto       odd_nums              = nums | ranges::view::remove_if( int_is_even );

const auto num_odd_nums_1_thru_4 = ranges::distance( odd_nums );
~~~~~

...the `odd_nums` view will be invalidated by any changes to `nums`. The following leads to undefined behaviour:

~~~~~.cpp
nums.push_back( 5 );
const auto num_odd_nums_1_thru_5 = ranges::distance( odd_nums );
~~~~~

**Comment by CaseyCarter** [comment]
> Are you arguing that the existence of multipass algorithms prohibits us from allowing ranges to change between passes? If so, I'd suggest `vector` is a counter-example: true, a `vector` must remain consistent between calls to `search` and, true, it mustn't change size whilst something's iterating over it, but we're used to those sorts of conditions and they certainly don't prohibit us changing a `vector` between passes.

My comment unfortunately gives the impression that it's not possible to create ranges/views with this property - responding to changes in an underlying range - which is not the case. The point I intended to make is that it's not required that *all* ranges have this property. It's a critical design goal that views be as time and space efficient as iterator/sentinel pairs, which would be impacted by requiring them to have the smarts to "reinitialize" when an underlying range changes.

Consider `string_view` / `array_view`, for example. They provide useful views of contiguous ranges of  elements while simultaneously erasing the type of the underlying range. If we required them to track changes they would need to keep a type-erased connection to the underlying range which would increase the size of the view objects and the implementation complexity thereof.

The views in range-v3 are as low-level as possible and do not provide this property. Someone could certainly implement a library of views that does, and I'd be surprised if someone does not eventually do so.

> Out of interest: does it also cause problems for complexity reasoning if comparison with the sentinel is potentially worse-than-constant time, as I'd imagine is the case with `view::drop_while`?

Yes it would. Comparison of iterators with sentinels is required to be O(1) just as is the case for comparison of two iterators. `view::drop_while` uses the iterator and sentinel types of its underlying view directly; comparing them is O(1) if the underlying view meets that requirement.

> Is this a strict requirement?

Ideally all requirements are strict requirements so that they provide strong guarantees. Filtering views have some problems with the complexity require but are far too useful to prohibit - we need to come up with a reasonable relaxation/compromise on the complexity requirements. It does concern me that a filtering view with a contiguous sequence of K filtered-out elements has iterator values with O(K) increment/decrement. If K is significant relative to the length of the overall range then we can't simply ignore the cost of iterator operations in describing algorithmic complexity.

> Shall I add it and issue a pull-request?

That seems like a better idea than expecting everyone who uses range-v3 to perform a thorough reading of the two hundred page TS and analyze the consequences of the requirements as they apply to rv3 ;)

**Comment by tonyelewis** [comment]
> The point I intended to make is that it's not required that *all* ranges have this property.

Ah - I see. Yes - I agree.

> Consider `string_view` / `array_view`, for example. They provide useful views of contiguous ranges of elements while simultaneously erasing the type of the underlying range. If we required them to track changes they would need to keep a type-erased connection to the underlying range which would increase the size of the view objects and the implementation complexity thereof.

Yes - I agree this makes sense for `string_view` / `array_view`. But I feel that their design constraints are quite different from those of the range-v3 views because, unlike range-v3 views, they're deliberately ignorant of the elements' parent range and so are unable to use that range's `begin()` / `end()` to get fresh valid iterators after a change.

> It's a critical design goal that views be as time and space efficient as iterator/sentinel pairs, which would be impacted by requiring them to have the smarts to "reinitialize" when an underlying range changes.

> The views in range-v3 are as low-level as possible and do not provide this property. Someone could certainly implement a library of views that does, and I'd be surprised if someone does not eventually do so.

But then, AFAIU, almost all of the range-v3 views *do* already achieve this. True, their iterators are invalidated whenever their parent ranges' iterators are invalidated. But by just using fresh `begin()` / `end()` calls for each pass, they remain valid and correct as long as their underlying ranges do. Quickly skimming through the 43 views listed on the docs' front page, I could only see three (`view::drop_while`, `view::remove_if` and `view::slice`) that break this by modifying in-view data during iteration (and I guess `view::adjacent_remove_if` is likely to join at some point).

Further, it looks like all three of those break it so they can cache their `begin` iterator. Hence I think:
 * though there are big benefits to having this sort of caching, there are big costs as well
 * the library only uses this sort of caching for 3 out of 43 views and all for the same purpose
 * all the other 40 views allow: modifying underlying ranges (including invalidating their iterators) between passes; modifying function behaviour between passes; thread safety; holding by const
 * in practice, this removes the choice from users: they must assume the worst and accept the costs for all 43 views
 * instead, I propose moving the caching out into a single, clearly documented `view::cached_begin` wrapper
 * then users pay none of the costs by default but could easily opt-in to begin-caching for any view they choose

> `view::drop_while` uses the iterator [...]

Yes - sorry - I didn't think that question through.

BTW, if users should generally assume that views are invalidated by changes to their underlying ranges, does that mean that it's a bad idea to change the underlying ranges through the views iterators (eg something like`*begin( my_vec | view::all ) = 5;`)? If so, should the library prevent that?

> That seems like a better idea than expecting everyone who uses range-v3 to perform a thorough reading of the two hundred page TS and analyze the consequences of the requirements as they apply to rv3 ;)

Great - thanks. Perhaps it should also say something about const / thread-safety / non-mutability. What do you think of the following?

Usage restrictions
------------------

A range-v3 view shouldn't be taken by const; though this may work at present this may fail to compile in the future.

Mulitple threads must not access (read) the same range-v3 view without suitable locking.

Range-v3 views should not be used to modify elements in the underlying range.

A range-v3 view and its iterators are invalidated if:
 * the underlying range's element values change,
 * the underlying range's iterators are invalidated or
 * any supplied Callables stop guaranteeing determinism (so then calls on identical inputs risk giving different results).

These restrictions allow range-v3 view to cache results and iterators between passes.

To illustrate view invalidation, though the following is OK:

~~~~~.cpp
const auto int_is_even           = [] (const int &x) { return ( x % 2 == 0 ); };

auto       nums                  = std::vector<int>{ 1, 2, 3, 4 };
auto       odd_nums              = nums | ranges::view::remove_if( int_is_even );

const auto num_odd_nums_1_thru_4 = ranges::distance( odd_nums );
~~~~~

...the `odd_nums` view will be invalidated by any changes to `nums`. Hence, the following leads to undefined behaviour:

~~~~~.cpp
nums.push_back( 5 );
const auto num_odd_nums_1_thru_5 = ranges::distance( odd_nums );
~~~~~

**Comment by ericniebler** [comment]
> in practice, this removes the choice from users: they must assume the worst and accept the costs for all 43 views

I don't see how it removes choice. I understand your point. *My* point is that I would rather a compile-time error -- "this view must maintain state to satisfy its complexity guarantees and so cannot be `const`" -- rather than silently violating complexity guarantees or doing away with them entirely. If 3 out of 43 views has an O(N) `begin` member function, then how are users to write portable and efficient generic code? Their code will compile, but it will be slow, and as views are composed, the complexity goes from O(N), to O(N^2), to O(N^3), to etc. .... Please no.

**Comment by tonyelewis** [comment]
I'm really sorry to make a nuisance of myself by returning to this issue (which I think none of you enjoyed the first time round) but...
 1. Eric: how do you feel about me adding something like the **Usage restrictions** text from [this comment](https://github.com/ericniebler/range-v3/issues/254#issuecomment-160751258) to the docs and sending a P-R?
 1. I still feel concerned by this issue and would like to post another comment after this to explain why. I realise that you all disagree, that I'm probably wrong, that you guys have much deeper understanding and expertise of these issues than do I. So you're all welcome to completely ignore it. But I feel like this issue is important enough that my case should be made well and I'm not sure I've yet done that.

Sorry. Thanks.

**Comment by tonyelewis** [comment]
A Proposed Design
=================

 * Views don't modify any state after construction
 * Views in `view::` don't store any state at all
 * A small number (probably 1) of `stateful_view`s are provided and their issues clearly documented
 * That primary stateful view is `stateful_view::cached_begin`, which caches the underlying range's `begin` iterator on construction
 * Views that can benefit from being composed with `cached_begin` are documented to clearly highlight that

The Drawback
------------

The drawback of this is:

 * :x: default performance is worse in the one case that:
   * the code in question is using one of the ~3/43 views that currently modify state (`drop_while` / `remove_if` / `slice`)
   * *and* the code iterates over that view more than once
   * *and* the code's data require those views incur non-trivial effort to find their first element of the underlying range.

In that rare case, there is a complete fix:

 * :white_check_mark: compose with `[...] | stateful_view::cached_begin`

The documentation for the relevant views highlights this fix; the user can choose based on the implied costs/benefits.

&nbsp;

The Current Design
==================

The current design is that some views both store and modify state. And AFAIU, there's no intention to give guarantees that any views won't do this in the future, so users must treat all views as though they do.

The Drawbacks
-------------

The drawbacks of having state (which under the proposed design would only apply when using `stateful_view`s):
 * :x: views are invalidated by any changes to their underlying ranges' elements; any further iteration over them may give incorrect results
 * :x: views are invalidated whenever the underlying range's iterators are invalidated; any further iteration over them implies undefined behaviour
 * :x: all functions passed to views must be deterministic; otherwise iteration over the view may give incorrect results

The drawbacks of modifying state (which under the proposed design would be absent):
 * :x: iterating over views is thread-unsafe, even for read-only access
 * :x: views can't be taken as const. To me, this is pretty counter-intuitive. It's also confusing to diagnose, easy to slip-up on (ie creating const views that currently compile) and quite a lot harder to write generic code for. Indeed from what I understand (apologies if wrong), this is the source of the issue that `const Rng` isn't always a range, and that issue appears to propagate substantial complexity throughout the range-v3 code.

These issues substantially increase complexity and create serious, non-obvious correctness/undefined-behaviour gotchas. All users of all views are subject to these problems; there are no fixes.

&nbsp;

Summary
=======

In the current design there are multiple serious problems affecting all uses of views. There is no fix or opt-out.

In the proposed design, there is one performance problem affecting a rare subset of cases. In that case, documentation alerts users to that issue and gives them a simple fix, whilst alerting them to the increased constraints they're opting into.

&nbsp;

-----

&nbsp;

Notes
=====

To be more precise, it would be OK for a `stateful_view` to modify state so long as it does it in const methods and provides thread safety.

-----

> as views are composed, the complexity goes from O(N), to O(N^2), to O(N^3), to etc

I'm likely wrong but I'd have guessed that the complexity of composing views would:

 * be dependent on the data and
 * typically increase like O(N+M) rather than O(N*M) (eg I'd expect `remove_if( some_pred ) | view::slice( 100, end )` to take 100 more steps than `remove_if( some_pred )`)

Is that right? Anyway, AFAIU `cached_begin` solves this problem.

**Comment by ericniebler** [comment]
I promise to read all of this in detail, but for now I stopped here:

> `Views don't modify any state after construction`

I think this is a flawed view (ahem) of views, and perhaps you're misled by the name "view". What range-v3 means by "view" is "lazy algorithm". They are algorithms like those in `<algorithm>`, except they put the iteration on the outside instead of on the inside. You would never try to argue that the algorithms in `<algorithm>` be unable to declare and mutate local state -- or that they guard the mutation with mutexes -- but that's what you're arguing for here (unless I'm mistaken, and I really will read the rest of your comment when I get a chance).

**Comment by gnzlbg** [comment]
I kind of like the idea of making the caching of `begin` an adaptor if possible but haven't explored it:

```c++
static constexpr auto&& remove_if = remove_if_ /*uncached*/ | cached_begin;
```

**Comment by tonyelewis** [comment]
> I think this is a flawed view (ahem) of views, and perhaps you're misled by the name "view". What range-v3 means by "view" is "lazy algorithm".

Yes, I think we're talking about two slightly different meanings of "view" (both of which I'd claim could reasonably be described as "lazy algorithm"). But range-v3 only means by "view" whatever you want it to mean by "view"; in the (unlikely) case you're persuaded by the meaning I'm advocating, there's nothing to stop you adopting it.

> They are algorithms like those in <algorithm>, except they put the iteration on the outside instead of on the inside. You would never try to argue that the algorithms in <algorithm> be unable to declare and mutate local state -- or that they guard the mutation with mutexes -- but that's what you're arguing for here.

No, importantly, I'm not arguing against state on the outside; I'm arguing that all such state should be held in the view's iterator rather than in the view itself. Maybe there's a really good example that shows why views must be able to hold/modify their *own* state to do the sorts of things we need them to do. But what is the example? AFAIU, none of the existing views does this as part of achieving its purpose (and only ~3/43 do this at all, which is just for handling the wrinkle of begin-caching, [discussed in the previous comment](https://github.com/ericniebler/range-v3/issues/254#issuecomment-261305365)).

<sub>*(If there are future possible examples, I'd argue for separating them out into `stateful_view::` so that range-v3 can offer users stricter guarantees for all the existing views within `view::`, giving users all the benefits outlined above.)*</sub>

> I promise to read all of this in detail, but for now I stopped here

No hurry. Thanks. I appreciate it and completely understand if you've all had enough of #254. :cold_sweat:

**Comment by tahonermann** [comment]
Caveat: I haven't followed this thread, so my context might be off...

> No, importantly, I'm not arguing against state on the outside; I'm arguing that all such state should be held in the view's iterator rather than in the view itself.

For whatever it is worth, this is the approach I took with text_view.  I agree that state that affects iteration typically belongs in the iterator.  This is necessary for forward iterators that might get copied and advanced independently.  For input iterators, I can see placing state that affects iteration in the view as an optimization since such views are single pass anyway.

**Comment by tonyelewis** [comment]
Tagging connection to #385 and #428.
