### ISSUE TITLE
Would nice if 'clashed' less with common std:: namespace functions + boost functions

### ISSUE THREAD

**Issue by mbevin** [ericniebler/range-v3#256]
I tend to have 'using namespace std' and then not use std:: where I can avoid it ... but if one includes the range-v3 header(s), and uses 'using namespace range', then you have to start qualifying a lot of std functions like std::move, std::replace etc, as the range lib is defining its own such functions .... while technically its no error and I obviously could live with not using the range namespace / qualifying the std functions, it would be nice if didn't define all these things that 'clash' with similar names in STL ..... and I also get similar issues with headers boost + range.

**Comment by CaseyCarter** [comment]
When two libraries implement the same API, they necessarily have to use the same names - there's really no getting around that. I'd recommend that you avoid `using namespace everything;` and instead create some short namespace aliases a la:
```c++
using namespace std;
namespace r = ranges;
namespace br = boost::ranges;

int main() {
  int some_integers[] = {1,2,3};
  begin(some_integers);
  r::begin(some_integers);
  br::begin(some_integers);
}
```

**Comment by mbevin** [comment]
Oh ok .... thanks for the response + tip.
