### ISSUE TITLE
can't compile without RTTI

### ISSUE THREAD

**Issue by Trass3r** [ericniebler/range-v3#262]
Tried the fibonacci example with clang on Windows.

```
In file included from range/v3/all.hpp:21:
In file included from range/v3/view.hpp:21:
range/v3/view/any_view.hpp(135,25): error : cannot use dynamic_cast with -fno-rtti
                                   dynamic_cast<any_cursor_impl const *>(&that);
```
and line 185.

Furthermore VS's functional depends on it.
```
Visual Studio 14.0\VC\include\functional(213,11): error : cannot use typeid with -fno-rtti
```
It seems that apart from utility/functional.hpp:18 at least some files like begin_end.hpp and tagged_pair.hpp contain unnecessary direct includes of functional.

**Comment by ericniebler** [comment]
I'm not interested in supporting non-standard dialects of C++.

**Comment by njlr** [comment]
Perhaps this should be re-opened since LLVM / Clang build with `'-fno-rtti'`?

**Comment by ericniebler** [comment]
I don't see why that should make a difference.

**Comment by xaxxon** [comment]
This is frustrating.

**Comment by CaseyCarter** [comment]
Feel free to post the URL of your fork that doesn't use RTTI and/or exceptions here; I'll add it to the README to send interested parties your way.

**Comment by aaron-michaux** [comment]
I can see Eric Niebler's point of view.

Be aware that there's only a few lines of checking code that needs to be commented out, in `any.hpp`, and `any_view.hpp`. Obviously this makes your programming experience less idiot proof.

Considering how minor the changes are, it would be nice to have the `typeid` stuff behind a `#ifdef`.
