### ISSUE TITLE
[license] [travis] [nitpick] .travis.yml is unlicensed

### ISSUE THREAD

**Issue by badair** [ericniebler/range-v3#270]
Eric,

I noticed that  range-v3/.travis.yml does not use an open source license. Do you intend add the Boost license to this file? Considering the nature of the code, I doubt anyone would care if I borrowed from it; however, to stay on the safe side, I will not base any commits on the unlicensed file for my toy project.

Regards,
Barrett

**Comment by ericniebler** [comment]
Apologies. Yes, it should be Boost licensed. Parts are taken from boostorg/hana, so it should also have Louis' copyright on it. I'll take care of this.

**Comment by badair** [comment]
Great, thank you!
