### ISSUE TITLE
Isn't Sortable concept too strong?

### ISSUE THREAD

**Issue by mmatrosov** [ericniebler/range-v3#271]
I'm trying to apply `ranges::sort` to a `std::vector<A>`. Seems like it is possible only when full set of relation operators (==, !=, <, <=, >, >=) is defined for `A`. However, for `std::sort` I only need `operator<()`. Is this intended?

**Comment by ericniebler** [comment]
It is intended. We may decide to relax this in the future, but for now it's necessary to define ask the operators.

**Comment by mmatrosov** [comment]
Is this what you plan to do for range-based `sort` in C++17? It seems a little inconsistent for me. Iterator-based `sort` has an explicit overload accepting a predicate for "less than" comparison. So it is kind of declared in its very interface. It would be strange if `std::sort(begin(r), end(r))` will compile, while `std::sort(r)` will not.

**Comment by ericniebler** [comment]
Neither will compile. The less function object that is defined in the Ranges TS is constrained to only accept objects that satisfy TotallyOrdered. That requires all the relational operators.

**Comment by mmatrosov** [comment]
Here I see two possibilities.

One. Range-based `sort` is placed in `std` namespace. `std::sort` requires `TotatllyOrdered` value types. All legacy code used `std::sort` for value types which provide only `operator<` is broken. I suppose this is not acceptable.

Two. Range-based `sort` is placed in a different namespace (e.g. `ranges`). In this case `std::sort` and `ranges::sort` behave differently. It seems inconsistent to me.

Sorry for bothering you with this stuff, but in the [very first example](https://ericniebler.github.io/std/wg21/D4128.html#motivation-and-scope) in ranges proposal it looks like the possibility one. I am frustrated with this.

**Comment by ericniebler** [comment]
I hear your frustration. The constrained algorithms are not going into namespace std. There will be no code breakage.

**Comment by mmatrosov** [comment]
Does that mean, that there will be no possibility to write `std::sort(v)`?

**Comment by CaseyCarter** [comment]
For now, *everything* in the Ranges TS is defined in namespace `std::experimental::ranges`. Legacy code that uses `std::sort` still works in exactly the same way since `std::sort` is unchanged. New code that passes a range or an iterator/sentinel pair to `std::experimental::ranges::sort` with a value type that is not `StrictTotallyOrdered` will either (1) fail to compile, or (2) specify a custom comparator that provides a `StrictWeakOrder`. In some cases "custom comparator" may be `[](const auto& x, const auto& y){ return x < y; }`.

**Comment by CaseyCarter** [comment]
If it seems silly to write a comparator that looks exactly like `less` to workaround `less`'s `StrictTotallyOrdered` requirement, you are not alone. I'm planning to reexamine the comparison functor requirements when EWG's work on default comparison operators and orderings is a bit further along. (There's a ton of related discussin at https://github.com/ericniebler/stl2/issues/154).

**Comment by ericniebler** [comment]
> Does that mean, that there will be no possibility to write std::sort(v)?

Long term, it may be std2::sort, or something.

**Comment by mmatrosov** [comment]
Ok, thank you. See also http://stackoverflow.com/q/34619540/261217
