### ISSUE TITLE
Fixed-size counted iterators

### ISSUE THREAD

**Issue by Morwenn** [ericniebler/range-v3#276]
I was thinking that counted iterators whose size is a template parameter could be a useful addition to the library. One of the main use cases is that some algorithms can benefit from optimizations for some specific sizes: for example, a sorting algorithm could use sorting networks if the size of the area to sort is known at compile-time and small enough (sorting networks are not the best example since they are only worth the cost for integers, but it illustrates the point). In order to implement such size-specific algorithms, one would simply have to overload the sorting algorithm on fixed-size counted iterators of specific sizes.

Basically, the fixed-size counted iterator type would act as a tag for optimizations and would fall back to a mechanism corresponding to regular counted iterators when there is no optimization available.

I currently use such small-size optimizations in a library when the algorithms are called on an `std::array` or a fixed-size C array, but I lack the ability to perform the same trick in a generic fashion with iterators input (as opposed to iterable inputs, and I know some places where it would be useful). An additional fixed-size counted iterator template would solve the problem elegantly enough, and might be of interest for algorithm developers in general.

**Comment by ericniebler** [comment]
If the distance to the end is part of the type of the iterator, what happens when you increment the iterator? It's type can't change.

**Comment by Morwenn** [comment]
Hum... Ok, I just thought as them as simple counted iterators with a "hint" at compile-time. I realize that forwarding them to other algorithms with an increased internal size different from the template size could cause wrong algorithms to be picked. Sorry, it's indeed probably not gonna go anywhere :/
