### ISSUE TITLE
Smart pointers behaviour with view::transform + view::indirect

### ISSUE THREAD

**Issue by mirth** [ericniebler/range-v3#279]
Possibly not an actual bug but the way you can shoot yourself in the foot.
Consider the following example:

```
#include <iostream>
#include <functional>
#include <range/v3/algorithm/for_each.hpp>
#include <range/v3/view/indirect.hpp>
#include <range/v3/view/transform.hpp>

struct foo{
 	foo(int _i):
    	i(_i) {}

	void bar() const{
	    std::cout << "foo::bar::i " << i << '\n';
	}
	~foo() {
	 	std::cout << "foo::~for \n";
	}

	int i;
};


using foo_ptr = std::unique_ptr<foo>;
// using foo_ptr = std::shared_ptr<foo>;

int main(){
 std::vector<int> const vec = {1};

 auto make_foo = [](auto i) {
 	return foo_ptr(new foo(i));
 };

 using namespace ranges;
 using std::placeholders::_1;

 for_each(vec
          | view::transform(make_foo)
          | view::indirect,        // foo::~for
          std::bind(&foo::bar, _1) // luckily it could be explicit segfault
	     );

 return 0;
}
```
For the first glance i've expected that lifetime of temporal pointer should be lasts until the end of the expression. But obviously it doesn't: smart pointer would be destroyed on `view::indirect`
and took object with it.

**Comment by ericniebler** [comment]
This is not how it works. The transform view generates temporary unique_ptrs. The indirect view takes those and returns the result of indirecting through them. It does not hold onto a copy of the pointer since that would require (a) storage within the indirect view (For how many elements? Just the current one?), (b) mutation, and (c) extra work. I guess my answer is: don't do that.

**Comment by gnzlbg** [comment]
There is no general way for `view::indirect` to detect that the "pointer"
it was given is going to delete its pointee when it goes out of scope.

One could, as a QoI issue, detect the special case of using
`view::indirect` with `std::unique_ptr` and static assert on that.

A more general alternative would be to have a trait that one could
specialize for `std::unique_ptr`, `boost::unique_ptr`, ... but I don't
think that this is worth it.

**Comment by sean-parent** [comment]
What about requiring that the pointer is copyable?

**Comment by CaseyCarter** [comment]
> What about requiring that the pointer is copyable?

`shared_ptr` is copyable, that does not imply that the pointee's lifetime won't end if we destroy the pointer.

**Comment by sean-parent** [comment]
I see - yes, I agree with Eric - don't do that :-) Or more specifically,
there is a precondition about the lifetime of the item referenced by
dereferencing in view::indirect must be sufficient. Not quite sure how to
state the precondition.
