### ISSUE TITLE
Lazy set algorithms?

### ISSUE THREAD

**Issue by tivek** [ericniebler/range-v3#280]
I need to compute set unions and intersections on ranges which may be infinite. To scratch that itch I used `view_facade` to write lazy versions of `set_intersection`, `set_difference`, `set_symmetric_difference`, and `set_union`.

A rough first version is [here](https://github.com/tivek/range-v3/blob/lazy-set-algorithm/include/range/v3/view/set_algorithm.hpp) (still need to write some tests...)

I would welcome a short look and comments to improve this code.

Here are some things I am mulling over:
- Any unobvious tricky situations to test for besides checking the common type/reference when doing union and symmetric difference?
- Resulting references/values of `set_intersection` and `set_difference` come from the first operand. `view_adaptor` would make for a simpler implementation.
- All these fat cursors are repetitive.

If lazy set operations sound useful to you I am willing to shape up the code and send a pull request.

**Comment by ericniebler** [comment]
This looks amazing! Are there tests?

**Comment by tivek** [comment]
In the following days I hope to have presentable tests for the most important properties: agreement with greedy algorithms, value and ref types, cardinalities.

**Comment by tivek** [comment]
Tests are here: [test/view/set_*.cpp](https://github.com/tivek/range-v3/tree/lazy-set-algorithm/test/view).

There's some unexpected behavior in set_difference and set_symmetric_difference (both lazy and greedy algorithms are affected): if input ranges have identical elements, the first of the same elements does not end up in the result.

**Comment by ericniebler** [comment]
Great, thanks. I am on a vacation this week with my family so I can't look right now.

**Comment by tivek** [comment]
No rush, enjoy the vacation!

**Comment by tonyelewis** [comment]
Just a quick note of support. For some time I've been thinking how great lazy set algorithms would be. I think this work could be really useful. Thanks!

**Comment by tivek** [comment]
Thanks for the support. I originally stumbled upon range-v3 as a way to make efficient lazy inner joins between two or more ranges of different types. To get my feet wet with the library (and get into C++14!) I tried to implement lazy set algorithms first.

I still have a lot to learn and tinker with this code - Travis [complains](https://travis-ci.org/tivek/range-v3/jobs/111094066) with Clang 3.7 and GCC 4.9 even though GCC 5.3.0 is pretty happy with the view.set_* tests. So I'm grateful for any hints. And if the lazy set algorithms are useful to anyone else, well I see that as a bonus. :)

**Comment by ericniebler** [comment]
Any chance this can be turned into a pull request?

**Comment by ericniebler** [comment]
Fixed by 27c40ab
