### ISSUE TITLE
Can't view::join vector<vector<int>> into a vector<int>

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#283]
The following snippet fails to compile under either Clang or GCC and under C++11 or C++14:

~~~~~.cpp
#include <range/v3/all.hpp>

int main() {
	const std::vector<std::vector<int>> nums = {
		{ 1, 2, 3 },
		{ 4, 5, 6 }
	};
	const std::vector<int> flat_nums = ranges::view::join( nums );
}
~~~~~

I would have hoped that this might work. Apologies if this is by-design or otherwise a non-issue.

Many thanks for your help.

**Comment by tonyelewis** [comment]
Here are files containing the compilers' errors:
[clang_errors.colour.txt](https://github.com/ericniebler/range-v3/files/137082/clang_errors.colour.txt)
[clang_errors.txt](https://github.com/ericniebler/range-v3/files/137083/clang_errors.txt)
[gcc_errors.colour.txt](https://github.com/ericniebler/range-v3/files/137084/gcc_errors.colour.txt)
[gcc_errors.txt](https://github.com/ericniebler/range-v3/files/137085/gcc_errors.txt)

**Comment by lomereiter** [comment]
Worked for me after declaring `nums` non-const. The error messages are incredibly convoluted indeed.

**Comment by ericniebler** [comment]
Ah yes, I missed that. The join view is stateful -- each sub range must be stored somewhere so it can be iterated -- so it can't be const. Maybe something can be done to improve the error message.

**Comment by ericniebler** [comment]
Oh wait, disregard that last comment. I shouldn't try to diagnose issues from my phone. I'll look deeper.

**Comment by tonyelewis** [comment]
Yep - looks good from this end. Thanks very much for fixing this and for doing it so quickly.
