### ISSUE TITLE
Make front() / back() return values (not references) from rvalue ranges

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#284]
The following two lines both compile but create dangling references:

``` .cpp
auto       &a = ranges::front( std::vector<int>( 1, 1 ) );
const auto &b = ranges::front( std::vector<int>( 1, 1 ) );
```

It'd be really nice if the compiler :
- prevented `a` with an informative message and
- used `b` to extend the lifetime of a copy of the relevant value.

I propose the following enhancement: split each of `front_fn::operator()` and `back_fn::operator()` into two overloads like this:

``` .cpp
/// For lvalue range, return its reference type
/// \return `*begin(rng)`
template<typename Rng,
    CONCEPT_REQUIRES_(Range<Rng>())>
RANGES_CXX14_CONSTEXPR
range_reference_t<Rng> operator()(Rng &rng) const
{
    return *begin(rng);
}

/// For rvalue range, return its value type
/// \return `*begin(rng)`
template<typename Rng,
    CONCEPT_REQUIRES_(Range<Rng>())>
RANGES_CXX14_CONSTEXPR
range_value_t<Rng> operator()(Rng &&rng) const
{
    return *begin(rng);
}
```

...which seems to achieve the above. The new error messages for `a` are good, eg GCC's is : `invalid initialization of non-const reference of type 'int &' from an rvalue of type 'ranges::v3::range_value_t<std::vector<int> > {aka int}'`.

Important issue: this code overloads on a universal reference and so may be better implemented using an internal despatch based on `std::is_lvalue_reference` (a la http://ericniebler.com/2013/08/07/universal-references-and-the-copy-constructo/). That said, because the extra overload is a _non-const_ reference, I don't think it suffers the notorious problems.

**Comment by ericniebler** [comment]
Whether the range is an rvalue is orthogonal to the lifetime of its references. Consider:

    vector<int> v{1,2,3};
    int &i = front(view::all(v)); // OK!

**Comment by tonyelewis** [comment]
Ah yes.

But maybe "orthogonal" is a bit strong - presumably `front()` needn't worry about the lifetime of references it returns from (non-malicious) lvalue ranges?

In that case, does your library enable you to do a more sophisticated version of what I'm attempting that returns the range's value type if it's an rvalue *and* isn't a view? (Ie is your library an E Niebler enabler?)

Can it be done using the mechanism you use to error-out on attempts to pipe rvalue, non-view ranges into views?

**Comment by tonyelewis** [comment]
Say I update my proposal as follows:

**Step 1**: Add a trait like:

~~~~~.cpp
template <typename T>
using range_entry_return_t = typename std::conditional<
	ranges::View<T>() || std::is_lvalue_reference<T>(),
	range_reference_t<T>,
	range_value_t<T>
>::type;
~~~~~

**Step 2**: change the return type of `front_fn::operator()` and `back_fn::operator()` to `range_entry_return_t<Rng>`?

I think that achieves what we'd want in all three cases:
 * prevents `auto       &a = ranges::front( std::vector<int>( 1, 1 ) );` with a nice message
 * stops `const auto &b = ranges::front( std::vector<int>( 1, 1 ) );` from dangling
 * leaves `int &i = front(view::all(v));` etc as was

Does that smell any better?

**Comment by tonyelewis** [comment]
(Just for context: I propose this approach be used for _any_ function that selects and returns a value from a range argument. For instance, the range-based `max()` / `min()` functions currently return a value but I suggest that they'd be better returning `range_entry_return_t<Rng>`. I'll open a separate issue about `max()` / `min()` soon.)

**Comment by ericniebler** [comment]
Your suggestion is not unreasonable, but it is more complex. I'm inclined to leave it as is and just tell people to not do that. Nevertheless, I'll reopen the issue and give it thought.

**Comment by tonyelewis** [comment]
Woo hoo! Thanks. Perhaps the trait would feel less complex with a descriptive comment :wink: :

~~~~~.cpp
/// \brief The type that functions should use to return one of the elements from a range argument of the given type
///
/// Where possible (ie for lvalue or view ranges),   return the range's entries by its reference type
/// Otherwise      (ie for rvalue, non-view ranges), return the range's entries by its value type
///
/// Example:
///
///     template <typename Rng>
///     range_entry_return_t<Rng> some_fn(Rng &&rng) {
///         [...]
///     }
template <typename T>
using range_entry_return_t = typename std::conditional<
    std::is_lvalue_reference<T>() || ranges::View<T>(),
    range_reference_t<T>,
    range_value_t<T>
>::type;
~~~~~

To be honest, though I *am* in favour of using it for `front` / `back`, I would agree that the value / complexity ratio is weaker here than with applying it to `max` / `min`, which currently always return by the value type. As I say, I'll aim to raise an issue about `max` / `min` soon.

Anyway, thanks very much for your time, effort and excellent library.
