### ISSUE TITLE
basic_iterator conversion is not always doing the right thing, related to #288

### ISSUE THREAD

**Issue by tivek** [ericniebler/range-v3#290]
Related to pull request #288. The C++14 errors found by clang [here](https://travis-ci.org/ericniebler/range-v3/builds/112324136) can be triggered by this minimal example:
```C++
#include <vector>
#include <range/v3/core.hpp>
#include <range/v3/utility/iterator.hpp>

int main()
{
    using namespace ranges;
    std::vector<int> vi;
    auto b = back_inserter(vi);
    auto m = move_into(b); // error complaining about not being able to convert back_insert_iterator<> to a move_into_iterator<>
    return 0;
}
```
As far as I understand, this is an edge case of the way how `basic_iterator<Cur, S>` prefers conversion from `basic_iterator<OtherCur, OtherS>` instead of the aggregate constructor handled by cursor `Cur`. In this particular case both `move_into_iterator` and `back_insert_iterator` derive from `basic_iterator`. So when `move_into(b)` tries to `return move_into_iterator<...>{std::move(b)};`, instead of aggregate initialization a conversion from `back_insert_iterator` to `move_into_iterator` is attempted.

This could be a pitfall for any iterator that derives from `basic_iterator`, relies on construction by its cursor/mixin, and its cursor's constructor takes a single iterator, possibly another `basic_iterator`, as input parameter.

It seems to me the tedious way around the problem is to explicitly write constructors for every iterator deriving from `basic_iterator` that wraps another iterator. It's late here and I'm tired, so... am I missing a more elegant solution?

**Comment by CaseyCarter** [comment]
This smells like [CWG1467](http://wg21.cmeerw.net/cwg/issue1467). I'll take a look.

**Comment by CaseyCarter** [comment]
> This smells like CWG1467.

But it is not. `basic_iterator` has constructors out the wazoo, so it is not an aggregate, and hence aggregate initialization never occurs. What *is* going on here is the problem I describe in https://github.com/ericniebler/range-v3/pull/288#issuecomment-193511483, which will be fixed by https://github.com/CaseyCarter/range-v3/commit/9c7821f6f10b1a549f46d582a9cd44ecdf15afa0 once we agree about the design direction for `basic_iterator`.

**Comment by tivek** [comment]
Thank you for looking into this, Casey!
