### ISSUE TITLE
MSVC 2015 Update 2 should now work

### ISSUE THREAD

**Issue by LegalizeAdulthood** [ericniebler/range-v3#292]
I believe according to their announcements, that expression SFINAE is supported enough in [Update 2](https://www.visualstudio.com/news/vs2015-update2-vs) to enable fully implementing all C++11, C++14 and (so far) C++17 library features.  Maybe give it a try and see if you can add it to your supported compilers list?

More details [here](https://blogs.msdn.microsoft.com/vcblog/2016/01/22/vs-2015-update-2s-stl-is-c17-so-far-feature-complete/) on expression SFINAE support:

> We previously announced that compiler support for Expression SFINAE became Partial in Update 1.  While it’s still Partial in Update 2, the compiler team was able to improve it to the point where the STL could carefully take a dependency on it.  As a result, Update 2’s STL fully supports N3462 “SFINAE-Friendly result_of” and LWG 2132 “std::function ambiguity”.  This is verified by exhaustive unit tests that run for every build.  (LWG 2132 allows meow(function<void (int)>) and meow(function<void (int, int)>) to be overloaded, then meow() can be called with a lambda taking 1 or 2 ints, and the corresponding overload will be selected.)

**Comment by ericniebler** [comment]
I will wait until the final release to try it. Visual Studio betas and release candidates have a history of messing up machines.

**Comment by LegalizeAdulthood** [comment]
I agree.  That's sensible. I just wanted to give you a heads up.

**Comment by pfultz2** [comment]
The [Tick](https://github.com/pfultz2/Tick) library which does the same style concept emulation already supports MSVC, so there is already sufficient support for expression SFINAE in the current MSVC. There was still a bit of workarounds needed to get it to work. I suspect that there will need to be more workarounds in the meta library as well.

**Comment by CaseyCarter** [comment]
Symbol length is going to be a problem with the MS ABI and linker. The layered/functional design of range-v3 results in some enormous symbols:

```c++
ranges::v3::basic_mixin<ranges::v3::detail::common_cursor<ranges::v3::basic_iterator<ranges::v3::adaptor_cursor<ranges::v3::basic_iterator<ranges::v3::adaptor_cursor<ranges::v3::basic_iterator<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::default_end_cursor>, ranges::v3::adaptor_base>, ranges::v3::adaptor_sentinel<ranges::v3::basic_sentinel<ranges::v3::default_end_cursor>, ranges::v3::iter_take_while_view<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::indirected<ranges::v3::split_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>, ranges::v3::view::split_fn::element_pred<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>&> >::cursor<true>::search_pred> >::sentinel_adaptor<true> > >, ranges::v3::indirect_view<ranges::v3::take_while_view<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::split_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>, ranges::v3::view::split_fn::element_pred<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>&> >::cursor<true>::search_pred> >::adaptor>, ranges::v3::adaptor_sentinel<ranges::v3::basic_sentinel<ranges::v3::adaptor_sentinel<ranges::v3::basic_sentinel<ranges::v3::default_end_cursor>, ranges::v3::iter_take_while_view<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::indirected<ranges::v3::split_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>, ranges::v3::view::split_fn::element_pred<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>&> >::cursor<true>::search_pred> >::sentinel_adaptor<true> > >, ranges::v3::indirect_view<ranges::v3::take_while_view<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::split_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>, ranges::v3::view::split_fn::element_pred<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>&> >::cursor<true>::search_pred> >::adaptor> >, ranges::v3::basic_sentinel<ranges::v3::adaptor_sentinel<ranges::v3::basic_sentinel<ranges::v3::adaptor_sentinel<ranges::v3::basic_sentinel<ranges::v3::default_end_cursor>, ranges::v3::iter_take_while_view<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::indirected<ranges::v3::split_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>, ranges::v3::view::split_fn::element_pred<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>&> >::cursor<true>::search_pred> >::sentinel_adaptor<true> > >, ranges::v3::indirect_view<ranges::v3::take_while_view<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::split_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>, ranges::v3::view::split_fn::element_pred<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>&> >::cursor<true>::search_pred> >::adaptor> > > >::basic_mixin(ranges::v3::detail::common_cursor<ranges::v3::basic_iterator<ranges::v3::adaptor_cursor<ranges::v3::basic_iterator<ranges::v3::adaptor_cursor<ranges::v3::basic_iterator<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::default_end_cursor>, ranges::v3::adaptor_base>, ranges::v3::adaptor_sentinel<ranges::v3::basic_sentinel<ranges::v3::default_end_cursor>, ranges::v3::iter_take_while_view<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::indirected<ranges::v3::split_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>, ranges::v3::view::split_fn::element_pred<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>&> >::cursor<true>::search_pred> >::sentinel_adaptor<true> > >, ranges::v3::indirect_view<ranges::v3::take_while_view<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::split_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>, ranges::v3::view::split_fn::element_pred<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>&> >::cursor<true>::search_pred> >::adaptor>, ranges::v3::adaptor_sentinel<ranges::v3::basic_sentinel<ranges::v3::adaptor_sentinel<ranges::v3::basic_sentinel<ranges::v3::default_end_cursor>, ranges::v3::iter_take_while_view<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::indirected<ranges::v3::split_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>, ranges::v3::view::split_fn::element_pred<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>&> >::cursor<true>::search_pred> >::sentinel_adaptor<true> > >, ranges::v3::indirect_view<ranges::v3::take_while_view<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::split_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>, ranges::v3::view::split_fn::element_pred<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>&> >::cursor<true>::search_pred> >::adaptor> >, ranges::v3::basic_sentinel<ranges::v3::adaptor_sentinel<ranges::v3::basic_sentinel<ranges::v3::adaptor_sentinel<ranges::v3::basic_sentinel<ranges::v3::default_end_cursor>, ranges::v3::iter_take_while_view<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::indirected<ranges::v3::split_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>, ranges::v3::view::split_fn::element_pred<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>&> >::cursor<true>::search_pred> >::sentinel_adaptor<true> > >, ranges::v3::indirect_view<ranges::v3::take_while_view<ranges::v3::iota_view<ranges::v3::basic_iterator<ranges::v3::iota_view<int, void>, ranges::v3::default_end_cursor>, void>, ranges::v3::split_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>, ranges::v3::view::split_fn::element_pred<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int, void>, true>&> >::cursor<true>::search_pred> >::adaptor> > >)
```

MS name mangling is fairly poor at compressing them, and the linker has a hard limit of 2047 characters in a symbol name. (This particular example is from act.split, which fails to link with Clang/C2.)

**Comment by ericniebler** [comment]
I've wondered whether lambdas could be effective at "erasing" types (from the POV of the linker) without actually erasing them (from the POV of the optimizer). I haven't investigated that idea yet, though.

**Comment by pfultz2** [comment]
> Symbol length is going to be a problem with the MS ABI and linker. The layered/functional design of range-v3 results in some enormous symbols

Actually, Boost.Xpressive suffers from this same limitation.

**Comment by sean-parent** [comment]
I have a vague recollection of a compiler inserting a hash for the
remainder of the symbol name when the symbol was too long... I couldn't
have sworn it was MS but my Google-fu is failing me.

**Comment by CaseyCarter** [comment]
> I have a vague recollection of a compiler inserting a hash for the
remainder of the symbol name when the symbol was too long... I couldn't
have sworn it was MS but my Google-fu is failing me.

You sir, are correct. I wasn't aware of this particular feature of the MS ABI. Clang/C2 writing an object file for act.split that contains a 4115 character long symbol name is a bug.

**Comment by sjeps** [comment]
I can't really wait starting using ranges as a "default" library for my projects.. Unfortunately now i'm developing on Windows... so this would be greatly appreciated

**Comment by LegalizeAdulthood** [comment]
Update 2 released
https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx

**Comment by sjeps** [comment]
Amazing.. Anyway i tested and it doesn't compile

**Comment by ericniebler** [comment]
Did you test with the Microsoft compiler (cl) or with clang-cl?

**Comment by CaseyCarter** [comment]
Update 2 C1XX and range-v3 do not play well together. Clang/C2 ("Clang with Microsoft Codegen") is very close, modulo bugs:

1. -Ofast has bad interactions with the standard library,
2. The frontend doesn't perform the MS ABI magic that replaces mangled symbol names longer than 2k (IIRC) characters with an MD5 hash, which can (a) ICE the compiler when generating debug info, and/or (b) cause linker errors about duplicate COMDATs.

CMake trunk has support for generating a solution with Clang/C2 as the toolset ("-T v140_clang_3_7"), which is convenient if you want to build the test suite. Not all tests will compile in debug, but last I checked release builds will compile and run tests with 0 failures if the "-Ofast" in CMakeLists.txt is replace with "-O3".

It's very likely that Update 3 Clang/C2 will work out-of-box with range-v3.

**Comment by ericniebler** [comment]
That's great news!

**Comment by sjeps** [comment]
I tried with the standard cl.exe. Anyway the meta headers failed to build.
Maybe now that update 2 is stable you could give it a try

**Comment by sjeps** [comment]
I tried with the standard cl.exe. Anyway the meta headers failed to build.
Maybe now that update 2 is stable you could give it a try

**Comment by ericniebler** [comment]
Closing this since it looks like we'll need to wait until Update 3.

**Comment by CaseyCarter** [comment]
> release builds will compile and run tests with 0 failures

Woops, this is a lie. act.aplit fails to link due to the mentioned duplicate COMDAT problem. 1/186 test failures.
