### ISSUE TITLE
Docs' description of view::adjacent_remove_if differs from its current behaviour

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#297]
The description of `view::adjacent_remove_if` includes (my emphasis):

> If the predicate evaluates to false, the **first** element of the pair is included in the result range; otherwise, it is skipped.

...but to match the current behaviour, I think this should be "[...]the **second** element of the pair [...]".
A small illustrative example:

~~~~~.cpp
#include <range/v3/all.hpp>

#include <iostream>

constexpr bool is_even(const int &x) { return ( x % 2 == 0 ); }
static_assert(   is_even( 0 ), "" );
static_assert( ! is_even( 1 ), "" );
static_assert(   is_even( 2 ), "" );
static_assert( ! is_even( 3 ), "" );

constexpr bool is_odd_then_even(const int &x, const int &y) { return ( ! is_even( x ) && is_even( y ) ); }
static_assert( ! is_odd_then_even( 0, 1 ), "" );
static_assert(   is_odd_then_even( 1, 2 ), "" );
static_assert( ! is_odd_then_even( 2, 3 ), "" );
static_assert(   is_odd_then_even( 3, 4 ), "" );

int main() {
	// this outputs: [0,1,2,3,4,5,6,7,8,9,10]
	std::cerr << ( ranges::view::iota( 0, 11 )                                                        ) << "\n";

	// this outputs: [0,1,3,5,7,9]
	std::cerr << ( ranges::view::iota( 0, 11 ) | ranges::view::adjacent_remove_if( is_odd_then_even ) ) << "\n";
}
~~~~~

This code asks `view::adjacent_remove_if` to remove elements when the pair's first is odd and its second is even. Since it's removing the even elements (including the very last one), it must be the **second** element of the pair that gets included/skipped.

**Comment by ericniebler** [comment]
The description is correct. The code was wrong. It's correct now, thanks.

This:

```c++
ranges::view::iota( 0, 11 ) | ranges::view::adjacent_remove_if( is_odd_then_even ) )
```

... should be: [0,2,4,6,8,10]

**Comment by tonyelewis** [comment]
Looks good to me. Thanks very much.
