### ISSUE TITLE
A view::get<N> to quickly select an element from a range of pair/tuple/array ?

### ISSUE THREAD

**Issue by Arzar** [ericniebler/range-v3#301]
What the best way to select an element from a range of pair/tuple/array ? 
Fairly often when working on a range, at some point in the pipeline I want to zip my range with another range, do something, then 'unzip' and continue on the original range.

For example, if for a step I really need an index, I would want to zip my range with view::iota then unzip :

```
   std::vector<int> v = { 3, 1, 4, 1, 5, 9, 2, 6, 5, 3 };
   auto r =     view::zip(v, view::ints(0))
             | view::filter([](const std::pair<int, int>& p) {return p.first < p.second; })
             //| view::transform(&std::get<0>); // doesn't compile
             //| view::transform(&std::get<0, int, int>); // doesn't compile
             | view::transform([](const std::pair<int, int>& p) {return p.first; }); // compile but a bit clumsy
```

Or filtering a range based on another one :

```
   std::vector<int> v = { 3, 1, 4, 1, 5, 9, 2, 6, 5, 3 };
   std::vector<bool> f = { true, false, false, true, true, false, true, true, false, true };
   auto r =     view::zip(v, f)
             | view::filter([](const std::pair<int, bool>& p) {return p.second; })
             | view::transform([](const std::pair<int, bool>& p) {return p.first; });
```

I wonder if it warrant some kind of view::get<N> ?

Because for a struct there is nice shorthand syntax to pick one of the member :

```
struct S {int x, int y, int y};
// . . .
view::transform(&S::y);
```

However for pair, tuple or array we need to use a full view::transform :

```
std::array<int, 3>
// . . .
view::transform([](const std::array<int, 3>& a) { return a[1]; } ;
```

**Comment by ericniebler** [comment]
For `std::pair`, you can use `view::keys` and `view::values` in view/map.hpp. For the rest, you could define a wrapper for `std::get`, like (untested):

```c++
template <std::size_t N>
struct get
{
    template <class T>
    auto operator()(T &&t) const
      -> decltype(std::get<N>(std::forward<T>(t)))
    {
         return std::get<N>(std::forward<T>(t));
    }
};
```

Then you would `view::transform(my::get<N>())`. This might be a worthwhile addition to range-v3. I just need to figure out what header to put it in.

**Comment by Arzar** [comment]
Thanks for the tip for view::keys and view::values ! 
Also the function-object wrapper around std:::get seems like a very good solution.

**Comment by BenFrantzDale** [comment]
This looks like it now exists here: https://github.com/ericniebler/range-v3/blob/master/include/range/v3/utility/get.hpp? Can this issue be closed?

**Comment by Arzar** [comment]
Wow, blast from the past.
So it's the two overload CPP_auto_fun(get)(TupleLike &&t) added in 2018 (a3e6a4a55e84df522e2f25f4427f65c8acdb09fb) that do the magic ?

**Comment by Arzar** [comment]
```
#include "range/v3/all.hpp"
#include <vector>
#include <iostream>
using namespace ranges;

int main(){

std::vector<int> v = { 3, 1, 4, 1, 5, 9, 2, 6, 5, 3 };
   auto r =    view::zip(v, view::ints(0, unreachable))
               | view::filter([](const std::pair<int, int>& p) {return p.first < p.second; })
               | view::transform(&get<0, std::pair<int, int>>); 

   std::cout << r;
}
```
This code now works! 
Unfortunately we have to specify the full type &get<0, std::pair<int, int>>, because just &get<0> doesn't compile.

**Comment by BenFrantzDale** [comment]
Yeah. I asked a related question here: https://stackoverflow.com/questions/70250524/c-class-template-taking-either-type-or-non-type/ and while there are various approaches, my conclusion is you can't make `get<0>` and `get<int>` be function objects in the same namespace and so you can't get the desirable Python-like syntax of `transform(get<int>)` or `transform(get<0>)`.

**Comment by Arzar** [comment]
Thanks for checking! Then I will close this issue.

**Comment by eroller** [comment]
std::ranges has [std::views::elements](https://en.cppreference.com/w/cpp/ranges/elements_view), but looks like this is not available in range-v3.

**Comment by Arzar** [comment]
Didn't know about std::views::elements. Nice. 
Can't believe that, 8 years after opening this issue, we can now solve it entirely in standard C++!
```
#include <print>
#include <ranges>
#include <vector>
#include <fmt/ranges.h>

int main()
{
    std::vector v = { 3, 1, 4, 1, 5, 9, 2, 6, 5, 3 };
    auto r =    std::views::zip(v, std::views::iota(0))
              | std::views::filter([](const auto& p) { return std::get<0>(p) < std::get<1>(p); })
              | std::views::elements<0>;

    fmt::print("{}", r);
}
```
