### ISSUE TITLE
GCC won't compile view::transform with function returning reference to ABC

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#302]
I'm attempting to use a `view::transform` to return a (const) reference to an abstract base class. Apologies if this is something I just shouldn't do. Anyway, the following code compiles (and runs) under Clang but not GCC.

~~~~~.cpp
#include <iostream>

#include <range/v3/all.hpp>

class abstr {
private:
	virtual std::string do_get_name() const = 0;
public:
	virtual ~abstr() = default;
	std::string get_name() const { return do_get_name();}
};

class concr final : public abstr {
private:
	virtual std::string do_get_name() const override final { return "advertising signs that con"; }
public:
	virtual ~concr() = default;
};

int main() {
	const std::vector<concr> v( 4, concr{} );

	auto the_view = ranges::view::iota( 0, 4 )
		| ranges::view::transform(
			[&] (const size_t &x) -> const abstr & {
				return static_cast<const abstr &>( v[ x ] );
			}
		);

	for (const auto &x : the_view) {
		std::cerr << x.get_name() << "\n";
	}
}
~~~~~

The core of the GCC's first error message is:

~~~~~
range-v3/include/range/v3/view/transform.hpp:89:89: error: no match for call to ‘(ranges::v3::iter_transform_view<ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<int>, true>, ranges::v3::indirected<main()::<lambda(const size_t&)> > >::adaptor<true>::fun_ref_ {aka ranges::v3::reference_wrapper<const ranges::v3::semiregular<ranges::v3::indirected<main()::<lambda(const size_t&)> > >, false>}) (ranges::v3::copy_tag, ranges::v3::basic_iterator<ranges::v3::iota_view<int>, ranges::v3::default_sentinel>)’
                     detail::decay_t<decltype(fun_(copy_tag{}, range_iterator_t<Rng>{}))>;
                                                                                         ^
~~~~~

...and that's followed by a list of candidates and their reasons for failure (including `error: invalid abstract return type ‘abstr’` at `range-v3/include/range/v3/utility/functional.hpp:347:18:`).

Is this an error in GCC? Or erroneous permissiveness in Clang? Can/should range-v3 be changed to make this work?

Many thanks for all your excellent work.

**Comment by ericniebler** [comment]
The problem comes from trying to compute the `value_type` of the resulting transform view. It is `abstr`, which is a little weird since you can't have values of that type.

**Comment by tonyelewis** [comment]
Indeed. It looks like Clang also deduces the `value_type` as `abstr` (and the `reference_type` as `const abstr &`). But Clang seems able to dereference iterators to `const abstr &` without complaining about not being able to return an abstract return type.

Can GCC be persuaded to do the same? Or is Clang being too permissive?

**Comment by ericniebler** [comment]
It's really just a simple matter of doing the `std::decay` at the  call site instead of in the function signature. Thanks for reporting this.

**Comment by tonyelewis** [comment]
This works for me. Thanks very much for the time and effort involved in making this change.
