### ISSUE TITLE
InputIterator concept too strict?

### ISSUE THREAD

**Issue by kristoczaj** [ericniebler/range-v3#304]
TL;DR: The InputIterator concept requires Readable<decltype(x++)> and DefaultConstructible<decltype(x++)>. Isn't that too strict? It fails in a case where the iterator's postfic operator ++ returns a proxy.

Example:

``` c++
#include "boost/iterator/iterator_facade.hpp"
#include "range/v3/utility/iterator.hpp"

template <class V, class Category>
class TestIter
    : public boost::iterator_facade<TestIter<V, Category>, V, Category, V> {
 public:
  using typename boost::iterator_facade<TestIter<V, Category>, V, Category,
                                        V>::difference_type;

  TestIter() : v_() {}

  explicit TestIter(V v) : v_(v) {}

 private:
  friend class boost::iterator_core_access;

  V dereference() const { return v_; }
  bool equal(const TestIter& other) const { return v_ == other.v_; }
  void increment() { ++v_; }
  void decrement() { --v_; }
  void advance(difference_type n) { v_ += n; }
  difference_type distance_to(const TestIter& other) const {
    return other.v_ - v_;
  }

  V v_;
};

using InIter = TestIter<int, std::input_iterator_tag>;

static_assert(ranges::InputIterator<InIter>(), "");

void f(InIter x) {
  static_assert(ranges::Readable<decltype(x++)>(), "");
  static_assert(ranges::DefaultConstructible<decltype(x++)>(), "");
}
```

I think `static_assert(ranges::InputIterator<InIter>(), "")` fails, because the two static_asserts in `f()` fail. So my question is: isn't InputIterator too strict about requirements on `decltype(x++)`?

The proxy doesn't satisfy Readable, because it doesn't provide a nested public `value_type`. And it isn't DefaultConstructible - why should it be?

Kind regards,
Kris

**Comment by gnzlbg** [comment]
Isn't `static_assert(Same<decltype(x++), void>{});` true? Obviously `void` isn't neither `Readable` nor `DefaultConstructible`, or what am I missing?

**Comment by gnzlbg** [comment]
What is the return type that `boost::iterator_facade` assigns to  `operator++` in your case?

**Comment by kristoczaj** [comment]
It returns `boost::iterators::detail::postfix_increment_proxy<TestIter<int, std::input_iterator_tag> >`.

```c++
    // iterators whose dereference operators reference the same value
    // for all iterators into the same sequence (like many input
    // iterators) need help with their postfix ++: the referenced
    // value must be read and stored away before the increment occurs
    // so that *a++ yields the originally referenced element and not
    // the next one.
    template <class Iterator>
    class postfix_increment_proxy
    {
        typedef typename iterator_value<Iterator>::type value_type;
     public:
        explicit postfix_increment_proxy(Iterator const& x)
          : stored_value(*x)
        {}

        // Returning a mutable reference allows nonsense like
        // (*r++).mutate(), but it imposes fewer assumptions about the
        // behavior of the value_type.  In particular, recall that
        // (*r).mutate() is legal if operator* returns by value.
        value_type&
        operator*() const
        {
            return this->stored_value;
        }
     private:
        mutable value_type stored_value;
    };
```

As you can see, the value_type nested type is private, and the proxy isn't `DefaultConstructible`. 

So why do ranges expect this proxy to satisfy these concepts?

**Comment by gnzlbg** [comment]
Looking at [Boost documentation](http://www.boost.org/doc/libs/1_60_0/libs/iterator/doc/new-iter-concepts.html) it seems that the `operator++` of a  `ReadableIterator` `X` is required to return `X&`, the same is true for `SinglePass` and `Forward` iterator. Since both require an associated `value_type` this might partially be a bug in `Boost.Iterator` implementation.

I don't think one can work around the missing `SemiRegular` constraint (so if you need this you are out of luck). 

Even though Boost `SinglePass` does not require it, Boost `ForwardIterator` and up do require `DefaultConstructible` as well. Do you have this problem with `std::forward_iterator_tag`?

I don't know why the Ranges TS (and range-v3) requires `SemiRegular` and `value_type` on `Readable`, but I can guess that it is to allow algorithms to cache the result of a read as well as pre-store a value of the iterator that `operator++` returns. What I know is that I find it extremely helpful that most/all of the types in range-v3 are at least `SemiRegular`. Often I need to store these types inside my own types, and range-v3 types being `SemiRegular` means that I don't have to work around them if I want to make my own type `SemiRegular`.  

For a definitive answer you need to wait on Eric or Cassey to comment on this.

**Comment by kristoczaj** [comment]
Hmm, in that case I'll check/ask at Boost, why the proxy isn't DefaultConstructible and why the typedef is private. I'll report back here.

Cheers,
Kris

**Comment by ericniebler** [comment]
I *think* `ranges::basic_iterator` is a superset of `boost::iterator_facade`, and it has a similar interface. You might just consider porting. But that's beside the main point.

No, I don't think the Iterator concepts are too strict. Requiring the result of `i++` to satisfy `Readable` (i.e, to be default constructible and have an accessible value type) is not onerous and is beneficial to generic code. I would rather see Boost.Iterator change its `postfix_increment_proxy`. I don't think the changes would be too invasive (although it might require putting the cached value in an `optional` if it's not already default-constructible).

Have you already asked on the Boost mailing list, or asked the maintainer of Boost.Iterators? Conformance with the concepts in the Ranges TS should be a strong motivator.

**Comment by kristoczaj** [comment]
Thanks Eric for explaining and for pointing to ranges::basic_iterator. In my case, the code that actually uses boost::iterator_facade may not depend on range_v3.

I filed the ticket https://svn.boost.org/trac/boost/ticket/12071
no responses yet. I intend to following up on the Boost mailing list in a day or two.

**Comment by ericniebler** [comment]
Good luck! You'll have better luck with Boost if you submit a patch.

**Comment by ericniebler** [comment]
@kristoczaj Any news from Boost about this?

**Comment by kristoczaj** [comment]
@ericniebler I posted on the Boos developers mailing list today. Perhaps the issue receives more attention there.

**Comment by ericniebler** [comment]
Many moons ago we changed `InputIterator` to require nothing of the result of post-fix increment. Closing.
