### ISSUE TITLE
Type with explicit default constructor fails DefaultConstructible concept under Clang

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#314]
The following fails to compile under Clang 3.6.2-1:

~~~~~.cpp
#include <range/v3/all.hpp>

struct expl_def_cons final {
	explicit expl_def_cons(const int = 0) {}
};

// Passes:
static_assert( static_cast<bool>( ranges::Constructible       <expl_def_cons>() ), "" );

// Fails under Clang:
static_assert( static_cast<bool>( ranges::DefaultConstructible<expl_def_cons>() ), "" );

int main() {}
~~~~~

I think this is because Clang rejects the `DefaultConstructible` `valid_expr` `new T[n]()` for `expl_def_cons`'s explicit default constructor.

That can be illustrated with the following:

~~~~~.cpp
struct expl_def_cons final {
	explicit expl_def_cons(const int = 0) {}
};

template <typename... Ts> void ignore_unused(Ts &&...) {}

int main() {
	ignore_unused( new expl_def_cons[ 42 ]{} );
}
~~~~~

...which Clang rejects:

~~~~~
clone_ptr_should_be_readable.cpp:8:41: error: chosen constructor is explicit in copy-initialization
        ignore_unused( new expl_def_cons[ 42 ]{} );
                                               ^
clone_ptr_should_be_readable.cpp:2:11: note: constructor declared here
        explicit expl_def_cons(const int = 0) {}
                 ^
clone_ptr_should_be_readable.cpp:8:41: note: in implicit initialization of array element 0 with omitted initializer
        ignore_unused( new expl_def_cons[ 42 ]{} );
                                               ^
1 error generated.
~~~~~

Can the valid expression be tweaked to allow an explicit default constructor?

**Comment by tonyelewis** [comment]
Two points to support the idea that this issue isn't just a quirk in an old Clang...

The standard's view of explicit default constructors is complicated
-----

See: http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#1518

Recent compilers are as-strict / stricter
-----

I've tried the latter snippet on more recent compilers using http://melpon.org/wandbox/.

"Clang HEAD 3.9.0 (trunk 265544)" still rejects with the same errors.

Though my "GCC v5.2.1" accepts, "GCC HEAD 6.0.0 20160405 (experimental)" now warns:

~~~~~
prog.cc: In function 'int main()':
prog.cc:8:41: warning: converting to 'expl_def_cons' from initializer list would use explicit constructor 'expl_def_cons::expl_def_cons(int)'
  ignore_unused( new expl_def_cons[ 42 ]{} );
                                         ^
prog.cc:8:41: note: in C++11 and above a default constructor can be explicit
~~~~~

**Comment by CaseyCarter** [comment]
It is intentional that [`DefaultConstructible` rejects types with explicit default constructors](https://github.com/CaseyCarter/cmcstl2/blob/master/include/stl2/detail/concepts/object/move_constructible.hpp#L129), just as `Move`/`CopyConstructible` reject types with explicit move / copy constructors, although that decision was made before recent changes to CWG1518.

Why should explicit default constructors be allowed?

**Comment by tonyelewis** [comment]
Thanks for the reply. Ah - I see.

> Why should explicit default constructors be allowed?

Well I guess my first thought is: why shouldn't they be? Why prevent the range-v3 magic working on a bunch of vaguely reasonable types unless you have to?

So then I guess an important question is: how much of the code that imposes the `DefaultConstructible` concept (or other derived concepts) can only be written to work if the type is *implicitly* default constructible?

If it isn't a large part then it seems a shame to impose a concept that rejects types on which the code would otherwise work.

What sort of code constructs require that a default constructible type has an *implicit* default constructor? The `valid_expr` illustrates that C-style arrays present one possible case but AFAIU that can be worked-around by replacing with `std::array`:

~~~~~.cpp
#include <array>
#include <iostream>

struct expl_def_cons final {
	int sub_value = 12345;
	explicit expl_def_cons(const int = 0) {}
};

int main() {
	std::array<expl_def_cons, 42> a;
	for (const auto &x : a) {
		std::cerr << "value is " << x.sub_value << "\n";
	}
}
~~~~~

Is that right?

Anyway, thanks very much for taking the time to reply and for all your hard work on this superb library.

**Comment by tonyelewis** [comment]
To explicitly (!) mention one possible approach that's implicit in the above: `DefaultConstructible` could be relaxed to allow explicit default constructors and then a new `ImplicitDefaultConstructible` concept could be added and deployed if/where needed.

**Comment by tonyelewis** [comment]
Quick side: does it make sense to make `ImplicitDefaultConstructible` more comprehensively reject explicit default constructors in all compilers with something along the lines of the following?

~~~~~.com
void implicit_fn(const T &);
implicit_fn( {} );
~~~~~

**Comment by gnzlbg** [comment]
Do you have a particular use case in mind for ranges of types with explicit
default constructors?

On Thursday, 7 April 2016, Tony E Lewis <notifications@github.com> wrote:

> Quick side: does it make sense to make ImplicitDefaultConstructible more
> comprehensively reject explicit default constructors in all compilers with
> something along the lines of the following?
>
> void implicit_fn(const T &);
> implicit_fn( {} );
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ericniebler/range-v3/issues/314#issuecomment-206758626>
>


-- 
Dipl.-Ing. Gonzalo Brito Gadeschi
Institute of Aerodynamics and Chair of Fluid Mechanics
RWTH Aachen University
Wuellnerstraße 5a
D-52062 Aachen
Germany
Phone: ++49-(0)241-80-94821
Fax: ++49-(0)241-80-92257
E-mail:  g.brito@aia.rwth-aachen.de
Internet: www.aia.rwth-aachen.de

**Comment by tonyelewis** [comment]
Thanks for the reply.

> Do you have a particular use case in mind for ranges of types with explicit default constructors?

No - I've been able to easily fix my original example. Thanks. :smiley:

But in general, it seems pretty reasonable for developers to:
 * make a class default constructible by adding a default argument to a single parameter constructor,
 * keep that constructor explicit if implicit conversions from the parameter type would be unhelpful.

I'd guess that the world's C++ code uses many such types and that many of those types' users are not easily able to modify them.

Of course, if there are good reasons why the bulk of the range-v3 code must require `DefaultConstructible` to mean `ImplicitDefaultConstructible`, then that's that. But if not, it seems a shame for that concept to require more than necessary and hence break range-v3 on types it could otherwise handle.

It's not clear to me why the bulk of the range-v3 code *would* require that, but I stress that I say this in full awareness that this may say more about me than about range-v3 / C++. :wink:

Also, I worry that when users see range-v3 reject their type as not `DefaultConstructible` but then find that the compiler *is* happy to default construct their type (eg `expl_def_cons a;`), many will just give up on range-v3 rather than digging deeper and/or reporting it.

**Comment by ericniebler** [comment]
> make a class default constructible by adding a default argument to a single parameter constructor,

They probably don't know when they are doing that that they are limiting how their class can be used. A concept check can help them. Yes, some code can't be changed. Those people can use STL1.

**Comment by tonyelewis** [comment]
Thanks for the reply.

> They probably don't know when they are doing that that they are limiting how their class can be used.

OK, so I suspect I'm just missing: how does it limit use? Of course, it means that some code needs to be explicit about the type (eg functions have to `return T{};` rather than `return {};`). Also, the concept code shows that `new T[ 42 ]{}` won't (consistently) work but, AFAIU, `new std::array<T, 42>` will and can substitute easily. In what other ways does it limit use?

If there aren't substantial obstacles, it feels a bit militant for a library to reject types with which it could otherwise easily work.

> A concept check can help them.

If I can't persuade you to drop the requirement, might I persuade you to rename the concept to `ImplicitDefaultConstructible`? Otherwise, I fear many people won't actually be helped by a concept called `DefaultConstructible` that's failing on a type they can see can be default constructed.

Anyway, thanks to all for your time and effort in responding and for your work on this superb library.

**Comment by CaseyCarter** [comment]
> Well I guess my first thought is: why shouldn't they be?

For the reason validated by the expression that rejects them: you can't value-initialize an array of objects that are not implicitly default constructible, or allocate an array of such objects with `new` regardless of how they are initialized thanks to [expr.new]/19:

> If the *new-expression* creates an object or an array of objects of class type, access and ambiguity control are done for the allocation function, the deallocation function (12.5), and the constructor (12.1). If the new-expression creates an array of objects of class type, the destructor is potentially invoked (12.4).

```c++
#include <array>

struct A { explicit A(int = 0) {} };

int main() {
    A[42]{}; // ill-formed
    std::array<A, 42>{}; // ill-formed
    new A[1]{A{42}}; // ill-formed (depending on interpretation of [expr.new]/19)
    [](int n){ new A[n]{ /* ill-formed regardless of what you put here */ }; }(2);
}
```

It's a design tenet of the object concepts that if I'm permitted to construct a `Foo`, I should be able to make an array of `Foo`, allocate a `Foo`, or allocate an array of `Foo`. Explicit default constructors are not compatible with that expectation.

> To explicitly (!) mention one possible approach that's implicit in the above: `DefaultConstructible` could be relaxed to allow explicit default constructors and then a new `ImplicitDefaultConstructible` concept could be added and deployed if/where needed.

I don't see this distinction as valuable enough to motivate creation of additional concepts. Every time we bifurcate a concept, we also bifurcate the sets of models and the sets of clients. Everyone who would have used the original concept now has to learn two, learn the distinction between them, and make a choice. Providing a standard library with thousands of extremely niche concepts would be a disservice to users far worse than providing a standard library with no concepts at all.

**Comment by gnzlbg** [comment]
+1.

**Comment by tonyelewis** [comment]
Thanks for the reply.

Ah, OK. So then my query focuses on `std::array`. I'm seeing an explicit default constructible `A` work in:

~~~~~.cpp
const auto ptr = new std::array<A, 42>{};
const auto arr =     std::array<A, 42>{};
~~~~~

under:
 * Clang 3.6.2-1
 * Clang 3.9.0 (HEAD trunk 265680, via Wandbox)
 * GCC 5.2.1-22ubuntu2
 * GCC 6.0.0 (HEAD 201604, via Wandbox)

Are these compilers wrong to allow this?

**Comment by CaseyCarter** [comment]
> Are these compilers wrong to allow this?

None of these compilers implements the resolution of [CWG1518](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#1518), since the issue has not been resolved yet ;) But yes, if the cases that CWG1518 seems to want to forbid were in fact forbidden, that initialization would be ill-formed since it copy-list-initializes `A`s from `{}`. ([GCC6](http://melpon.org/wandbox/permlink/NEWMjBdfuodhlQgy) and [Clang 3.9](http://melpon.org/wandbox/permlink/aaJ7iZIqgRnyhCci) both issue diagnostics for most lines of the sample program I posted.)

**Comment by tonyelewis** [comment]
Thanks for the reply.

From skimming [(the November 2014 draft of) the C++14 standard](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf), I'd got the impression that `std::array`'s aggregate initialization initializes members without corresponding initializer clauses with expression of the form `T{}` (see the example in 8.5.1.7, p202) and so didn't fall under the remit of CWG1518.

Still, I clearly have much less of a clue about this than you. I don't suppose you consider it reasonable to use variadic templates and `std::index_sequence` to provide explicit initializer clauses in a `std::array`'s initializer list?

I agree with the previously described doubts about splitting the concepts. Any chance of me persuading anyone of a rename to `ImplicitDefaultConstructible`?

Either way, thanks to all for your time and effort spent on responding. I'm happy for this issue to be closed.

**Comment by ericniebler** [comment]
> I agree with the previously described doubts about splitting the concepts. Any chance of me persuading anyone of a rename to `ImplicitDefaultConstructible`?

I prefer to leave it the way it is and get more field experience. If it becomes an obstacle for many, we can revisit it.

**Comment by tonyelewis** [comment]
One last hurrah: might it be worth adding a brief note to all `static_assert`s that check for `DefaultConstructible`, say "[...] (note: the default constructor must not be explicit)"?

I think this would help more users understand this point quickly. That in turn would help to make the field experience more trustworthy.

Anyway, thanks to all for all responses.
