### ISSUE TITLE
[Q] How to apply rotate to the right?

### ISSUE THREAD

**Issue by krzysztof-jusiak** [ericniebler/range-v3#318]
Hi,

Firstly, thank you for a great library with enormous potential to simplify STL.
I have a few newbie questions though because I can't figure how to do them and it's hard to find answers online.

So, I have a simply example in which I would like to rotate a single row, however, I can't make it to work :(

```cpp
int values[] = {1, 2, 3, 4,
                1, 2, 3, 4,
                0, 1, 1, 3,
                1, 2, 3, 4};

check_equal(values, {1, 2, 3, 4,
                     1, 2, 3, 4,
                     0, 1, 1, 3,
                     1, 2, 3, 4});

auto&& row_view = values | view::chunk(4) | view::slice(2, 3);

// Seems not to have effect on values :(
// In my understanding view just refer to
// original values so rotate should change them?
/ /ranges::rotate(row_view, ranges::begin(row_view) + 1);

// How to rotate to the right?
// In STL it would be 'std::rotate(v.rbegin(), v.rbegin() + 1, v.rend());'
// ranges::rotate(row_view, ranges::rbegin(row_view) + 1); // doesn't comile

check_equal(values, {1, 2, 3, 4,
                     1, 2, 3, 4,
                     3, 0, 1, 1,
                     1, 2, 3, 4});
```

Moreover, is there any easy way without creating a custom view facade to get a column_view?

```cpp
auto&& column_view = values | view::filter([](auto it) { return !(it % 4); } ) | view::slice(2, 3);
check_equal(column_view, {1, 1, 3, 1});
```

Thank you

**Comment by ericniebler** [comment]
When you chunk a range, you end up with a range of ranges. A slice of a range of ranges is still a range of ranges. So when you are calling `rotate`, you aren't trying to rotate elements. You are trying to rotate *ranges*. (You can confirm that with `cout << row_view`. That prints `[[0,1,1,3]]`, which is a range of one element, which is a range of 4 elements.)

Try this:

```c++
auto const && rows_view = values | view::chunk(4) | view::slice(2, 3);
auto const && third_row = front(rows_view);
ranges::rotate(third_row, ranges::end(third_row) - 1);
```

> is there any easy way without creating a custom view facade to get a column_view?

I think you're looking for a `transpose` view. range-v3 doesn't have one yet, but you can find one if you look in examples/calendar.cpp. Just grab `interleave` and `transpose`, and you should have what you want.
