### ISSUE TITLE
CONCEPT_REQUIRES_(Range<Rng>() && Permutable<I>()) error when rotate a range view

### ISSUE THREAD

**Issue by krzysztof-jusiak** [ericniebler/range-v3#319]
I have the same problem when using join after chunk. Is this kind of transformation disallowed?

```cpp
int data[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
auto const && v = data | view::chunk(3) | view::transform([=](auto r) { return front(r | view::drop(2) | view::take_exactly(1));});
std::cout << v << std::endl; // [3, 6, 9] // seems like it's a range
ranges::rotate(v, ranges::begin(v) + 1); // doesn't compile CONCEPT_REQUIRES_(Range<Rng>() && Permutable<I>())
std::cout << v << std::endl; // [6, 9, 3] // expected
```

**Comment by ericniebler** [comment]
Your lambda is returning elements by value. You can't permute a range of values. They need to be references so you can swap elements. Change the lambda to return references to elements.

**Comment by ericniebler** [comment]
```c++
int data[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
auto const && v = data | view::drop(2) | view::stride(3);
std::cout << v << std::endl; // [3, 6, 9]
ranges::rotate(v, ranges::begin(v) + 1);
std::cout << v << std::endl; // [6, 9, 3]
```

**Comment by krzysztof-jusiak** [comment]
That's awesome! Thank you. I have seen stride in tests (I'm learning from them) but, somehow, forgotten about it. Probably, because tests for stride are a bit more complex than others. Anyway, I honestly love concept of views. There is no even a comparison to STL.
