### ISSUE TITLE
Is there a way to create a joined but not flattened range view of given ranges?

### ISSUE THREAD

**Issue by krzysztof-jusiak** [ericniebler/range-v3#321]
I'm sorry for bothering again, but I can't find any solution for merging 2 or more views without flattening them and I bet, it's possible somehow. I tried join and looked into all views, however, I could't find a way to do so yet.

```cpp
auto merge_views = [](auto&& v1, auto&& v2) {
    //return [v1, v2];
    //return v1 | v2;
    //return v1, v2;
    //return view::make_range(v1, v2);
    
    //this one seems to work, however, its a bit awkward
    return view::concat(v1 | view::chunk(ranges::size(v1)), v2 | view::chunk(ranges::size(v2)));
};

int main() {
    int values[] = {1, 2, 3, 4, 5};
    auto const&& v1 = v | view::take(2);
    auto const&& v2 = v | view::drop(2) | view::take(3);
    std::cout << merge_views(values) << std::endl;// [[1, 2], [3, 4, 5]]
}
```

**Comment by gnzlbg** [comment]
Have you tried concat?

**Comment by ericniebler** [comment]
You have N ranges, and you want to turn it into a range of N ranges? That's not possible in the general case. The two ranges `v1` and `v2` in `merge_ranges` might have different types. What should the `value_type` of the resulting range be? Just think: you're asking for an iterator that when dereferenced gives you back the first range, then you increment it and dereference again and you get the second range. They better have the same type!

*If* they had the same type, then you can just put them in a vector and you're done. I'll note that a vector is a container, not a view. You seem to be wanting a view.

**Comment by gnzlbg** [comment]
> What should the value_type of the resulting range be?

Worst solution ever but it could be an any =/
