### ISSUE TITLE
Should EqualityComparable require that types provide inequality operator?

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#323]
I suspect that you'll just bat this one straight back (:smiley:) but...

For my money, I would rather see the `EqualityComparable` concept lose its requirement for an inequality operator ([here](https://github.com/ericniebler/range-v3/blob/80237c31b8528fa411e84500afcac93b62ed738c/include/range/v3/utility/concepts.hpp#L429)).

I'm presuming that the library code could use ` ! ( a == b )` wherever it wants `( a != b)` but apologies if not and if this is another case like #214 where I'm missing the subtleties of why a particular concept requirement is required.

Here are my reasons...

1. I think it feels more in line with the general tone of C++ libraries (eg that you're only expected to provide `operator<` and then libraries deal with that).

2. It seems to be more in keeping with Concept references like:
 * Section 17.6.3.1 of [the November 2014 working draft of the standard](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf).
 * http://en.cppreference.com/w/cpp/concept/EqualityComparable

3. Until compilers routinely provide good concept diagnostics, it takes (or took me) quite a lot of time and effort to go from a failed call to `ranges::equal()` to figuring out that the ranges' value types should have inequality operators. OK, I'm an idiot and should have guessed that sooner but there'll be lots of idiots like me who'll get stuck on why `ranges::equal()` won't work on their ranges of types with an equality operator.

Anyway, thanks very much.

**Comment by ericniebler** [comment]
> OK, I'm an idiot and should have guessed that sooner but there'll be lots of idiots like me who'll get stuck on why `ranges::equal()` won't work on their ranges [...]

This is a real problem, but the fix isn't to loosen the concepts. It's to find a way to improve the diagnostics. I would love to have a good answer for you, but at the moment I don't.

**Comment by tonyelewis** [comment]
> > OK, I'm an idiot [...]

> This is a real problem [...]

Yes

> I would love to have a good answer for you, but at the moment I don't.

FWIW, my wife's fruitless search for a good answer to that problem has been going for some time.

Yes - understand concepts diagnostics is a tricky one. I'd still vote for keeping the concept no bigger than is actually useful (as with the similar Equality concepts linked to above), rather than adding more compile-fix cycles to the universe for unclear gain. Still, I wasn't optimistic about persuading you. :-)

Anyway, thanks for taking the time to consider this.
