### ISSUE TITLE
Update `RANGES_FOR` for C++1z

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#329]
`RANGES_FOR` should use C++1z's range-based for-loop when available (e.g. in clang > 3.8).

**Comment by CaseyCarter** [comment]
> (e.g. in clang > 3.8)

[Clang 3.9 still defines `__cpp_range_based_for` to 200907 when compiling with `-std=c++1z`](http://melpon.org/wandbox/permlink/c9BcbrgX9b7cdsYw), despite supporting the Jacksonville ranged-for semantics. We need to poke them to fix that.

**Comment by CaseyCarter** [comment]
Filed [bug 27468](https://llvm.org/bugs/show_bug.cgi?id=27468) against clang to update the value of `__cpp_range_based_for` to `201603`.
