### ISSUE TITLE
`is_final` strikes back

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#337]
```shell
range-v3/include/range/v3/utility/box.hpp:134:32: error: no member named 'is_final' in namespace 'std'
                         !std::is_final<Element>::value>
                          ~~~~~^
```

**Comment by gnzlbg** [comment]
The feature testing macros are used for `is_final` now since today. 

I get the failure with clang 3.9 and libstdc++ 4.9. 

I don't know where the feature testing macros utilities for the library are defined, but if they are defined in the compiler clang might be screwing it up here. Gotta check it out.

**Comment by gnzlbg** [comment]
So no, the feature testing macro should be defined in the standard library, and libstdc++4.9 doesn't define it for is final. 

The problem is that if I compile in C++14 mode range-v3 still tries to use is_final even if I am using libstdc++4.9. This wasn't the case before, so I guess I need to use the new feature system somehow:  

- Should I define `RANGES_CXX_LIB_IS_FINAL` in my build system to something when I am using libstdc++4.9 with c++14 mode? If that is the case, range-v3 should IMO detect this and explain what needs to be done using `#pragma error`. 

- Should range-v3 detect the combination of libstdc++4.9 and C++14 and make the sane choice?

I would prefer the second option.

**Comment by gnzlbg** [comment]
A workaround for the current situation is to just define `RANGES_CXX_LIB_IS_FINAL` to `0` before including range-v3 when compiling in C++14 mode using a standard library that does not define the `__cpp_lib_is_final` feature testing macro.

**Comment by CaseyCarter** [comment]
Your implementation is lying: it defines `__cplusplus` to the C++14 value, but it does not fully implement C++14. You have a few options:

* Update libstdc++: 4.9.3 has `is_final`
* Compile with `-std=c++11` to keep clang from lying to range-v3
* Define `RANGES_CXX_LIB_IS_FINAL` to `0` to override the detection

**Comment by CaseyCarter** [comment]
> Should range-v3 detect the combination of libstdc++4.9 and C++14 and make the sane choice?

To me, a C++14 compiler with a C++11 library seems like a configuration we shouldn't expend effort to support.

**Comment by gnzlbg** [comment]
As long as there is an available workaround I am happy, but something doesn't make much sense to me.

> Your implementation is lying: it defines __cplusplus to the C++14 value, but it does not fully implement C++14.

How do the feature detection macros interact with the `__cplusplus` macro? Can an implementation set the `__cplusplus` macro to e.g. C++14 even though some feature detection macros for C++14 features are not set? If not, this is a clang bug. If yes, this is a range-v3 bug. I thought that the purpose of the feature detection macros was to allow an implementation to partially implement a new standard (which is normal between standard and compiler releases). Otherwise the feature detection macros make no sense since all we need is the `__cplusplus` macro.

> To me, a C++14 compiler with a C++11 library seems like a configuration we shouldn't expend effort to support.

Currently, range-v3 is querying if the library feature `is_final` is there and, in my case (which I agree is a weird one), it is getting the right answer from the implementation: no. 

I don't know what is the right thing to do here, but querying it, getting the right answer, and then going on and ignoring it seems weird to me.

**Comment by CaseyCarter** [comment]
> How do the feature detection macros interact with the `__cplusplus` macro?

They don't, but the rv3 configuration system does. Since nothing in SD-6 is standardized, compilers can and do choose not to implement any of it. rv3 uses a 3-tier system to determine a version number for each feature `foo`:

* `RANGES_CXX_FOO` is already defined from the command line.
* If `__cpp_foo` is defined, that definition is used for `RANGES_CXX_FOO`.
* Otherwise, the version of `foo` that was current in the last standard released on or before `__cplusplus`.

The fallback is necessary since the lack of a definition of `__cpp_foo` isn't a clear indication that `foo` is unsupported. It breaks down in a case like yours, in which the implementation does not conform to the standard corresponding to `__cplusplus`.

**Comment by gnzlbg** [comment]
> - Otherwise, the version of foo that was current in the last standard released on or before __cplusplus. 
> 
> The fallback is necessary since the lack of a definition of __cpp_foo isn't a clear indication that foo is unsupported.

Since `__cplusplus` is provided by the implementation (the compiler) independently of whether a standard library is included at all I don't see how it is a useful fallback for library level features. Using it as a fallback for language level features looks fine, but for library level features one should use the version macros of the standard library implementation since `__cplusplus` has nothing to do with that.

**Comment by CaseyCarter** [comment]
Using an old standard library with a new compiler - where "old" and "new" are out of sync by one or more standard versions - is not a motivating use case to me. It may be to someone else.

**Comment by gnzlbg** [comment]
Well the world is complicated. I need to link a C++14 library using range-v3 against a binary library that uses libstdc++-4.9 in some systems. It all worked fine until yesterday, it all still works fine with the workaround.
