### ISSUE TITLE
Workaround for SFINAE on MSVC 

### ISSUE THREAD

**Issue by RPeschke** [ericniebler/range-v3#341]
Hello,

During your talk at cppcon you mentioned that your library cannot be compiled with the MS compiler due to the missing feature of expression SFINAE. I had a struggle with a similar problem and I found this blog entry on stackoverflow:

http://stackoverflow.com/questions/17201329/c11-ways-of-finding-if-a-type-has-member-function-or-supports-operator

He calls the technique CFINAE. It basically does the same but from my experiences it works well with msvc. 

As he describes it you have to put the statement that you want to check in a decltype statement

I have a short example for this: 

```c++
 class HasNONE {
 
};
 
class hasA {
public:
  int A = 0;
};
 
class hasAD :public hasA {
};
 
class hasB{
public:
  int B = 1;
};
 
 

template<typename ret, typename... args>
ret _check(args...);
 
 // default template 
template <typename... T>
auto print_objB(T... t)  ->int {
  std::cout << "has no B \n";
  return 1;
}
 
// template specialization 
template <typename T>
auto print_objB(T&& t)  ->decltype(_check<int>(t.B)) {
  std::cout << "B = " << t.B << std::endl;
  return 1;
}
 

// cascaded default template
template <typename T,typename... args>
auto print_objA(T&& t,args...)  ->int {
  std::cout << "has no A \n";
  print_objB(t);
  return 1;
}
 
// Specialization 
template <typename T>
auto print_objA(T&& t) -> decltype(_check<int>(t.A)) {
  std::cout << "A = " << t.A << std::endl;
  return 1;
}
 

// overloading of specializations seems not to be possible
// template <typename T>
// auto print_objA(T& t) -> decltype(_check<int>(t.B)) {
//   std::cout << "hasB \n";
//   return  1;
// }
 
int main(int argc, char **argv) {
  
  
  print_objA(HasNONE());  // has no A
                          //  has no B

  print_objA(hasA());       //  A = 0
  print_objA(hasAD());      //  A = 0

  print_objA(hasB());       //  has no A
                            //  B = 1


}
```

I hope this is useful for you. I would really like to see your library compiling with msvc.

**Comment by ericniebler** [comment]
I'm familiar with that trick. I don't believe it is flexible enough to do the kind of expression introspection Rv3 needs.
