### ISSUE TITLE
Is clang + libstdc++4.9 still supported?

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#354]
Is clang + libstdc++4.9 still supported?

This:

https://github.com/ericniebler/range-v3/commit/c87ee78556387073cf1b65ac23a1b2516b3f3983#diff-fd7428cd3570678c7c7d079b05bf9a3dL257

breaks clang + libstdc++ on Linux, and the configuration is not tested on Travis, so I am not sure if this is still the case (since other PRs have also partially removed support for this configuration).

**Comment by ericniebler** [comment]
We should revert that change and find a patch that doesn't regress a platform. @Casey?

**Comment by casey** [comment]
I think you mean a different @casey :–)

**Comment by CaseyCarter** [comment]
> I think you mean a different @casey :–)

Yes, yes he did ;)

> We should revert that change and find a patch that doesn't regress a platform.

See #355.
