### ISSUE TITLE
Calendar example may be ill-formed

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/range-v3#357]
I've been trying to get GCC to compile the calendar example. The root cause of the errors seems to be that the compiler tries to instantiate the call operators of generic lambdas that are meant to be used to transform a range with iterators into the range, which is obviously ill-formed. Recall that `transform_view<Range, Fn>` is implemented in terms of `iter_transform_view<Range, indirected<Fn>>`. Why then would the program instantiate `declval<Fn>()(declval<range_iterator_t<Range>())` when we ask about `Function<indirected<Fn>, range_iterator_t<Range>>()`?

* Captureless lambdas have a member conversion operator that converts to a pointer-to-function.
* Captureless *generic* lambdas have a member conversion operator *template* that converts to a pointer-to-function whose return type is deduced from the call operator.
* **Member conversion operators are inherited.**
* `indirected<Fn>` privately inherits from `Fn` to take advantage of the Empty Base Optimization.

See where this is headed? Overload resolution for `declval<indirected<Fn>>()(declval<range_iterator_t<Range>>())` has to instantiate the conversion operator template of `indirected<Fn>`'s base `Fn`, which has to deduce the return type of `Fn::operator()(declval<range_iterator_t<Range>>())`, which is ill-formed.

Minimal repro that illustrates the issue:
```c++
template <class T> T&& declval() noexcept;
template <class, class>
constexpr bool is_same = false;
template <class T>
constexpr bool is_same<T, T> = true;

template <class F>
struct indirected : F {
    indirected(F f) : F(f) {}
    template <class I>
    auto operator()(I i) -> decltype(declval<F&>()(*i)) {
        return static_cast<F&>(*this)(*i);
    }
};

int main() {
    auto f = [](auto rng) {
        static_assert(is_same<decltype(rng), int>, "");
        return 42;
    };
    indirected<decltype(f)> i(f);
    static_assert(is_same<decltype(i(declval<int*>())), int>, "");
}
```
Gcc 6 & trunk diagnose this program as ill-formed. GCC 4.9 and 5, all versions of clang I have tried, even MSVC and EDG, compile without errors.

I've posted a summary of this to core@lists.isocpp.org, will update.

**Comment by ericniebler** [comment]
That's awful. Just awful. :-( I guess we need to stop using EBO for function object we get from the user.

**Comment by ericniebler** [comment]
Thanks for doing this investigation. We should report this to the committee. It really should be fixed. The conversion operator needs to be constrained somehow.

**Comment by ericniebler** [comment]
We should also try to understand why GCC and clang disagree, and who is right. Probably need to do that first.

**Comment by CaseyCarter** [comment]
I failed to make the point that the inherited conversion operator template can't even be safely hidden: hiding of conversion operators is based on return types, so overload resolution can't determine if a derived class conversion operator hides the base class conversion operator template without performing the problematic return type deduction.

It's a mess.
