### ISSUE TITLE
zip view returns range with non-Readable iterators

### ISSUE THREAD

**Issue by ncrookston** [ericniebler/range-v3#367]
The following code fails to compile:
```c++
#include <range/v3/all.hpp>

namespace r = ranges;
namespace v = ranges::view;

int main() {
  auto zints = v::for_each(v::ints(0,10), [](int i) {
    return v::zip(v::repeat_n(i,2),v::ints(0,2));
  });
  static_assert(r::Readable<decltype(r::begin(zints))>{}, "Iterator type not readable");
}
```

I assume the common_reference_t code is failing in the Readable concept (it is SemiRegular and Movable).  Does it need a specialization to handle this case?  Or am I missing something?

Aside: what I'd really like is to take a list like [1 2 3] and output something with each element incremented and decremented, like [0 2 1 3 2 4].  I could do that by transforming zints (if zints were Readable).  Is there an easier way?  The requirement that yield_from take a not-container-like View prevents the simplest way (for solid technical reasons, I'm sure.)

Thanks for the great library, and the std.proposal!

**Comment by CaseyCarter** [comment]
> Aside: what I'd really like is to take a list like [1 2 3] and output something with each element incremented and decremented, like [0 2 1 3 2 4].

```c++
auto foo = v::for_each([](auto i) {
  return v::concat(v::single(i - 1), v::single(i + 1));
});

int main()
{
  int some_ints[] = {1, 2, 3};
  std::cout << (some_ints | foo) << '\n';
}
```

**Comment by ericniebler** [comment]
> The iterator type is not Readable because common_type_t<common_pair<int, int>, common_pair<int, int>> is std::pair<int, int>.

That sounds like a bug alright.

**Comment by CaseyCarter** [comment]
> That sounds like a bug alright.

I agree that it's a bug, [but it seems to be intentional](
https://github.com/ericniebler/range-v3/blob/master/include/range/v3/utility/common_tuple.hpp#L431):

```c++
template<typename F1, typename S1, typename F2, typename S2>
struct common_type<common_pair<F1, S1>, common_pair<F2, S2>>
  : detail::common_type_tuple_like<common_pair<F1, S1>, common_pair<F2, S2>,
        meta::quote<std::pair>>
{};
```
thoughts?
