### ISSUE TITLE
Compilation error when returning a view::stride from function

### ISSUE THREAD

**Issue by Arzar** [ericniebler/range-v3#368]
Hello.
I'm getting a weird compilation error when using view::stride, but only when returning it from a function.
I'm using visual studio with "Clang with Microsoft CodeGen (March 2016)". it's based on clang 3.7

```
#include <range/v3/all.hpp>
#include <iostream>
#include <vector>


template <typename R>
auto foo1(const R& r, int n) {
   return r | ranges::view::stride(n); // compilation error
};

template <typename R>
auto foo2(const R& r, int n) {
   return r | ranges::view::slice(2, 5); // compile ok
};

int main()
{
   std::vector<int> v = { 1, 2, 3, 4, 5 , 6 , 7 , 8 };
   auto vv = v | ranges::view::stride(2); // compile ok
   std::cout << vv; // OK 1 , 3, 5, 7 
}
```
Build error log :

> 1>------ Début de la génération : Projet : TestClang, Configuration : Release Win32 ------
> 1>  TestClang.cpp
> 1>TestClang.cpp(37,15): error : no matching function for call to object of type 'const ranges::v3::view::view<ranges::v3::view::stride_fn>'
> 1>     return r | ranges::view::stride(n); // compilation error
> 1>                ^~~~~~~~~~~~~~~~~~~~
> 1>  F:\code\GitHub\range-v3\include\range/v3/view/view.hpp(123,21) :  note: candidate template ignored: disabled by 'enable_if' [with Rng = int &, Rest = <>, _concept_requires_123 = 42]
> 1>                      CONCEPT_REQUIRES_(ViewConcept<Rng, Rest...>())>
> 1>                      ^
> 1>  F:\code\GitHub\range-v3\include\range/v3/utility/concepts.hpp(854,9) :  note: expanded from macro 'CONCEPT_REQUIRES_'
> 1>          (CONCEPT_PP_CAT(_concept_requires_, __LINE__) == 43) || (__VA_ARGS__),      \
> 1>          ^
> 1>  F:\code\GitHub\range-v3\include\range/v3/view/view.hpp(131,22) :  note: candidate template ignored: substitution failure [with Ts = <int &>, V = ranges::v3::view::stride_fn]: no matching function for call to 'bind'
> 1>                  auto operator()(Ts &&... ts) const
> 1>                       ^
> 1>  1 error generated.
> ========== Génération : 0 a réussi, 1 a échoué, 0 mis à jour, 0 a été ignoré ==========

**Comment by CaseyCarter** [comment]
Minimizes to:
```c++
#include<range/v3/view/stride.hpp>

int main()
{
    int n = 2;
    ranges::view::stride(n);
}
```

Failure is caused by ambiguous overload resolution of `stride_fn::bind(range::view::stride, n)`. There are two viable unordered overloads:
* template<typename Difference, CONCEPT_REQUIRES_(Integral<Difference>())>
                 static auto bind(stride_fn stride, Difference step)

**Comment by CaseyCarter** [comment]
Minimizes to:
```c++
#include<range/v3/view/stride.hpp>

int main()
{
    int n = 2;
    ranges::view::stride(n);
}
```

Failure is caused by ambiguous overload resolution of `stride_fn::bind(range::view::stride, n)`. There are two viable unordered overloads:
* The "good" overload:
```c++
template<typename Difference, CONCEPT_REQUIRES_(Integral<Difference>())>
static auto bind(stride_fn stride, Difference step)
```
*  The "bad" overload that catches erroneous calls with non-integer strides:
```c++
template<typename Difference, CONCEPT_REQUIRES_(!Integral<Difference>())>
static detail::null_pipe bind(stride_fn, Difference &&)
```
They are intended to be mutually exclusive, and they are until someone calls `ranges::view::stride` with an lvalue, so that `Difference` in the second declaration deduces to e.g. `int&`. The "bad" overload is improperly viable since `int&` is not an integral type.
