### ISSUE TITLE
CMake errors out due to re_enable_warnings.hpp being removed

### ISSUE THREAD

**Issue by tivek** [ericniebler/range-v3#378]
Since a7a7f1ed9f27e1ea111c364f0d3f41763e8356f3 CMake reports an error:
```
CMake Error at CMakeLists.txt:72 (list):
  list sub-command REMOVE_ITEM requires two or more arguments.
Call Stack (most recent call first):
  CMakeLists.txt:79 (range_v3_list_remove_glob)
```

Cause: include/range/v3/detail/re_enable_warnings.hpp is not present anymore.

Tested on a fresh build with CMake 3.0.2 and 3.5.2. I am not sure why Travis CI builds are happy with this.

**Comment by CaseyCarter** [comment]
> I am not sure why Travis CI builds are happy with this.

The CI builds use `-DRANGE_V3_NO_HEADER_CHECK=1` to avoid the "header checking" facility since (a) errors therein are undebuggable, and (b) they make cmake configuration a couple orders of magnitude slower (120 seconds vs. 1.1 seconds on my machine).

**Comment by tivek** [comment]
... I don't know how I missed that switch. Useful stuff. Thanks for confirming and the quick patch!
