### ISSUE TITLE
chunk_view::distance_to and cyclic ranges

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/range-v3#382]
All of the tests in test/view/chunk.cpp commented with "Strange, but not wrong necessarily" are in fact necessarily wrong. From the definition of `SizedSentinel`/`SizedIteratorRange`, `b - a == n` implies `b == next(a, n)`. Many of these examples violate that axiom. Checking in test/view/chunk.cpp (CaseyCarter/range-v3@d6368d2bf7b645356e5a9b4b28fb686aa6751104) spews:

<pre>
> ERROR: CHECK failed "next(it, next(it, 2) - it) == next(it, 2)"
>   /home/casey/dev/range-v3/test/view/chunk.cpp(94)
>   EXPECTED: <non-streamable type>
>   ACTUAL: <non-streamable type>
> ERROR: CHECK failed "next(it, next(it, 5) - it) == next(it, 5)"
>   /home/casey/dev/range-v3/test/view/chunk.cpp(97)
>   EXPECTED: <non-streamable type>
>   ACTUAL: <non-streamable type>
> ERROR: CHECK failed "next(it, next(it, 1) - it) == next(it, 1)"
>   /home/casey/dev/range-v3/test/view/chunk.cpp(124)
>   EXPECTED: <non-streamable type>
>   ACTUAL: <non-streamable type>
> ERROR: CHECK failed "next(it, next(it, 2) - it) == next(it, 2)"
>   /home/casey/dev/range-v3/test/view/chunk.cpp(125)
>   EXPECTED: <non-streamable type>
>   ACTUAL: <non-streamable type>
> ERROR: CHECK failed "next(it, next(it, 4) - it) == next(it, 4)"
>   /home/casey/dev/range-v3/test/view/chunk.cpp(127)
>   EXPECTED: <non-streamable type>
>   ACTUAL: <non-streamable type>
> ERROR: CHECK failed "next(it, next(it, 5) - it) == next(it, 5)"
>   /home/casey/dev/range-v3/test/view/chunk.cpp(128)
>   EXPECTED: <non-streamable type>
>   ACTUAL: <non-streamable type>
> ERROR: CHECK failed "next(it, next(it, 7) - it) == next(it, 7)"
>   /home/casey/dev/range-v3/test/view/chunk.cpp(130)
>   EXPECTED: <non-streamable type>
>   ACTUAL: <non-streamable type>
> ERROR: CHECK failed "next(it, next(it, 4) - it) == next(it, 4)"
>   /home/casey/dev/range-v3/test/view/chunk.cpp(158)
>   EXPECTED: <non-streamable type>
>   ACTUAL: <non-streamable type>
> ERROR: CHECK failed "next(it, next(it, 5) - it) == next(it, 5)"
>   /home/casey/dev/range-v3/test/view/chunk.cpp(159)
>   EXPECTED: <non-streamable type>
>   ACTUAL: <non-streamable type>
> ERROR: CHECK failed "next(it, next(it, 6) - it) == next(it, 6)"
>   /home/casey/dev/range-v3/test/view/chunk.cpp(160)
>   EXPECTED: <non-streamable type>
>   ACTUAL: <non-streamable type>
> ERROR: CHECK failed "next(it, next(it, 7) - it) == next(it, 7)"
>   /home/casey/dev/range-v3/test/view/chunk.cpp(161)
>   EXPECTED: <non-streamable type>
>   ACTUAL: <non-streamable type>
</pre>

**Comment by ericniebler** [comment]
This needs deeper investigation. I want to settle once and for all whether cyclic iterators fit comfortably within the framework we've built for ourselves. If not, I think it's a problem.

**Comment by ericniebler** [comment]
The only way I can think to fix this is to give cycle view's iterators a count so that they aren't cyclic. Either that, or make the cycle view Input-only. :-/
