### ISSUE TITLE
Thread-local default_random_engine broken on Clang/Mac OS

### ISSUE THREAD

**Issue by tcbrindle** [ericniebler/range-v3#403]
Commit aa62c9f causes a compile error with Clang (AppleClang 7.3.0) on Mac OS when the utility/random.hpp header is included:

```
range-v3/include/range/v3/utility/random.hpp:500:66: error: initializer for thread-local variable must be a constant expression
                RANGES_STATIC_THREAD_LOCAL default_random_engine engine{
                                                                 ^~~~~~~
```

A workaround is to simply change the definition of RANGES_STATIC_THREAD_LOCAL to just `static` (rather than `static __thread`) on Apple systems, but of course this is less than ideal...

**Comment by CaseyCarter** [comment]
Blech. My understanding of `__thread` was that the qualified object must have trivial destruction; I did not realize that constant initialization is also necessary. (And of course, [OSX on Travis told me this was just fine](https://travis-ci.org/CaseyCarter/range-v3/jobs/137014737).)

Fixing.

**Comment by tcbrindle** [comment]
Confirming fix, thanks for dealing with this so quickly 👍
