### ISSUE TITLE
Thread-local storage is not supported on iOS (__IPHONE_OS_VERSION_MIN_REQUIRED <= 70100)

### ISSUE THREAD

**Issue by mtak-** [ericniebler/range-v3#407]
This error comes from `random.hpp` when `__IPHONE_OS_VERSION_MIN_REQUIRED <= 70100`:
```cpp
error: thread-local storage is not supported for the current target
                static __thread bool initialized = false;
                       ^
error: thread-local storage is not supported for the current target
                static __thread meta::_t<std::aligned_storage<
                       ^
```
`boost::thread_specific_ptr` works on this platform, but it might be a lot of work to port it. Since my company has no use for the default random engine, just having a way to opt out of TLS would be adequate.

**Comment by CaseyCarter** [comment]
So, it should work for `__IPHONE_OS_VERSION_MIN_REQUIRED > 70100` ?

**Comment by CaseyCarter** [comment]
Plan B: don't call `default_random_engine()` on IPhone until someone fixes it properly.

**Comment by mtak-** [comment]
Yep. It comples fine if `__IPHONE_OS_VERSION_MIN_REQUIRED > 70100`. I'll do some more testing tomorrow just in case it compiles but doesn't work.

Your pull request would let us keep building. Thanks for staying on top of these things.

**Comment by mtak-** [comment]
Spawned off a bunch of threads. The fix works on both `__IPHONE_OS_VERSION_MIN_REQUIRED <= 70100` and `__IPHONE_OS_VERSION_MIN_REQUIRED > 70100`. Thanks again.
