### ISSUE TITLE
crashes at runtime while constructing a vector from a view with nested transforms

### ISSUE THREAD

**Issue by mtak-** [ericniebler/range-v3#413]
The following code crashes at runtime in `skips` while constructing a `vector`:
```cpp
#include <iostream>
#include <range/v3/all.hpp>

using namespace ranges::view;

std::vector<std::vector<int>> skips(std::vector<int> xs) {
    return ints(0, (int)xs.size())
        | transform([&](int n) {
            return xs | chunk(n + 1)
                      | transform(drop(n))
                      | join;
        });
}

int main() {
    auto skipped = skips({1,2,3,4,5,6,7,8});
    return 0;
}
```

If you change `transform(drop(n))` to just `drop(n)`, it compiles and runs.

Compiled with `Apple LLVM version 7.3.0 (clang-703.0.31)`

[coliru](http://coliru.stacked-crooked.com/a/e3aae50976021de0)

**Comment by ericniebler** [comment]
You are returning a view on `xs`, a local vector that is no longer in scope after `skips` has returned.

**Comment by CaseyCarter** [comment]
The return type is `vector<vector<int>>`. The view in the return statement
is initializing a `vector`, not being returned from the function.

**Comment by CaseyCarter** [comment]
(My point is that `xs` is alive longer than the view, since callers destroy
parameters.)

**Comment by ericniebler** [comment]
Oh,  missed that. My bad.

**Comment by CaseyCarter** [comment]
The bug here is that `drop(n)` assumes the input range has at least `n` elements, it otherwise explodes upon trying to evaluate `next(begin(foo), n)`. Fix is to use `next(begin(foo), n, end(foo))` instead.

For @mtak-, I'll point out that `chunk(n + 1) | transform(drop()) | join` is equivalent to `stride(n)`, except that `view::stride` (a) would not have this bug and (b) would likely be more efficient.

**Comment by mtak-** [comment]
Nice optimization. Had to modify it slightly, since `stride` still includes the first element (not desired), so `return xs | drop(n) | stride(n + 1);` solves the problem.

I should've narrowed the bug down a bit more before reporting it. Thanks for the fix!
