### ISSUE TITLE
concat fails when given two ranges (of ranges) that are different types

### ISSUE THREAD

**Issue by mtak-** [ericniebler/range-v3#415]
`concat` explodes when the `range_reference` types of its arguments don't have a `common_reference`, which makes ranges of ranges with the same number of dimensions and innermost `range_reference` types, like the following, not compile:
```cpp
std::vector<std::set<char>> x;
std::vector<std::vector<char>> y;
std::vector<std::vector<char>> error = concat(x, y);

// very surprising
std::vector<std::vector<char>> error2 = concat(single(generate_n([] { return '4'; }, 1)),
                                               // different callable type
                                               single(generate_n([] { return '2'; }, 1)));

```

The compiler error message vomit is pretty long, but it looks like an issue caused by `common_reference` not being specialized for ranges. It fails in `concat_view`'s `cursor` here (around line `219`):

```cpp
using reference = common_reference_t<range_reference_t<constify_if<Rngs>>...>;
```

**Comment by ericniebler** [comment]
> ```
> std::vector<std::set<char>> x;
> std::vector<std::vector<char>> y;
> std::vector<std::vector<char>> error = concat(x, y);
> ```

This can't possibly work, so I suspect you think it should be doing something it doesn't do. You have a range of sets and a range of vectors, and you want to concatenate them into a range of ... what? Are you looking to flatten each range of ranges into a range of characters and then concatenate those? Then this should work (untested):

```
std::vector<std::set<char>> x;
std::vector<std::vector<char>> y;
std::vector<char> error = concat(join(x), join(y));
```

I don't know how you expect to get a vector<vector<char>> though.

> ```
> // very surprising
> std::vector<std::vector<char>> error2 = concat(single(generate_n([] { return '4'; }, 1)),
>                                                // different callable type
>                                                single(generate_n([] { return '2'; }, 1)));
> ```

I confess I don't know what you're trying to do here. As before, you're trying to concatenate two ranges of ranges, and they have different value types (every lambda has a unique type). If you can describe the semantics you're after, then maybe I could help.

**Comment by ericniebler** [comment]
Or maybe you want this:

```
std::vector<std::set<char>> x;
std::vector<std::vector<char>> y;
std::vector<std::vector<char>> error = concat(transform(x,to_vector), y);
```

?

**Comment by mtak-** [comment]
That looks more like what I'd want; this is probably more of a feature request.

The `generate_n` example is the one I'd really want to work:
```cpp
std::vector<std::vector<char>> error2 = concat(single(generate_n([] { return '4'; }, 1)),
                                               single(generate_n([] { return '2'; }, 1)));
```

To use concat with views of views (that are different types) you first have to evaluate them AFAICT.
```cpp
std::vector<std::vector<char>> vec0 = single(generate_n([] { return '4'; }, 1));
std::vector<std::vector<char>> vec1 = single(generate_n([] { return '2'; }, 1));
std::vector<std::vector<char>> concatted = concat(vec0, vec1);
```
This sacrifices laziness in a big way, and would not work if either view was an infinite range.

It'd be nice to have something like a type erased view, and/or a `view_variant` that would maintain this laziness:
```cpp
erased_view<erased_view<char>> rng0 = single(generate_n([] { return '4'; }, 1));
erased_view<erased_view<char>> rng1 = single(generate_n([] { return '2'; }, 1));
auto concatted = concat(rng0, rng1); // still lazy, yay
```
It would also allow a developer to work with lazy ranges without writing templates.

Since this would have a performance penalty, I guess I shouldn't have expected concat to do this automagically.

Hope that explains things a bit better.

**Comment by ericniebler** [comment]
> It'd be nice to have something like a type erased view

See any_view. You just got your wish. :-)
