### ISSUE TITLE
Should I be able to view::join a view::repeat of a std::vector

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#433]
I tried to do this:

~~~~~.cpp
#include <iostream>
#include <vector>

#define RANGES_NO_STD_FORWARD_DECLARATIONS
#include <range/v3/all.hpp>

int main() {
	const auto a                   = std::vector<int>{ 1, 2, 3 };
	auto       repeated            = ranges::view::repeat_n( a, 5 );
	auto       repeated_and_joined = repeated | ranges::view::join;

	std::cerr << repeated_and_joined << "\n";
}
~~~~~

But that fails the static assert `"Cannot get a view of a temporary container"` (line 77 of range/v3/view/all.hpp).

Intuitively, this seemed like a reasonable thing to do. Does it fail because the `repeat_n` is returning temporary copies of the `vector`? If so, is that as-designed?

In that case, what do you think of the idea of two new views called something like `repeat_range` / `repeat_range_n` that repeat over a range rather than a single value?

**Comment by ericniebler** [comment]
Seems like that should just work. Could be a bug. I'll look into it when I get a sec. Thanks.

**Comment by tonyelewis** [comment]
This fix works for me - thanks very much for this and all other work on this excellent library.
