### ISSUE TITLE
Could view::iota be allowed to dangle?

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#434]
Trying this:

~~~~~.cpp
#include <range/v3/all.hpp>

#include <iostream>

int main() {
	std::cerr << *ranges::max_element( ranges::view::iota( 0, 10 ) ) << "\n";
}
~~~~~

I get a `ranges::v3::dangling` error from the compiler. This `ranges::v3::dangling` mechanism is really cool and very impressive.

However I wonder: in this case is it being too strict? Would it actually be fine to have a dangling iterator into an expired `view::iota` because does the iterator contain all the information it needs? In that case, is is possible to make the `ranges::v3::dangling` mechanism allow views like this?

Many thanks for your continued work on this superb library.

**Comment by gnzlbg** [comment]
> Would it actually be fine to have a dangling iterator into an expired view::iota [...]

It is fine to have a dangling iterator into an already destroyed view; you can get that iterator using `.get_unsafe()`.

> [...] because does the iterator contain all the information it needs?

The only information the iterator contains is a pointer to an already destroyed range. Doing almost anything with it results in undefined behavior.

The only sensible things you can do with that iterator in this case is either destroy it, or assign it a new value. 

There are some safe use cases for `.get_unsafe`, but this is not one of them.

**Comment by ericniebler** [comment]
@gnzlbg in this case it *is* fine. @tonyelewis is specifically asking about `view::iota`, a range whose iterators happen not to refer in any way the range.

@tonyelewis There is no general mechanism for marking a range as having dangle-safe iterators. The member `dangling::get_unsafe()` exists for just this purpose: when you have special knowledge about the range and just want the iterator, despite the fact that the range has gone away.

**Comment by gnzlbg** [comment]
> a range whose iterators happen not to refer in any way the range.

My bad, I had no idea about this. Since `view::iota` does not define a cursor I just thought that the iterators provided by `view_facade` would just refer to the range. I need to check how `view_facade` actually works.

**Comment by tonyelewis** [comment]
Thanks both.

> There is no general mechanism for marking a range as having dangle-safe iterators.

Understood. So perhaps that's an issue that could be documented for those views for which users can confidently end up calling `get_unsafe()`? Perhaps that list would roughly match the "create a range" views:

- `view::counted`
- `view::empty`
- `view::generate`
- `view::generate_n`
- `view::ints`
- `view::iota`
- `view::repeat`
- `view::repeat_n`
- `view::single`
- `view::unbounded`

Anyway, thanks very much to both of you. Feel free to close the issue on my account.

**Comment by ericniebler** [comment]
I would be wary of documenting it for any view in range-v3 so as to leave myself the freedom to change the implementation without breaking users' code.

**Comment by tonyelewis** [comment]
> I would be wary of documenting it for any view in range-v3 so as to leave myself the freedom to change the implementation without breaking users' code.

Fair enough. Maybe in the long-term, you might eventually consider it worth adding that guarantee to a small number of cases? Or maybe not.

-----

BTW, just as food for thought... is there any point of opposing contact between the discussion here and that in issue:284?

 * There you were, in part, arguing that `vector<int> v{1,2,3}; int &i = front(view::all(v));` is OK and that trying to prevent the error cases nearby at compile-time would be more trouble than it'd be worth.
 * Here, I believe you're arguing that `vector<int> v{1,2,3}; auto i = ranges::max_element(view::all(v))` is close enough the error cases that the library must prevent it at compile-time (albeit with the option to explicitly `.get_unsafe()`.

(Apologies: I'm simplifying somewhat to highlight the point)
