### ISSUE TITLE
view::zip with view::for_each fails to compile

### ISSUE THREAD

**Issue by etam** [ericniebler/range-v3#439]
Here's a minimal example:

    #include <vector>
    
    #include <range/v3/core.hpp>
    #include <range/v3/to_container.hpp>
    #include <range/v3/view/for_each.hpp>
    #include <range/v3/view/zip.hpp>
    
    
    using namespace ranges;
    
    int main()
    {
        const auto v1 = std::vector<int>{1, 2, 3};
        const auto v2 = std::vector<char>{'a', 'b', 'c'};
        view::zip(v1 | view::for_each([](const auto& el) { return yield(el); }), v2) | to_vector;
        // expected std::vector<std::pair<int,char>>{{1,'a'},{2,'b'},{3,'c'}}
    }

And here's the compilation error: http://susepaste.org/3a5b89e2

I'm using gcc 6.1.1

**Comment by etam** [comment]
and here's the output from clang 3.8.0: http://susepaste.org/bfb57dee

**Comment by CaseyCarter** [comment]
This is due to an erroneous assumption in `view::zip_with`, which is used to implement `view::zip`: `zip_with` unconditionally assumes the iterators of its underlying range can be compared with `==`, which is not true for `view::join`.
