### ISSUE TITLE
Performance of any_view: dynamic_cast

### ISSUE THREAD

**Issue by aldanor** [ericniebler/range-v3#447]
I was investigating the somewhat poor performance of `any_view` and in the simplest examples it turns out that almost all of the time is spent on `dynamic_cast` in the hot path of the code, I believe [here](https://github.com/ericniebler/range-v3/blob/d343d002bfe65264b033c906e83c9eb1c04ba5ef/include/range/v3/view/any_view.hpp#L125).

I've put together a simple benchmark test to check the overhead of `any_view`, check here for the code and the results below:

- https://gist.github.com/aldanor/c8d2ea07132db536bb1645bc97aefb6c

It's nice to see almost zero overhead from a simple range as compared to direct for loop; however the same thing wrapped in `any_view` seems to be 8x slower.

Looking at the profiling log, almost all of the extra overhead time is spent in `all_sentinel_impl::equal()` which does a `dynamic_cast` on each iteration. Dynamic casts are a lot heavier than the virtual call machinery, and having one in the hot path has huge performance implications. The irony is, it has to check the same thing over and over and over, if it's iterating over the same range it does the dynamic cast on the same pointer type for each element which seems like a bit of a waste; it sounds like the kind of the thing that could potentially be just done once if possible.

Just wondering if anyone has any ideas on whether and how this could be improved?

**Comment by ericniebler** [comment]
Sure. Boost has [`polymorphic_downcast`](http://www.boost.org/doc/libs/1_61_0/libs/conversion/cast.htm#Polymorphic_cast) for exactly this case. In release builds, it's just a `static_cast`, but in debug builds it checks the result with a `dynamic_cast`. That ought to fix the problem.

**Comment by aldanor** [comment]
So, essentially, something like this?

```cpp
bool equal_(Input const &that) const
{
#ifndef NDEBUG
    auto pthat = dynamic_cast<any_cursor_impl const *>(&that);
    RANGES_ASSERT(pthat != nullptr);
#else
    auto pthat = static_cast<any_cursor_impl const *>(&that);
#endif
    return pthat->it_.get() == it_.get();
}
```

This makes sense, I could open a PR if you'd like. Could probably add polymorphic_downcast to a separate header in /utility to avoid copy/paste.

**Comment by ericniebler** [comment]
I prefer you add a `polymorphic_downcast` function template to a new header `utility/polymorphic_cast.hpp`. The implementation from Boost is perfect:

```c++
template <class Target, class Source>
inline Target polymorphic_downcast(Source* x)
{
    assert( dynamic_cast<Target>(x) == x );  // detect logic error
    return static_cast<Target>(x);
}
```

Be sure to have the Boost license header and an acknowledgement to David Abrahams, who authored this piece of code.

**Comment by aldanor** [comment]
Ref: #449

**Comment by ericniebler** [comment]
Fixed
