### ISSUE TITLE
Build warnings

### ISSUE THREAD

**Issue by aldanor** [ericniebler/range-v3#451]
If extra warnings are enabled, `ranges` triggers quite a few build warnings which is not cool if the downstream code has tight warnings settings.

Mostly, it's `-Wundef`, like this:

```
range/v3/utility/functional.hpp:186:13: error: "__apple_build_version__" is not defined [-Werror=undef]
         #if __apple_build_version__

range/v3/utility/random.hpp:79:9: error: "__i386__" is not defined [-Werror=undef]
     #if __i386__
```

I think these could be fixed e.g. like so `#if defined(__i386__) && __i386__`. This warning is an especial PITA since it can't be suppressed by pragmas due to long-standing bug in gcc.

or `-Wold-style-cast`:

```
range/v3/algorithm/max.hpp:59:53: error: use of old-style cast [-Werror=old-style-cast]
                         result = (decltype(tmp) &&) tmp;

range/v3/view_interface.hpp:102:41: error: use of old-style cast [-Werror=old-style-cast]
                 return (range_size_t<D>)Cardinality;
```

(and a whole bunch more).

Do we want these addressed (e.g. replacing casts with a more verbose but more modern `static_cast`)? It would be sure nice if the library didn't throw any warnings on both gcc/clang.

**Comment by gnzlbg** [comment]
[Warnings have been discussed a lot of times](https://github.com/ericniebler/range-v3/issues?utf8=%E2%9C%93&q=warnings). Which warnings you use in your own code is up to you, but since _it is impossible_ to make code warning free in all compilers, at the end of the day you should be either including range-v3 as a system library (using `-isystem` instead of `-I`) or using `pragma push/pop` before the range-v3 hearders.

FWIW I think that the `-Wundef` warnings should be fixed (`#if defined(identifier)` is probably enough for most cases). I find old-style casts more convenient to write, but explicit casts more convenient to read.

Which other warnings are you getting?

**Comment by aldanor** [comment]
> FWIW I think that the -Wundef warnings should be fixed (#if defined(identifier) is probably enough for most cases).
I think those should just get fixed for good, too.

> Which warnings you use in your own code is up to you, but since it is impossible to make code warning free in all compilers
But we can consciously try to make it *mostly warning free*.

Re: `-Wold-style-casts` warning, the current code mixes both styles, `(T)` and `static_cast<T>`. I agree that the former is easier to write / less typing, while the second is more explicit and is easier to read / search. If there are no objections in regards to this, I could open a PR and try and fix the cast styles.

**Comment by gnzlbg** [comment]
> But we can consciously try to make it mostly warning free :) 

Sure, we should strive for warning free builds as long as it makes sense. 

> And then it would most likely won't require hacks like -isystem of #pragma diagnostic ignored in the downstream code.

While `#pragma diagnostic...` is a "hack", `-isystem` is telling the compiler "this library is outside my control, so don't show me any warnings from it". 

Warning choices of libraries outside your control should not affect your workflow in your own code. Lots of warnings are either contradictory with other warnings (e.g. "don't do A, do B instead" vs "don't do B, do A instead"), controversial (e.g. `-Wshadow`), or of stylistic nature (e.g. `camelCase` vs `snake_case`, `m_` for member variables, ...).

> I could open a PR and try and fix the cast styles.

It would be better to send independent PRs for the different warnings, and also to wait for @ericniebler  and @CaseyCarter opinion.

**Comment by aldanor** [comment]
More warnings, I believe: `noexcept` specifier mismatches when using `view_facade` (`-Wnoexcept`):

```cpp
In file included from env/include/range/v3/core.hpp:17:0,
                 from env/include/range/v3/all.hpp:17,
                 from src/foo.h:6,
env/include/range/v3/begin_end.hpp:125:39: error: 
noexcept-expression evaluates to ‘false’ because of a call to 
‘ranges::v3::view_facade<Foo, (ranges::v3::cardinality)-1>::end<Foo, 42, 0>()meta::v1::detail::_if_<meta::v1::list<ranges::v3::concepts::Same::same<decltype (ranges::v3::range_access::begin_cursor((declval<Foo&>)(), 42)), decltype (ranges::v3::range_access::end_cursor((declval<Foo&>)(), 42))>::type, ranges::v3::basic_iterator<decltype (ranges::v3::range_access::begin_cursor((declval<Foo&>)(), 42)), decltype (ranges::v3::range_access::end_cursor((declval<Foo&>)(), 42))>, ranges::v3::basic_sentinel<decltype (ranges::v3::range_access::end_cursor((declval<Foo&>)(), 42))> >, std::integral_constant<bool, true> >::type’ 
[-Werror=noexcept]
                 static constexpr auto impl(Rng && rng, int)
                                       ^
In file included from env/include/range/v3/core.hpp:21:0,
                 from env/include/range/v3/all.hpp:17,
                 from src/foo.h:6,
env/include/range/v3/view_facade.hpp:86:42: 
error: but 
‘ranges::v3::view_facade<Foo, (ranges::v3::cardinality)-1>::end<Foo, 42, 0>()meta::v1::detail::_if_<meta::v1::list<ranges::v3::concepts::Same::same<decltype (ranges::v3::range_access::begin_cursor((declval<Foo&>)(), 42)), decltype (ranges::v3::range_access::end_cursor((declval<Foo&>)(), 42))>::type, ranges::v3::basic_iterator<decltype (ranges::v3::range_access::begin_cursor((declval<Foo&>)(), 42)), decltype (ranges::v3::range_access::end_cursor((declval<Foo&>)(), 42))>, ranges::v3::basic_sentinel<decltype (ranges::v3::range_access::end_cursor((declval<Foo&>)(), 42))> >, std::integral_constant<bool, true> >::type’ 
does not throw; perhaps it should be declared ‘noexcept’ [-Werror=noexcept]
             detail::facade_sentinel_t<D> end()
```

**Comment by ericniebler** [comment]
In general, I hate playing whack-a-mole with compiler warnings, especially when some compiler implementer has decided to warn on perfectly valid code, like `-Wundef`. It's an endless time sink. If this is important to you, please submit a pull request.

However...

> noexcept specifier mismatches when using view_facade (-Wnoexcept)

If I understand the warning, this one is interesting, and it's worth looking into.
