### ISSUE TITLE
Travis-ci builds are failing for clang toolsets

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/range-v3#459]
`which $CXX` for `$CXX` == `clang++-3.9` (for example) finds nothing and exits with `1`, stopping the build. @gnzlbg ?

**Comment by CaseyCarter** [comment]
http://llvm.org/apt/precise returns a "403 Forbidden". Perhaps they've shut us off again.

**Comment by gnzlbg** [comment]
We are also in that time of the year again where the `llvm-toolchain-precise` switches from clang-3.9 to clang-4.0 (clang 3.9 RC1 is out). I'll look into it. Maybe switching to `llvm-toolchain-precise-3.9` for clang-3.9 fixes this.

**Comment by ericniebler** [comment]
Fixed in #476
