### ISSUE TITLE
Circular include of view_facade.hpp

### ISSUE THREAD

**Issue by foonathan** [ericniebler/range-v3#468]
I'm currently fixing standardese bugs, one of them occurs because of a circular include:

`view_facade.hpp` includes `view_interface.hpp` which includes `utility/common_iterator.hpp` which includes `view_facade.hpp`.
Somewhere an include isn't needed because otherwise you'd get compilation failures.

I'll fix standardese to handle it, just wanted to point that one out.

**Comment by CaseyCarter** [comment]
> `utility/common_iterator.hpp` which includes `view_facade.hpp`

This is almost certainly unnecessary: `common_iterator.hpp` doesn't define any views. I'll look into it.
