### ISSUE TITLE
value_type missing in iter_transform_view

### ISSUE THREAD

**Issue by adah1972** [ericniebler/range-v3#475]
The following innocent-looking test code currently fails:

```cpp
#include <algorithm>
#include <iostream>
#include <vector>
#include <range/v3/all.hpp>

template <typename _Fn, class _Cont>
auto reduce(_Fn reducefn, const _Cont& inputs)
{
    auto result = typename _Cont::value_type();
    for (const auto& item : inputs)
        result = reducefn(result, item);
    return result;
}

int sqr(int x)
{
    return x * x;
}

int main()
{
    std::vector<int> data{1, 2, 3, 4, 5};
    auto sum = [](auto x) { return reduce(std::plus<int>(), x); };
    std::cout << sum(data | ranges::view::transform(sqr)) << std::endl;
}
```

Until I add the following lines at l. 111 of include/range/v3/view/transform.hpp (copied from `iter_transform_view::adaptor` to `iter_transform_view`:

```cpp
            using value_type =
                detail::decay_t<decltype(fun_(copy_tag{}, range_iterator_t<Rng>{}))>;
```

I guess my usage is valid, and it is not asking too much to require a range to know its value type. :-)

I think issue #421 is related.

**Comment by CaseyCarter** [comment]
A range does know its `value_type`, and we retrieve it with `range_value_t`:
```c++
auto result = range_value_t<_Cont>{};
```
You should also be aware that not all ranges are `const`-iterable; some of the range-v3 view types mutate state during iteration and therefore only have non-`const` `begin` and `end`. Your `reduce` function, since it only accepts references to `const` ranges, will not work with ranges that are not `const`-iterable. Put differently: there are some range types `R` such that `const R` is not a range.

**Comment by adah1972** [comment]
Why not renaming `range_value_t` to `value_type`, or just adding a typedef? Ignoring the `const`-problems in the `reduce` code, I think it is normal to expect `reduce` to accept either containers or ranges, right?

I did not write the `reduce` code for ranges. I just happened to find it did not work with ranges.

**Comment by CaseyCarter** [comment]
> Why not renaming range_value_t to value_type, or just adding a typedef?

It will probably become `value_type_t` to agree with the Ranges TS in the not-too-distant future. It will not become a member typedef: we try to avoid requirements that make it impossible to non-intrusively adapt a third party type to the range concepts. One good example of a third-party type that would be hard to change in this way is core language arrays. We will never be able to add a member typedef to int[4], but we still want it to be a range.

**Comment by adah1972** [comment]
Regarding const-ness. I found that I could remove the `const` before `Cont&`, but I cannot remove the `const` before `auto &`—otherwise the compiler still complains about “non-const lvalue reference to type 'int' cannot bind to a temporary of type 'reference_t' (aka 'int')”. Does this conform to your expectation? In the general case, should functions like `reduce` use a generic `Cont&` to take a range/container, but only use const references to iterate?

**Comment by adah1972** [comment]
Regarding `value_type`. I understand what you say in the general case (thinking about how `begin` and `end` function in the range-based for loop). I still have two questions:

1. What changes will be put into the range-v3 library and when?
2. In code that potentially interacts with containers/ranges, what traits/typedef/etc. do you recommend should be used to achieve what I wanted to do in the `reduce` code?

**Comment by ericniebler** [comment]
> 1. What changes will be put into the range-v3 library and when?

The renaming of `range_value_t`, like Casey suggested.

> 2. In code that potentially interacts with containers/ranges, what traits/typedef/etc. do you recommend should be used to achieve what I wanted to do in the reduce code?

Change `reduce` to:

```c++
template <typename Fn, class Cont>
auto reduce(Fn reducefn, Cont&& inputs)
{
    range_value_t<std::remove_reference_t<Cont>> result{};
    for (auto&& item : inputs)
        result = reducefn(result, item);
    return result;
}
```

(Note: don't use `_Caps` identifiers. They are reserved by the implementation.)

**Comment by adah1972** [comment]
@ericniebler In that case the code would be explicitly dependent on ranges. I would appreciate a solution that can work with standard containers and ranges without being dependent on the ranges library. That is why I requested that ranges should have a value_type typedef or similar.

**Comment by adah1972** [comment]
BTW, I use `_Caps` identifiers in some library code, for some legacy reasons. I know they are reserved. However, using them has the benefit that it should never conflict with user code (admittedly rarely a problem, so legacy might be the primary reason: I saw many people model their code after the standard library code too...), though the authors then have the obligation to make sure it does not cause problems on all supported platforms.

**Comment by pfultz2** [comment]
Something like this should work in your code to compute `value_type` without needing the ranges library:

```cpp
namespace adl
{
    using std::begin;
    template<class Range>
    auto adl_begin(Range&& r) -> decltype(begin(r));
}

namespace mini_ranges
{
    template<class Range>
    using value_type = typename std::iterator_traits<decltype(*adl::adl_begin(r))>::value_type;
}
```

**Comment by CaseyCarter** [comment]
>
```c++
template<class Range>
using value_type = typename std::iterator_traits<decltype(*adl::adl_begin(r))>::value_type;
```

`decltype(*adl::adl_begin(r))` is the reference type of `r`, not the iterator type; it needs to be `decltype(adl::adl_begin(r))`.

**Comment by CaseyCarter** [comment]
Also, be aware that ranges can have differing iterator and sentinel types for their `begin` and `end`, which won't work with the range-based-for loop on compilers that do not implement the C++17 range-based-for.

**Comment by pfultz2** [comment]
> decltype(*adl::adl_begin(r)) is the reference type of r, not the iterator type; it needs to be decltype(adl::adl_begin(r)).

Oops you are right.

> Also, be aware that ranges can have differing iterator and sentinel types for their begin and end, which won't work with the range-based-for loop on compilers that do not implement the C++17 range-based-for.

Are sentinels ever used for the `begin`?

**Comment by CaseyCarter** [comment]
> Are sentinels ever used for begin?

No, sorry, that comment was meant to point out that use of range-based-for in the implementation of `reduce` in the OP won't work for all ranges on all compilers.

**Comment by adah1972** [comment]
Thanks for all the prompts and comments! Problem is solved (for now).

One minor correction: `value_type` should be defined as follows, I think:

```cpp
template<class Range>
using value_type = typename std::iterator_traits<decltype(
    adl::adl_begin(std::declval<Range>()))>::value_type;
```
