### ISSUE TITLE
Consider adding sub_range<Rng> (perhaps just as type-alias to iterator_range<...>)

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/range-v3#484]
Possibly a quick one...

I miss [boost::sub_range<>](http://www.boost.org/libs/range/doc/html/range/reference/utilities/sub_range.html) from range-v3. It's essentially the same thing as `iterator_range` but its template parameter specifies the range type rather than the iterator (and sentinel) type(s). I like this because it makes for concise, descriptive type-names that help express intent clearly.

Please may I suggest adding something like this to range-v3, even if only as a type-alias to the appropriate `iterator_range<...>`?

Example:

``` .cpp
#include <range/v3/all.hpp>
#include <iostream>

namespace ranges {

    // I'm proposing a type-alias like this:
    template <typename T>
    using sub_range = iterator_range< range_iterator_t< T >,
                                      range_sentinel_t< T > >;
}

using ranges::sub_range;
using std::vector;

// Which allows function signatures that are really descriptive, like this:
sub_range<const vector<int>> with_ends_clipped_off(const vector<int> &x) {
    return {
        ranges::next( ranges::cbegin( x ) ),
        ranges::prev( ranges::cend  ( x ) )
    };
}

int main() {
    const vector<int> a = { 0, 1, 2, 3, 4 };
    std::cerr << with_ends_clipped_off( a ) << "\n";
}
```

(...and of course, the improvement in concision is even greater for types with sentinel iterator types and for template types in generic code.)

As always, thanks very much for all your hard work on this excellent library.

---

Compile commands:

```
g++     -std=c++11                -isystem range-v3/include sub_range.cpp -o sub_range.gcc_bin   && ./sub_range.gcc_bin
clang++ -std=c++11 -stdlib=libc++ -isystem range-v3/include sub_range.cpp -o sub_range.clang_bin && ./sub_range.clang_bin
```

**Comment by ericniebler** [comment]
```
namespace ranges {
    // I'm proposing a type-alias like this:
    template <typename T>
    using sub_range = iterator_range< range_iterator_t< T >,
                                      range_sentinel_t< T > >;
}
```

I think that's the wrong alias. If the sentinel has a different type than the iterator, such a `sub_range` could only ever represent a sub-range starting a `pos` and ending at the end of the range. It should probably be:

```
namespace ranges {
    template <typename T>
    using sub_range = iterator_range< range_iterator_t< T > >;
}
```

Do you agree, and is that still useful?

**Comment by tonyelewis** [comment]
Ah yes, good point, thanks. So your revised `sub_range` would then cover all cases except representing a somewhere-to-end sub-range of a range with a different sentinel type?

Anyway, yes: I still think this is really worthwhile and I'd advocate for that being the recommended way to express that sort of intent. If it gets enough uptake and the sentinel issue becomes a bigger problem, then the option remains open to upgrade `sub_range` from a type alias to a full type that does more to handle that case.

Out of interest, how would you do that? Have you hit this sort  of issue before in which you want to make the iterator/sentinel type distinction into a run-time distinction? If so, how do you handle it? `variant<iterator, sentinel>`?

Many thanks.

**Comment by ericniebler** [comment]
> Have you hit this sort of issue before in which you want to make the iterator/sentinel type distinction into a run-time distinction? If so, how do you handle it? 

See `common_iterator<iterator,sentinel>`.

**Comment by tonyelewis** [comment]
Ta.

**Comment by tonyelewis** [comment]
So would:

~~~~~.cpp
template <typename T>
using sub_range = iterator_range< range_iterator_t< T >,
                                  common_iterator< range_iterator_t< T >, range_sentinel_t< T > > >;
~~~~~

...make sense? Do you prefer that or just ` [...] = iterator_range< range_iterator_t< T > >;`

Either way, shall I try to add this type alias and issue a P-R?

In `range_fwd.hpp`? Any thoughts on test that should accompany it?

**Comment by tonyelewis** [comment]
AFAIU from a brief skim, `safe_subrange_t<Rng>` does what this issue was asking for, along with added handling of `dangling`. So I think this issue is obsolete and can be closed. Ta muchly.
