### ISSUE TITLE
Bring back post-increment for InputIterators?

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/range-v3#490]
While writing a paper on the Readability of `i++` for `InputIterators`, I thought of a design direction that could potentially solve the problem, although I'm uncertain of its implications.

Recapping the problem: `InputIterator`'s post-fix increment operator returns a proxy that holds the previous value so that `*i++` can return a reference to it after the iterator has been moved past that element. This requires the iterator's `value_type` be `Movable`, but not all types are; in particular, abstract types and arrays are not. So it would seem that any single-pass iterator that has one of those types as a `value_type` cannot satisfy `InputIterator`.

But can't we rig things so that `i++` does not actually increment the iterator until after the read (or write) has finished? The idea is to return a proxy that holds a pointer to `i` and pre-increments it in its destructor. Here is the proxy returned by `op++(int)`:

```c++
template<typename I>
struct postfix_increment_proxy
{
private:
    I *p_ = nullptr;
public:
    using value_type = iterator_value_t<I>;
    postfix_increment_proxy() = default;
    postfix_increment_proxy(postfix_increment_proxy const&) = delete;
    RANGES_CXX14_CONSTEXPR
    postfix_increment_proxy(postfix_increment_proxy &&that) noexcept
        : p_(detail::exchange(that.p_, nullptr))
    {}
    postfix_increment_proxy &operator=(postfix_increment_proxy &&that) noexcept
    {
        RANGES_ASSERT(false && "operation not supported");
        this->~postfix_increment_proxy();
        p_ = detail::exchange(that.p_, nullptr);
        return *this;
    }
    RANGES_CXX14_CONSTEXPR
    explicit postfix_increment_proxy(I &i) noexcept
        : p_(std::addressof(i))
    {}
    ~postfix_increment_proxy()
    {
        if(p_ != nullptr)
            ++p_;
    }
    RANGES_CXX14_CONSTEXPR
    iterator_reference_t<I> operator*() const
    {
        return **p_;
    }
    RANGES_CXX14_CONSTEXPR
    friend iterator_rvalue_reference_t<I>
    indirect_move(postfix_increment_proxy const &ref)
    {
        return indirect_move(*ref.p_);
    }
};
```

I'm fairly certain this is a horrible idea, but I haven't yet figured out why. Relying on the destructor of a temporary object to advance a single-pass iterator is way sketchy. But this range is single-pass, so folks can't complain if they squirrel this `Readable` proxy thingie away and get weird behavior.

This is implemented in f6cceba8aec0353ea55d8f42e0c10d045efd37e0 and miraculously range-v3 passed all its tests. Probably indicates poor test coverage.

If requiring that `i++` model `Readable` does not permit this implementation, can we use the STL1 trick by only specifying the requirements on `*i++`?

@CaseyCarter, thoughts?

See also #474.

**Comment by CaseyCarter** [comment]
Initial reaction: eww.

I can't break it immediately. I would rather relax `Readable` to `MoveConstructible` than use that "move assignment" operator.

**Comment by gnzlbg** [comment]
Why isn't the move assignment operator deleted?

**Comment by CaseyCarter** [comment]
> Why isn't the move assignment operator deleted?

Readable requires DefaultConstructible and Movable; this type is "pretending" to be Movable.

**Comment by ericniebler** [comment]
I don't think the move assignment operator has the wrong semantics. I could remove the assert, but it seems better to keep it. I'd rather not weaken Readable for this one case.

Mostly, I'm interested in finding out whether this proxy makes the semantics of InputIterator's postfix increment operator wrong.

**Comment by ericniebler** [comment]
I'm inclined to replace the `{i++}->Readable` requirement with appropriate constraints on `*i++`. Perhaps, `{*i++}->CommonReference<reference_t<I>>`. If we do that, then I can just `=delete` the move-assign operator on this proxy, and this hack is more clearly(?) in-bounds. Thoughts?

Also, it seems to me that if we want `*o++ = 42` to work for `OutputIterator`s (do we?), we need to add a similar constraint to `OutputIterator`. That could be implemented with a similar postfix increment proxy.

**Comment by ericniebler** [comment]
I think I've convinced myself that this implementation is non-conforming. The expression `v = (i++, *i);` should be equivalent to `v = *++i`, but the proxy destructor that does the increment won't be run until the end of the full expression (i.e., the semicolon), so the read happens as if `(v = *i, ++i)`. That's bogus.

I'll add some tests to conform all this.

**Comment by gnzlbg** [comment]
I am relieved that this is broken. My expectation is that `it++` should return an `Iterator` independently of whether there is a dereference infront of it or not. If only `ForwardIterator`s can satisfy this, then that's the way it is, but allowing `*it++` for `InputIterator`s seems fishy to me. What was the motivation for allowing it?

**Comment by ericniebler** [comment]
> That's bogus.

Confirmed. Closing.

**Comment by ericniebler** [comment]
> allowing `*it++` for `InputIterator`s seems fishy to me. What was the motivation for allowing it?

From Sean Parent:

> the expression *p++ is exactly why we have post-increment (it maps to post
> increment addressing instructions) and that is very common usage (you’ll see
> *p++ quite a lot in K&R)

**Comment by gnzlbg** [comment]
Yes, but `*p++` in K&R refers to `RandomAccessIterator`s, which are a completely different beast from `SinglePass` `InputIterator`s :/

I mean, I am not saying that `*p++` is not useful, but I am curious whether it is useful enough for `InputIterator`s to justify it given the pitfalls it contains. In particular, how would one specify in a `concept` that `*p++` is allowed, but `p++` is not (with a look towards a future model that includes template definition checking).

**Comment by ericniebler** [comment]
> In particular, how would one specify in a concept that *p++ is allowed, but p++ is not

By not constraining the type of `p++` in any way. How could you use it in generic code?

**Comment by gnzlbg** [comment]
I thought that if you don't constrain it at all, you cannot check whether
generic code uses the type correctly until template instantiation time.

So one would need to constrain it to be dereferenceable, destructible
(which is an implicit constraint I suppose) and maybe move assignable, so
that an hypothetical definition checker can ensure that those are the only
things that generic code can do with it.

Maybe there is a way for such a definition checker to enforce that generic
code doesn't do anything with it without any constrain at all, but I don't
know of any language that works this way :/

**Comment by ericniebler** [comment]
> I thought that if you don't constrain it at all, you cannot check whether
> generic code uses the type correctly until template instantiation time.

In a world with separate checking, the compiler checks the body of the template and flags as ill-formed any use of a type that isn't explicitly sanctioned in the requirements. So a type that is completely unconstrained has _no_ valid uses in the function body.

In today's world, there is no separate checking, so the point is moot.

**Comment by CaseyCarter** [comment]
C++ concepts don't constrain types: they constrain expressions. If I define:
```c++
template<class T>
concept bool C = requires (const T& t) { t + t * t - t; };

void foo(C a, C b, C d) {
  a + b * d - a;
}
```
Then `foo` is properly constrained, and a definition-checking design must be smart enough to know that the types of the sub-expressions are immaterial.

**Comment by gnzlbg** [comment]
> C++ concepts don't constrain types: they constrain expressions.

Thanks, I never thought of C++ concepts like this before.
