### ISSUE TITLE
Underconstrained functions in iota view

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#506]
The iota views take two different types, `From` and `To`, and call `iota_minus(to_, from_)` multiple times, e.g., [here](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/view/iota.hpp#L261). 

This requires `Same<From, To>` since otherwise `iota_minus` cannot deduce `Val` but this constraint is not expressed.

We have lots of options:

- constrain all the functions that call `iota_minus(to_, from_)` on `Same<From, To>`, 
- allow `iota_minus` to work with two different types,
- or force a conversion to one of the types, e.g.,  by using`detail::iota_minus<From>(to_, from_)`. 

No idea what the right way to fix this is. I would say that `iota_minus` ought to work with different types, or otherwise it doesn't really make much sense to have all the iota views take two different types. 

EDIT: FYI there are no tests for the iota views taking two different types.

**Comment by ericniebler** [comment]
IIRC, the iota view permits the types to differ so that things like view::iota(0, vec.size()) works. But really I think that's misguided and we should force users to say what they mean in cases like that.

**Comment by gnzlbg** [comment]
IIRC `view::ints(0, vec.size())` fails for the same reason (both int should have the same type), so we might want to make it consistent for `iota` as well.

**Comment by ericniebler** [comment]
Oh I remember. view::iota should be usable with iterator/sentinel pairs.

**Comment by gnzlbg** [comment]
Then I guess `iota_minus` must work with two different types (instead of only one).

**Comment by ericniebler** [comment]
I notice `iota_minus` is only ever called with different types from asserts. This is easy to fix.
