### ISSUE TITLE
Problem using ranges::{lower,upper}_bound

### ISSUE THREAD

**Issue by seertaak** [ericniebler/range-v3#540]
Aforementioned functions do not mirror behaviour of std::{lower, uppper}_bound -- instead, produce a compiler error when used.

Please see minimal test.cpp and associated compiler error.

    #include <vector>

    #include <range/v3/all.hpp>

    using namespace std;
    namespace view = ranges::view;

    struct Foo {
        int x;
    };

    int main(int argc, const char* argv[]) {
        vector<Foo> xs = view::ints(0, 10) | view::transform([] (auto i) { return Foo{i*i}; });

        auto works_fine = lower_bound(xs.begin(), xs.end(), 10, [] (auto l, auto r) { return l.x < r; });
        assert(works_fine != xs.end());

        // following line produces lengthy error message under clang tip.
        auto does_not_compute = ranges::lower_bound(xs, 10, [] (auto l, auto r) { return l.x < r; });
        assert(does_not_compute != xs.end());

        return 0;
    }

[errors.txt](https://github.com/ericniebler/range-v3/files/676972/errors.txt)

**Comment by ericniebler** [comment]
It's not my intention to mirror the behavior in the standard. Try using a projection instead: 

```c++
ranges::lower_bound(xs, 10, [] (int l, int r) { return l < r; }, &Foo::x);
```
