### ISSUE TITLE
Consuming multiple ranges and performing side-effects

### ISSUE THREAD

**Issue by lostman** [ericniebler/range-v3#543]
I want to consume multiple ranges and perform side-effects.

I tried using `zip_with`:
```
void test1() {
    using namespace ranges;
    single_view<int> r1 = view::single(5);
    single_view<int> r2 = view::single(9);
    auto f =
        [](int x, int y) {
            std::cout << x << " " << y << std::endl;
        };

    auto rng = view::zip_with(f, r1, r2);
}
```
But couldn't find a way to do anything with `rng`. How can I consume it and execute the side-effects?

This works but requires yielding values:
```
void test2() {
    using namespace ranges;
    single_view<int> r1 = view::single(5);
    single_view<int> r2 = view::single(9);
    auto f =
        [](int x, int y) {
            std::cout << x << " " << y << std::endl;
            return yield(0);
        };
    auto rng = view::zip_with(f, r1, r2);
    for_each(rng, [](auto){});
}
```
And in my use-case I have nothing to yield.

In the end I settled on:
```
ranges::for_each(
    ranges::view::zip(r1, r2),
    [&](const auto &x) { std::experimental::apply(f, x); });
```
But it doesn't have the same clarity as `zip_with`.

Is there some approach I might be missing?

**Comment by CaseyCarter** [comment]
> Is there some approach I might be missing?

If you simply need a way to force "evaluation" of a range `rng` for side effects `ranges::for_each(rng, [](auto&&){});` will do so. It's a bit awkward (dangerous?) to do so with `zip_with`: `zip_with` expects the transform function to be side-effect-free in order that the range can be multipass.

This seems like a use case for a variadic `ranges::for_each`. I hate that:

```c++
template<class... Rngs, class Fn>
void for_each(Rngs&&... rngs, Fn f);
```

is not usable syntax.

**Comment by lostman** [comment]
Wouldn't that work if `Fn f` went first?

**Comment by gnzlbg** [comment]
@CaseyCarter 

Why not just:

```c++
template<class... Args>
void for_each(Args&&... args);
```

?

**Comment by CaseyCarter** [comment]
> Wouldn't that work if `Fn f` went first?

Yes, but it would be inconsistent with the parameter ordering of `std::for_each`.

> I mean, it sucks that we cannot do what you propose, but we still can offer that API right?

We could implement it, I'm not sure we could implement it with reasonable compile-time efficiency. Selecting all-elements-but-the-last from a parameter pack is nasty.
