### ISSUE TITLE
Sorting requires less to accept different types.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [ericniebler/range-v3#545]
Hi.

I would generally expect this to compile 
(clang++ --std=c++1z use_ranges.cc -I range-v3/include/)
```
struct map_less {
  template <typename T>
  bool operator()(const T& x, const T& y) const {
    return x.first < y.first;
  }
};

int main() {
  std::vector<int> keys = {1, 3, 2};
  std::vector<std::string> values = {"a", "c", "b"};
  sort(view::zip(keys, values), map_less{});
}
```

However, it doesn't. It compiles if I deduce arguments for both sides, like this:
```
int main() {
  std::vector<int> keys = {1, 3, 2};
  std::vector<std::string> values = {"a", "c", "b"};
  sort(view::zip(keys, values),
       [](const auto& x, const auto& y) { return x.first < y.first; });
}
```

**Comment by ericniebler** [comment]
It can't work the way you expect. The zip view has the following associated types:

reference = pair<int&,string&>
value_type = pair<int, string>

The sort algorithm needs to save off values into temporaries and then compare the current element to the temporary, like:

pair<int,string> tmp = *i;
...
if (cmp(tmp, *i))

The types of tmp and *i differ; hence, you get a compile error when you require them to be the same type.
