### ISSUE TITLE
Compilation failed if only join.hpp included

### ISSUE THREAD

**Issue by SmorkalovG** [ericniebler/range-v3#548]
Use case:
```
#include <range/v3/view/join.hpp>

using namespace ranges::view;

int main()
{
    return 0;
}
In file included from ../Ranges/range/v3/numeric.hpp:15:0,
                 from ../Ranges/range/v3/view/join.hpp:23,
                 from ../Ranges/main.cpp:1:
../Ranges/range/v3/numeric/adjacent_difference.hpp:52:25: error: 'in' is not a member of 'ranges::v3::tag'
             tagged_pair<tag::in(I), tag::out(O)>
                         ^
../Ranges/range/v3/numeric/adjacent_difference.hpp:52:25: note: suggested alternatives:
In file included from ../Ranges/range/v3/view/join.hpp:19:0,
                 from ../Ranges/main.cpp:1:
../Ranges/meta/meta.hpp:2698:46: note:   'meta::v1::in'
         using in = not_<empty<find<List, T>>>;
                                              ^
../Ranges/meta/meta.hpp:2698:46: note:   'meta::v1::in'
../Ranges/meta/meta.hpp:2705:42: note:   'meta::v1::lazy::in'
             using in = defer<in, List, T>;
```
Including of all.hpp or algorithm/tagspec.hpp before join.hpp solves the problem. Bug is reproducable with gcc version 4.9.2 (Debian 4.9.2-10) and mingw 5.3.

**Comment by RicoAntonioFelix** [comment]
To resolve the issue you must include `<range/v3/core.hpp>`

**Comment by CaseyCarter** [comment]
Woops - my bug. The headers should all be self-sufficient.

**Comment by RicoAntonioFelix** [comment]
Interesting...Guess the library diverged from the [documentation](https://ericniebler.github.io/range-v3/index.html)

**Comment by SmorkalovG** [comment]
My fault, I have never read this part of documentation. It is interesting that everything worked with some old versions and failed after update.
I understand the point about documentation but is it normal to keep such include-order-dependency? Usually it is a bad style for C++, are there any reasons to do this? Why don't just include <range/v3/core.hpp> everywhere?
