### ISSUE TITLE
segfault when initializing vector-of-vector with range-of-range

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#556]
According to the documentation you can initialize a sequence container with a view over the same value-type. Is this supposed to work for two-dimensional views and containers, too?

This program crashes for me in the last assignment:
```c++
#include <iostream>
#include <range/v3/all.hpp>
#include <string>

int main()
{
    std::string s{"abc"};
    ranges::any_random_access_view<ranges::any_random_access_view<char>> v1 = ranges::view::single(s | ranges::view::drop(1));
    ranges::any_random_access_view<ranges::any_random_access_view<char>> v2 = ranges::view::single(s | ranges::view::drop(2));
    
    auto v3 = ranges::view::concat(v1, v2);

// both of these crash:
//    std::vector<std::vector<char>> owner = v3;
//    std::vector<std::string> owner = v3;

    return 0;
}
```

Thanks!

edit: clarified which calls create a crash

**Comment by FloopCZ** [comment]
Hi h-2, could you provide your compiler version and compiler flags, please (`g++ -v`)?

I have been unable to reproduce the bug with neither g++ 6.3.1 or clang++ 3.9.1 on my Arch. Both versions of your code snippet compile fine, produce no error when run and valgrind reports no leaks.

**Comment by h-2** [comment]
Hm, that's curious. From my home computer I also cannot reproduce this now. Tried with gcc-versions between 4.9 and 7 and clang versions between 3.5 and 4.0.
I will double-check in the office on Monday. Maybe it's also something that has been fixed in the meantime?

**Comment by FloopCZ** [comment]
According to Travis, the problem affects gcc 4.7-4.9
https://travis-ci.org/ericniebler/range-v3/builds/202624667
I have been able to reproduce it with gcc 4.9.2 just moments ago.

In #563, there is an ugly workaround if you really need that functionality right now. :-)

**Comment by h-2** [comment]
@FloopCZ thanks for investigating! I don't have urgent need for a fix, I am just doing smaller tests right now to see if/how things work. And I will be targetting only newer compilers anyway!
