### ISSUE TITLE
Would in-place reduction fit into the ethos of range-v3?

### ISSUE THREAD

**Issue by OsePedro** [ericniebler/range-v3#558]
I am very interested in using ranges as a basis for implementing computer vision algorithms. Range reduction is a common operation in such algorithms, but due to performance constraints, it is often preferable to perform such reductions in-place, to avoid dynamically allocating memory for intermediate results. E.g. the Eigen library has a type `Eigen::VectorXd` that represents resizable vectors. Given a range `xs` of vectors, I could calculate their sum with something like
```c++
int n=xs.begin()->size();
auto sum=ranges::accumulate(xs, Eigen::VectorXd::Zero(n).matrix());
```
but within `ranges::accumulate`, every call to the `=` operator would cause an array of `n` doubles to be allocated. It would be preferable if there was an in-place reduction function that does the equivalent of:
```c++
Eigen::VectorXd sum=Eigen::VectorXd::Zero(n);
for(const auto& x: xs) sum+=x;
```
Does range-v3 have something like this already? If not, would a function like this work well with the rest of the library? Could it be made composable (e.g. to do an in-place reduction of a range of ranges of `Eigen::VectorXd` to a `std::vector<Eigen::VectorXd>`, and pass the result to another function)?

**Comment by ericniebler** [comment]
I think you could use `ranges::accumulate` like:

```c++
Eigen::VectorXd sum=Eigen::VectorXd::Zero(n);
ranges::accumulate(xs, std::ref(sum), [](auto sum, auto& x) { sum.get() += x; return sum; });
```

Is that acceptable?

**Comment by OsePedro** [comment]
Oh actually, that might have been a bad example - I don't think each iteration of `accumulate` would dynamically allocate memory in that case after all. I'll comment again with a better example soon.

**Comment by OsePedro** [comment]
Thanks for the swift  reply! We commented simultaneously, and my last comment was a reference to my first, not a reply. Your suggestion does look like it would work, but as I said, I chose a bad example.

**Comment by OsePedro** [comment]
It looks like using `std::ref`, as you suggested, should satisfy my performance needs in other examples. Am I right in thinking it would be safe to use the same idea with `view::partial_sum`? E.g. to calculate moving averages using the integral image trick, it might be preferable to use a pair of overlapping `partial_sum` ranges (containing pointers to distinct `sum` objects) than to cache all the partial sums in a temporary `std::vector`. 

I'll close this issue and try implementing and benchmarking various algorithms using range-v3. If I encounter any performance issues, I'll ask about them here.
