### ISSUE TITLE
Two sentinel ends are not comparable

### ISSUE THREAD

**Issue by ryanhaining** [ericniebler/range-v3#564]
This seems like this should work

    auto ns = ranges::view::ints(1) | ranges::view::take(10);
    std::end(ns) != std::end(ns);  // expect false

But instead fails to compile with a pretty long template instantiation + macro expansion error. Is there a reason for sentinels to not support comparison with each other?

**Comment by CaseyCarter** [comment]
> Is there a reason for sentinels to not support comparison with each other?

At one time, range-v3 supported equality comparison for sentinels with the semantic that "all sentinels always compare equal." That semantic caused some inconsistencies in the design, i.e., if all sentinels always compare equal, and iterators are sometimes sentinels, shouldn't those iterators always compare equal?"

We fixed the design problem by removing the requirement for equality comparison from sentinels entirely. It's not useful to have an operation that either invokes undefined behavior or returns `true`: that operation goes unused, causes confusion, and mostly becomes a horrible code smell (an indication that the programmer doesn't completely understand the model and is probably making an error).

**Comment by ryanhaining** [comment]
>  if all sentinels always compare equal, and iterators are sometimes sentinels, shouldn't those iterators always compare equal?

I don't think I understand this, could you show an example cause what I'm imagining doesn't seem like a problem. Below is more contrived than what I actually did to run into the problem
```c++
template <typename T, typename U>
void f(T it1, U it2) {
    while (it1 != it2) {
       // ...
    }
}

f(std::end(seq), std::end(seq));
```

irl I was able to [handle it](https://github.com/ryanhaining/cppitertools/blob/master/internal/iterator_wrapper.hpp#L148) at the type level. In upgrading to c++17 with `std::variant` I had to pass a callable to `std::visit` with an overload specifically for two end iterators. I'd just like to understand the decision better

**Comment by CaseyCarter** [comment]
> could you show an example

Consider:
```c++
int some_ints[] = {0,1,2};
auto p0 = some_ints + 0, p1 = some_ints + 1, p2 = some_ints + 2;
```
`[p0, p0)` is a range with sentinel value `p0`. `[p0, p1)` is a range with sentinel value `p1`. If "all sentinels always compare equal," then `p0 == p1` must be true, so `some_ints + 0 == some_ints + 1`, and therefore `0 == 1`.

> irl I was able to handle it at the type level.

This is exactly the intent of the change: to force users to determine *why* they want to compare sentinels in the first place. Two ranges whose end sentinels are equal don't necessarily have any other property in common. Conversely, two ranges with end sentinels that are not equal may in fact be equal ranges. Consider the "threshold" sentinel:
```c++
template<class T>
struct threshold {
  T bound_;
};
template<class I, class T,
  CONCEPT_REQUIRES_(StrictTotallyOrdered<iterator_value_t<I>, T>())>
operator==(I const& i, threshold<T> const& t) {
  return *i >= t.bound_;
}
// define t == i, i != t, t != i accordingly
int some_ints[] = {0,1,2,10};
```
`[some_ints, threshold<int>{4})` and `[some_ints, threshold<int>{5})` are equal ranges with equal iterator values and non-equal sentinel values.

**Comment by ryanhaining** [comment]
Ok thank you for the explanation, I think I get the goal. Is this ever an issue if you're only comparing iterators from the same range?

**Comment by CaseyCarter** [comment]
>  Is this ever an issue if you're only comparing iterators from the same range?

This critically depends on how you define "the same range." `[some_ints, threshold<int>{4})` and `[some_ints, threshold<int>{5})` are ranges of identical - not just "equal values", but "equal addresses" -  integers. If you consider that to mean that `threshold<int>{4}` and threshold<int>{5}` are "from the same range" then it may trouble you that they are not equal. If instead you mean "a variant whose value is either `s` or some iterator in `[i, s)` then two variants that both contain sentinels must contain `s` and are trivially equal; this is the case for `common_iterator` in the Ranges TS, and I think for your `IteratorWrapperImpl` as well.

**Comment by ryanhaining** [comment]
I was thinking the latter, but it's definitely not a great line to draw. I'd have expected the stdlib to call it UB to compare iterators from different ranges under the latter definition, so this is certainly better.
