### ISSUE TITLE
view::move and view::for_each do not work together

### ISSUE THREAD

**Issue by FloopCZ** [ericniebler/range-v3#566]
view::for_each passes an lvalue reference to its functor, even if it is preceded by view::move. A workaround is to combine view::transform and view::join instead of using view::for_each directly.

Consider the following code:
```c++
#include <vector>
#include <memory>
#include <range/v3/view.hpp>

using namespace ranges;

int main()
{
  std::vector<std::unique_ptr<int>> data;
  data.emplace_back(std::make_unique<int>(42));

  // does not compile
  auto rng1 = data | view::move | view::for_each([](std::unique_ptr<int> ptr) {
    return yield(42);
  });

  // does compile
  auto rng2 = data | view::move | view::for_each([](const std::unique_ptr<int>& ptr) {
    return yield(42);
  });

  // workaround
  auto rng3 = data | view::move | view::transform([](std::unique_ptr<int> ptr) {
    return yield(42);
  }) | view::join;
}
```

**Comment by FloopCZ** [comment]
Thank you for such a fast answer. Your suspicion seems to be correct. When the constraint is removed, it compiles indeed.

**Comment by FloopCZ** [comment]
To be more specific, both the [IndirectInvocable and Range\<Invocable::result_t\>](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/view/for_each.hpp#L63#L64) constraints have to be removed for the example to compile.

**Comment by CaseyCarter** [comment]
I suspect a recent relaxation of the constraints on the transform or join views didn't get propagated to for_each. We should investigate having view:: for_each literally return `view:: join(view:: transform(range, function))` to avoid recurrence.

**Comment by FloopCZ** [comment]
It seems to work just fine, but I am not sure what could be the consequences.
https://github.com/ericniebler/range-v3/compare/master...FloopCZ:simplify_for_each
