### ISSUE TITLE
strange result: sort + transform

### ISSUE THREAD

**Issue by Jarod42** [ericniebler/range-v3#573]
I know I can use projection, but I got strange result when mixing sort and transform:

    struct C
    {
        explicit C(std::string a) : bar(a) {}
    
        std::string bar;
    };

    int main()
    {
        std::vector<C> cs = { C("z"), C("d"), C("b"), C("c") };

        ranges::sort(cs | ranges::view::transform([](const C& x) {return x.bar;}));

        for (const auto& c : cs) {
            std::cout << c.bar << std::endl;
        }
    }

ouput:

    z
    d
    b
    c

http://coliru.stacked-crooked.com/a/003094553996239e

**Comment by ericniebler** [comment]
The lambda should be `[](C& x) -> std::string& {return x.bar;}`. Curious that this code even compiles. I should look into it.

**Comment by ericniebler** [comment]
The problem is this:

```
/Users/eniebler/Code/range-v3/scratch/scratch.cpp:28:2: error: static_assert failed ""
        static_assert(!std::is_assignable<std::string, std::string>::value, "");
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Yuk! :-( Indeed, the following nonsensical code compiles:

```c++
std::string() = std::string();
```

It means that `ranges::indirect_swap` accepts things it shouldn't. I think we need to lock it down to only accept readable types that have a real reference for `*it`.

This has implications for STL2. ATTN: @CaseyCarter

**Comment by CaseyCarter** [comment]
Yes, prvalues of class type are typically "mutable" thanks to all the years of C++ that preceded the development of reference-qualifiers for member functions. We should consider fixing that in STL2:

* operators that require lvalues when applied to fundamental types should require lvalues when applied to class types: `@=`, `++`, `--`, and technically `&`. We should consider a core language change to the definition of the default assignment operators for class types to require lvalues.

* functions that return references should require lvalues to reduce the occurrence of dangling. This applies to obvious things like `front`, `data`, and `begin` as well as less obvious examples like `[]`, `at`, and `c_str`. 

* mutating member functions should either require lvalues, or accept rvalues and return the mutated object by value (for the "operation chaining" fans). For example:

```c++
class basic_string {
public:
  void append(const basic_string&) &;
  basic_string append(const basic_string& s) && { append(s); return *this; }
  [...]
```

**Comment by ericniebler** [comment]
@CaseyCarter this is Solution 3 of ericniebler/stl2#381, which I describe and dismiss as impractical for the Ranges TS. There's a simpler "engineering fix" (AKA hack) that I describe there too.
