### ISSUE TITLE
range from std iterators

### ISSUE THREAD

**Issue by tower120** [ericniebler/range-v3#581]
Hi!
Is it possible to somehow construct range from two std iterators (begin, end)?
Tried `ranges::make_range`, but it didn't work:
```
auto first = std::find_if(list.begin(), list.end(), cond);
auto last  = std::find_if(list.rbegin(), list.rend(), cond);

return ranges::make_range(first, last);
```

**Comment by FloopCZ** [comment]
Hi!

Almost there. There is make_iterator_range function just for this purpose. ;-)
https://ericniebler.github.io/range-v3/structranges_1_1v3_1_1make__iterator__range__fn.html

**Comment by tower120** [comment]
Hmm:
`Error	C3861	'make_iterator_range': identifier not found`
I use VS2015's ranges, and it seems that I even don't have iterator_range.hpp.

Is this should be in core.hpp?
Can you, please, show example code?

**Comment by gnzlbg** [comment]
Its here: https://github.com/ericniebler/range-v3/blob/master/include/range/v3/iterator_range.hpp#L190

**Comment by gnzlbg** [comment]
@tower120 can you try using `make_range(begin, end)` ?

https://github.com/Microsoft/Range-V3-VS2015/blob/master/include/range/v3/range.hpp#L267

That seems to be available.

**Comment by tower120** [comment]
I started from it:
`Error	C2338	Concept check failed: IteratorRange<I, S>()`

But now I think that this is because 
```
auto first = std::find_if(list.begin(), list.end(), cond);
auto last  = std::find_if(list.rbegin(), list.rend(), cond);

return ranges::make_range(first, last);
```

`first` is iterator, while
`last` is reverse_iterator

Can I somehow convert them to one type, or make it somehow work as is with make_range?

**Comment by gnzlbg** [comment]
Indeed, both iterators need to either be of the same type, or, be an iterator/sentinel pair. This is not the case here, so the static assert is telling you that. 

What is the type of your iterators? If your `first` is of type `Iter`, and `last` is of type `std::reverse_iterator<Iter>`, you can do:

```c++
    return ranges::make_range(first, last.base());
``` 

(note: `std::reverse_iterator<Iter>().base()` returns the iterator being adapted by `reverse_iterator`)

**Comment by tower120** [comment]
Thanks
```return ranges::make_range(first, last.base());```
Seems to work.
