### ISSUE TITLE
ranges::at vocabulary

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#585]
All std:: containers use `at` for checked access, but range-v3 uses `at` for unchecked access.

I like it this way but I would be surprised if no-one would complain about this when trying to standardize it.

**Comment by gnzlbg** [comment]
So in #584, 

- @ericniebler suggests renaming this to `ranges::index`
- @CaseyCarter says that this could be problematic in `BSD`:

> [index](https://www.freebsd.org/cgi/man.cgi?query=index&sektion=3) could be challenging to standardize thanks to the existence of the legacy BSD string function of the same name. POSIX dropped the function in 2008, so we may be able to get away with it.

What about `ranges::idx` ? I don't like abbreviations but I really like `ranges::index` as a name for unchecked indexed access.

**Comment by ericniebler** [comment]
Despite BSD and POSIX, I think `index` is the right name and will happily accept a PR that makes this change, also making `ranges::at` bounds-checked and throwing. For compatibility, you can have an overload of `ranges::at` that accepts non-sized ranges, is not bounds-checked, and is deprecated.

**Comment by gnzlbg** [comment]
> Despite BSD and POSIX, I think index is the right name and will happily accept a PR that makes this change, 

I'll get to it once #584 is finished. 

- I'll duplicate the current `ranges::at` to `ranges::index`
- I'll replace the `RANGES_EXPECT` in `ranges::at` with a throw.

> For compatibility, you can have an overload of ranges::at that accepts non-sized ranges, is not bounds-checked, and is deprecated.

IIUC `ranges::at` as checked access should also work with `RandomAccessRange`s that are `!SizedRange` right?  Shouldn't it also throw in those cases ?

**Comment by CaseyCarter** [comment]
> IIUC `ranges::at` as checked access should also work with `RandomAccessRanges` that are `!SizedRange`, right? Shouldn't it also throw in those cases ?

You can't perform the bounds check in O(1) on non `SizedRange`s.

**Comment by gnzlbg** [comment]
Roger, I'll have that overload call `ranges::index` and marked as deprecated.

**Comment by ericniebler** [comment]
@gnzlbg will you be doing that as part of #584?

**Comment by gnzlbg** [comment]
Yes, I can also update this PR to actually do that directly if you prefer.

**Comment by gnzlbg** [comment]
There is one inconsistency between `ranges::at`/`ranges::index` and the `.at` and `operator[]` member functions in the standard containers that needs to be resolved.

- `ranges::at/index(Rng, difference_type)` vs e.g. `vector<T>::at(size_type)/operator[](size_type)`

This will have consequences, e.g., indexing a `view::indices<uint64_t>` using `ranges::at` can never index the second half of the range. 

IMO I should change this to size_type. Thoughts?

**Comment by gnzlbg** [comment]
I have made this change and:

- this would mean that `ranges::at/index` cannot be used with negative indices, I think this is ok (they did not assert before that the difference type is >= 0 though,...).
-  `begin()[n]` would implicitly convert `n` from `size_type` (e.g. `unsigned long`) to `difference_type` (e.g. `long`) but I think this implicit conversion is fine as well.

**Comment by CaseyCarter** [comment]
> indexing a `view::indices<uint64_t>` using `ranges::at` can never index the second half of the range.

You also cannot calculate `i - begin` for iterators in the back half of the range; things start to break down at the edges of representability. I don't think that design decisions that affect all uses should be based on the behavior of corner cases.
