### ISSUE TITLE
Are clang modules making Travis flakey?

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/range-v3#607]
I have seen many instances recently of "error: standard header xxx.h changed since building the pch" and also "error: the following bits of the standard library are unresolved at link time". I have a feeling clang modules are to blame.

@gnzlbg ? @EricWF ?

**Comment by gnzlbg** [comment]
Clang modules complain that the header changed between building different tests (without modules the clang invocations don't know anything about each other, but with modules things get cached, and the cache has time stamps). 

So... while modules make this issue surface, the real question is: why are these headers being modified during a build?  I haven't filled a travis issue yet, but would probably do so sooner or later.

**Comment by ericniebler** [comment]
> why are these headers being modified during a build? This just shouldn't be happening. I haven't filled a travis issue yet, but would probably do so sooner or later.

That would be good to know, but really in the short term the only thing I care about is range-v3's test results. I suggest we turn off clang modules on Travis until we can use them reliably.

**Comment by gnzlbg** [comment]
I'll send a PR.
