### ISSUE TITLE
Concepts TS and polymorphism

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#610]
If I understand the current implementation of range-v3 correctly, it never uses "real" Concepts (as specified in http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4651.pdf ) and always uses the library implementation that works with C++14, right?
And it seems this library implementation of concepts does not support static polymorphism, or is there some way to make it work?

Here's a small example: 

```c++
#include <string>
#include <iostream>

#include <range/v3/all.hpp>

template <typename type>
    requires (bool)ranges::Range<type>()
void test1(type const & range)
{
    std::cout << "general\n";
}

template <typename type>
    requires (bool)ranges::RandomAccessRange<type>()
void test1(type const & range)
{
    std::cout << "special\n";
}

int main()
{
    std::string foo{"abc"};
    ranges::any_random_access_view<char> bar = foo | ranges::view::drop(1);

    test1(bar);
}
```

This is ambiguous, although with Concepts TS it wouldn't be, because Range is a strict subset of RandomAccessRange and the compiler always picks the strictest interface.

I could of course reimplement all the concepts as "real" concepts, but I was hoping there is an easier way.

Thanks for your help!

**Comment by gnzlbg** [comment]
You want [`most_refined`](https://github.com/ericniebler/range-v3/blob/630fc70baa07cbfd222f329e44a3122ab64ce364/include/range/v3/utility/concepts.hpp#L206), check out how [`range_concept_t`](https://github.com/ericniebler/range-v3/blob/630fc70baa07cbfd222f329e44a3122ab64ce364/include/range/v3/range_concepts.hpp#L302) is used in [view::slice](https://github.com/ericniebler/range-v3/blob/630fc70baa07cbfd222f329e44a3122ab64ce364/include/range/v3/view/slice.hpp#L258) to dispatch to [`invoke_`](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/view/slice.hpp#L204).

**Comment by h-2** [comment]
@gnzlbg thanks for the pointer, I knew I was missing something. We do try to get everything to the concepts ts syntax, though and I just realised it's actuelly quite easy to wrap the few concepts definitions, like this:
```c++
template <typename type>
concept bool range_concept               = (bool)ranges::Range<type>();

// these are independent specializations of range_concept
template <typename type>
concept bool view_concept                = range_concept<type> && (bool)ranges::View<type>();

template <typename type>
concept bool sized_range_concept         = range_concept<type> && (bool)ranges::SizedRange<type>();

template <typename type>
concept bool bounded_range_concept       = range_concept<type> && (bool)ranges::BoundedRange<type>();

// the following specialize incrementally
template <typename type>
concept bool input_range_concept         = range_concept<type> && (bool)ranges::InputRange<type>();

template <typename type>
concept bool forward_range_concept       = input_range_concept<type> && (bool)ranges::ForwardRange<type>();

template <typename type>
concept bool bidirectional_range_concept = forward_range_concept<type> && (bool)ranges::BidirectionalRange<type>();

template <typename type>
concept bool random_access_range_concept = bidirectional_range_concept<type> && (bool)ranges::RandomAccessRange<type>();
```

This really is quite minimal and -- if I am not mistaken -- this is more specific than just adding `most_refined`, or not? Or would most_refined also work if the most refined function overload is actually not the most refined concept that a type fulfills?

**Comment by gnzlbg** [comment]
What do you mean by more specific?

> Or would most_refined also work if the most refined function overload is actually not the most refined concept that a type fulfills?

Yes this works. If there isn't a `concept::RandomAccessIterator*` overload, but there is e.g. a `concept::ForwardIterator*` and a `concept::BidirectionalIterator*` one, and you pass it a random access iterator, the bidirectional one will be called.

**Comment by h-2** [comment]
Ah, ok, that's good to know! Thanks for the quick replies!
