### ISSUE TITLE
Concatenating a vector of strings

### ISSUE THREAD

**Issue by cpockrandt** [ericniebler/range-v3#612]
What would be the easiest way to concatenate a vector of strings?
e.g.

```
std::vector<std::string> in{{"foo"}, {"bar"}};
auto v = ranges::view::all(in) | ranges::view::? ;
```

concat and join don't work, because we have only a single range of two "string values".

Thanks a lot!

**Comment by CaseyCarter** [comment]
This is exactly the purpose of `join`: flattening a range of ranges of `T` into a range of `T`:
```c++
#include <iostream>
#include <string>
#include <vector>
#include <range/v3/all.hpp>

int main() {
    using namespace ranges;
    std::vector<std::string> in{{"foo"}, {"bar"}};
    auto rng = in | view::join;
    std::cout << rng << '\n'; // outputs "[f,o,o,b,a,r]"
    RANGES_ASSERT(ranges::equal(rng, std::string{"foobar"})); // does not fire
}
```

**Comment by cpockrandt** [comment]
I didn't realize that my input would be interpreted as a range of ranges, thanks a lot @CaseyCarter!
