### ISSUE TITLE
range-v3 fails to build with gcc 5.2.1 post 0.1.1

### ISSUE THREAD

**Issue by tahonermann** [ericniebler/range-v3#614]
The 0.1.1 and earlier releases of range-v3 (commit a94a9183185069eaa9f501bff68a4edfacc93257) build successfully with gcc 5.2.1 (as distributed with the Ubuntu 15.10 distribution I happen to be running).  However, builds have been failing since commit 0091c1eb39c17cd1f79d678663edba8174d9dc81 (the intervening commit, 8362ba08104c9b825f7096941ad6277dc6a64686, between the 0.1.1 release and commit 0091c1eb39c17cd1f79d678663edba8174d9dc81) doesn't build successfully regardless of compiler version).

I'm assuming that gcc 5.2.1 is intended to be supported.  I see Travis builds are successful with gcc 5.4.1.

I haven't been able to muster much time to look into this.  I suspect the issue is that gcc is issuing a hard error where SFINAE should be kicking in.

**Comment by tahonermann** [comment]
Attached is a subset of build output demonstrating the errors.  This was produced with commit 7d82079f947fcd99f66d52f6790646d546fb2185 (current head) on an Ubuntu 15.10 system with gcc 5.2.1 with the build produced by:
```
cmake -DCMAKE_BUILD_TYPE=DEBUG ..
cmake --build . --config DEBUG -- VERBOSE=1
```

[build-output.txt](https://github.com/ericniebler/range-v3/files/872708/build-output.txt)

**Comment by ericniebler** [comment]
The gcc mirrors don't even have a gcc-5.2.1. :-( And gcc-5.2.0 isn't building on my Mac. Sorry. Patches welcome.

**Comment by gnzlbg** [comment]
@tahonermann Can you try compiling with `-DRANGES_CXX_CONSTEXPR=RANGES_CXX_CONSTEXPR11` (passing it to cmake)?

**Comment by CaseyCarter** [comment]
[Ubuntu 15.10 reached end-of-life on 2016-07-28](https://wiki.ubuntu.com/Releases). I would strongly encourage you to upgrade to a more recent 'buntu with a more recent compiler: 5.2 is two patches worth of bug fixes behind the current GCC 5 release. I, at least, am not interested in working around compiler bugs that have already been fixed.

**Comment by ericniebler** [comment]
Please let me know if #615 fixed your problem. It worked for me with gcc-5.2.0.

**Comment by tahonermann** [comment]
> Can you try compiling with -DRANGES_CXX_CONSTEXPR=RANGES_CXX_CONSTEXPR11 (passing it to cmake)?

Thanks for the suggestion.  This did not avoid the problem (which is unsurprising given the workaround that Eric identified).

> Ubuntu 15.10 reached end-of-life on 2016-07-28. I would strongly encourage you to upgrade to a more recent 'buntu with a more recent compiler: 5.2 is two patches worth of bug fixes behind the current GCC 5 release. I, at least, am not interested in working around compiler bugs that have already been fixed.

I know I know.  This system has a cadre of compilers that I test with; the distribution provided gcc 5.2.1 is just one that I test with.  I hear you about supporting old compilers.  We still support gcc 3.x where I work (not as a compiler that we build with!)

> Please let me know if #615 fixed your problem. It worked for me with gcc-5.2.0.

It certainly did!  Would you mind sharing how you isolated where gcc was going wrong and that running the type evaluation through an identity function would work around it?

**Comment by ericniebler** [comment]
> Would you mind sharing how you isolated where gcc was going wrong and that running the type evaluation through an identity function would work around it?

From the error, I quickly determined that gcc wasn't correctly doing SFINAE on expressions of the form `&Concept::template requires_<Args...>`. From there it was a matter of throw-everything-at-the-wall-and-see-what-sticks. _\<shrug\>_ 

Even with that change, gcc-5.2 wasn't happy with `&Destructible::template requires_<void>`, which was forming a reference to `void` in the argument list. As luck would have it, we have a PR to change `Destructible` to no longer require that. :-)
