### ISSUE TITLE
loss of type (undesired down cast?)

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#617]
This is a fairly simply example I would say:
```c++
#include <string>
#include <iostream>

#include <range/v3/all.hpp>

template <typename t>
void print(t const & in)
{
    std::cout << in << '\n';
}

int main()
{
    std::string foo{"abcdefgeherefwwee"};
    ranges::any_random_access_view<char &> bar = foo | ranges::view::drop(3) | ranges::view::take(4);
    std::cout << bar << '\n';
//     print(bar);
}
```

Printing bar in main's scope works as expected, but uncommenting the print() call breaks the build:
GCC7 (`-std=c++17 -fconcepts`):
```
loss_of_ra.cpp: In instantiation of 'void print(const t&) [with t = ranges::v3::any_view<char&, (ranges::v3::category)3>]':
loss_of_ra.cpp:17:14:   required from here
loss_of_ra.cpp:9:15: error: no match for 'operator<<' (operand types are 'std::ostream {aka std::basic_ostream<char>}' and 'const ranges::v3::any_view<char&, (ranges::v3::category)3>')
     std::cout << in << '\n';
[...]
```
 CLANG4  (`-std=c++14`):
```
loss_of_ra.cpp:9:15: error: invalid operands to binary expression ('ostream' (aka 'basic_ostream<char>') and 'const ranges::v3::any_view<char &, ranges::v3::category::random_access>')
    std::cout << in << '\n';
    ~~~~~~~~~ ^  ~~
loss_of_ra.cpp:17:5: note: in instantiation of function template specialization 'print<ranges::v3::any_view<char &, ranges::v3::category::random_access> >' requested here
    print(bar);
```
Also `[]` doesn't work in the print-functions.

Is this a bug, or am I missing something fundamental?

Thanks!

**Comment by CaseyCarter** [comment]
`any_view` is probably not `const`-iterable (See #385). Try accepting the parameter to `print` by forwarding reference:
```c++
template <typename t>
void print(t && in)
```

**Comment by gnzlbg** [comment]
Or just passing it by value, `view`s are cheap to copy (O(1)).

**Comment by CaseyCarter** [comment]
1 can be pretty big for `any_view` since it allocates on copy ;)

**Comment by h-2** [comment]
> any_view is probably not const-iterable (See #385).

Hm, that's a real issue. These kind of interface are the de-facto standard for read-only access to generic data structures.

> Or just passing it by value, views are cheap to copy (O(1)).

The problem is that I am designed generic interfaces that should handle any kind of (random access) ranges, i.e. containers, ranges and views. I don't want any copy involved anywhere, and I also want const protection of the original data.

> 1 can be pretty big for any_view since it allocates on copy ;)

Hm?

**Comment by gnzlbg** [comment]
> Hm, that's a real issue. These kind of interface are the de-facto standard for read-only access to generic data structures.

Views are _stateful_ lazy algorithms. They mutate its internals when you ask them for something (like their values). If you make them const, this cannot happen, and there is not much that you can do with them. 

> The problem is that I am designed generic interfaces that should handle any kind of (random access) ranges, i.e. containers, ranges and views. I don't want any copy involved anywhere, and I also want const protection of the original data.

You can use `Rng&&` for that, and constrain on `std::is_const<range_reference_t<Rng>`, also, if you want to ""make the reference type of a view const"", you can use `view::const`. 

> Hm?

A single memory allocation on copy is still O(1), but _might_ have high latency (its a syscall).

**Comment by ericniebler** [comment]
`view::any` is not `const`-iterable because the user may ask to erase the type of a view that is also not `const`-iterable.

> These kind of interface are the de-facto standard for read-only access to generic data structures.

I'm not sure what "these kinds" refers to, but if you are saying that you should just be able to put a `const` on the top level and expect the `const`-ness to apply *deeply*, then you're mistaken. C++ doesn't work that way, and it never has.

```c++
template <typename T>
void perfectly_ok( T const & t ) {
  *t = 42; // mutation!
}

int main() {
  int i = 0;
  perfectly_ok( &i );
  assert( i == 42 );
}
```

The problem lies with your assumption that the values of a view's elements should participate in the value of the view itself. It doesn't, any more that the value of a pointer or iterator includes the value of the thing they point to.
