### ISSUE TITLE
Create own view as combination of existing views

### ISSUE THREAD

**Issue by sarahet** [ericniebler/range-v3#620]
Hi,
We want to create our own views as a combination of already existing views, e.g.

    auto foo = input | drop(1)
                     | take(input.size() - 5)
                     | reverse
                     | chunk(3)
                     | transform(foobar);

and be able to call it like this:

    auto foo = input | my_fancy_view;

We read the manual about view_facade and view_adaptor. The view_facade seems only be suitable for implementing a new view from scratch. The example from the docs of the view_adaptor seems to be an overkill for the simple task we want to manage. Is there a shortcut for achieving this?

**Comment by FloopCZ** [comment]
Hi sarahet,

The pipe operator applied solely to views is also a view and can be used as such.
```
auto my_fancy_view = drop(1)
                   | take(input.size() - 5)
                   | reverse
                   | chunk(3)
                   | transform(foobar);
auto foo = input | my_fancy_view;
```
Does it fit your needs?

**Comment by sarahet** [comment]
Yes, thanks a lot.

**Comment by ericniebler** [comment]
> The pipe operator applied solely to views is also a view and can be used as such.

Should be "The pipe operator applied solely to *adaptors* is also *an adaptor* and can be used as such."
