### ISSUE TITLE
GCC ICE with ranges::box and constexpr

### ISSUE THREAD

**Issue by maikel** [ericniebler/range-v3#627]
Hi,

for quite some while I am looking for a minimal example of the following ICE in gcc, which bothers me since some months.

Clang does accept the following code. 

Sorry for posting it here, but I didn't know if this belongs to gcc itself or here, since I can only reproduce it with range-v3.

If I remove `constexpr` from the `Throws_if_false`-operator or let `GreaterThan` not inherit from `ranges::box` it does compile without ICE.

[proof for ice on gcc-trunk](https://wandbox.org/permlink/GG89578DXNKbhqgj)
[proof for clang accepting it](https://wandbox.org/permlink/WRE1aZVdOkuYal93)
[proof for gcc accepting without inheriting from `ranges::box`](https://wandbox.org/permlink/QpoUJgVEriDluB72)

```
#include "range/v3/utility/invoke.hpp"
#include "range/v3/utility/compressed_pair.hpp"

namespace foo
{
  template <typename Exception = std::logic_error>
  struct Throws_if_false
  {
    template <typename P, typename ...A>
    constexpr void
    operator()(P pred, A&& ...args) const
    {
      if (!ranges::invoke(pred, std::forward<A>(args)...)) {
        throw Exception("Some Error occured");
      }
    }
  };
  
  template <auto N, typename Comp = std::less<>>
  class GreaterThan: private ranges::box<Comp, GreaterThan<N, Comp>>
  {
    using base = ranges::box<Comp, GreaterThan<N, Comp>>;
    using base::get;
  public:
    using base::base;
    
    template <typename T>
      constexpr bool operator()(const T& x) const
      {
        return get()(N, x);
      }
  };

  template <typename T, typename P, typename E = Throws_if_false<>>
  class Constrained: private ranges::compressed_pair<P, E>
  {
  private:
    using base_type = ranges::compressed_pair<P, E>;
    T value_;

    constexpr T enforce_constraint(T value) const
    {
      ranges::invoke(executor(), predicate(), value);
      assert(ranges::invoke(predicate(), value));
      return value;
    }

  public:
    constexpr Constrained(const T& value)
    : Constrained(value, P(), E()) {}

    template <typename T_>
      constexpr Constrained(T_&& value, P predicate, E executor)
      : base_type{std::move(predicate), std::move(executor)}
      , value_{enforce_constraint(std::forward<T_>(value))}
      {}

    constexpr const P& predicate() const& noexcept
    { return base_type::first(); }

    constexpr const E& executor() const& noexcept
    { return base_type::second(); }
  };
}

int main()
{
  using Positive = foo::Constrained<int, foo::GreaterThan<0>>;
  constexpr Positive n [[maybe_unused]] = 1;
}
```

**Comment by CaseyCarter** [comment]
> Sorry for posting it here, but I didn't know if this belongs to gcc itself or here, since I can only reproduce it with range-v3.

An ICE is *always* a bug in the compiler; it may or may not also indicate a bug in range-v3.

The root cause here seems to be an interaction between `GreaterThan`'s base - which is a specialization of `box` - and `compressed_pair`, which has two bases that are instances of `box`. The ICE doesn't manifest if either `GreaterThan` is modified to not derive from `box` or `Constrained` is modified to not derive from `compressed_pair`.

**Comment by maikel** [comment]
Additionally, it only causes an ICE if I `constexpr` is kept on `Throws_if_false`-operator... idk. 

I posted to bugzilla: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80294
