### ISSUE TITLE
Unnecessary copies of lambdas whilst calculating pipeline results

### ISSUE THREAD

**Issue by KayEss** [ericniebler/range-v3#630]
I posted a question to StackOverflow about this, and since I've done a bit more investigating. It turns out that whilst evaluating a pipeline multiple copies of the contained lambdas are made. This is the direct cause of the unexpected crash I was seeing, but if the lambdas have large closures this is also likely to cause multiple heap allocations.

I expect that the evaluation should be taking the lambdas using references or some sort of function view so that the copes don't happen. This ought to be a performance optimisation in the evaluation.

The program used to test this and it's output can be seen at http://stackoverflow.com/a/43197978/115526 along with some discussion.

Test program:

    #include <iostream>
    #include <vector>
    #include <range/v3/all.hpp>

    struct Noisy {
        Noisy() { local_ = ++cnt_; std::cout << "Noisy() ctor " << local_ << '\n'; }
        Noisy(const Noisy&) { local_= ++cnt_; std::cout << "Noisy(Noisy&) copy ctor " << local_ << '\n'; }
        Noisy(Noisy&&) { local_ = ++cnt_; std::cout << "Move constructor " << local_ << '\n'; }
        ~Noisy() { std::cout << "~Noisy() dtor with local " << local_ << '\n'; }

        // global object counter
        static int cnt_;

        // local count idx
        int local_ = 0;

        // Make this a range as well. Empty is fine
        std::vector<int> range;
        auto begin() { return range.begin(); }
        auto end() { return range.end(); }
    };
    int Noisy::cnt_ = 0;

    auto counter = []() {
        Noisy n;
        return ranges::make_pipeable([=](auto x) mutable -> Noisy& {
            std::cout << "Returning Noisy range " << n.local_ << '\n';
            return n;
        });
    };

    int main(int argc, char *argv[])
    {
        auto steps = counter();
        std::vector<int> data{{1, 2}};
        std::cout << "Applying" << '\n';
        auto result = data | steps;
        std::cout << "Displaying" << '\n';
        ranges::for_each(result, [](auto&& v) {
            std::cout << "Local result " << v << '\n';
        });
        std::cout << "Deleting" << '\n';
        return 0;
    }

Produces this output:

    Noisy() ctor 1
    Noisy(Noisy&) copy ctor 2
    Move constructor 3
    Move constructor 4
    ~Noisy() dtor with local 3
    ~Noisy() dtor with local 2
    ~Noisy() dtor with local 1
    Applying
    Noisy(Noisy&) copy ctor 5
    Noisy(Noisy&) copy ctor 6
    Returning Noisy range 6
    ~Noisy() dtor with local 6
    Noisy(Noisy&) copy ctor 7
    ~Noisy() dtor with local 5
    Displaying
    Deleting
    ~Noisy() dtor with local 7
    ~Noisy() dtor with local 4

**Comment by ericniebler** [comment]
Most places in the Standard Library that take functions as arguments (e.g. the algorithms) do so by value, and the library is free to copy them. Range-v3 follows suit. If you have an expensive and/or stateful function, and you would like to pass it to range-v3, you can use `std::reference_wrapper`.
