### ISSUE TITLE
[Documentation] view_adaptor example

### ISSUE THREAD

**Issue by michkot** [ericniebler/range-v3#637]
In the [documetation](https://ericniebler.github.io/range-v3/index.html#tutorial-quick-start) the following example for creating a range adaptor is given:
```c++
// A class that adapts an existing range with a function
template<class Rng, class Fun>
class transform_view : public view_adaptor<transform_view<Rng, Fun>, Rng>
{
    friend range_access;
    semiregular_t<Fun> fun_; // Make Fun model SemiRegular if it doesn't
    class adaptor : public adaptor_base
    {
        semiregular_t<Fun> fun_;
    public:
        adaptor() = default;
        adaptor(semiregular_t<Fun> const &fun) : fun_(fun) {}
        // Here is where we apply Fun to the elements:
        auto read(iterator_t<Rng> it) const -> decltype(fun_(*it))
        {
            return fun_(*it);
        }
    };
    adaptor begin_adaptor() const { return {fun_}; }
    adaptor end_adaptor() const { return {fun_}; }
public:
    transform_view() = default;
    transform_view(Rng && rng, Fun fun)
      : transform_view::view_adaptor{std::forward<Rng>(rng)}
      , fun_(std::move(fun))
    {}
};
```
I found, by trial and error and comparing to the current real implementation of transform_view, several problems with this example:

- it does not explain the `adaptor_base` class, thus inhibits making more complex adapters difficult 
- the method `read `of `adapter_based` is not the right one to "override" (hide) anymore. Is the January version of VS2015 version, it was `current `and it is `get `now I believe
- namespaces are not used in the example
- I was not able to find `iterator_t<Rng>` in any ranges namespace, ending up with `ranges::range_iterator_t<Rng>`

Also the - unexplained - Semiregular concept from the full implementation is retained but method ` auto indirect_move(range_iterator_t<Rng> it) const ` is stripped from the example without explanation.

My goal was to create a custom transform-like view [success] with an explicit definition of the begin and end iterators [failure, not enough info], to help Visual Studio to infer the type of object in range-for loop (VS does not handle all the nested templates well..)

I understand that this project is continuously WIP, but examples for view_facade and view_adaptor are IMHO crucial for users. If I can help improving the examples/doc, let me know, although I do not think I understand the library deeply enough....

My current custom adaptor:
```c++
template <class ViewT, class OutT>
class ObjectSeo : public ranges::view_adaptor<ObjectSeo<ViewT, OutT>, ViewT> {
private:
  friend ranges::range_access;
  Impl::Graph& graph;
  class adaptor : public ranges::adaptor_base
  {
    Impl::Graph* const graph;
  public:
    adaptor() = default;
    adaptor(Impl::Graph& g) : graph{&g} {};
    OutT get(ranges::range_iterator_t<ViewT> it) const {
      return {*it, *graph};
    }
  };
  adaptor begin_adaptor() const { return {graph}; }
  adaptor end_adaptor()   const { return {graph}; } 
public:
  ObjectSeo() = default;
  ObjectSeo(ViewT&& rng, Impl::Graph& context)
    : ObjectSeo::view_adaptor{std::forward<ViewT>(rng)}
    , graph(context)
  {}
};
```

**Comment by ericniebler** [comment]
There is no `range_iterator_t` in the library anymore (except as a deprecated interface). Please make sure you are using the latest version of the code. You might find the documentation to be slightly more accurate that way.

**Comment by michkot** [comment]
Oh... I am sorry, I was looking through the sources for too long and got confused with the latest range-v3 and fork changes, closing.
