### ISSUE TITLE
meta::for_each puzzles me no end

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#638]
I want to do metaprogramming on a list of types and I thought `meta::for_each` would be my friend, but I can't seems to figure it out:
```c++
auto constexpr _cummulative_type_sizes = meta::for_each(
    meta::list<int, long, float>{}, [ last = 0ull ] (auto && val) mutable constexpr
{
    last += sizeof(std::decay_t<decltype(val)>);
    return last;
})();
```
I thought that this should give me `{4, 8, 4}`, but it expects a parameter for `operator()`. When I give it 0, it then returns the number 20. Some debugging led me to the conclusion that
a) it runs for both the parameters in the type list **and** whatever you pass `operator()`
b) it only returns the value of the last call.

While the latter might be the expected behaviour (and I can work around it by caching inside the lambda and e.g. returning an array), a) seems really weird to me :question: 
But maybe I am doing it completely wrong? `meta` is already saving me a lot of code, but it is not exactly straight-forward to read :nerd_face:

**Comment by CaseyCarter** [comment]
`meta::for_each` is analagous to `std::for_each`: for each successive type element `T` in the first argument, it invokes the second argument with `T{}`. It then returns the second argument. This is great if you want to apply the modified function object to other values, but not so much if you want to retrieve state from it. You want something more like `std::accumulate` for this use case, to add up the sizes of the types in the input list ([DEMO](https://wandbox.org/permlink/tTarOCGXKyIjmn0d)):
```c++
template<class... Ts>
constexpr std::size_t _cummulative_type_sizes = 
    meta::accumulate<
        meta::transform<
            meta::list<Ts...>, 
            meta::quote<meta::sizeof_>>,
        meta::size_t<0>, 
        meta::quote<meta::plus>>::value;
```

**Comment by gnzlbg** [comment]
Do as @CaseyCarter says, but if you really want to use a lambda, you can still use `meta::for_each`:

```c++
auto constexpr _cummulative_type_sizes = []() {
    auto last = 0ull;
    meta::for_each(meta::list<int, long, float>{}, 
                   [&last] (auto val) { last += sizeof(val); });
    return last;
}();
```

The only thing you seem to be missing is that `meta::for_each` is analogous to `std::for_each(range, unaryF) -> unaryF`, which as you can see returns the `unaryF` that is being passed to. So if you want to use `for_each` as a poor-man's `accumulate`, you need to keep the state somewhere (out of the lambda, or using your own user-defined stateful unary function).

Anyhow `meta::for_each` is almost out-of-scope for `meta`. If you need to reach for it often you might want to take a look at Hana (or Fusion).

**Comment by h-2** [comment]
Thank you for your replies! Summing up the sizes was more of a minimal example that I used to try to figure out `meta::for_each`, the actual example is of course more complicated, or I wouldn't have chosen this route (I actually don't want to accumulate, but get individual returns from the calls). I was mainly confused by the lambda being the return type, but that is clear now!

> If you need to reach for it too often you might want to take a look at Hana

Yeah, I have been trying to avoid that up until now, but I might consider it.
