### ISSUE TITLE
travis-ci tests older clangs with new libc++

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/range-v3#640]
The `install_libcxx.sh` script that travis-ci uses to install libc++ always fetches tip-of-trunk libc++ sources and builds from that. That's regardless of what version of clang is being used. Trouble is, that's not how our users are likely to do it. Clang-3.6 (for instance) was released with a specific version of libc++, and testing with any other version is likely to either hide real problems or turn up spurious ones.

Find some way to install a version of libc++ that is appropriate for the version of clang that is being used.

ATTN: @gnzlbg

**Comment by gnzlbg** [comment]
The proper fix is probably to have the `install_libcxx.sh` take an argument with the clang version, and if its not e.g. `TRUNK`, then fetch the source code of `libc++` and `libc++abi` from `http://releases.llvm.org/` and extract it. The pattern seem to be:

- libc++: `http://releases.llvm.org/$VERSION/libcxx-$VERSION.src.tar.xz`
- libc++abi: `http://releases.llvm.org/$VERSION/libcxxabi-$VERSION.src.tar.xz`

I'll look into this after PR #600 is finished.

**Comment by gnzlbg** [comment]
Seems like clang 3.6 with libc++ 3.6 is broken, see: https://travis-ci.org/gnzlbg/range-v3/jobs/221700230#L1709

**Comment by ericniebler** [comment]
I know. You need to rebase on master. That's the `std::is_function` bug I just worked around.
