### ISSUE TITLE
Does the view cache it's size?

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#642]
My understanding of views was that all the things that effect what you are looking at happen on being accessed, i.e. it saves something like a reference to the underlying data structure, but instiates the iterators when needed. But it doesn't look like it:

```c++
#include <iostream>
#include <string>

#include <range/v3/view/transform.hpp>
#include <range/v3/view/single.hpp>
#include <range/v3/view/all.hpp>
#include <range/v3/view/reverse.hpp>

int main()
{
    std::string vec = "ACTTTGATA";
    auto v = vec | ranges::view::reverse;
    std::cout << vec << '\n';
    std::cout << v << '\n';

    vec = "ActttGATAn";
    std::cout << vec << '\n';
    std::cout << v << '\n';

    return 0;
}
```
gives:
```
ACTTTGATA
[A,T,A,G,T,T,T,C,A]
ActttGATAn
[A,T,A,G,t,t,t,c,A]
```
Although I thought it should give `[n, A,T,A,G,t,t,t,c,A]` in the last row... or does the view get invalidated when the underlying container is changed?

**Comment by CaseyCarter** [comment]
> or does the view get invalidated when the underlying container is changed?

In general, anything that would invalidate iterators into a range also invalidates views of that range.

**Comment by h-2** [comment]
@CaseyCarter thanks for the quick reply! I will close.

But out of curiosity: this probably happens for performance reasons / so that you can cache things on creation? Is the expected cost so noticable? I mean, why does the view not just call begin/end/operator[] whenever it needs to?

**Comment by ericniebler** [comment]
The view saves off `vec.begin()` and `vec.end()` on construction. That's all.

**Comment by CaseyCarter** [comment]
Much like how iterator operations are expected to be O(1), view operations are required to be amortized O(1) so that the performance of view compositions is predictable. Some views perform an expensive precomputation whose cost is amortized across many calls to e.g. `begin`. That precomputation could be made lazy - which I'll point out would not help in your case since the modification to the base range happens after the first pass through the view - but only at the cost of increased space and branching inside the pertinent operations.

The design approach range-v3 chooses is to do everything possible to make views fast and lightweight so they can simply be used and thrown away. The design intent is for you to do this:

```c++
int main()
{
    std::string vec = "ACTTTGATA";
    std::cout << vec << '\n';
    std::cout << ranges::view::reverse(vec) << '\n';

    vec = "ActttGATAn";
    std::cout << vec << '\n';
    std::cout << ranges::view::reverse(vec) << '\n';
}
```

or

```c++
int main()
{
    std::string vec = "ACTTTGATA";
    auto rev = [&]{ 
        return /* complicated view composition that I don't want to type over and over */;
    };
    std::cout << vec << '\n';
    std::cout << rev() << '\n';

    vec = "ActttGATAn";
    std::cout << vec << '\n';
    std::cout << rev() << '\n';
}
```

instead of thinking of a view composition as something expensive that you should cache.

**Comment by ericniebler** [comment]
> ```c++
>     auto rev = [&]{ 
>        return /* complicated view composition that I don't want to type over and over */;
>     };
> ```

No, it's better than than. A chain of adaptors can be preassembled into a pipeline and saved off for future (re-)use.

```c++
auto pipeline = view::reverse | view::take(4);
std::string s = "ACTTTGATA";
std::cout << (s | pipeline) << '\n'; // ATAG
s = "ABCDEFGHIJ";
std::cout << (s | pipeline) << '\n'; // JIHG
```

**Comment by h-2** [comment]
> No, it's better than than. A chain of adaptors can be preassembled into a pipeline and saved off for future (re-)use.

Yes, I have been doing that all along, it's really cool.

> The view saves off vec.begin() and vec.end() on construction. That's all.

I was still wondering, why not instead save a pointer to the underlying range and call `begin()` and `end()` when needed? Would that really be slower? Or are there other architectural drawbacks of this approach? [that's  how we implemented views before starting to use range-v3 but our scope was much smaller]

I know that your views "are much more like iterators" than I thought in the beginning (and that might a good design decision), but wouldn't you get "future safety" (no invalidation by resize/reallocs...) for free when doing this differently? Or am I missing something?
