### ISSUE TITLE
"Variadize" transform implementation

### ISSUE THREAD

**Issue by khlebnikov** [ericniebler/range-v3#644]
The implementation of transform has 2 versions - for one and two ranges. Is there interest in unifying those and also supporting more than two ranges by making transform variadic? I'd be happy to contribute if there is.

**Comment by CaseyCarter** [comment]
I can see such a thing being useful. I suspect the work will be made more "interesting" by the fact that `view::transform` takes its function parameter last to be consistent with `std::transform`.

**Comment by khlebnikov** [comment]
Yeah, this will be "interesting" indeed. But an extra challenge is sometimes even good :)
I'll make some version of this and let's see where it goes.

**Comment by ericniebler** [comment]
That view already exists, and it's called `zip_with`.

**Comment by khlebnikov** [comment]
I see. If I understand it correctly, transform has 2 versions because STL has two and `zip_with` is the variadic version. I'll look at something else I can help with then.

**Comment by khlebnikov** [comment]
On the other hand unless you think it makes no sense (I doubt it's impossible) - I could try making variadic transform conform to the STL-ish interface (function parameter being last) because it seems more intuitive to me than having 2 views with different names doing pretty much the same thing, but having different order of arguments. 

Let me know what you think about this.

**Comment by ericniebler** [comment]
I'm not sure it's worth the trouble, honestly. Given range-v3's concept checking system, it would be possible to constrain such an algorithm, but I'm struggling seeing how to write the concept checks once we move to proper concepts.

**Comment by khlebnikov** [comment]
I see. Well, I'm definitely not at the level of fully understanding the code to contribute further to this discussion. It just struck me as strange that `transform` has separate one- and two-range versions. 

I currently have some spare time and I'd like to contribute something useful. I'll look further into the existing issues (although some of them are quite hard to "decode" without some additional context). 

Thanks,
  Rostislav.
