### ISSUE TITLE
Compile error in MinGW

### ISSUE THREAD

**Issue by CHChang810716** [ericniebler/range-v3#654]
compiler: g++ 6.3
platform: windows10 / x86_64
range-v3: range-v3-0.2.4

================================

Scanning dependencies of target container_conversion                                                                                
[ 54%] Building CXX object test/CMakeFiles/container_conversion.dir/container_conversion.cpp.obj                                    
In file included from C:/Users/JohnChang/range-v3-0.2.4/include/range/v3/detail/optional.hpp:20:0,                                  
                 from C:/Users/JohnChang/range-v3-0.2.4/include/range/v3/utility/semiregular.hpp:21,                                
                 from C:/Users/JohnChang/range-v3-0.2.4/include/range/v3/utility/basic_iterator.hpp:26,                             
                 from C:/Users/JohnChang/range-v3-0.2.4/include/range/v3/utility/iterator.hpp:28,                                   
                 from C:/Users/JohnChang/range-v3-0.2.4/include/range/v3/begin_end.hpp:27,                                          
                 from C:/Users/JohnChang/range-v3-0.2.4/include/range/v3/core.hpp:17,                                               
                 from C:\Users\JohnChang\range-v3-0.2.4\test\container_conversion.cpp:18:                                           
C:/Users/JohnChang/range-v3-0.2.4/include/range/v3/detail/variant.hpp: In member function 'meta::v1::if_c<(N != M)> ranges::v3::deta
il::construct_fn<N, Ts>::operator()(ranges::v3::detail::indexed_datum<U, std::integral_constant<long long unsigned int, M> >&) [with
 U = meta::v1::nil_; long long unsigned int M = 0ull; long long unsigned int N = 1ull; Ts = {ranges::v3::_counted_iterator_::counted
_iterator<ranges::v3::_basic_iterator_::basic_iterator<ranges::v3::iota_view<int, void> >, void>&&}]':                              
C:/Users/JohnChang/range-v3-0.2.4/include/range/v3/detail/variant.hpp:398:17: error: 'noreturn' function does return [-Werror]      
                 }

**Comment by CaseyCarter** [comment]
Which distribution of MinGW, exactly? Does this program:
```c++
[[noreturn]] void f() {
   (false ? void() : __builtin_unreachable());
}

int main() {}
```
produce a similar error?

**Comment by CHChang810716** [comment]
work fine

I download my distribution here
https://nuwen.net/files/mingw/mingw-14.1.exe

**Comment by CaseyCarter** [comment]
MinGW's `assert` is apparently brain-damaged and doesn't know it cannot return (https://sourceforge.net/p/mingw-w64/bugs/306/).

**Comment by CHChang810716** [comment]
Work fine.
Thanks !

**Comment by CHChang810716** [comment]
oops!
another compile failed
[ 87%] Building CXX object test/utility/CMakeFiles/utility.functional.dir/functional.cpp.obj
In file included from C:/Users/JohnChang/range-v3/include/range/v3/utility/box.hpp:25:0,
                 from C:/Users/JohnChang/range-v3/include/range/v3/utility/functional.hpp:24,
                 from C:\Users\JohnChang\range-v3\test\utility\functional.cpp:14:
C:\Users\JohnChang\range-v3\test\utility\functional.cpp: In function 'int main()':
C:\Users\JohnChang\range-v3\test\utility\functional.cpp:269:47: error: '__vectorcall' was not declared in this scope
         CONCEPT_ASSERT(ranges::Invocable<void(__vectorcall*)()>());

**Comment by CaseyCarter** [comment]
To my knowledge, #657 addresses all remaining MinGW issues.
