### ISSUE TITLE
CMAKE Errors on GCC 7.1

### ISSUE THREAD

**Issue by fuocor** [ericniebler/range-v3#661]
Just getting started on Ubuntu builds of my code and

ran the following

`git clone https://github.com/ericniebler/range-v3.git`
`cd range-v3`
`mkdir build && cd build`
`cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DRANGE_V3_NO_HEADER_CHECK=1 ..`

which output the following

`-- The CXX compiler identification is GNU 7.1.0
-- Check for working CXX compiler: /usr/local/gcc-7.1/bin/c++
-- Check for working CXX compiler: /usr/local/gcc-7.1/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Found Git: /usr/bin/git (found version "2.7.4")
Valgrind not found
CMake Error at CMakeLists.txt:76 (elseif):
  given arguments:

    "CMAKE_CXX_COMPILER_VERSION" "VERSION_GREATER_EQUAL" "7.0"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
See also "/home/richf/git/ericniebler/range-v3/build/CMakeFiles/CMakeOutput.log".`

**Comment by CaseyCarter** [comment]
Sorry - my mistake. `VERSION_GREATER_EQUAL` was added in cmake 3.7. You can work around this locally  before the PR is merged by changing that to `VERSION_GREATER` in CMakeLists.txt.

**Comment by fuocor** [comment]
Thanks... I just upgraded to cmake 3.8.1 and it works fine
