### ISSUE TITLE
Suggestion: `ranges::shuffle` should have the same outcome as `std::shuffle`

### ISSUE THREAD

**Issue by yfeldblum** [ericniebler/range-v3#663]
Given the same input range (or iterator-pair) and the same random generator, `ranges::shuffle` should rearrange the items in the exact same way that `std::shuffle` would.

**Comment by ericniebler** [comment]
Why?

**Comment by yfeldblum** [comment]
So that the observable behavior would remain identical when switching from `std::shuffle` to `ranges::shuffle`, tied only to which implementation of the standard library is in use. It seems to me to be a useful property to have.

In my case, there is a complicated function which uses `std::shuffle` somewhere inside. There are unit-tests for that function, which provide a deterministically-seeded generator and which check a given set of test vectors. Then switching to `ranges::shuffle` is likely to break the unit-tests. (In that case, we do presume a given implementation of the standard library; switching that is also likely to break the unit-test.)

**Comment by CaseyCarter** [comment]
If you're prepared to modify your unit test whenever you change libraries, or whenever your standard library decides to change its implementation, why would you be bothered by modifying the unit test upon switching to `ranges::shuffle`?

**Comment by ericniebler** [comment]
I agree with @CaseyCarter. This just seems like a poorly designed test.

In the case when `decltype(rng.begin())` is not the same as `decltype(rng.end())` there is _no_ way to make `ranges::shuffle` have the same observable behavior as `std::shuffle` without perf loss. I'm not inclined to pay that cost, and special-casing the `BoundedRange` case adds complexity without a compelling (IMO) reason.
