### ISSUE TITLE
Failure to infer range type when passing range of containers to std::size transform

### ISSUE THREAD

**Issue by aw1621107** [ericniebler/range-v3#677]
Example program:

```
#include <vector>
#include <range/v3/view/transform.hpp>
int main() {
    std::vector<std::vector<int>> vec;
    vec | ranges::view::transform(&std::size);
}
```

Compilation command and results:

```
rp:tmp awang$ clang++ -std=c++1z -I/Users/awang/code/range-v3/include test.cpp
test.cpp:6:8: error: no matching function for call to object of type 'const
      view<ranges::v3::view::transform_fn>'
        vec | ranges::view::transform(&std::size);
              ^~~~~~~~~~~~~~~~~~~~~~~
/Users/awang/code/range-v3/include/range/v3/view/view.hpp:124:22: note: candidate
      template ignored: couldn't infer template argument 'Rng'
                auto operator()(Rng && rng, Rest &&... rest) const
                     ^
/Users/awang/code/range-v3/include/range/v3/view/view.hpp:132:22: note: candidate
      template ignored: substitution failure [with Ts = <>, V =
      ranges::v3::view::transform_fn]: no matching function for call to 'bind'
                auto operator()(Ts &&... ts) const
                     ^
1 error generated.
```

I would have expected a range of `std::size_t` with the respective sizes of the vectors. Compilation succeeds if `&std::size` is replaced with `&std::size<std::vector<int>>` or `&std::vector<int>::size`. At least to my inexperienced eyes the compiler should have enough information to figure out the template argument. Is there anything that can be done about the failure to infer the template arguments, or is it a language limitation? Or something else?

**Comment by CaseyCarter** [comment]
In the OP, `ranges::view::transform` accepts a function object. At the callsite, there is no indication what argument types will eventually be passed to that function object. Indeed, you could pipe ranges of different types through the result of transforming via the same function object:
```c++
auto foo = view::transform([](auto && r) { return std::size(r); });
std::vector<std::vector<int>> | foo;
std::vector<std::list<float>> | foo;
```
The result of all of that generality is that the compiler cannot possibly infer the type of the argument to `view::transform`.

The solution for this case where you want to pass an overload set or function template is to wrap it in a lambda - as I did with `size` above. In the specific case of `size`, you could simply use the `ranges::size` function object provided by range-v3 that knows how to determine the size of ranges.

**Comment by aw1621107** [comment]
Hmmm... I originally thought that the `view::transform` call would desugar into an rvalue, and because of that the compiler could infer the type for that specific call instead of trying to figure out the general case. Your example made me think of it as normal function calls, and from that point I can see why it wouldn't work. The way I thought it would work would only actually work after many inlining/substitution passes, and by then it's far too late.

Thanks for correcting me! Didn't know about `ranges::size`, either; seems like that does the trick.
