### ISSUE TITLE
ranges::size seems not to work on a ranges::view::filter range

### ISSUE THREAD

**Issue by wickedmic** [ericniebler/range-v3#681]
I tried to to use ranges::size on a range, which was constructed with ranges::view::filter, and it looks like size does not accept this range. Here is a boiled down example, which produces the same error (gcc-6.3/clang-3.8 with -std=c++1z):
```c++
#include <range/v3/all.hpp>
int main(){
  auto r = ranges::view::iota(0,20) | ranges::view::filter([](auto i){ return i % 3 == 0; });
  return ranges::size(r);
}
```
I looked into the sources (my checkout is at tag 0.2.6) and found an overload of `ranges::v3::_size_::fn::impl_(..)` (size.hpp:70), which looks like it should deal with forward ranges (I'm assuming r is at least a forward range). 

If I'm not missing some error in my code, I feel like this should compile.

**Comment by ericniebler** [comment]
`ranges::size` requires a SizedRange, which is a range that knows its size in O(1). You want `ranges::distance`.
