### ISSUE TITLE
Check for thread support

### ISSUE THREAD

**Issue by remyabel** [ericniebler/range-v3#682]
Currently utility/random.hpp has this:

```C++
#ifndef __MINGW32__
                    // Hash our thread id.  It seems to vary from run to run on OS X, not
                    // so much on Linux.
                    *it++ = randutils::hash(std::this_thread::get_id());
#endif
```

However, this doesn't take into account systems that don't have thread support (i.e, cross compiling for a homebrew kernel). Patching it out is trivial, but I think pedantically there should be a CMake check at least. Potentially with `try_compile` since libstdc++ for example has this macro define:

`#if defined(_GLIBCXX_HAS_GTHREADS) && defined(_GLIBCXX_USE_C99_STDINT_TR1)`

and doesn't define `thread` otherwise, which means checking for existence of `<thread>` and this platform-specific macro is not sufficient.

**Comment by CaseyCarter** [comment]
range-v3 traditionally has not gone out of its way to support environments that don't fully implement C++11. `random.hpp` is, however, already the biggest exception to that policy: it goes to great lengths to work on implementations with poor support for `thread_local` storage. It doesn't seem unreasonable to me to have a very small `try_compile` check for this.

**Comment by remyabel** [comment]
Hi thanks for the patch. I was actually writing nearly identical code when you beat me to the punch.

It's not that the implementation doesn't support C++11, just libstdc++ removes the class altogether if it doesn't detect thread support. I think given the context (trying different sources for entropy) it's not that big of a deal to change.

**Comment by CaseyCarter** [comment]
> It's not that the implementation doesn't support C++11, just libstdc++ removes the class altogether if it doesn't detect thread support.

To me, that sounds *exactly* like "the implementation doesn't support `<thread>`, which is part of C++11."

> I think given the context (trying different sources for entropy) it's not that big of a deal to change.

Agreed.

**Comment by remyabel** [comment]
> To me, that sounds exactly like "the implementation doesn't support <thread>, which is part of C++11."

The libstdc++ implementation is there, but it requires OS support (i.e porting pthreads) which has nothing to do with C++, as C++ only specifies the implementation for the standard library.
