### ISSUE TITLE
Feature request: Add `at` to view_interface template struct

### ISSUE THREAD

**Issue by apmccartney** [ericniebler/range-v3#686]
Random-access view_interface instantiations doesn't seem to provide a bounds-checking `at` method as vector does. Vector-api compatability is helpful when introducing range-v3 to an existing generic codebase. 

I was considering adding this capability and filing a pull request, but wanted to verify there wasn't a reason I ought not do so.

**Comment by ericniebler** [comment]
Seems reasonable. Go for it!
