### ISSUE TITLE
range_concepts.hpp presumes namespace std

### ISSUE THREAD

**Issue by tlanc007** [ericniebler/range-v3#694]
**range_concepts.hpp** has a number of references to begin/end without std::.  Is it assumed that namespace std should always be defined with ranges?

**Comment by ericniebler** [comment]
It's not referencing the `begin` and `end` in namespace `std`. It's referencing the `begin` and `end` in namespace `ranges`.

**Comment by tlanc007** [comment]
Yeah, I was just starting to realize that after looking at begin_end.hpp.

Thanks.
