### ISSUE TITLE
Find a better name for iterator_range

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#697]
Especially when dealing with old/current interfaces you sometimes have a pair of begin/end iterators you have to deal with. It would be great if I could e.g. `view::all_between(it, it_end) | view::join | ...`

Does something like this exist and I just overlooked it? If not, do you agree, it would be nice to have? I could look into it and maybe create a PR...

**Comment by FloopCZ** [comment]
Hi, you may be looking for [ranges::iterator_range](http://ericniebler.github.io/range-v3/structranges_1_1v3_1_1iterator__range.html) and [ranges::make_iterator_range](http://ericniebler.github.io/range-v3/structranges_1_1v3_1_1make__iterator__range__fn.html).

**Comment by h-2** [comment]
Hm, I still think it is not very intuitive that it is neither in the view namespace nor has "view" in its name, although it is one and probably one of the ones used more frequently, also by consumers of the library.

**Comment by ericniebler** [comment]
That's a fair point. Do you have a suggestion for a better name?

**Comment by FloopCZ** [comment]
I remember that the first time a have been looking for it, it also took me a while. Maybe just moving it into `view::` namespace would be more intuitive. `view::iterator_range(begin, end)` sounds good to me.

**Comment by ericniebler** [comment]
It's strange that it's called "`iterator_range`" when it's really a View. I wonder if it wouldn't be better to permit users to create this thing with `view::all(begin, end)` and have it return an instance of ... what? `iterator_view`? Iterator and View are both concepts; putting them together like that feels weird. In the standard, [`begin`,`end`) is called a "range", but "`range_view`" is even weirder than "`iterator_view`". I'm tempted to just call that damn thing "`view`" but that's a non-starter. @CaseyCarter?

Naming Is Hard.

**Comment by h-2** [comment]
> I wonder if it wouldn't be better to permit users to create this thing with view::all(begin, end)

Yes, that was the first place I looked and would be a lot better than the current name. Or what I proposed in my first post in this thread was: `view::all_between(it, it_end)`
That keeps it close to `view:all`, but also has some "ranginess" without using the range-term (which I agree would be confusing here).

> Naming Is Hard.

True.

**Comment by CaseyCarter** [comment]
I don't hate `view::all(begin, end)`. I might prefer `view::subrange`. As views go, this one has the interesting property that its iterators are known to outlive the range itself. I don't know how useful that property is, but there it is.

**Comment by h-2** [comment]
> I might prefer `view::subrange`.

The thing is that it doesn't necessarily have to be "sub". it could well be `view::foo(rbegin(other), rend(other)` resulting in the equivalent of `view::reverse`. → For these kind of cases `view::all`, `view::all_between` would be better IMHO.
Since "range" is now something more general / less constrained than a view or container, I would avoid using it in names of views, it would just confuse people.

Something not yet mentioned here: `view::span` 
I think it fits quite well and isn't yet used in range-v3 terminology, but it could cause confusion with the GSL span 😑

**Comment by tahonermann** [comment]
I called this basic_view in Text_view. 

https://github.com/tahonermann/text_view/blob/master/include/text_view_detail/basic_view.hpp

**Comment by CaseyCarter** [comment]
> Something not yet mentioned here: `view::span`

`ranges::span` is an implementation of [the `span` proposal](http://wg21.link/p0122).

> I called this `basic_view` in `Text_view`.

I think it would be confusing to have both a `view_base` and a `basic_view` in the same design.

**Comment by h-2** [comment]
> ranges::span is an implementation of the span proposal.

Yeah, that's what I meant by the GSL implementation. However this would be kind of obsolete if Ranges TS is merged with all the view code, or not?

**Comment by h-2** [comment]
@ericniebler What are your thoughts on the proposed names?

If we don't reach consensus here now, could we rename the issue and re-open so that it doesn't fall of the radar? Thanks!

**Comment by gnzlbg** [comment]
FWIW I write `view::all(begin, end)` every now and then by mistake before the compiler reminds me that I have to use `iterator_range`. 

BTW, what does `all` in `view::all` stand for? In my head I translate it to `view::make`.

**Comment by ericniebler** [comment]
> BTW, what does `all` in `view::all` stand for? In my head I translate it to `view::make`.

`view::all(rng)` : "Get me a View of all the elements in the Range `rng`."

**Comment by CaseyCarter** [comment]
> FWIW I write `view::all(begin, end)` every now and then by mistake before the compiler reminds me that I have to use `iterator_range`.

I agree that `view::all(b, e)` is the best suggestion we have for this. `make_iterator_range` will never be proposed for standardization anyway: now that we have constructor template argument deduction, simple  `make` functions are extraneous.

> BTW, what does all in `view::all` stand for? In my head I translate it to `view::make`.

"All" stands for, well, "all." It creates a view over "all" of the elements of the range parameter.

**Comment by ericniebler** [comment]
> now that we have constructor template argument deduction, simple `make` functions are extraneous.

But what is the name of the type returned from `view::all(b, e)`? We can't replace `view::all` with a deduction guide until we know what the class template is called.

**Comment by CaseyCarter** [comment]
I doubt we can *ever* replace `view::all` with a deduction guide; I can't pass a deduction guide as an argument like I can a function object. Remember that the exact return type of `view::all` is conditional: it returns its argument directly if it is a `View`, and otherwise returns an `iterator_range` over the argument if it is an lvalue `Range`. That's why we have a `view::all_t` alias rather than an `all_view`. (And I'd like to replace the second case with a `ref_view<T>` that stores a reference to the lvalue range `T` rather than storing an iterator *and* a sentinel *and* potentially a size, but that's a separable issue.)

**Comment by ericniebler** [comment]
I actually went with `all_view` for my range adaptors proposal. Objections?

**Comment by ericniebler** [comment]
And I'm starting to like `subrange` for `iterator_range`.

**Comment by CaseyCarter** [comment]
> And I'm starting to like `subrange` for `iterator_range`.

+1. I find it interesting that `iterator_range` is the only(?) view whose iterators are guaranteed to be comparable to those of another range: it is always a subrange of some range. There are a class of users who expect `span` and `string_view` to have that behavior and are surprised when they do not.

**Comment by h-2** [comment]
From twitter:

> My favourites ares:
> `view::span`
> `view::between`
> `view::interval`
> I think the namespace is important for consistency... 

Being a fan of latin I just came up with `view::inter` (the latin version of `view::between`), you would definitely get a comedy award from the committee for introducing the "inter-view" 😉 

@ericniebler :
> span is taken already. 

But the current use will be obsoleted with the Ranges TS / TS2, or not? Then again, maybe it should be reserved for something that creates a sized-view from a random-access-range a la `view::span(begin_iterator, length)`... something like a combination of the current `iterator_range` and and take or take_exactly. Anyway, different point.

> Interval already means something in math (closed range, not half open).

Not where I am from 😎  Intervals can be open, closed, or half-open. In fact at the computer science department where I work an unspecified "interval" usually refers to a zero-indexed half-open interval.
Wikipedia also distinguishes these for the term "interval" : 
https://en.wikipedia.org/wiki/Interval_(mathematics)

Me:
> And "subrange" falsely suggests a smaller size than original, but maybe that's just my German ears hearing it 😅

@ericniebler :
> "proper_subrange" would imply smaller than the original. Think set/subset/proper subset

Hm, yeah, I guess we have the situation for most of the terms that they can mean different things, especially when paired with an adjective.
To me a "subrange" mostly closely sounds like what `view::slice` currently does (in fact it took me a while do find slice when first looking for it because a grepped for "sub"). I agree with the "proper subset" analogy, and of course it should be possible to create a subset that contains the full set, however I feel like there will be many uses of the `iterator_range` that have nothing to do with a subset at all, simply because it's the easiest way of turning iterators into a view – and iterators are used for a lot of things right now, e.g. if a collection of elements represents a tree, I could have implemented iterators that do different order traversals. Now wanting to turn these into a view I would be confused to learn that the proper way is a `subrange`.

In any case, I agree, this is all quite subjective. You could make a poll on twitter with a link to this issues...
I would just like to maintain that, independent of name, it be placed in `view::` and be documented with the rest of the views.

**Comment by maikel** [comment]
> But the current use will be obsoleted with the Ranges TS / TS2, or not? Then again, maybe it should be reserved for something that creates a sized-view from a random-access-range a la view::span(begin_iterator, length)... something like a combination of the current iterator_range and and take or take_exactly. Anyway, different point.

`span` is a special *contiguous view*. It has therefore a very special interface. Random access is not enough.

**Comment by ericniebler** [comment]
And here in an interesting (to me) suggestion: if "view" gets shot down in LEWG because it too-strongly suggests "read-only", can we replace it everywhere with "subrange"? E.g. `rng | subrange::filter(pred)` returns a `filter_subrange`, and the range concept hierarchy goes:

```txt
Range <- SizedRange
      <- SubRange
```

For the record, I vastly prefer "view", but it's not the worst suggestion, right?

**Comment by tahonermann** [comment]
I like ‘subrange’ as a replacement for ‘iterator_range’, but not for when a filter or transformation is involved.  I think of a subrange as a continuous fragment of a sequence.

**Comment by ericniebler** [comment]
> I think it would be confusing to have both a `view_base` and a `basic_view` in the same design.

See also: `ios_base` and `basic_ios`. :-P

**Comment by ericniebler** [comment]
Superseded by #766.
