### ISSUE TITLE
view::generate and range for loop is incompatibe

### ISSUE THREAD

**Issue by ErofeevK** [ericniebler/range-v3#705]
The following code snippet is failed to compile. 
``` 
auto x = ranges::view::generate_n([](){return 1;}, 5);
//    auto x = ranges::view::generate([](){return 1;}) | ranges::view::take(3);
    for (auto i: x){
        std::cout << i;
    }
```

Probably my expectation is wrong.  But range for loop works just fine with  other  types of `ranges::view`

```
error: inconsistent begin/end types in range-based ‘for’ statement: ‘ranges::v3::detail::facade_iterator_t<ranges::v3::generate_n_view<read_file_range(const cfg_t&)::<lambda()> > > {aka ranges::v3::_basic_iterator_::basic_iterator<ranges::v3::generate_n_view<read_file_range(const cfg_t&)::<lambda()> >::cursor>}’ and ‘ranges::v3::detail::facade_sentinel_t<ranges::v3::generate_n_view<read_file_range(const cfg_t&)::<lambda()> > > {aka ranges::v3::default_sentinel}’
     for (auto i: x){
                  ^
error: conversion from ‘ranges::v3::detail::facade_sentinel_t<ranges::v3::generate_n_view<read_file_range(const cfg_t&)::<lambda()> > > {aka ranges::v3::default_sentinel}’ to non-scalar type ‘ranges::v3::detail::facade_iterator_t<ranges::v3::generate_n_view<read_file_range(const cfg_t&)::<lambda()> > > {aka ranges::v3::_basic_iterator_::basic_iterator<ranges::v3::generate_n_view<read_file_range(const cfg_t&)::<lambda()> >::cursor>}’ requested
error: no match for ‘operator!=’ (operand types are ‘ranges::v3::detail::facade_iterator_t<ranges::v3::generate_n_view<read_file_range(const cfg_t&)::<lambda()> > > {aka ranges::v3::_basic_iterator_::basic_iterator<ranges::v3::generate_n_view<read_file_range(const cfg_t&)::<lambda()> >::cursor>}’ and ‘ranges::v3::detail::facade_iterator_t<ranges::v3::generate_n_view<read_file_range(const cfg_t&)::<lambda()> > > {aka ranges::v3::_basic_iterator_::basic_iterator<ranges::v3::generate_n_view<read_file_range(const cfg_t&)::<lambda()> >::cursor>}’)
```

**Comment by CaseyCarter** [comment]
Ranges TS / range-v3 ranges sometimes return objects of different types from `begin` and `end`. Before C++17, the core language's range-based-for loop requires `begin` and `end` to return the same type. As you have noticed, these two facts are in conflict.

There are a few options for dealing with this problem:
1. Don't write range-based for loops: use `ranges::for_each` with a lambda instead:

  ```c++
  ranges::for_each(x, [](auto i) { std::cout << i; });
  ```
  This is workable, but requires lots of annoying boilerplate.

2. Always use a compiler that supports enough of C++17 to allow different `begin` and `end` types in range-based for loops. If you can get away with code that only compiles with the most recent releases of compilers, this is reasonable. (All of gcc/clang/msvc have supported C++17's range-based-for for a couple of releases.)

3. include the `range_for.hpp` header and use the `RANGES_FOR` macro where you want a range-based for loop that may need to work with ranges with differing iterator and sentinel types:
```c++
#include <range/v3/range_for.hpp>
// ...
RANGES_FOR(auto i, x) {
    std::cout << i;
}
```

The third solution is what we usually recommend.
