### ISSUE TITLE
From iterator to index in contiguous container

### ISSUE THREAD

**Issue by mlund** [ericniebler/range-v3#706]
I have tried to reduce my problem to the following, where `rng` is a range with one random element, pointing either to index 2 or 3 in `v`:
```cpp
#include <vector>
#include <range/v3/all.hpp>
int main() {
    std::vector<int> v = {10,20,30,30,40};
    auto rng = v | ranges::view::filter( [](int i){return i==30;} )
        | ranges::view::sample(1); // [30]
}
```
Normally I would use `distance(v.begin(), rng.begin())` to find the index in `v` (2 or 3), but this is not applicable here for reasons I think I understand. My current solution is:

```cpp
int index = std::distance( v.data(), &(*rng.begin()) ); // 2 or 3
```
My question is if there is a more convenient way of achieving this?

**Comment by ericniebler** [comment]
Use the `find` algorithm to obtain an iterator pointing to the first 30 in the vector, then subtract the beginning of the vector.

**Comment by mlund** [comment]
Thanks for your quick response. I do not see how `find` solves the problem, but my question was imprecise. Let's say that `v={10,20,30,40,30,11}` and I want to randomly pick _one_ of the two 30'ies and convert it to an index, i.e. either 2 or 4 in this case.

**Comment by CaseyCarter** [comment]
I would use:
```c++
std::vector<int> v = {10,20,30,30,40};
auto rng = ranges::view::indices(v.size())
  | ranges::view::filter([&v](std::size_t i) { return v[i] == 30; })
  | ranges::view::sample(1);
// Assumes rng is not empty
auto index = ranges::front(rng);
```
