### ISSUE TITLE
Problems creating a stand-alone view

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#708]
I have created a class that meets the View concept, i.e. it's a range, its Movable and DefaultConstructible and `detail::view_predicate_<T>` resolves to true. However it is not derived from view_base and doesn't use any of the range-v3 internals.
AND when I try to combine it with range-v3-views I get all sorts of problems, apparently relating to the fact that the `iterator<T>` and `iterator<T const>` are not the same. These are the relevant member types defined on my type:
```cpp
    using iterator          = random_access_iterator<view_join_ra>;
    using const_iterator    = random_access_iterator<view_join_ra const>;
    using value_type        = std::remove_reference_t<ref_t>;
    using reference         = ref_t;
    using const_reference   = std::conditional_t<std::is_lvalue_reference_v<ref_t>, std::add_const_t<ref_t>, ref_t>;
```
That is, for a given ref_t (input reference type) of `char &`, I want `reference` of the new view to also be `char &` and `const_reference` to be `char const &`; while if ref_t is just `char`, I want both `reference` and `const_reference` to also be `char`.
The random_access_iterator is defined in a way where its `reference` is equal to it's container's `reference` in case the container is non-const, and equal to its container's `const_reference` in case the container is const.

BUT if I do it this was, I get internal errors from the range library, that it cannot convert a const_iterator to an iterator (which my iterator does not allow for obvious(?) reasons):
```
/home/mi/h4nn3s/devel/seqan3/test/../range-v3/include/range/v3/view_adaptor.hpp:359:18: error: no matching function for call to 'ranges::v3::adaptor_cursor<seqan3::detail::random_access_iterator<const seqan3::detail::view_join_ra<seqan3::dna5&> >, ranges::v3::iter_transform_view<seqan3::detail::view_join_ra<seqan3::dna5&>, ranges::v3::indirected<seqan3::view::<lambda(auto:2)> > >::adaptor<true> >::iter_move_(int) const'
             auto move() const
                  ^~~~
/home/mi/h4nn3s/devel/seqan3/test/../range-v3/include/range/v3/view_adaptor.hpp:313:15: note: candidate: template<class A, class X> X ranges::v3::adaptor_cursor<BaseIt, Adapt>::iter_move_(int) const [with A = A; X = X; BaseIter = seqan3::detail::random_access_iterator<const seqan3::detail::view_join_ra<seqan3::dna5&> >; Adapt = ranges::v3::iter_transform_view<seqan3::detail::view_join_ra<seqan3::dna5&>, ranges::v3::indirected<seqan3::view::<lambda(auto:2)> > >::adaptor<true>]
             X iter_move_(int) const
               ^~~~~~~~~~
/home/mi/h4nn3s/devel/seqan3/test/../range-v3/include/range/v3/view_adaptor.hpp:313:15: note:   template argument deduction/substitution failed:
/home/mi/h4nn3s/devel/seqan3/test/../range-v3/include/range/v3/view_adaptor.hpp:310:42: error: no matching function for call to 'ranges::v3::iter_transform_view<seqan3::detail::view_join_ra<seqan3::dna5&>, ranges::v3::indirected<seqan3::view::<lambda(auto:2)> > >::adaptor<true>::iter_move(const seqan3::detail::random_access_iterator<const seqan3::detail::view_join_ra<seqan3::dna5&> >&) const'
             template<typename A = Adapt, typename X = decltype(
                                          ^~~~~~~~
In file included from /home/mi/h4nn3s/devel/seqan3/test/../include/seqan3/range/view/to_char.hpp:43:0,
                 from /home/mi/h4nn3s/devel/seqan3/test/range/view/view_join_ra_test.cpp:44:
/home/mi/h4nn3s/devel/seqan3/test/../range-v3/include/range/v3/view/transform.hpp:86:22: note: candidate: decltype (ranges::v3::function_objects::invoke(((const ranges::v3::iter_transform_view<Rng, Fun>::adaptor<IsConst>*)this)->ranges::v3::iter_transform_view<Rng, Fun>::adaptor<IsConst>::fun_, ranges::v3::move_tag{}, it)) ranges::v3::iter_transform_view<Rng, Fun>::adaptor<IsConst>::iter_move(ranges::v3::iterator_t<Rng>) const [with bool IsConst = true; Rng = seqan3::detail::view_join_ra<seqan3::dna5&>; Fun = ranges::v3::indirected<seqan3::view::<lambda(auto:2)> >; decltype (ranges::v3::function_objects::invoke(((const ranges::v3::iter_transform_view<Rng, Fun>::adaptor<IsConst>*)this)->ranges::v3::iter_transform_view<Rng, Fun>::adaptor<IsConst>::fun_, ranges::v3::move_tag{}, it)) = char; ranges::v3::iterator_t<Rng> = seqan3::detail::random_access_iterator<seqan3::detail::view_join_ra<seqan3::dna5&> >]
                 auto iter_move(iterator_t<Rng> it) const
                      ^~~~~~~~~
/home/mi/h4nn3s/devel/seqan3/test/../range-v3/include/range/v3/view/transform.hpp:86:22: note:   no known conversion for argument 1 from 'const seqan3::detail::random_access_iterator<const seqan3::detail::view_join_ra<seqan3::dna5&> >' to 'ranges::v3::iterator_t<seqan3::detail::view_join_ra<seqan3::dna5&> > {aka seqan3::detail::random_access_iterator<seqan3::detail::view_join_ra<seqan3::dna5&> >}'
```

If I give up on propagating the `&` through my view altogether and instead generate copies of the value_type and can therefore always use the const_iterator, it all "works":
```cpp
    using iterator          = random_access_iterator<view_join_ra const>;
    using const_iterator    = random_access_iterator<view_join_ra const>;
    using value_type        = std::remove_reference_t<ref_t>;
    using reference         = value_type;
    using const_reference   = value_type;
```

But, of course, I do want to propagate the `&` if possible! What am I doing wrong? Or what assumptions does range-v3 have on views that are not listed in the concept?

**Comment by CaseyCarter** [comment]
You also need to strip cv-qualifiers from your `value_type`:
```c++
using value_type = std::remove_cv_t<std::remove_reference_t<ref_t>>;
```
and note that `std::is_lvalue_reference_v<T>` implies `std:is_same_v<T, std::add_const_t<T>>` (["If `T` is a reference, function, or top-level `const`-qualified type, then `type` names the same type as `T`, otherwise `T const`."](http://eel.is/c++draft/meta.trans.cv#tab:type-traits.const-volatile)) so `const_reference` is always the same type as `reference`.

From a design perspective: It's weird for a type `T` that models `View` to have differing valid range behaviors for `T` and `T const`. "Weird" is obviously not the same as "forbidden," but it wouldn't surprise me  if this expectation had leaked into the range adaptor machinery somewhere.

**Comment by h-2** [comment]
Thanks for the hints, I wasn't aware that `std::add_const<int&>` is not `int const &`, but `int &` (which I think is kinda awkward, but oh well).

I have changed the type definitions to:
```cpp
    using iterator          = random_access_iterator<view_join_ra>;
    using const_iterator    = random_access_iterator<view_join_ra const>;
    using value_type        = std::remove_cv_t<std::remove_reference_t<ref_t>>;
    using reference         = ref_t;
    using const_reference   = std::conditional_t<std::is_lvalue_reference_v<ref_t>, value_type const &, value_type>;
```

But I see the same errors.

> From a design perspective: It's weird for a type T that models View to have differing valid range behaviors for T and T const. 

Hm, I don't understand your point. I want the following, which I thought other views like ranges::view::reverse in range-v3 do internally as well:

| `reference` of input range | `value_type` of returned range | `reference` of returned range | `const_reference` of returned rage |
|---|---|---|---|
| char | char | char | char
| char & | char | char & | char const & |
| char const & | char | char const & | char const & |

The `const_iterator` on the other hand is just a an iterator that always delegates to the range's `const_reference` instead of the range's `reference`. How is this behaviour unusual?

**Comment by ericniebler** [comment]
> which I thought other views like `ranges::view::reverse` in range-v3 do internally as well:

You could test `ranges::view::reverse` and see that your assumption is incorrect.

```c++
std::vector<int> v{1,2,3,4};
auto rv = v | view::reverse;
*rv.begin() = 42; // mutable

auto const & crv = rv;
*crv.begin() = 4; // still mutable
```

When you think "View", think "pair of iterators". Internally, the `reverse` view is storing a pair of `vector` iterators. It is not storing a copy of the data -- that would make it a Container. As a pair of iterators, the const-ness of the view doesn't effect the const-ness of the iterator's reference type.

Iterators, and by extension views, represent an indirection. With respect to `const` they behave like all indirections do in C++: by ignoring it. Consider:

```c++
int i = 0;
int *pi = &i;
*pi = 42; // mutable
int *const cpi = pi;
*cpi = 0; // still mutable
```

Containers, on the other hand, do _not_ represent an indirection. They represent a value. `const`, when applied to a value, is _not_ ignored. That's why containers have `iterator` and `const_iterator` as separate types with separate semantics.

Hope that helps.

**Comment by CaseyCarter** [comment]
There are mutable-only view types `T` in range-v3 for which `const T` does not satisfy `Range`; those types are sensitive to `const` after a fashion. There are no view types `T` such that `T` and `const T` *both* satisfy `Range` but with differing iterator types `iterator_t<T>` and `iterator_t<T const>`.

**Comment by h-2** [comment]
@ericniebler Thanks for pointing this out again, I was aware of the general situation and remember your examples from the other discussions, but I didn't internalize the implications for writing my own view. I now have `iterator` == `const_iterator` and `reference` == `const_reference` and everything seems to work fine.

@CaseyCarter Yep, I understand now. My view is not supposed to be mutable-only, and I didn't actually want different behaviour for with and without const.
