### ISSUE TITLE
Allow injecting variables into comprehension

### ISSUE THREAD

**Issue by pfultz2** [ericniebler/range-v3#71]
Right now, if I try to write a function that returns the unique items like this:

``` c++
template<class Range>
auto unique_items(Range& r)
{
    std::unordered_set<range_value_t<Range>> values;

    return view::for_each(r, [=](auto&& x) mutable
    {
        return yield_if(values.insert(x).second, x);
    });
}


int main()
{
    std::vector<int> ints = { 1, 1, 2, 3, 1, 2, 4, 5, 5 };
    auto unique_ints = unique_items(ints);
    std::cout << "First: " << std::endl;
    RANGES_FOR(int i, unique_ints)
    {
        std::cout << i << std::endl;
    }

    std::cout << "Second: " << std::endl;
    RANGES_FOR(int i, unique_ints)
    {
        std::cout << i << std::endl;
    }
}
```

The first loop prints the unique items, but the second time it iterates its empty. Of course, this is partly due to using a `mutable` lambda. It would nice to be able to inject variables and not have to use a `mutable` lambda, perhaps write something like a `let` mechanism:

``` c++
template<class Range>
auto unique_items(Range& r)
{
    return view::for_each(r, 
        []{ return std::unordered_set<range_value_t<Range>>(); }, 
    [=](auto&& x, auto& values)
    {
        return yield_if(values.insert(x).second, x);
    });
}
```

I not sure the best way to write it would be.

Or perhaps, there is another way where the range could be made lazy, although a `mutable` lambda would still be needed:

``` c++
template<class Range>
auto unique_items(Range& r)
{
    return lazy_range([&]
    {
        std::unordered_set<range_value_t<Range>> values;

        return view::for_each(r, [=](auto&& x) mutable
        {
            return yield_if(values.insert(x).second, x);
        });
    });
}
```

**Comment by pfultz2** [comment]
So I realized later that I can accomplish this already in the library by doing this:
```cpp
template<class Range>
auto unique_items(Range& r)
{
    using value_set=std::unordered_set<range_value_t<Range>>;

    return view::for_each(yield(value_set{}), [&](auto values) 
    {
        return view::for_each(r, [&, values](auto&& x) mutable
        {
            return yield_if(values.insert(x).second, x);
        });
    });
}
```

Now the parameter to the lambda must be by value or else you get a confusing compile error, and you must capture by value or else it will seg fault, but doing this will work. Perhaps the library could provide a `let` function for this, which in addition could handle references(currently it always by value).

**Comment by ericniebler** [comment]
This is clever. Let me think about this.
