### ISSUE TITLE
action, view, ... and factory?

### ISSUE THREAD

**Issue by morinmorin** [ericniebler/range-v3#719]
How about making a new directory <tt><include/ranges/v3/**factory**></tt> that contains headers for things that create ranges and start pipe chains? This would make searching a header easier.

Here is a list of candidate headers: 
- From `<include/ranges/v3/view>`,
  - `empty.hpp`
  - `iota.hpp`
  - `generate.hpp`
  - `generate_n.hpp`
  - `repeat.hpp`
  - `single.hpp`
- From `<include/ranges/v3>`,
  - `getlines.hpp`
  - `istream_range.hpp`

`iterator_range.hpp` might also be a candidate.

**Comment by h-2** [comment]
I would rather add a documentation entry that designates some views as "source" implying that they can only be at the beginning of a pipe.
Conversely, one could also add "sink", see #652.

**Comment by morinmorin** [comment]
> I would rather add a documentation entry that designates some views as "source" implying that they can only be at the beginning of a pipe.

Hm, that's not what I'm hoping for. I don't think `generate` is a view; but maybe my understanding that views are range-adaptors is wrong...

**Comment by CaseyCarter** [comment]
> I don't think `generate` is a view; but maybe my understanding that views are range-adaptors is wrong...

A `Range` is an object `r` such that `ranges::begin(r)` and `ranges::end(r)` are valid expressions with return types that satisfy the `Sentinel` concept.

A `View` is an object `v` whose type satisfies the `Range` and `SemiRegular` (default construction, and copy/move construction/assignment) concepts, and for which all of the operations used by the `Range` and `SemiRegular` concepts have amortized O(1) complexity.

Everything listed in the OP is a `View` by that definition.

**Comment by ericniebler** [comment]
There is a bit of an inconsistency in the current organization. `view::ints`  is properly a `View`, but something like `view::join` is not. It is an adaptor that operates on `View`s and returns `View`s. And `view::generate` turns a callable into a `View` and cannot have a `View` piped into it, like `view::join` can.

So the OP had a point, but I am not convinced that a different organization would be an improvement. These are all utilities that are closely related to `View`ness. Putting them together doesn't feel wrong to me. On the contrary, scattering them might make the structure of the library harder to grok.

**Comment by morinmorin** [comment]
OK, I understand what View is. `generate` is View as well as "factory", so it would be hard to make clean organization. 

> scattering them might make the structure of the library harder to grok.

For developers and intensive library users, I agree with this. At the same time, I think functionality-based organization (i.e. `action`, `adaptor` and `factory`) would work well for casual library users.

Anyway, thanks for the explanations, Casey and Eric!

Regards,
Michel

**Comment by h-2** [comment]
I liked to add to this, as I think there are some sources for confusion. For any of the view that don't piggyback on another view,  there is (simplified):

```cpp
struct view_foo { ...};

struct foo_fn { ... }; // operator() returns a view_foo

operator|(Rng, foo_fn) { ... } // calls foo_fn's operator() or returns view_foo directly

foo_fn view::foo; // instance of foo_fn
```

By definition a `view` is the first thing, it is the actual type that satisfies the view concept. What most people *perceive* as "the view" is `view::foo` – which isn't a type, it's an instance; and not even of the view. I understand this design now and it makes sense, but it also confuses people, because of terminology.
I have no good solution for this problem, but maybe one could consider calling `view::foo` a "view-producer" or "view-generator", because that's what it does – independent of where in the pipe it can occur. [I don't suggest changing the namespaces or folders, this is purely for the documentation]

**Comment by morinmorin** [comment]
Since the Standard now has "factories" (cplusplus/draft#2619), can range-v3 have `factory.hpp` too?
