### ISSUE TITLE
range_value_type vs value_type (and others)

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#722]
With the release of 0.2.0 the iterator metafunctions were renamed to not contain iterator in the name which is good IMHO. But why not just use the same metafunctions for iterators and ranges where applicable?

The intuition is that since
```cpp
foo::value_type -> value_type[_t]<foo>
```
Independent of what foo is.

And the confusing part is, that this actually works for containers (I guess because they actually provide the member type), but it doesn't work for e.g. views which require `range_value_type[_t]`...

What is the reason for the distinction? And if it is just a legacy, could it be changed? I think it would really improve the metaprogramming with range-v3.

Thanks!

P.S: If you agree with the proposal I could make a PR to unify this and preserve the old metafunctions marked as deprecated.

**Comment by ericniebler** [comment]
There was a time when the metafunctions behaved that way, curtesy of @CaseyCarter. It turned out to cause hard errors in some situations, and so the change was backed out.

**Comment by h-2** [comment]
> There was a time when the metafunctions behaved that way, curtesy of @CaseyCarter. It turned out to cause hard errors in some situations, and so the change was backed out.

Really? Wow, I wouldn't know why, but if it is was tried and broke I guess there is nothing to be done. For what it's worth, in this case I feel that having `value_type` be on only for iterators (and containers?) and `range_value_type` be for ranges is inconsistent, but oh well.
