### ISSUE TITLE
Why does the stored range in `view_adaptor` need to be mutable?

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#726]
[`view_adaptor`]() has the following data member:

```c++
            // Mutable here. Const-correctness is enforced below by disabling
            // begin_cursor/end_cursor if "BaseRng const" does not model
            // the View concept.
            mutable base_range_t rng_;
```

I've been trying to understand why this isn't implemented as:

```c++
            base_range_t rng_;
            base_range_t & mutable_base() const
            {
                return const_cast<base_range_t&>(rng_);
            }
```

without much luck (the comment doesn't really help). Making the member `mutable` allows modifying `rng_` even if `view_adaptor` is stored in a const object without introducing undefined behavior. However, modifying the `rng_` object from a `const` method without synchronization is unsafe. Since `const` views are close to useless, I also wonder why this matters.

---

To put this in context, `mutable` data members cannot be accessed by constexpr methods, so this prevents many views from being usable in `constexpr` contexts.

**Comment by gnzlbg** [comment]
The `view_adaptor::mutable_base` method is only used inside `adaptor`s `const`-methods (`satisfy`, `next`, `begin`, ...). I would expect all these methods to mutate the adapted view, so I don't understand why they must be const either.

**Comment by ericniebler** [comment]
Mutating a variable after casting away const is undefined behavior. The whole `mutable_base` thing is a hold-over from a time when I believed that views _always_ have the same iterator type for const and non-const access. This is not always true. In the cmcstl2/range-adaptors-ts branch, I'm doing a clean-room redesign of the views, and I'm embracing views with different const and non-const iterators.

**Comment by gnzlbg** [comment]
I will hold constexpr views until that is done then. I agree that doing the
redesign there is time better spent, and  we can always backport the
redesign here once it solidifies.

I'd just add that if you are going to redesign the views, almost all of
them can run inside constexpr function in C++14. It would be easier to make
them constexpr friendly from the start in a redesign than to try to make
them constexpr later.
