### ISSUE TITLE
ranges::upper_bound predicate requirements

### ISSUE THREAD

**Issue by Predelnik** [ericniebler/range-v3#747]
If I have range of `std::pair<int, int>` and I want to use `upper_bound` with `int`. For normal `std::upper_bound` I just need to provide predicate less between an `int` and a `pair<...>` but it seems like `ranges::upper_bound` doesn't want neither of two possible comparisons (http://coliru.stacked-crooked.com/a/703c3679628c0ba6). 

Should I provide overloaded comparison like for `std::equal_range`? If so, doesn't it diminish simplicity in applying `upper_bound`?

**Comment by ericniebler** [comment]
You should just use `less<>` as the predicate, but provide `&pair<int,int>::first` (or `second`) as a projection (extra argument after the predicate).

**Comment by Predelnik** [comment]
Thanks! Now it makes sense.
