### ISSUE TITLE
range:: algorithms with custom comparators.

### ISSUE THREAD

**Issue by john-preston** [ericniebler/range-v3#749]
Perhaps I didn't understand the idea, sorry for that. I tried to use ranges::lower_bound() as a drop-in replacement for std::lower_bound(begin(..), end(..)) and I couldn't make things work with custom comparators:
```
struct int_wrap {
	int value;
};
struct int_wrap_comparator {
	using is_transparent = void;
	bool operator()(const int &lhs, const int &rhs) const { return lhs < rhs; }
	bool operator()(const int_wrap &lhs, const int &rhs) const { return lhs.value < rhs; }
	bool operator()(const int_wrap &lhs, const int_wrap &rhs) const { return lhs.value < rhs.value; }
	bool operator()(const int &lhs, const int_wrap &rhs) const { return lhs < rhs.value; }
};
struct int_wrap_projection {
	const int &operator()(const int_wrap &other) const {
		return other.value;
	}
};
void test() {
	std::vector<int_wrap> v;
	auto i = std::lower_bound(std::begin(v), std::end(v), 0, int_wrap_comparator()); // works
	auto j = ranges::lower_bound(v, 0, int_wrap_comparator()); // doesn't work
	auto k = ranges::lower_bound(v, 0, std::less<>, int_wrap_projection()); // works
}
```
As I understood this should be done with projections. But what if I have a std::vector of types T and a custom comparator that can compare them in any ways with some unrelated type U - is there a way to perform binary search on that vector by a value of type U?

My example is a custom container class of type T that has a template argument C - comparator (possibly transparent) for T (so I can't write projections for the users of that container class) and internally I use lower_bound() in some implementation methods - is there a way to use ranges::lower_bound method instead of std:: there?

Or generic code that currently takes as arguments only custom comparators, but not projections, can't use ranges:: algorithms instead of std::?

**Comment by ericniebler** [comment]
Custom comparitors like that don't work in the Ranges TS. You'll need to restructure your code to pass a comparitor and a projection.

**Comment by john-preston** [comment]
I see, thanks.
