### ISSUE TITLE
Automatic conversion of views to aggregate containers

### ISSUE THREAD

**Issue by akreuzkamp** [ericniebler/range-v3#754]
It seems to me like a missing piece in the puzzle, that the range-v3 library can't convert views to aggregate containers like std::array or C-arrays (neither using ranges::to_ nor implicitly).

I'm not sure, how one could implement such a thing though. Maybe a possible implementation would be to use something like availability of std::tuple_size<Cont> to check for fixed-sized containers and if so, just default-construct the container and then copy the range into it.

Especially, I'm interested in converting a range of ranges into an std::array of std::arrays.

**Comment by gnzlbg** [comment]
The user would need to provide the type that a view should convert to, e.g. an array or a tuple, and we could pattern match that and see if the size of the range matches.

The size would need to match exactly, e.g., if you provide a 9 element array, but the range only has 8 elements, we cannot convert the range to the array. This also means that providing a container with the wrong size is probably a logic error, so we would need to throw an exception. 

All in all looks like a lot of work, why do you need this?

**Comment by akreuzkamp** [comment]
I was playing around with using range-v3 in grid-based numerical calculations/simulations. There I used a std::array of std::arrays because using dynamically resizing containers wouldn't really make sense there (the grid is there a priori, it doesn't make sense to add or remove grid points, you only fill them). When I start using it for real world use cases I'm probably going to use my own specialized container classes, for which I can implement the required interfaces.

Still it kind of massively reduces the coolness factor, if it doesn't Just Work™ at least for all standard-containers. Every now and then I'm trying to convince some of my python-using colleagues that C++ is worth a try. range-v3 (especially if part of the standard) would massively halp with that. But then in turn if std::arrays and C-Arrays aren't just fully supported, that would spoil the party quickly...

So even, if it's only for the PR, it seems like a must-have to me.

**Comment by ericniebler** [comment]
> But then in turn if std::arrays and C-Arrays aren't just fully supported, that would spoil the party quickly

C-style arrays cannot be supported under any circumstances. They are not move constructible. 

`std::array`s can be supported with sufficient effort, but like @gnzlbg says, we have the difficulty of what to do when the cardinality exceeds the capacity of the `array`. I don't like that the best possible answer AFAICT is "throw an exception". It encourages unsafe code.

I suggest you write your own helper function that converts a range to a `std::array`. That way, you get to say what happens on overflow.

**Comment by ericniebler** [comment]
> I suggest you write your own helper function that converts a range to a `std::array`. That way, you get to say what happens on overflow.

After more thought about this issue, I still feel that this is the best option here. Closing.
