### ISSUE TITLE
ranges::Swappable<int> vs std::is_swappable<int>

### ISSUE THREAD

**Issue by KVic** [ericniebler/range-v3#757]
Source code:
```cpp
#include <type_traits>
#include <range/v3/all.hpp>
#include <iostream>

template <class T>
concept bool GccSwappable =
    requires(T & a, T & b) {
        ranges::swap(a, b);
    };

int main()
{
    std::cout << std::boolalpha;

    std::cout << "std::is_swappable_v<int> = " << std::is_swappable_v<int> << std::endl;
    std::cout << "GccSwappable<int>        = " << GccSwappable<int>        << std::endl;
    std::cout << "ranges::Swappable<int>() = " << ranges::Swappable<int>() << std::endl;

    return 0;
}
```

Output:
```
std::is_swappable_v<int> = true
GccSwappable<int>        = true
ranges::Swappable<int>() = false
```

Who is right?

-----
GccSwappable  - [std::experimental::ranges::Swappable](http://en.cppreference.com/w/cpp/experimental/ranges/concepts/Swappable), [Working Draft, C++ Extensions for Ranges N4685](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4685.pdf) 7.3.11 Concept Swappable.

Test environment:
std=c++17

- std::is_swappable
- - g++ (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 7.2.0
- - Microsoft (R) C/C++ Optimizing Compiler Version 19.11.25547 for x86
- GccSwappable & ranges::Swappable
- - g++ (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 7.2.0

**Comment by CaseyCarter** [comment]
range-v3 has not yet implemented the changes that flowed into the Ranges TS via [P0651 "Switch the Ranges TS to Use Variable Concepts,"](https://wg21.link/p0651) including the change to make usage of the `Swappable`/`SwappableWith` concepts consistent with usage of the `is_swappable` / `is_swappable_with` traits. There's no way to get exactly the variable concept syntax (`Swappable<int>` with no `()`) without C++14 variable templates, and range-v3 must compile with C++11.

I'm sure we don't want to drop C++11 support in range-v3 at this time, but it would probably make sense to bring the concepts more inline with P0651, e.g., split the "old" `Swappable<T, U>` out into `Swappable<T>` and `SwappableWith<T, U>` even if users would still need to specify the `()` to use them.

**Comment by KVic** [comment]
Thanks for the explanation! And sorry for the short and ambiguous question. I wanted to pay attention: `Swappable<int>` should be `true` or `false`? Regardless of the syntax.

**Comment by CaseyCarter** [comment]
> `Swappable<int>` should be `true` or `false`? Regardless of the syntax.

Before P0651, `Swappable<T>()` required `swap(declval<T>(), declval<T>())` to be a valid expression. In other words, if `swap(E1, E2)` is valid for subexpressions `E1` and `E2` such that `decltype((E1))` and `decltype((E2))` are both `T`. `Swappable<int>()` asks if two rvalues - expressions whose `decltype` is `int` - are swappable, which is not the case in C++.

After P0651, `Swappable<T>` requires `swap(declval<T&>(), declval<T&>())` to be a valid expression which is consistent with the `is_swappable` traits in the Ranges TS and C++17. Post-651 `Swappable<T>` is exactly equivalent to pre-651 `Swappable<T&>()`. (P0651 also renamed the old cross-type `Swappable<T, U>()` concept to `SwappableWith<T, U>`.) `Swappable<int>` asks if two lvalue expressions whose type is `int` are swappable, which *is* the case in C++.

**Comment by KVic** [comment]
Ok, thank you very much!
