### ISSUE TITLE
Update concepts per P0651 to agree with the TS

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/range-v3#759]
To avoid confusion as in #757. We cannot achieve the exact variable concept syntax `Concept<T>` / `ConceptWith<T, U>` in C++11, but we could certainly ensure that `Concept<T>()`/`ConceptWith<T, U>()` has the same semantics as in the Ranges TS.

See also #605.

**Comment by ericniebler** [comment]
This is done on the v1.0-beta branch. This change will not be made in master until I merge the v1.0-beta branch, so closing this as "fixed".
