### ISSUE TITLE
Adopt coronet's concepts sub-library

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/range-v3#768]
https://github.com/ericniebler/coronet has a concepts emulation layer that makes the usage look like:

```c++
CO_PP_template(class T)(
    requires CompletionToken<T>)
auto get_allocator(T t)
{
    return t.get_allocator();
}
```

This is arguably nicer than range-v3's `CONCEPT_REQUIRES_()` macro, and it permits an implementation in terms of real C++20 concepts.

Concepts in this system are defined like:

```c++
namespace concepts
{
struct CompletionToken
{
    template<class T>
    auto requires_(T t)
        -> decltype((t.get_executor()) ->* satisfies<Executor>,
                    (t.get_allocator()) ->* satisfies<Allocator>);
};
}
template<class T>
inline constexpr bool CompletionToken = is_satisfied_by<concepts::CompletionToken, T>;
```

This is also arguably nicer than range-v3's system.

**Comment by gnzlbg** [comment]
This is a pretty large breaking change. May I suggest doing a release before doing it?

**Comment by ericniebler** [comment]
The concept definitions are largely backwards compatible. Since I need to support C++11, I'll probably avoid variable templates. The only thing different is the macro, and I can keep the old one around for folks that are using it.

**Comment by gnzlbg** [comment]
I am also using the library to define my own concepts. IIUC those would be affected as well, right?

**Comment by ericniebler** [comment]
I might be able to do it in a way that is compatible. Do you use `concepts::refines<>`?

**Comment by gnzlbg** [comment]
> Do you use `concepts::refines<>`?

Yes.

> I might be able to do it in a way that is compatible.

I don't mind about my code breaking if I know it is going to break: I can fix a "good" commit before and when I have time do the upgrade to master (hence the suggestion to do a release before that I could target). In general it isn't a big deal when things break because it is typically a 10 minute thing and the latest commits make clear what happen. 

But in this case I suspect it is going to take me a bit longer and I'd rather not be surprised by it (e.g. waking up and seeing all the CI red because of it).

**Comment by h-2** [comment]
> This is arguably nicer than range-v3's CONCEPT_REQUIRES_() macro, and it permits an implementation in terms of real C++20 concepts.

Does this mean we might soon get a range-v3 version that actually runs with C++20 concepts or the Concepts TS soon? 😍

**Comment by ericniebler** [comment]
> Does this mean we might soon get a range-v3 version that actually runs with C++20 concepts 

It's a step in that direction.

**Comment by ericniebler** [comment]
Related: I have a macro that lets me define pseudo-concepts in C++11 like:

```c++
CONCEPT_def(
    template(typename T, typename U),
    concept Assignable,
        requires (T t, U &&u) {
            (t = (U &&) u) ->* Same<_&&, T>()
        } &&
        True<std::is_lvalue_reference<T>>()
);
```

Not too shabby, IMO.
