### ISSUE TITLE
Can't compile view_facade that produces vectors

### ISSUE THREAD

**Issue by etam** [ericniebler/range-v3#772]
I want to write a range that for given vector produces a range of vectors with all possible permutations.

Here's what I've come up with:

```c++
#include <vector>
#include <range/v3/all.hpp>


class AllPermutations
    : public ranges::view_facade<AllPermutations>
{
private:
    friend struct ranges::range_access;
    std::vector<int> mRange;
    bool mIsLast = false;

    const std::vector<int>& read() const
    {
        return mRange;
    }

    bool equal(ranges::default_sentinel) const
    {
        return mIsLast;
    }

    void next()
    {
        mIsLast = !ranges::next_permutation(mRange);
    }

public:
    AllPermutations(const std::vector<int>& range)
        : mRange{range /* | ranges::action::sort */}
    {}
};


int main()
{
    const auto v = std::vector<int>{1,2,3};
    auto p = AllPermutations(v);
}
```

I tried compiling this with
- ranges
    - 0.3.0
    - master 4ade4af
- compilers
    - g++ (SUSE Linux) 7.2.1 20180116 [gcc-7-branch revision 256737]
    - clang version 5.0.1 (tags/RELEASE_501/final 312548)

Results:
[clang-0.3.0.log](https://github.com/ericniebler/range-v3/files/1653629/clang-0.3.0.log)
[clang-4ade4af.log](https://github.com/ericniebler/range-v3/files/1653630/clang-4ade4af.log)
[gcc-0.3.0.log](https://github.com/ericniebler/range-v3/files/1653631/gcc-0.3.0.log)
[gcc-4ade4af.log](https://github.com/ericniebler/range-v3/files/1653632/gcc-4ade4af.log)

**Comment by CaseyCarter** [comment]
This unconstrained, implicit container constructor:
```c++
AllPermutations(const std::vector<int>& range)
```
is the problem: I believe it's hitting constraint recursion when this declaration:
```c++
auto p = AllPermutations(v);
```
triggers overload resolution for the copy-initialization of `p` from the prvalue `AllPermutations(v)`. The compiler sees that the implicitly-defined copy and move constructors are viable, but checking the `AllPermutations(const std::vector<int>&)` constructor for viability requires determining if there's an implicit conversion sequence from `AllPermutations` to `const std::vector<int>&` which requires checking...

This belief is reinforced by the fact that the sample program compiles fine as C++17 (https://godbolt.org/g/YRoG3i) with guaranteed copy elision. I think you can avoid the problem pre-C++17 by making your constructor `explicit` (https://godbolt.org/g/Q75pNb).

**Comment by etam** [comment]
Right! How could I forget about explicit constructor?

Anyway, now with this code:

```c++
#include <iostream>
#include <vector>
#include <range/v3/all.hpp>


class AllPermutations
    : public ranges::view_facade<AllPermutations>
{
private:
    friend struct ranges::range_access;
    std::vector<int> mRange;
    bool mIsLast = false;

    const std::vector<int>& read() const
    {
        return mRange;
    }

    bool equal(ranges::default_sentinel) const
    {
        return mIsLast;
    }

    void next()
    {
        mIsLast = !ranges::next_permutation(mRange);
    }

public:
    explicit
    AllPermutations(const std::vector<int>& range)
        : mRange{range /* | ranges::action::sort */}
    {}
};


int main()
{
    const auto v = std::vector<int>{1,2,3};
    auto allPerms = AllPermutations(v);
    ranges::for_each(allPerms, [](auto perm) {
        for (auto i : perm) {
            std::cout << i << ',';
        }
        std::cout << '\n';
    });
}
```

here are results:
[clang-0.3.0.log](https://github.com/ericniebler/range-v3/files/1657008/clang-0.3.0.log)
[clang-4ade4af.log](https://github.com/ericniebler/range-v3/files/1657009/clang-4ade4af.log)
[gcc-0.3.0.log](https://github.com/ericniebler/range-v3/files/1657010/gcc-0.3.0.log)
[gcc-4ade4af.log](https://github.com/ericniebler/range-v3/files/1657011/gcc-4ade4af.log)

**Comment by etam** [comment]
It was not easy to understand from output, but I've found that view_facade expects the deriving class to be default constructible.

I don't know if it's possible to get better error messages. If you think it's good enough you can close this issue.

**Comment by CaseyCarter** [comment]
> It was not easy to understand from output, but I've found that view_facade expects the deriving class to be default constructible.

The first error in the Clang log "no type named 'type' in `concepts::most_refined</*...*/ range_access::Cursor>`" is trying to tell you that your type doesn't model any of the `Cursor` concepts, which is necessary for `basic_iterator` to wrap it up as an iterator. Views/Iterators/Cursors are all `Semiregular`, and therefore necessarily `DefaultConstructible`.

**Comment by ericniebler** [comment]
Error messages are hard when we can only emulate concept checking. Closing this...
