### ISSUE TITLE
Weird crashes when using transform views...

### ISSUE THREAD

**Issue by seertaak** [ericniebler/range-v3#773]
First off, thanks for the wonderful library -- it's amazing what this has done for the readability of my code!

My situation is as follows. Our UI library is for historical reasons inheritance-driven. There is a base class called `zui::node` and this class makes available its children via a method called `child_pointers()`; returning a `std::vector<std::shared_ptr<zui::node>>`. A much higher level class called `track_node` (which is-a `zui::node`) uses the children as storage for `RegionNode`s (which are also `zui::nodes`). 

I would like to make those available through an API that doesn't require `std::static_pointer_cast` at the point of use. In addition, since the storage for children is polymorphic, I store another type of `zui::node`, at index zero. In other words, typically the children of a `track_node` look like this:

    { track_leader, region0, region1, ...}

This means I need to skip the first child, and cast the rest from `std::shared_ptr<zui::node>` to `std::shared_ptr<RegionNode>`. Here's my attempt to do this with range-v3 (for `namespace rs = ranges; namespace rsv = rs::view`):

      auto regions() {
            return rsv::all(child_pointers()) | rsv::tail | rsv::transform(
                       [](auto& cp) { return std::static_pointer_cast<RegionNode>(cp); });
        }

Am I doing something fundamentally wrong? If use this within code:

    auto rng = some_track_node.regions();
    for (auto&& region_ui: rng) { /* use region node */ }

is this expected to work?  Or am I only allowed to use the range constructed through the above within the regions() function? I get crashes when I attempt to use the `rng`; it's as if something goes out of scope and I'm trying to freed memory. FYI I was doing something similar to this using `boost::range` library, and it worked ok, so I was a little surprised that this caused a problem. 

(By the way, I tried without the call to `rsv::all()` which seems to work, so I'm also unclear as to the purpose of that function.)

**Comment by seertaak** [comment]
Oh man. This was totally my fault, I apologize for wasting your time. My remark about the awesomness of the library stands and so does my question about `rsv::all`, which I still don't totally get.

**Comment by ericniebler** [comment]
`view::all` returns a View that contains all the elements in the Range. A Range is anything with a begin/end iterator/sentinel pair (e.g., a container). A View is generally a non-owning Range (e.g., a pair of iterators).

So `view::all(r)` returns `r` is `r` is already a View; otherwise, it returns essentially `[begin, end)`.

Hope that helps.
