### ISSUE TITLE
Beginner's questions about range-v3.

### ISSUE THREAD

**Issue by xfbs** [ericniebler/range-v3#774]
The simplicity and elegance is what has brought be to use `range-v3`, but I have a few questions that I don't know where else to ask:

1. Is there a convenience method to get the first element (or nth element) of a range? I wasn't able to find anything in the documentation. For example, something like:

```cpp
auto odd_perfect_square = first_element(
  view::ints
  | view::transform([](int a){return a * a;}) // make perfect squares
  | view::filter([](int a){return a % 2 == 1;}) // keep odd ones
  | view::drop_exactly(2) // we don't care about 1 and 9
);
assert(odd_perfect_square == 25);
```

2. What is `ranges::v3::dangling` all about?

With this code I need to call `.get_unsafe()`:

```cpp
#include <range/v3/all.hpp>
using std::cout;
using std::endl;
using namespace ranges;

auto doub = [](int i) -> int { return 2 * i; };

int main() {
  auto e = find_if( view::ints(1) | view::transform(doub), is_six );
  cout << "find-six: " << *e.get_unsafe() << endl;
}
```

Whereas with this code I don't:

```cpp
#include <range/v3/all.hpp>
using std::cout;
using std::endl;
using namespace ranges;

auto doub = [](int i) -> int { return 2 * i; };

int main() {
  auto candidates = view::ints(1) | view::transform(doub);
  auto e = find_if( candidates, is_six );
  cout << "find-six: " << *e << endl;
}
```

Does that mean that the first code example (where I have to call `get_unsafe()`) is wrong? Is the second example more idiomatic?

Cheers and thanks in advance, 
Patrick.

**Comment by xfbs** [comment]
Update: ignore question #1, I found [`ranges::front(rng)`](include/range/v3/front.hpp), which returns `*begin(rng)` which is the first element of the range 👍

**Comment by ericniebler** [comment]
For (2), with the first example, you are passing a temporary range to an algorithm that is returning an iterator into that range. `get_unsafe` is telling you that there is a high likelihood that the iterator is no longer valid.

The second case does not suffer from that problem. Prefer the second.
