### ISSUE TITLE
Proposal: add accumulate algorithm

### ISSUE THREAD

**Issue by seertaak** [ericniebler/range-v3#787]
Maybe I'm wrong, but I think `range::transform` can't be used to collapse a range of values to a single value given some binary operation -- it's designed to output iterators/ranges. 

The canonical example of what I would like to do is:

    auto xs = rsv::iota(0, 100) | rs::to_vector;
    auto sum = std::accumulate(begin(xs), end(xs), 0, plus<int>()); // <-- makes me sad.
    /* use sum */

It should be obvious what the range-v3 equivalent ought to be. Is there a reason this is not in the library?

I keep saying this but literally range-v3 is taking over my codebase and it's a night and day difference. I will make a blog post soon, and sing the paeans for this wonderful library.

**Comment by CaseyCarter** [comment]
Does the `ranges::accumulate` algorithm suffice?

```c++
#include <range/v3/numeric.hpp>
/* ... */
auto sum = ranges::accumulate(rsv::iota(0, 100), 0);
assert(sum == 100 * 99 / 2);
```

**Comment by seertaak** [comment]
Ah, it's in numeric. Makes sense -- sorry I missed that.
