### ISSUE TITLE
Possible bug in dealing with input ranges defined independently of range-v3

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#791]
I am working on a Tutorial for writing custom Views. I am doing this for the other developers in my group, but had also planned on publishing in on my blog for whoever is interested.

The goal is to create a complete view, not just re-using existing views and I want to do so without reusing internal bits of range-v3. One reason for that is that the internals will likely change, and the other is that it takes another month of teaching to explain the internals of range-v3 ;-) Also in the medium term it should work with C++20 Ranges so I don't want to rely on internal range-v3 stuff too strongly.

In any case, this is the code:
https://gist.github.com/h-2/7e47a038f3eb56cbdf4820979a373584 [`view::add_number`]

I hope the code is understandable; I am implementing a view that gets passed a number that it adds to all elements when iterated over. Obviously this could easily be done by just reusing transform, but, as I said, I am trying to make self-sufficient example that explains all constructs involved (lengthy explanations now stripped from the code). To keep the code small I just want to provide an InputRange + View interface, no other fancy things required.

In the above example I test all relevant concepts on the iterator of the range and range itself, they all pass. Then I test three things:

1. `std::cout << *(view::add_number(42)(in).begin()) << '\n';`
2. iterating over a view
3. piping my view into `ranges::view::take` to check whether it is chainable.

No 1. and 2. succeed with GCC7, but 3. fails; it prints three garbage uints. If I don't manually set `ranges::disable_sized_range` an assertion actually fails in your library somewhere; range-v3 seems to assume sizedness for some reason (and then fails to compute the size). 

As you can see in the code I have tried with two different "minimal" InputIterators definitions, it fails with both. Peculiarly a slightly modified example works without problems:
https://gist.github.com/h-2/430456b7f83ced8fee0b036513581692 [`view::add_constant`]
(It's mostly the same, except that you can't specifiy the number to be added, it always adds `42`; the only structural difference is that `operator|` doesn't have to go through `std::bind`)

**And** if I implement a sized random access iterator on my view_add_number, instead of just an InputIterator, everything also works as expected. So it does look like a bug to me, but maybe I am also overlooking something :thinking: 

Thanks for your help!

**Comment by CaseyCarter** [comment]
The [`view_add_number(irng_t, uint64_t)` constructor](https://gist.github.com/h-2/7e47a038f3eb56cbdf4820979a373584#file-range_add_number-cpp-L108) binds a reference inside `data_members_t` to its by-value parameter which will dangle after the corresponding argument is destroyed. I think it's unspecified whether that happens immediately after the constructor returns or at the end of the full-expression that invokes the constructor, but in any case that reference is dangling the next time you access it.

The reason range-v3 view adaptors are *view* adaptors instead of *range* adaptors is so that we can store the base view directly in the adapting view and avoid lifetime and memory allocation issues like this.

**Comment by h-2** [comment]
> The view_add_number(irng_t, uint64_t) constructor binds a reference inside data_members_t to its by-value parameter which will dangle after the corresponding argument is destroyed. 

Wow, how did that happen :man_facepalming:
Too much work, too little caffeine. :expressionless: 

> The reason range-v3 view adaptors are view adaptors instead of range adaptors is so that we can store the base view directly in the adapting view and avoid lifetime and memory allocation issues like this.

Yep, I realised that, although it is an implementation choice, not something suggested by the TS/standard, right? I do see that the behaviour will actually be different, because my views would accept  container-temporaries as initial input while yours don't. And for views that are not read-only I need to make a distinction anyway, too (capturing view temporaries by copy / `&&` and regular range lvalues by `&`). So I might switch to your model for consistency.

**Comment by ericniebler** [comment]
The TS requires that `View` copy/move operations are constant time. If your view aggregates a container by value, it is no longer a `View`.

**Comment by h-2** [comment]
> The TS requires that View copy/move operations are constant time. If your view aggregates a container by value, it is no longer a View.

It aggregates the underlying range (container or not) within a `shared_ptr` so copy and move are still constant.
