### ISSUE TITLE
Why is there a difference of calling signatures between `transform` into another range by `ranges::transform` and by `view::transform`?

### ISSUE THREAD

**Issue by denchat** [ericniebler/range-v3#797]
Shouldn't `ranges::transform` and `view::transform` have the same calling signature? Why?
```
    auto vec = std::vector<int>{ 100 };
    auto vec_back_inserter = ranges::back_inserter(vec);

    auto strs = std::vector{ "200"s, "300"s, "400"s, "500"s };

    auto stoi_unary = [](const auto& str) { return std::stoi(str); };  

    // this is okey.
    ranges::transform(strs | ranges::view::take(2), 
                      vec_back_inserter,
                      stoi_unary);

    /* same signature but won't compile, why?
    strs | ranges::view::take(2) 
         | ranges::view::transform(vec_back_inserter, stoi_unary);
    */
```
[godbolt.org/g/z5R1eX](https://godbolt.org/g/z5R1eX)

**Comment by ericniebler** [comment]
The range adaptors, like `view::transform`, do not write their result into output iterators. They return adapted ranges so that operations on them chain.

**Comment by gnzlbg** [comment]
FWIW you can just `| action::copy(output)` to traverse the view copying the results into the output.

**Comment by denchat** [comment]
@gnzlbg  could `action::copy` still make it these days?
```
error: no member named 'copy' in namespace 'ranges::v3::action'
```
[godbolt.org/g/3oBZNp](https://godbolt.org/g/3oBZNp)

Perhaps, that's the way it is, i guess.

When somethings so lazy at theirs nature that you can't even expect any result until the moment you _**actually**_ pull from it one by one, so assigning them to interact with another entity _**ahead of time**_ just doesn't make sense if not, even worse, _**a lie**_.

**Comment by gnzlbg** [comment]
My bad, `action::push_back` is used like this: https://godbolt.org/g/jYBcTn
You can also use `ranges::copy` w/o a back inserter:  https://godbolt.org/g/4QZvD9

I can't recall why `action::push_back` can't be used just as `rng | push_back(container);` (maybe had something to do with ownership), and I also can't recall why there isn't an `action::copy` (maybe nobody bothered implementing it).
