### ISSUE TITLE
Should view::c_str() have a version that takes an arbitrary length (Char* sz, N) also?

### ISSUE THREAD

**Issue by denchat** [ericniebler/range-v3#806]
Or should we absolutely avoid that?

In that context, should one go for `ranges::span<const char*, N>` instead?

What do you think?

This is related to https://stackoverflow.com/q/49134927

Apart from the aspect of arbitrary length convenience, I suspect that the N version might yield better assembly than the unreachable sentinel one?

Interestingly, when I try to fool it by reinterpret back to `char (*) [N]`, the compiler seems to ignore it completely and call the sentinel version anyway. Is it too lazy to do strlen at compile time?!.. Or the sentinel version is the winner assembly?!

    auto str = "the quick brown fox is jumping on a lazy dog\nthe quick brown fox is jumping on a lazy dog\n";
    auto& str2 = *reinterpret_cast<const char (*) [strlen(str)]>(str);
    ranges::for_each(ranges::view::c_str(str2), std::putchar);

This yield binary like the sentinel one :

	main:                                   # @main
			pushq   %rbx
			movb    $116, %al
			movq    $-90, %rbx
	.LBB0_1:                                # =>This Inner Loop Header: Depth=1
			movq    stdout(%rip), %rsi
			movsbl  %al, %edi
			callq   _IO_putc
			movzbl  .L.str+91(%rbx), %eax
			incq    %rbx
			jne     .LBB0_1
			xorl    %eax, %eax
			popq    %rbx
			retq
	.L.str:
			.asciz  "the quick brown fox is jumping on a lazy dog\nthe quick brown fox is jumping on a lazy dog\n"

Whereas, the N version

    auto& str = "the quick brown fox is jumping on a lazy dog\nthe quick brown fox is jumping on a lazy dog\n";
    ranges::for_each(ranges::view::c_str(str), std::putchar);

yields:

	main:                                   # @main
			pushq   %rbx
			movq    $-90, %rbx
	.LBB0_1:                                # =>This Inner Loop Header: Depth=1
			movsbl  .L.str+90(%rbx), %edi
			movq    stdout(%rip), %rsi
			callq   _IO_putc
			incq    %rbx
			jne     .LBB0_1
			xorl    %eax, %eax
			popq    %rbx
			retq
	.L.str:
			.asciz  "the quick brown fox is jumping on a lazy dog\nthe quick brown fox is jumping on a lazy dog\n"

If the sentinel version yields winner in assembly, why should `view::c_str()` have the N version also?

[godbolt.org/g/3oNw9w](https://godbolt.org/g/3oNw9w)

**Comment by ericniebler** [comment]
You want `view::counted`, I think.
