### ISSUE TITLE
Proposal. `make_empty`  for runtime?

### ISSUE THREAD

**Issue by tower120** [ericniebler/range-v3#815]
Consider following code:

```c++
bool is_empty;
std::vector<int> list;

auto get_range(){
   if (is_empty){
      return empty_range;
   } else {
      return list_range;
   }
}
```
`get_range` must return the same type on all paths. What possible to do currently is:
```c++
auto get_range(){
      return list_range 
             | view::drop( is_empty ? MAX_INT : 0 );
}
```

I do believe, that the following is possible:

```c++
auto get_range(){
      auto list_range = ...;

      if (is_empty) list_range.make_empty();
      return list_range;
}
```

I imagine that internal implementation of `make_empty` could be:
```c++
void make_empty(){
   begin_iter = end_iter;
}
```
`make_empty` applicable for views only.

----

If not as view member function, then maybe this:
```c++
auto get_range(){
      return list_range 
             | view::drop_all_if( is_empty);   // or with closure predicate
}
```

**Comment by ericniebler** [comment]
You can use `ranges::iterator_range` for this. It is just pair of iterators. You can initialize it however you like.
