### ISSUE TITLE
view::split does not accept functor predicate

### ISSUE THREAD

**Issue by bmanga** [ericniebler/range-v3#816]
The following code fails to compile with gcc 7.2, triggering a CONCEPT_ASSERT_MSG:
``` c++
template <char first, char ... rest>
struct any_of_chars
{
	bool operator() (char c) const {
		return c == first || ((c == rest) || ...);
	}
};
int main()
{
	std::string text = "aaa!bbb ccc";
	auto var = text | view::split(any_of_chars<' ', '!'>{});
}
```
Using `any_of_chars<' ', '!'>{}` in other views (such as `replace_if`) seems to work fine.

**Comment by CaseyCarter** [comment]
Works for me: https://wandbox.org/permlink/JEV8X7X303tyHLBF. Could you post a complete repro with a command line?

**Comment by bmanga** [comment]
I tried again this morning and somehow I can't seem to repoduce it anymore.
Really sorry about the noise!

**Comment by CaseyCarter** [comment]
> Really sorry about the noise!

Bugs we don't have to fix are the best kind!
