### ISSUE TITLE
single_view should not copy the value

### ISSUE THREAD

**Issue by ilyapopov** [ericniebler/range-v3#817]
Currently, `single_view` requires value type to be copy constructible, and copies it into itself. This, in my view, goes against the concept of view, which is not supposed to own values, but to refer to the original values. Thus I believe `single_view` should store a reference to original value.

**Comment by ericniebler** [comment]
I disagree. Many views own state. They must have O(1) copy and move, and `single_view` satisfies that requirement.

**Comment by ilyapopov** [comment]
But this places unnecessary requirements on the element type (one can't use it with non-copiable types). It is also a clear performance pessimization (copy can be expensive). If not changed, it should probably be renamed, since in the current form it is more of a container, rather than a view. 

Use case I had is: I have a generic function that takes a range of objects and processes them. But in one place I want to call this function with only one object. I considered passing a `single_view`, and was surprised by behavior, which is different from what I expect from a view, hence the issue.

**Comment by ericniebler** [comment]
That's merely a heuristic for guessing at the view-ness of a range. That heuristic cannot know that the single_view only holds one element.

**Comment by apmccartney** [comment]
@ilyapopov  As a work around, how about
```cpp
struct reference_single_view_fn {
  auto operator(const T& value) const {
    return ranges::view::single(&value) | ranges::view::indirect;
  }
};

static constexpr reference_single_view_fn reference_single_view{};
```

**Comment by ericniebler** [comment]
@CaseyCarter can you remind me why the `single_view` returns by value instead of by (`const`?) lvalue reference? It prevents `view::single` from working with move-only types.

**Comment by CaseyCarter** [comment]
No idea. `single_view`'s iterators are pointers in P0896:
```c++
template<CopyConstructible T>
  requires is_object_v<T>
class single_view : public view_interface<single_view<T>> {
private:
  semiregular<T> value_; // exposition only
public:
  single_view() = default;
  constexpr explicit single_view(const T& t);
  constexpr explicit single_view(T&& t);
  template<class... Args>
    requires Constructible<T, Args...>
  constexpr single_view(in_place_t, Args&&... args);

  constexpr T* begin() noexcept;
  constexpr const T* begin() const noexcept;
  constexpr T* end() noexcept;
  constexpr const T* end() const noexcept;
  constexpr static ptrdiff_t size() noexcept;
  constexpr T* data() noexcept;
  constexpr const T* data() const noexcept;
};

template<class T>
  explicit single_view(T&&) -> single_view<decay_t<T>>;
```

**Comment by ericniebler** [comment]
I like P0896's formulation better.

**Comment by CaseyCarter** [comment]
FWIW: `span<T, 1>` provides a good "reference to a single element" `View`, albeit one that is awkward to construct.

**Comment by ericniebler** [comment]
#918 makes `single_view` work with move-only types by returning by reference, as in P0896.
