### ISSUE TITLE
utility/safe_int.hpp and utility/any.hpp

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/range-v3#832]
.. are both unused leaf headers. Any reason not to get rid of them?

**Comment by ericniebler** [comment]
utility/safe_int.hpp should go. Probably utility/any.hpp as well. I don't know if anybody is using it out there in TV land.

**Comment by gnzlbg** [comment]
I think I have one project using `any` but I don't think it would be to hard to move them to some other `any` implementation, but I'll worry about that when you remove the headers.
