### ISSUE TITLE
Compilation errors for fibonacci.cpp 

### ISSUE THREAD

**Issue by marcoippolito** [ericniebler/range-v3#840]
Trying to compile this example file: 
    https://raw.githubusercontent.com/ericniebler/range-v3/master/example/fibonacci.cpp

    `g++ -std=c++17 fibonacci.cpp -ofibonacci
    In file included from fibonacci.cpp:23:0:
    ./recursive_range.hpp:47:47: warning: ‘using any_input_view = struct ranges::v3::any_view<int,  
    (ranges::v3::category)1, void>’ is deprecated: Use any_view<Ref, category::input> instead.  
    [-Wdeprecated-declarations]
                 std::function<any_input_view<int>()> fun_;
                                                   ^
    In file included from /usr/include/range/v3/view.hpp:23:0,
                         from /usr/include/range/v3/all.hpp:21,
                         from fibonacci.cpp:22:
    /usr/include/range/v3/view/any_view.hpp:613:45: note: declared here
                 = any_view<Ref, category::input>;
                                                 ^
    In file included from fibonacci.cpp:23:0:
    ./recursive_range.hpp:54:51: warning: ‘using any_input_view = struct ranges::v3::any_view<int,   
    (ranges::v3::category)1, void>’ is deprecated: Use any_view<Ref, category::input> instead.  
    [-Wdeprecated-declarations]
                     std::function<any_input_view<int>()> const *fun_;
                                                       ^
    In file included from /usr/include/range/v3/view.hpp:23:0,
                     from /usr/include/range/v3/all.hpp:21,
                     from fibonacci.cpp:22:
    /usr/include/range/v3/view/any_view.hpp:613:45: note: declared here
                 = any_view<Ref, category::input>;
                                                 ^
    In file included from fibonacci.cpp:23:0:
    ./recursive_range.hpp:55:26: warning: ‘using any_input_view = struct ranges::v3::any_view<int, 
    ( ranges::v3::category)1, void>’ is deprecated: Use any_view<Ref, category::input> instead.   
    [-Wdeprecated-declarations]
                     optional<any_input_view<int>> rng_;
                              ^~~~~~~~~~~~~~~~~~
    In file included from /usr/include/range/v3/view.hpp:23:0,
                     from /usr/include/range/v3/all.hpp:21,
                     from fibonacci.cpp:22:
    /usr/include/range/v3/view/any_view.hpp:613:45: note: declared here
                 = any_view<Ref, category::input>;
                                                 ^
    In file included from fibonacci.cpp:23:0:
    ./recursive_range.hpp:57:42: warning: ‘using any_input_view = struct ranges::v3::any_view<int,  
    (ranges::v3::category)1, void>’ is deprecated: Use any_view<Ref, category::input> instead.    
    [-Wdeprecated-declarations]
                     any_input_view<int> &rng()
                                              ^
    In file included from /usr/include/range/v3/view.hpp:23:0,
                     from /usr/include/range/v3/all.hpp:21,
                     from fibonacci.cpp:22:
    /usr/include/range/v3/view/any_view.hpp:613:45: note: declared here
                 = any_view<Ref, category::input>;
                                                 ^
    In file included from fibonacci.cpp:23:0:
    ./recursive_range.hpp:63:56: warning: ‘using any_input_view = struct ranges::v3::any_view<int,    
    (ranges::v3::category)1, void>’ is deprecated: Use any_view<Ref, category::input> instead.   
    [-Wdeprecated-declarations]
                     impl(std::function<any_input_view<int>()> const &fun)
                                                            ^
    In file included from /usr/include/range/v3/view.hpp:23:0,
                     from /usr/include/range/v3/all.hpp:21,
                     from fibonacci.cpp:22:
       /usr/include/range/v3/view/any_view.hpp:613:45: note: declared here
                 = any_view<Ref, category::input>;
                                                 ^
    In file included from fibonacci.cpp:23:0:
    ./recursive_range.hpp:80:28: warning: ‘using any_input_view = struct ranges::v3::any_view<int, 
    (ranges::v3::category)1, void>’ is deprecated: Use any_view<Ref, category::input> instead.   
    [-Wdeprecated-declarations]
                     iterator_t<any_input_view<int>> begin()
                                ^~~~~~~~~~~~~~~~~~
    In file included from /usr/include/range/v3/view.hpp:23:0,
                     from /usr/include/range/v3/all.hpp:21,
                     from fibonacci.cpp:22:
    /usr/include/range/v3/view/any_view.hpp:613:45: note: declared here
                 = any_view<Ref, category::input>;
                                                 ^
    In file included from fibonacci.cpp:23:0:
    ./recursive_range.hpp:84:28: warning: ‘using any_input_view = struct ranges::v3::any_view<int, 
    (ranges::v3::category)1, void>’ is deprecated: Use any_view<Ref, category::input> instead.    
    [-Wdeprecated-declarations]
                     sentinel_t<any_input_view<int>> end()
                                ^~~~~~~~~~~~~~~~~~
    In file included from /usr/include/range/v3/view.hpp:23:0,
                     from /usr/include/range/v3/all.hpp:21,
                     from fibonacci.cpp:22:
    /usr/include/range/v3/view/any_view.hpp:613:45: note: declared here
                 = any_view<Ref, category::input>;
                                                  ^
    In file included from fibonacci.cpp:23:0:
    ./recursive_range.hpp:88:44: warning: ‘using any_input_view = struct ranges::v3::any_view<int, 
    (ranges::v3::category)1, void>’ is deprecated: Use any_view<Ref, category::input> instead.   
    [-Wdeprecated-declarations]
                     any_input_view<int> & base()
                                                ^
    In file included from /usr/include/range/v3/view.hpp:23:0,
                     from /usr/include/range/v3/all.hpp:21,
                     from fibonacci.cpp:22:
    /usr/include/range/v3/view/any_view.hpp:613:45: note: declared here
                 = any_view<Ref, category::input>;
                                                 ^
    In file included from /usr/include/range/v3/utility/copy.hpp:18:0,
                     from /usr/include/range/v3/begin_end.hpp:23,
                     from /usr/include/range/v3/core.hpp:17,
                     from /usr/include/range/v3/all.hpp:17,
                     from fibonacci.cpp:22:
    ./recursive_range.hpp:96:56: warning: ‘using any_input_view = struct ranges::v3::any_view<Ref,
     (ranges::v3::category)1>’ is deprecated: Use any_view<Ref, category::input> instead. [-Wdeprecated-  
     declarations]
                         ConvertibleTo<result_of_t<Fun&()>, any_input_view<Ref>>())>
                                                            ^~~~~~~~~~~~~~~~
     In file included from /usr/include/range/v3/view.hpp:23:0,
                     from /usr/include/range/v3/all.hpp:21,
                     from fibonacci.cpp:22:
     /usr/include/range/v3/view/any_view.hpp:613:45: note: declared here
                 = any_view<Ref, category::input>;
                                                 ^
    fibonacci.cpp: In lambda function:
    fibonacci.cpp:32:38: warning: ‘ranges::v3::detail::take_exactly_view_<ranges::v3::iota_view<From, void>,
    true> ranges::v3::view::closed_ints_fn::operator()(Val, Val) const [with Val = int; bool  
    _concept_requires_573 = false; typename std::enable_if<(_concept_requires_133 ||  
    ranges::v3::concepts::models<ranges::v3::concepts::Integral, T>())>::type* <anonymous> = 0]’ is 
    deprecated: view::closed_ints is deprecated; use view::closed_indices instead! [-Wdeprecated-
    declarations]
             return concat(closed_ints(0,1), zip_with(std::plus<int>{}, fibs(), tail(fibs())));
                                          ^
    In file included from /usr/include/range/v3/view/split.hpp:34:0,
                     from /usr/include/range/v3/action/split.hpp:28,
                     from /usr/include/range/v3/action.hpp:30,
                     from /usr/include/range/v3/all.hpp:19,
                     from fibonacci.cpp:22:
    /usr/include/range/v3/view/iota.hpp:575:66: note: declared here
                     detail::take_exactly_view_<iota_view<Val>, true> operator()(Val from, Val to) const
                                                                      ^~~~~~~~
    ` 

What am I missing?
Marco

**Comment by johelegp** [comment]
These are all warnings. The example uses a [deprecated alias](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/view/any_view.hpp#L612), that's it.

**Comment by marcoippolito** [comment]
Thanks @johelegp

**Comment by CaseyCarter** [comment]
I'd appreciate a pull request that changes the uses in `fibonacci.cpp` from `any_input_view<T>` to `any_view<T, category::input>` if someone was motivated to submit one ;)
