### ISSUE TITLE
Ranges with coroutines: example taken from the blog : fatal error: 'functional' file not found

### ISSUE THREAD

**Issue by marcoippolito** [ericniebler/range-v3#842]
Taken from http://ericniebler.com/2017/08/17/ranges-coroutines-and-react-early-musings-on-the-future-of-async-in-c/   

    `
    //#include <iostream>
    #include <range/v3/all.hpp>
    #include <range/v3/experimental/utility/generator.hpp>

    using namespace ranges;

    // Define a range of all the unsigned shorts:
    experimental::generator<unsigned short> ushorts()
    {
      unsigned short u = 0;
      do { co_yield u; } while (++u);
    }

    int main()
    {
      // Filter all the even unsigned shorts:
      auto evens = ushorts()
                 | view::filter([](auto i) {
                       return (i % 2) == 0; });

      // Write the evens to cout:
      //copy( evens, ostream_iterator<>(std::cout, "\n") );
    }
`

Compiling with clang with all warnings disabled and with `-fcoroutines-ts -stdlib=libc++` : 

    `clang++ -Qunused-arguments -fcoroutines-ts -stdlib=libc++ -std=c++17 rangesCoroutines01.cpp 
    -orangesCoroutines01
    In file included from rangesCoroutines01.cpp:4:
    In file included from /usr/include/range/v3/all.hpp:17:
    In file included from /usr/include/range/v3/core.hpp:17:
    /usr/include/range/v3/begin_end.hpp:17:10: fatal error: 'functional' file not found
    #include <functional>
             ^~~~~~~~~~~~
    1 error generated.
    `
How can I solve it?
Marco

**Comment by johelegp** [comment]
[It works.](https://godbolt.org/g/kWeG38). Do you have libc++ installed?

**Comment by marcoippolito** [comment]
Hi @johelegp ,
after installing in my Ubuntu 16.04 Server edition libc++-dev, libc++abi1 and libc++1
I got this error `message:

    `clang++ -Qunused-arguments -fcoroutines-ts -stdlib=libc++ -std=c++17 rangesCoroutines01.cpp 
    -orangesCoroutines01
    In file included from rangesCoroutines01.cpp:5:
    /usr/include/range/v3/experimental/utility/generator.hpp:20:10: fatal error: 'experimental/coroutine' 
    file not found
    #include <experimental/coroutine>
             ^~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    `

**Comment by johelegp** [comment]
At least on Arch Linux, there's an AUR libc++experimental package. Maybe you're missing that one.

**Comment by marcoippolito** [comment]
Following these updated instructions  [https://solarianprogrammer.com/2017/12/13/linux-wsl-install-clang-libcpp-compile-cpp-17-programs/](url) I re-installed clang-6.0.0 in my Ubuntu 16.04 server edition.
While the two test examples can be nicely compiled and executed:

    `marco@PC:~/CplusplusGoodCodeExamples/clangExamples$ export PATH=/usr/local/clang_6.0.0
    /bin:$PATH
    marco@PC:~/CplusplusGoodCodeExamples/clangExamples$ export LD_LIBRARY_PATH=/usr/local
    /clang_6.0.0/lib:$LD_LIBRARY_PATH

    clang++ -std=c++17 -stdlib=libc++ -Wall -pedantic if_test.cpp -oif_test
    marco@PC:~/CplusplusGoodCodeExamples/clangExamples$ ./if_test
    Local variable a is < 8
    marco@PC:~/CplusplusGoodCodeExamples/clangExamples$ clang++ -std=c++17 -stdlib=libc++ 
    -Wall -pedantic test_fs.cpp -o test_fs -lc++experimental
    marco@PC:~/CplusplusGoodCodeExamples/clangExamples$ ./test_fs
    "./if_test.cpp"
    "./test_fs.cpp"
    "./if_test"
    "./clang01"
    "./test_fs"
    "./clang01.cpp"
    `
The compilation of the range with coroutines gives some errors:

    `marco@PC:~/CplusplusGoodCodeExamples/exampleRangeV3$ export PATH=/usr/local/clang_6.0.0  
    /bin:$PATH
    marco@PC:~/CplusplusGoodCodeExamples/exampleRangeV3$ export LD_LIBRARY_PATH=/usr/local
    /clang_6.0.0/lib:$LD_LIBRARY_PATH
    marco@PC:~/CplusplusGoodCodeExamples/exampleRangeV3$ lang++ -std=c++17 -stdlib=libc++ 
    -Wall -pedantic rangesCoroutines01.cpp -o rangesCoroutines01 -lc++experimental
    No command 'lang++' found, did you mean:
     Command 'clang++' from package 'clang' (universe)
    lang++: command not found
    marco@PC:~/CplusplusGoodCodeExamples/exampleRangeV3$ clang++ -std=c++17 -stdlib=libc++
      -Wall -pedantic rangesCoroutines01.cpp -o rangesCoroutines01 -lc++experimental
    rangesCoroutines01.cpp:10:1: error: use of undeclared identifier 'experimental'
    experimental::generator<unsigned short> ushorts()
    ^
    rangesCoroutines01.cpp:13:8: error: unknown type name 'co_yield'
      do { co_yield u; } while (++u);
           ^
    2 errors generated.
    `

**Comment by marcoippolito** [comment]
@johelegp You are right.

Now it works:

    `marco@PC:~/CplusplusGoodCodeExamples/exampleRangeV3$ clang++ -std=c++17 -fcoroutines-ts 
    -stdlib=libc++ -Wall -pedantic rangesCoroutines01.cpp -orangesCoroutines01 -lc++experimental
    marco@PC:~/CplusplusGoodCodeExamples/exampleRangeV3$
    `
Thank you very for your kind help.
Marco
