### ISSUE TITLE
Feature request: Improve conan package

### ISSUE THREAD

**Issue by pleroux0** [ericniebler/range-v3#849]
## Feature request

Change conan package to use cmake install so that the cmake targets can be used in a cmake package. 

This allows for consumer packages to use modern cmake in their build systems:

```cmake
find_package(range-v3 REQUIRED)
target_link_libraries(my_target PRIVATE range-v3)
```
instead of

```cmake
target_include_directories(my_target PRIVATE ${CONAN_INCLUDE_DIRS_RANGE-V3})
```

If a consumer uses the `cmake_paths` generator one can even skip the usual

```cmake
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```

which conan requires with the `cmake` generator. Making the consumer project's use of conan transparent.

I would be happy to make a pull request if you give the go ahead.

**Comment by ericniebler** [comment]
I believe this is resolved fixed. @pleroux0 please reopen if there is still more to do here.
