### ISSUE TITLE
Handle proxy iterators

### ISSUE THREAD

**Issue by sbabbi** [ericniebler/range-v3#85]
One really nice feature would be to be able to sort (or applying any mutating algorithm, really), a `zip view`.

Example:

    int keys[] = {4,2,1,6};
    int values[] = {1,2,3,4};
    sort ( view::zip(keys, values) );

AFAIK there is no easy way to do that in C++11, and it does not work with `range-v3` atm because sort expects a lvalue-ref to a range. 

In general in the current standard the problem of implementing a `zip_iterator` with that semantics is that it `iterator::reference` must be `iterator::value_type&`. Having a `zip_iterator` whose `value type` is `tuple<Ts ... >` and `reference` is `tuple<Ts& ... >` is (I think) probably the desired semantics.

Even then an overload of `swap( tuple<Ts & ...>, tuple <Ts & ...> )` that can swap two tuples of references passed *by value* would be necessary.

Just random thoughts, apologies if this is has already been discussed.

**Comment by ericniebler** [comment]
Although there is still work to be done, tests to be written, and bugs to be squashed, proxy iterator support is in there and basically works. You can now sort a zip view.
