### ISSUE TITLE
sort predicate confusion

### ISSUE THREAD

**Issue by mjhurd** [ericniebler/range-v3#851]
I'm a bit simple it seems as I'm not quite able to see clearly the cause of this error on the line marked error below.

std::sort and boost::sort picks up the default predicate, but ranges-v3 doesn't for some reason. This is ranges-v3 0.36. Similar error on clang 6/7 & gcc 7/8.

```cpp
#include <range/v3/all.hpp>

#include <algorithm>
#include <boost/hana.hpp>
#include <utility>
#include <vector>
#include <boost/range/algorithm.hpp>


namespace hana = boost::hana;

template< typename T = int>
struct point_t {
  BOOST_HANA_DEFINE_STRUCT(point_t<T>, (T, x), (T, y));

  constexpr bool operator<(const point_t<T> &b) const noexcept {
    return hana::less(hana::to_tuple(*this), hana::to_tuple(b));
  };
};

int main() {

  std::vector<point_t<point_t<>>> all;

  boost::sort(all); // OK
  std::sort(std::begin(all), std::end(all)); //OK

  ranges::sort(all, std::less<point_t<point_t<>>>()); // OK
  ranges::sort(all, hana::less); // OK

  ranges::sort(all); // error no matching function for call to object of type 'const with_braced_init_args<ranges::v3::sort_fn>'

  return 0;
}
```
Godbolt reference: https://godbolt.org/g/8mXUdp
A kick in the butt would be most welcome.

Thanks in advance, --matt.

**Comment by CaseyCarter** [comment]
`ranges::sort` without a comparator argument requires the type to be sorted to model the [StrictTotallyOrdered concept](https://en.cppreference.com/w/cpp/concepts/StrictTotallyOrdered). That means the type must define all of `==`, `!=`, `<`, `>`, `<=`, and `>=` with consistent semantcs.

**Comment by mjhurd** [comment]
Thank you for getting back so quickly. I understand now. I must say it's a little disappointing it is incompatible with std::sort and boost::sort requirements. That is the price we pay for range-v3 loveliness I guess.  

Thanks again, --Matt.
