### ISSUE TITLE
Are more adaptors headed for C++20?

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#855]
Now that P0789 has (almost) landed:
do you have a list of other things (more views?) that you want to get into C++20 or is all focus on fixing up the current confirmed features/wording? Do you plan to get more views into the standard in the long run, or do you think people should rely on libraries/own-code for things like `view::take` also in the future?

I know you are busy also with other proposals so I am not asking for anything (in fact I would offer to try and help with wording if you think more views should be merged), but it would be nice to know the general direction for those parts of range-v3 that are currently not considered for the standard so that one can design code to be able to accept C++20's STL as a replacement for the range-v3 dependency (which of course only works if one doesn't rely on the other bits).

Thanks!

**Comment by ericniebler** [comment]
@cjdb has a paper in the San Diego pre-meeting mailing (coming out soon) proposing additional views. Maybe he can chime in here.

In the end, I hope to upstream just about all of range-v3 in one form or another. That's a looong-term proposition, as range-v3 is not small.

Closing this issue, but feel free to comment.
