### ISSUE TITLE
Compilation failure with _GLIBCXX_DEBUG and std=c++17

### ISSUE THREAD

**Issue by FloopCZ** [ericniebler/range-v3#857]
Hi everyone,

Consider the following code:
```c++
#include <range/v3/core.hpp>
int main() { }
```
Compile with:
```bash
g++ -std=c++17 -D_GLIBCXX_DEBUG main.cpp
```
The compilation fails with:
```c++
In file included from /home/floop/.local/include/range/v3/range_fwd.hpp:21,
                 from /home/floop/.local/include/range/v3/begin_end.hpp:22,
                 from /home/floop/.local/include/range/v3/core.hpp:17,
                 from test.cpp:1:
/home/floop/.local/include/range/v3/to_container.hpp:106:9: error: template argument 1 is invalid
         RANGES_INLINE_VARIABLE(detail::to_container_fn<meta::quote<std::vector>>,
         ^~~~~~~~~~~~~~~~~~~~~~
/home/floop/.local/include/range/v3/to_container.hpp:106:9: error: template argument 1 is invalid
         RANGES_INLINE_VARIABLE(detail::to_container_fn<meta::quote<std::vector>>,
```
Note that it works fine if `-std=c++14` or `-std=c++11` is used.
With `#include <range/v3/all.hpp>`, the compilation fails even with `c++11` and `c++14`, though.

System info:
```
gcc version 8.1.1 20180531 (GCC)
clang version 6.0.0 (tags/RELEASE_600/final)
Linux pine 4.17.3-1-ARCH #1 SMP PREEMPT Tue Jun 26 04:42:36 UTC 2018 x86_64 GNU/Linux
```
Test online with [Coliru](http://coliru.stacked-crooked.com/a/e2c00b2e3d78243c).

**Comment by CaseyCarter** [comment]
Does `-DRANGES_NO_STD_FORWARD_DECLARATIONS` make the problem go away?

**Comment by FloopCZ** [comment]
> Does -DRANGES_NO_STD_FORWARD_DECLARATIONS make the problem go away?

Yes sir! Thank you.

**Comment by CaseyCarter** [comment]
> Yes sir! Thank you.

Then apparently libstdc++ has started putting declarations in `std` in inline namespaces, at least in debug mode.

**Comment by FloopCZ** [comment]
> Then apparently libstdc++ has started putting declarations in std in inline namespaces, at least in debug mode.

You may be right:
```c++
--- <vector> ---
...
#ifdef _GLIBCXX_DEBUG
# include <debug/vector>
#endif
...
```
```c++
--- <debug/vector> ---
...
namespace std _GLIBCXX_VISIBILITY(default)
{
namespace __debug
{
  /// Class std::vector with safety/checking/debug instrumentation.
  template<typename _Tp, typename _Allocator = std::allocator<_Tp> > class vector
...
```
```c++
--- <x86_64-pc-linux-gnu/bits/c++config.h> ---
...
# ifdef _GLIBCXX_DEBUG
  inline namespace __debug { }
# endif
...
```

**Comment by ericniebler** [comment]
My kingdom for a `<stdfwd>` header.

**Comment by CaseyCarter** [comment]
> My kingdom for a `<stdfwd>` header.

We've been kicking around the idea of `<fwd>` at MSFT. We implemented a warning for forward declarations in namespace `std`, which triggered in thousands of places in Windows / our "Real World Code" test suite, so it had to be disabled by default. I suspect if we actually proposed such a thing people would say that "Modules fixes it."
