### ISSUE TITLE
to_container assumes equality-preservation of iterator_t == sentinel_t

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#858]
Given an InputRange r, I understand the concept definitions to not require `begin(r) == end(r)` to be equality preserving, is that correct?

Because the `to_container` functionality implicitly assumes this by adding common'ness and delegating to the container's  [begin, end)-constructor.

This small example illustrates the problem:

```cpp
auto take_line =  ranges::view::iter_take_while([] (auto it) { if (*it == '\n') { ++it; return false;} return true; }); // takes until newline, but consumes the newline
std::string s = "foo\nbar";
auto v = s | view::single_pass_input /*decays to single_pass input view*/ | take_line;
std::cout << v << '\n'; // [f,o,o]
std::cout << v << '\n'; // [b,a,r]
```
BUT if we convert to string this fails:
```cpp
auto take_line =  ranges::view::iter_take_while([] (auto it) { if (*it == '\n') { ++it; return false;} return true; }); // takes until newline, but consumes the newline
std::string s = "foo\nbar";
auto v = s | view::single_pass_input /*decays to single_pass input view*/ | take_line;
std::cout << std::string(v) << '\n'; // "foobar"
std::cout << std::string(v) << '\n'; // ""
```

I assume this is because the respective constructor calls begin == end more than once, thus reading over the termination criterium in the first run.

If you agree this is a bug, I would make a PR that changes the behaviour of `to_container` for InputRanges to not use the [begin, end)-constructor, but a back-inserter and ranges::copy instead. For ForwardRanges it can remain as is.

**Comment by CaseyCarter** [comment]
`begin` is not required to be equality-preserving for single-pass ranges, but iterator-sentinel comparisons are required to be equality-preseriving. From a quick inspection, `to_container` correctly only ever calls `begin` once.

The lambda you're passing to `iter_take_while` is effectively useless: either the type of `it` satisfies forward iterator, and the increment inside the lambda has no effect outside the lambda, or the type of `it` is single-pass and by incrementing it you've invalidated the copy outside the lambda that the view is using to iterate.

Also, the non-equality-preservation of `begin` means you invoke UB by trying to iterate over the same input view twice: in the first sample with `std::cout << v << '\n';`, and `std::string(v)` in the second.

It looks like you want `view::split('\n')`: https://wandbox.org/permlink/TvrkAQKV8MDeRYiB.

**Comment by CaseyCarter** [comment]
(Note to self: we *really* need to assert that `begin` is called at most once on a single-pass view in debug compiles.)

**Comment by h-2** [comment]
> begin is not required to be equality-preserving for single-pass ranges, but iterator-sentinel comparisons are required to be equality-preseriving. 

Ah, ok, I missed that. Is it stated anywhere? I couldn't find this requirement anywhere in the current documents.

> The lambda you're passing to iter_take_while is effectively useless: either the type of it satisfies forward iterator, and the increment inside the lambda has no effect outside the lambda, 

That's desired, for ForwardRanges it's supposed to behave like `view::take_while([] (auto const & val) { return (*it == '\n'); })`.

> or the type of it is single-pass and by incrementing it you've invalidated the copy outside the lambda that the view is using to iterate.

Well, the view is not using it anymore, because it always stops when I do this :laughing: No serisously, why would it be invalid? The way the view is implemented, all iterators share an underlying iterator, an increment of one updates the other.

> Also, the non-equality-preservation of begin means you invoke UB by trying to iterate over the same input view twice: in the first sample with std::cout << v << '\n';, and std::string(v) in the second.

Why would this be UB? The input view just behaves like a stream:
```cpp
std::string s = "foobar";
auto v = s | view::single_pass_input ;
auto v2 = v | view::take(2);
std::cout << v2 << '\n'; // [f,o]
std::cout << v << '\n'; // [o,b,a,r]
```
See also #702 
I think this behaviour is very logical. When defining v, you say that you want to pass over the underlying range s exactly once. I pass over the first two elements via v2, so when iterating over the rest (by calling begin again on v), I get the remaining ones and exhaust v, now it's empty.

> (Note to self: we really need to assert that begin is called at most once on a single-pass view in debug compiles.)

Again, why would that be desirable for all input views? How would you achieve "input stream" behaviour then? Just because repeated calls to begin are not equality preserving, doesn't make them UB or does it?

> It looks like you want view::split('\n')

The example of repeated invocation of the take_line is not my actual use-case (although repeated calls to the input view's begin is). In fact I am actually parsing for '\r\n' or '\n' and doing something like it with split seems overly complex: I would need to split at '\n', drop a potential '\r' from the end, take the first of the range-of-range and then join that to collapse away the added dimension :slightly_frowning_face:
In that case I would rather just take_while-not-on-newline and then look at the input stream for '\r' and '\n' and move the iterator past them (that's what I was doing before I wrote the `view::take_line`).

**Comment by CaseyCarter** [comment]
> > begin is not required to be equality-preserving for single-pass ranges, but iterator-sentinel comparisons are required to be equality-preseriving.
>
> Ah, ok, I missed that. Is it stated anywhere? I couldn't find this requirement anywhere in the current documents.

[Sentinel](https://timsong-cpp.github.io/cppwp/ranges-ts/iterators.sentinel) refines [WeaklyEqualityComparable](https://timsong-cpp.github.io/cppwp/ranges-ts/concepts.lib.compare.equalitycomparable) which requires the expressions `==` and `!=` to be valid and (implicitly per [[concepts.lib.general.equality]/4](https://timsong-cpp.github.io/cppwp/ranges-ts/concepts.lib.general.equality#4)) equality-preserving.

> Why would this be UB? The input view just behaves like a stream:
>
> ```c++
> std::string s = "foobar";
> auto v = s | view::single_pass_input ;
> auto v2 = v | view::take(2);
> std::cout << v2 << '\n'; // [f,o]
> std::cout << v << '\n'; // [o,b,a,r]
> ```

It's a perfectly valid design choice for your view to provide additional guarantees over what is required. One of range-v3's views adapting your view won't necessarily preserve those additional guarantees. So this could may be valid - depending on the implementation of `single_pass_input` - but the code in the OP that iterates twice over an `iter_take_while_view` is unsupported.

> > (Note to self: we really need to assert that begin is called at most once on a single-pass view in debug compiles.)
>
> Again, why would that be desirable for all input views?

My intent wasn't "all input views", only the single-pass views we implement in range-v3 that do not provide the additional guarantee that repeated calls to `begin` are sane.

**Comment by h-2** [comment]
> Sentinel refines WeaklyEqualityComparable which requires the expressions == and != to be valid and (implicitly per [concepts.lib.general.equality]/4) equality-preserving.

Thanks, the last link was the part that I was missing!

> So this could may be valid - depending on the implementation of single_pass_input - but the code in the OP that iterates twice over an iter_take_while_view is unsupported.

Yes, that makes sense under these circumstances. I can rewrite the view so that for single pass input ranges it will read until EOL, consume the EOL and just be empty if read from again. That preserves `it == end` and still does what I need.

> > Given an InputRange r, I understand the concept definitions to not require begin(r) == end(r) to be equality preserving, is that correct?

My assumption was incorrect so I am closing this issue. Thanks for taking the time.
