### ISSUE TITLE
`ordered_less` too restrictive for `lower_bound`, `upper_bound`?

### ISSUE THREAD

**Issue by tower120** [ericniebler/range-v3#866]
I don't want to whine, but isn't `ordered_less` too restrictive for `lower_bound` ? Doesn't `less` enough?
binary search requires only `<`, `>` operators...
And even `less` seems to restrictive, because require  `<=`, `>=` .

Either I don't see reasoning behind this, either it needs at least one more "Comparison concept" for < > only (less strict then current `WeaklyOrdered`).

**Comment by ericniebler** [comment]
It is strict by design. Any type that provides `<` can and should provide the other ordering operators.
