### ISSUE TITLE
Why does ranges not support std::back_inserter?

### ISSUE THREAD

**Issue by yaoxinliu** [ericniebler/range-v3#867]
```
        auto src = std::vector<int>{ 1, 2, 3 };
	std::vector<int> dst;

	// ok
	std::copy(src.begin(), src.end(),
		std::back_inserter(dst));

	// ok
	ranges::copy(src, ranges::back_inserter(dst));

	// not ok
	ranges::copy(src, std::back_inserter(dst));
```

**Comment by ericniebler** [comment]
Because it doesn't satisfy the `Iterator` concept as the range library defines it (it's not default constructible). That will be fixed in C++20. At least, that's the plan.

**Comment by correaa** [comment]
I bumped into the same problem: https://stackoverflow.com/questions/56571907/why-is-back-inserter-iterator-not-weaklyincrementable-in-rangev3

I think by following existing rules too strickly the library is consistently overconstraining the algorithms. I think there was no need to define Iterator as default constructible in the first place. If that is not possible to change, unfortunately we will have to define  `NonDefaultConstructibleIterator` relaxing that conditions. 

Another example is requiring Sentinels to be left and right comparable with iterators when one can adopt the convention that Sentinels to be right and left comparable.
