### ISSUE TITLE
Why is filter deprecated?

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#87]
I find both `filter` and `remove_if` useful.  Replacing `filter(pred)` with `remove_if(not(pred))` makes IMO the code less readable. The intent is just harder to understand due to the double negation: do something on the elements that are not the elements for which the predicate is not true (my brain melts).

**Comment by gnzlbg** [comment]
Thinking about this again, it occurred to me that the gap `filter` fills is that of a `view` analogous to the `find` algorithm.

**Comment by ericniebler** [comment]
Riddle me this: `find_if_not` is to `remove_if`, as `find_if` is to <ins>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</ins>.

**Comment by pfultz2** [comment]
> Riddle me this: find_if_not is to remove_if, as find_if is to         .

Why can't we just have `find` and `find_if` views? And if you only want one element then `r | find(x) | take(1)` could be used.

**Comment by ericniebler** [comment]
Logically, `find` returns a position. A `find` view doesn't make sense to me. Or, in D, `find` returns a range starting at the found position and continuing to the end. I somewhat like `keep_if`. If an algorithm that logically negated `remove_if` ever got proposed, I think `keep_if` would be a contender.

**Comment by pfultz2** [comment]
> Logically, find returns a position.

Or positions. There is no reason to think of it as singular. As a view, it would lazily return all positions, not just the first position.

> Or, in D, find returns a range starting at the found position and continuing to the end.

I am not suggesting something like that. That is called `drop`. It doesn't make sense to be called `find`.

**Comment by ericniebler** [comment]
> As a view, \[`find`\] would lazily return all positions, not just the first position.

I would call that `find_all`, and it would yield a range of positions, not of elements.

> > Or, in D, `find` returns a range starting at the found position and continuing to the end.
>
> I am not suggesting something like that. That is called `drop`. It doesn't make sense to be called `find`.

`drop` takes an integral number of elements to drop. You're thinking of `drop_while`.

**Comment by pfultz2** [comment]
> it would yield a range of positions, not of elements.

A range of iterators is completely unnecessary. The iterators to the range hold the position.

**Comment by ericniebler** [comment]
Range-v3 itself uses ranges of iterators to implement some views. They are not useless.

**Comment by pfultz2** [comment]
> Range-v3 itself uses ranges of iterators to implement some views.

Interesting. Where is this used? I just can't think of a good use case to do this that wouldn't already be satisfied by using the iterators to the range instead, or providing a range of ranges instead.

**Comment by ericniebler** [comment]
See [the implementation of the split view](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/view/split.hpp#L70). Passing an iterator to `view::iota` yields a range of iterators. It's needed here because the split predicate operates on positions, not values.

**Comment by pfultz2** [comment]
> See the implementation of the split view.

Ok I see, but it seems like its needed for more "advance" usage. IMO, it would be better to default to values always and provided a view that maps that range to a range of base iterators(like PStade Oven's [outdirected](http://p-stade.sourceforge.net/oven/doc/html/oven/range_adaptors.html#oven.range_adaptors.outdirected) adaptor).

> Passing an iterator to view::iota yields a range of iterators. 

That makes sense why `iota` would do this. It doesn't make sense why `find` would do this.

> It's needed here because the split predicate operates on positions, not values.

For operating on iterators and other algorithms like this, it would be nice to have a haskell-like `unfold` construct like this:

```cpp
template<class Range, class T>
auto split(Range& r, const T& x)
{
    return unfold(begin(r), [&](auto i)
    {
        auto i_next = find(i, end(r), x);
        return while_(i != end(r))
            // Next value to be passed to the function
            .next(i_next)
            // The value to be yielded to the range
            .yield(make_iterator_range(i, i_next));
    });
}
```

Which would be nice in complementing the list comprehension.

**Comment by gnzlbg** [comment]
I cannot get used to `remove_if`, it just expresses the opposite of what I want to do _all_ the time. 

Can we either not deprecate filter or remove it from `view.hpp` such that I can include my own in the without the deprecation warning in the `view` namespace? I'd rather do that than turn of the deprecation warning globally. Those who want to use the deprecated version can still do so by including the specific file.
