### ISSUE TITLE
InputIterator concept doesn't check dereferenceability of const iterator.

### ISSUE THREAD

**Issue by Predelnik** [ericniebler/range-v3#873]
If I read standard correctly type `const Iterator` should be dereferencable to satisfy `InputIterator`.

http://eel.is/c++draft/iterators#iterator.requirements.general-14
> In the following subclauses, a and b denote values of type X or const X

http://eel.is/c++draft/iterators#input.iterators
> A class or pointer type X satisfies the requirements of an input iterator...
> Requires: a is dereferenceable. 
The expression
(void)*a

However in ranges-v3 `InputIterator` is fine with iterator having non-const `operator*` (thus `const X` - non dereferencable):
https://godbolt.org/g/5q8fGK

Is this intentional or perhaps an oversight?

**Comment by ericniebler** [comment]
Intentional. The `Readable` concept as proposed for C++20[*] agrees with range-v3.

\[*\]: [P0896](http://wg21.link/P0896)
