### ISSUE TITLE
Reverse iterate over an any_view object

### ISSUE THREAD

**Issue by ClementPavue** [ericniebler/range-v3#874]
Hello,

I need to reverse iterate over an an_view range and when invoking the `reverse_view` function I get hte following error: `static assertion failed: Concept check failed: BidirectionalRange<Rng>()`. I can't change the type of my input object. Any clue on how I can make it work ? 

Cheers and thanks in advance,
Clément.

**Comment by ClementPavue** [comment]
Ok is there any way to reverse iterate without reversing the entire view ?

**Comment by ericniebler** [comment]
> I can't change the type of my input object.

If you don't have a bidirectional range, you can't iterate it in reverse.
