### ISSUE TITLE
RegularInvocable does not check that the callable isn't modified

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#877]
The source code suggests that RegularInvocable actually does not perform any checks beyond those of Invocable and while some things are hard to check, I think it would be easy to add code that checks whether a `const` qualified version of the callable would still be invocable – thus verifying that the Invocable does not change during invocation.

Am I right, or did I miss something? Would you accept a PR?

Here is an example of where compilation should fail on the assert, but only fails later on invocation:

```cpp
#include <range/v3/range_concepts.hpp>
#include <range/v3/utility/functional.hpp>

auto v = [count = 0] (char c) mutable { ++count; return c == '\n'; };


static_assert(ranges::RegularInvocable<decltype(v), char>());

int main()
{
    v('A');

    auto const & v2 = v;
    v2('C');
}
```

**Comment by h-2** [comment]
Hm, I see this is all already according to the newly merged concepts into the IS. Is the motivation for not implementing RegularInvocable's constraints to allow for callables that *could* change, but *don't* ?

Why was this chosen? Because for non-object non-member functions you don't know if they keep state?

**Comment by ericniebler** [comment]
> allow for callables that could change, but don't ?

Yes, and also because checking whether the `const`-qualified type is invocable doesn't actually mean it's regular. It could be referencing function-local statics or thread locals, or a host of other ways of subverting `const`-correctness. Basically, `const` doesn't mean a lot in C++, and using it to infer regularity of functions seems specious.
