### ISSUE TITLE
Emulate range-for begin/end lookup rules

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/range-v3#88]

**Comment by anders-sjogren** [comment]
I've implemented the analogue to this, but for another function than begin and with a few more options for customization (e.g. static member functions), but lacking the array case in section 6.5.4.1.1 of N4296. Is the priority tag idiom used below a good way to get the fallback mechanism of 6.5.4.1?

    constexpr int MaxPrioLevel = 1;
    template<int Level> struct Prio : public Prio<Level-1>
    {
      constexpr Prio(){}
      static_assert(Level<=MaxPrioLevel,"Level must not be greater than MaxPrioLevel, to make sure MaxPrio means maximum priority. It is safe to increase MaxPrioLevel if needed.");
    };
    template<> struct Prio<0>{constexpr Prio(){}};
    constexpr Prio<MaxPrioLevel> maxPrio;

    struct begin_fn
    {
    private:
      //Member function
      template<typename T, typename... Args>
      auto f(Prio<1>, T&& x, Args&&... args) const ->
      decltype(std::forward<T>(x).begin(std::forward<Args>(args)...))
      {
        return std::forward<T>(x).begin(std::forward<Args>(args)...);
      }
      
      //Free function (e.g. from argument dependent lookup (ADL))
      template<typename... Args>
      auto f(Prio<0>, Args&&... args) const ->
      decltype(begin(std::forward<Args>(args)...))
      {
        //Add a using namespace (such as std) here to enable those free functions
        return begin(std::forward<Args>(args)...);
      }
    public:
      template <typename... Args>
      auto operator()(Args&&... args) const ->
      decltype(f(maxPrio, std::forward<Args>(args)...))
      {
        return f(maxPrio, std::forward<Args>(args)...);
      }
    };

**Comment by anders-sjogren** [comment]
Should all involved functions be `constexpr`?
If I understand 7.1.5.6 of N4296 correctly, it is valid to mark them as `constexpr` even if for some template arguments they will not be `constexpr`? Will they in essence then be constexpr whenever the template arguments allow it then. Should one always mark forwarding template functions constexpr then?

**Comment by ericniebler** [comment]
Your `Prio` class could be a handy way to implement this, but the partial ordering could be tricky once you add the array case.

**Comment by anders-sjogren** [comment]
Could you elaborate on this?
If the array case is implemented with Prio<2>, it will be matched first for arrays, then member functions (as Prio<1>) and finally free functions (adl, as Prio<0>). Wouldn't this perfectly mimic 7.1.5.6?

**Comment by ericniebler** [comment]
Fixed in e8332a5
