### ISSUE TITLE
iter_swap on view to swap underlying range

### ISSUE THREAD

**Issue by Svalorzen** [ericniebler/range-v3#882]
In my current c++17 project I have a function that takes two iterators to a range of type `A`, and shuffles it around inline depending on some logic. Now it turns out that it would be very convenient for me to be able to use the same function on ranges of type `B`, where `B` contains an `A`. To do this, I used `boost::transform_iterator` and I had to define a SFINAE `iter_swap` to make it work.

I was wondering if ranges could do something similar. As an example of what I am trying to do, here is some code:

```
#include <range/v3/all.hpp>  //get everything
#include <vector>
#include <iostream>

struct A {
    int x;
};

struct B {
    int y;
    A a;
};

/**
 * @brief A function that does some work inline on a range of A.
 *
 * It uses iter_swap in the hope of working on the overall range, not
 * necessarily on just the view it is given.
 */
template <typename It>
void f(It begin, It end) {
    while (begin < end) {
        --end;
        if (begin->x < end->x)
            std::iter_swap(begin, end);
        ++begin;
    }
}

/**
 * @brief A function that calls f on a range.
 *
 * I'm not sure what is the best way to do this here, I'm kind of new with ranges.
 */
template <typename Range>
void f(Range & r) {
    f(ranges::begin(r), ranges::end(r));
}

int main() {
    // Create data
    std::vector<B> b{{1,{2}},{3,{4}},{5,{6}}};

    // Transform data in to view of A, so that 'f' can work on it
    auto b_as_a = b | ranges::view::transform([](auto const& x) -> A const& { return x.a; });

    // Do work inline on the view, but hopefully on the underlying b too.
    f(b_as_a);

    // Print results.
    for (auto x : b)
        std::cout << '(' << x.y << ", " << x.a.x << ")\n";
    std::cout << "\n";

    // expected:
    //
    // (5, 6)
    // (3, 4)
    // (1, 2)

    return 0;
}
```

Now this does not work as apparently the `view::transform` gives back a `const` range (if I am understanding the compiler errors correctly). Is it possible to do in another way?

I've read similar ideas in P0022, and also [in this blog post](http://ericniebler.com/2015/02/03/iterators-plus-plus-part-1/), so I was wondering whether there was a way to do this.

**Comment by ericniebler** [comment]
Your problem is with the lambda you passed to `view::transform`. Since it returns `A const&`, you can't mutate the elements. Try this:

```c++
    // Transform data in to view of A, so that 'f' can work on it
    auto b_as_a = b | ranges::view::transform([](auto& x) -> A& { return x.a; });
```

**Comment by Svalorzen** [comment]
Yes, this would make it compile. Unfortunately, in this way, only the part of the container that is viewed as `A` is modified, which is not what I am trying to do.

To express again the toy problem I have there, I have this range `b` of `B` elements:

        std::vector<B> b{{1,{2}},{3,{4}},{5,{6}}};

The `f` function I am using basically reverses a range of `A`. If I do the modification you proposed on the code, I end up with:

    {{1, {6}}, {3, {4}}, {5, {2}}} // Only `A`s are reversed, not the y elements

As you can see, here `f` reversed only the `A` part of the original list `b`. What instead I would like is to preserve the original elements, and reverse the overall list:

    {{5, {6}}, {3, {4}}, {1, {2}}}

The idea is that `f` performs an `iter_swap` on the range based on the information it sees (via the transformed range which exposes `B`s as `A`s), but the swaps directly act on the overarching range.

I hope I have been more clear.

**Comment by ericniebler** [comment]
You're trying to reverse a range of B's, but you're passing a range of A's. That is not a sensible thing to do. If you want to swap B's, you should pass a range of B's.

I suggest you post this to stackoverflow, add the `range-v3` tag, and give more context to motivate your use case.
