### ISSUE TITLE
Complexity of view::group_by

### ISSUE THREAD

**Issue by justanotheruser** [ericniebler/range-v3#886]
Can someone explain complexity of algorithm behind view::group_by? Its hard to look up the source code for someone not very familiar with templates besides STL.
If group_by would accept unary predicate that returns some sort of a key, I can imagine algorithm that works better than O(n^2). However, with binary predicate I can't imagine something that works better than comparing everything to everything.

**Comment by CaseyCarter** [comment]
`group_by` is a lazy linear algorithm that splits a range into subranges of equivalent (according to the predicate) elements. For example, given an underlying range of integers `{0,0,1,1,1,2,2,0,0,0}` with a predicate of `ranges::equal_to`, the subranges produced are `{0,0}`, `{1,1,1}`, `{2,2}`, and `{0,0,0}`.

**Comment by justanotheruser** [comment]
Thanks, I misunderstood what group_by does.

**Comment by ericniebler** [comment]
And although `view::group_by` is O(1) -- as are all the lazy view adaptors -- it makes two passes over the input range. I think it could do just one pass for input ranges, but that hasn't been implemented.
