### ISSUE TITLE
Zip to group

### ISSUE THREAD

**Issue by bobkocisko** [ericniebler/range-v3#902]
Is there a simple way to zip two sequences of the same type into a group rather than into a tuple?  Everything I've thought of short of writing my own custom view_facade + view_adaptor seems to break down.  I want to avoid tuple ownership in the view so a simple custom view_adaptor of a tuple is out.  I want to avoid all dynamic allocation so interleave/transpose is out.  And I want to make sure that reference-type tuple values are preserved in the process.  My thoughts are either to write a custom view_facade like group_by which generates a view on the fly to iterate the tuple (via the range, not via the tuple value).  That could then be used like `view::zip(...) | group_tuple`.  My other thought is to try to build a custom `zip_group` algorithm.  Which sounds like more of a project than I'm ready to commit to.  Am I missing something simpler?

```c++
// example inputs
std::vector<int> a {1,  2, 3, 4, 5};
std::vector<int> b {15, 6, 3, 9, 8, 7};

// ... zip_group(a, b) ...

// desired result
// [[1, 15], [2, 6], [3, 3], [4, 9], [5, 8]]
```

**Comment by Mog-Closet** [comment]
Have you looked into zip_with?

**Comment by bobkocisko** [comment]
Yes.  The only way I can conceive of doing this with zip_with is to return `view::concat(view::single(tpl.first), view::single(tpl.second))` but then I'm copying the tuple values into the single views which I don't want to do.  Is there another way to use it which doesn't copy the values?

**Comment by ericniebler** [comment]
Consider posting your question to stackoverflow. Save the issue tracker for bugs.
