### ISSUE TITLE
[question] const-iterability of views (never-ending...)

### ISSUE THREAD

**Issue by h-2** [ericniebler/range-v3#925]
Ok, so I understood all the reasoning for certain views not being `const`-iterable and I agree that it's the only way to go and to design your interface to taking forwarding references instead of const references.

When I implemented the views in our library, I have also designed them to have `iterator` and `const_iterator` be the same (if the view is const-iterable at all). But I am still unsure, of whether the const-iterabality should also depend on the const-iterability of the underlying range or not. 
My first intuition was that this should be entirely independent, because the `const`-ness of the view doesn't suggest that you can't change the underlying range, but also it feels kind of alien that you could wrap a single-pass input range in `view::all` and consume it merely by iterating over a `const &` to the view.
Is this the desired behaviour for views? Or should const-iterability be a feature that requires const-iterability of the underlying range?

This also has implications for implementing the general design of views. I have recently switched from always wrapping the underlying range in a shared_ptr to just storing a copy of the underlying view and passing non-view-lvalue-reference-ranges through `view::all`, as the range-library does, as well(?).
In the previous design it was easy to just make begin() forward to the wrapped range's begin() independent of the current view's const-ness, but if I want to achieve the above mentioned behaviour(full independence of const-iterability) in the new design I would need to make the member that holds the underlying view `mutable` or add some other form of indirection, or not?

**Comment by h-2** [comment]
OK, I have dug through the current version of p0896 and it seems that for most views that are const-iterable cbegin is only available if the underlying range is also const-iterable, e.g. `transform_view`.
The only exception seems to be *ref-view* which is returned by `view::all` for lvalue-reference-non-views. 

So I cannot iterate over `auto const & v = my_range | view::filter(...) | view::transform()`, i.e. view::transform won't add const-iterability to `view::filter`, but I can iterate over `auto const & v = something | view::transform()` even if `something` is a non-const-iterable input range, correct?

**Comment by ericniebler** [comment]
Yes, that's correct. This doesn't work:

```c++
 auto const & v = my_range | view::filter(...) | view::transform(...); // v is not a Range
```

But this is fine:

```c++
auto & f = my_range | view::filter(...);
auto const & v = f | view::transform(...); // OK, v is a Range
```

In the second case, `v` ends up holding a non-`const` reference to `f`, which gets mutated as `v` is iterated. That's fine because `v` really is `const`: no part of it gets mutated while it is iterated. Only `f` gets mutated, which is held by reference.

It's just like how you can write through a `int *const` and change the pointed-to integer, even though the pointer itself is `const` and cannot be mutated.

**Comment by h-2** [comment]
Thanks for taking the time to reply!

> It's just like how you can write through a int *const and change the pointed-to integer, even though the pointer itself is const and cannot be mutated.

Yeah, I understand the reasoning for the whole thing.

> In the second case, v ends up holding a non-const reference to f, which gets mutated as v is iterated. 

But wouldn't the decayed type of `f` model `View` and thereby f would be copied into `v`, instead of being bound by *ref_view*. The latter would "reroute" the iterator from const to non-const, but copying does not. Or did I completely misunderstand http://eel.is/c++draft/range.all in this regard?

**Comment by ericniebler** [comment]
/facepalm. You're right.

**Comment by h-2** [comment]
Ok, but then that means that views are currently deep-const in regard to other views and shallow-const in regard to non-views which is kind of strange, or not? (that was the original question although I didn't explain it well maybe)

I mean, in practice we don't expect const-iteration to be different from regular iteration in views, but especially since the first one might not exist you get unexpected behaviour in exactly those cases you took as an example above where getting "some range" as input to an algorithm and applying a view on that and passing it on as const might work or fail, not depending on whether the underlying range is const-iterable (which could seem related but would suggest deep const semantics), but on whether or not that "some range" was a view. The latter distinction appears very arbitrary to people not familiar with the implementation detail, or not?

**Comment by h-2** [comment]
> /facepalm. You're right.

In the light of this inconsistency and also the fact iterating over `view const` might not be thread-safe because of shallow-constness and e.g. single-pass input range as underlying range, would you reconsider the possibility of removing const-iterability altogether?

You originally brought this up here, but I don't know ho serious it was at the time:
https://github.com/ericniebler/range-v3/issues/385#issuecomment-223640608

I think at the current point it would just simplify things a lot. And it doesn't inhibit re-adding a form of const-iterability later... should we discuss this on lib-ext@ or are you happy with the current state in the IS and "done" with this topic?

Thanks for taking the time!

**Comment by ericniebler** [comment]
I would encourage you to write this discussion up and post to lib-ext@ and see what discussion ensues.
