### ISSUE TITLE
Is there a flatMap operation? 

### ISSUE THREAD

**Issue by njlr** [ericniebler/range-v3#929]
In JavaScript we have [`Array.prototype.flatMap`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap):

> The flatMap() method first maps each element using a mapping function, then flattens the result into a new array. It is identical to a map followed by a flat of depth 1, but flatMap is often quite useful, as merging both into one method is slightly more efficient.

Does `range-v3` provide this? ([searched](https://github.com/ericniebler/range-v3/search?q=flatmap&unscoped_q=flatmap))

**Comment by FloopCZ** [comment]
In the world of `range-v3` this is probably a combination of `view::transform` and `view::join`. This should be exactly what `view::for_each` does.

**Comment by ericniebler** [comment]
Yes, `view::for_each`.
