### ISSUE TITLE
Behaviour of `take_exactly` on a too-small view

### ISSUE THREAD

**Issue by mortenfyhn** [ericniebler/range-v3#943]
First of all, thanks for all the work you've all done with this library and the proposal, it's great.

The documentation states that when using `take_exactly`,

> The source range must have at least that many elements.

which makes sense. However, if I try to take more elements than are in the range, it runs fine:
```cpp
auto r1 = view::iota(0, 2);
auto r2 = view::iota(0, 2) | view::take_exactly(4);
printf("r1.size() = %zu\n", r1.size());  // prints 2
printf("r2.size() = %zu\n", r2.size());  // prints 4
```

Is `take_exactly(n)` guaranteed to make sure the resulting view is `n` elements even if the original view is smaller? Or is this supposed to raise an exception / other visible error? Or is it just undefined behaviour and fine the way it is?

Either way, what would be the best way to check that the original view is large enough? Actually checking `.size()` will probably have to evaluate the whole thing, which is inefficient. (In this particular case, I'm generating a range with a generator function, filtering out parts of it, then taking the first `n` elements.)

**Comment by CaseyCarter** [comment]
The sole difference between `take` and `take_exactly` is that it's a precondition for `take_exactly` that the range has at least that many elements. `take(n)` will "do the right thing" and produce a view with fewer than `n` elements if the range is too small, and `take_exactly(n)` will have undefined behavior.

**Comment by mortenfyhn** [comment]
Allright, thanks!
