### ISSUE TITLE
concepts requirement on ranges::copy

### ISSUE THREAD

**Issue by mitsutaka-takeda** [ericniebler/range-v3#95]
First, I'd like thank you for the great library! I'm very excited to see this library is coming to C++.

I just start exploring your library with replacing std::algorithm with ranges::algorithm, and have a difficult time to compile the following snippet.

````c++
#include <range/v3/all.hpp>
#include <iostream>
#include <iterator>
#include <vector>

int main(int argc, char *argv[]) {
	std::vector<int> ints = {0, 1, 2, 3};

	// old c++ way to print "0123"
	std::copy(std::begin(ints), std::end(ints), std::ostream_iterator<int>(std::cout));
	std::cout << std::endl;

	// using ranges::for_each
	ranges::for_each(ints, [] (auto x) {
			std::cout << x;
		});
	std::cout << std::endl;

	static_assert(ranges::WeaklyIncrementable<std::ostream_iterator<int>>::value,""); // static assert fail
	ranges::copy(ints, std::ostream_iterator<int>(std::cout)); // compile error here!
	std::cout << std::endl;
    return 0;
}
````

I can't call ranges::copy with std::ostream_iterator due to the concepts requirement on ranges::copy. The concept WeaklyIncrementable requires that a type I has an integral associated type difference_t<I>. The difference_t<std::ostream_iterator<int> > is void, and std::ostream_iterator<int> fails to model WeaklyIncrementable. 

So I have two questions. First, am I using ragnes::copy in the correct way or should I use another function. Second, is the concepts requirement on ranges::copy is intended one.

I'm fairly a novice to the concepts world. I'm sorry if I'm making some stupid mistakes.

**Comment by ericniebler** [comment]
You're right, you can't use `std::ostream_iterator` with the algorithms in range-v3. The [Palo Alto TR](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3351.pdf) is very precise about iterator requirements. They need an Integral difference type, and they need to be default constructible. `std::ostream_iterator` is neither. There are other std iterators that don't pass the test: the insert iterators, in particular. Range-v3 provides conforming versions of those iterators. Just use `ranges::ostream_iterator` and you should be all set.

I understand that this is an inconvenience, but it's important that we get usage experience with the concepts as specified in N3351.

**Comment by mitsutaka-takeda** [comment]
Thanks! 

Of course, there should be reanges' iterators! I'm going to try ranges::ostream_iterator.
