### ISSUE TITLE
view::transform downgrade iterator_category of boost::iterator_facade

### ISSUE THREAD

**Issue by tower120** [ericniebler/range-v3#953]
https://wandbox.org/permlink/jrU4pXQNisMyXDbr

```cpp
#include <iostream>

#include <iterator>
#include <vector>
#include <boost/iterator/iterator_facade.hpp>
#include <range/v3/iterator_range.hpp>
#include <range/v3/view/transform.hpp>

// just a wrapper around std::vector::iterator
template<class T>
class node_iterator
	: public boost::iterator_facade
	  <
		node_iterator<T>, T, boost::random_access_traversal_tag
	  >
{
public:
        node_iterator() = default;
	explicit node_iterator(typename std::vector<T>::iterator iter)
		: iter(iter) {}

private:
	friend class boost::iterator_core_access;

	void increment() { iter++; }
        void decrement() { iter--; }
        void advance(std::ptrdiff_t n) { iter += n; }

	bool equal(node_iterator const& other) const
	{
		return this->iter == other.iter;
	}

   T& dereference() const { 
        return *iter;
    }

    decltype(auto) distance_to(const node_iterator& other) const {
        return std::distance(iter, other.iter);
    }
public:
    typename std::vector<T>::iterator iter;
};


void show_category(ranges::random_access_iterator_tag) {
    std::cout << "random_access" << std::endl;
}

void show_category(ranges::bidirectional_iterator_tag) {
    std::cout << "bidirectional" << std::endl;
}


int main() {
    auto range = ranges::iterator_range(node_iterator<int>{}, node_iterator<int>{});
    auto b =
        range
        //| ranges::view::all
        | ranges::view::transform([](auto& i)->auto& { return i; })
        ;

    using T = decltype(b);
    using C = ranges::range_category_t<T>;
    C c{};

    show_category(c);
    return 0;
}
```

Output: bidirectional

Is there a particular reason for this?

**Comment by CaseyCarter** [comment]
Oops:
```c++
I& base() { return this->iter; }
```
in my original response is incorrect, I've corrected it to:
```c++
I& base() { return this->get().iter; }
```

**Comment by tower120** [comment]
Please copy/paste your example to documentation :) Just copy/paste, nothing more [In basic_iterator section].
I was trying to do the same thing with `ranges::view_facade`. But I was unable to access data stored in iterator (for erase operation, for example) -  https://stackoverflow.com/questions/53400346/ranges-v3-access-cursor-internals. Thus shifted to boost iterator_facade.

---

But let's go one step further... 

A:
At first look, it seems that `boost::iterator_facade` _does_ model RandomAcessIterator Concept:
https://wandbox.org/permlink/4ZwWWZFDZfioM2em
```
    using I = node_iterator<int>;
    using Category = ranges::iterator_category_t<I>;
```
Category is ranges::random_access_iterator_tag.

B:
But it doesn't, if dig deeper:
https://wandbox.org/permlink/xZUhmplZVKcJ8rh6

```
    using I = node_iterator<int>;
    bool b = concepts::models<concepts::RandomAccessIterator, I>::value;
    std::cout << std::boolalpha << b;
```

Shouldn't iterator_category_t with random_access_iterator_tag model RandomAccessIterator ? Why inconsistent?




_P.S.
Please do clarify one thing for me. Previously, only InputIterator could return value. Now I looking at Range TS here: https://en.cppreference.com/w/cpp/experimental/ranges/iterator/Iterator . Iterator must derefernce to auto&& ... And no more refinement of this further in richer iterators. Which means that any kind of iterator must dereference to auto&&.
So. Does this mean that with ranges I can freely work with proxy object (keeping in mind, that proxy object will not have reference to data stored in iterator) in ANY iterator? ... What about operator->?_
