### ISSUE TITLE
Visual Studio 2017 Community Edition and Range-v3

### ISSUE THREAD

**Issue by adah1972** [ericniebler/range-v3#957]
I have read that Visual Studio 2017 should finally support range-v3. From the issues, it seems some people are successful. For me, I get 374 lines of error messages with a simple test case (the same as in #939).

Is it because I am using the Community Edition (15.9.3, CL 19.16.27024.1), or something else? My command line is like the following:

```
cl /EHsc /std:c++17 /I \range-v3\include test.cpp
```

Of course it is not a bug report. I guess it might be the quickest way to get an answer. And I may not be the only soul frustrated by this problem.

**Comment by tower120** [comment]
It's work. You need /permissive- flag also. And DON'T !!! add /Za flag.

Mine looks like this:
```
/JMC /permissive- /GS /analyze- /W3 /Zc:wchar_t /ZI /Gm- /Od /sdl /Fd"Debug\vc141.pdb" /Zc:inline /fp:precise /D "_MBCS" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /Oy- /MDd /std:c++17 /FC /Fa"Debug\" /EHsc /nologo /Fo"Debug\" /Fp"Debug\FlatMultiMapTest.pch" /diagnostics:classic 
```

**Comment by CaseyCarter** [comment]
>  Can I say that this is very counter-intuitive on the Microsoft part?

Sorry about that. We had to put some of the 15.9 alias template fixes that range-v3 requires under `/permissive-` to avoid breaking code that was successfully compiling in permissive mode in 15.8. Since 15.9 is the long-term support release for VS2017 we're required to be extremely conservative about potential breaks.

> This does not work:
>
> ```
> #include <boost/coroutine2/all.hpp>
> #include <range/v3/all.hpp>
> ```
>
> Reversing these two lines will work…

I'll take a look at this.

**Comment by CaseyCarter** [comment]
> I'll take a look at this.

It looks like `<boost/coroutine2/all.hpp>` is being a bad kitty and including `<Windows.h>`, which is a horribly behaved header that leaks `min` and `max` macros (and others like `small`). Defining `NOMINMAX` in your project properties makes it compile correctly regardless of inclusion order.
