### ISSUE TITLE
range-v3 and boost::coroutine

### ISSUE THREAD

**Issue by voivoid** [ericniebler/range-v3#960]
Hi!

The following code does not compile

```
#include "range/v3/view/transform.hpp"
#include "boost/coroutine2/all.hpp"


int main() {

    using Coro = boost::coroutines2::coroutine<int>;
    Coro::pull_type coro{ [](Coro::push_type& yield) {
        for (int i = 0; i < 10; ++i) {
           yield(i);
        }
    } };

    auto r = coro | ranges::view::transform( []( int x ) { return x + 1; } );

    return 0;
}
```

As far as I understand the problem is that begin iterator is required to be WeaklyIncrementable while boost::pull_coroutine::iterator has no post increment ( https://github.com/boostorg/coroutine2/blob/develop/include/boost/coroutine2/detail/pull_coroutine.hpp#L130 ). Everything seems to work fine if the post increment op is implemented in boost::coroutine iterators.

While c++ native coroutines are still on the way I wonder if there is a way to fix the problem? Or this is a boost coroutine issue?

Thanks!

**Comment by ericniebler** [comment]
All `boost::pull_coroutine::iterator` needs to satisfy C++20's (and range-v3's) `WeaklyIncrementable` concept is to define a post increment operator that does the same thing and pre increment and returns void. They will want to make this change.
