### ISSUE TITLE
std::iterator_traits<RangesIter>::iterator_category evaluates to input_iterator_tag

### ISSUE THREAD

**Issue by david8dixon** [ericniebler/range-v3#961]
After transforming a range, the `iterator_category` evaluates to `input_iterator_tag`. 

https://wandbox.org/permlink/gmb9lGKe3YXYF18s

```c++
#include <iostream>
#include "range/v3/all.hpp"

template<typename T>
void f(T){
  std::puts(__PRETTY_FUNCTION__);
}

int main(){

  auto range = ranges::view::repeat_n(1.0, 100);
  f(std::iterator_traits<decltype(range.begin())>::iterator_category{});

  auto transform_range = range | ranges::view::transform([](auto&& entry){return 2*entry;});
  f(std::iterator_traits<decltype(transform_range.begin())>::iterator_category{});

}
```
Output:
```
void f(T) [with T = std::random_access_iterator_tag]
void f(T) [with T = std::input_iterator_tag]
```

**Comment by ericniebler** [comment]
By design. The old standard iterator categories require forward iterators to return real references. Your `transform_range` returns prvalues; hence, its iterator can model (C++98) InputIterator at best.

However, if you ask for `ranges::iterator_category_t`, you'll get the new-style iterator category, which is random-access.

https://wandbox.org/permlink/CjK2McrU3DGCoouV

**Comment by apmccartney** [comment]
> The old standard iterator categories require forward iterators to return real references

Oh that's a tragedy. Given the ranges merge in the working paper (congratulations by the way) will this be addressed in `std::iterator_traits` in C++20 or will there be an alternative in the `std::ranges` namespace?

**Comment by CaseyCarter** [comment]
Ranges-friendly code in C++20 won't look at `iterator_traits<foo>::iterator_category` - it will instead be constrained with the iterator concepts. [`ForwardIterator`](http://eel.is/c++draft/iterator.concept.forward) doesn't care of your iterator's reference type is `value_type&` or `const value_type&` (as required by [the *`Cpp17ForwardIterator`* requirements](http://eel.is/c++draft/forward.iterators)) or `value_type` or `some_proxy_reference`.

**Comment by ericniebler** [comment]
Right. Once you're using the Iterator concepts and `if constexpr` in C++20, the iterator tags are just legacy cruft -- except occasionally when you're defining an iterator (to distinguish between Input and Forward, or between RandomAccess and Contiguous, for instance).
