### ISSUE TITLE
view::drop_last?

### ISSUE THREAD

**Issue by tower120** [ericniebler/range-v3#979]
There is `view::drop`, which "removes" **first** elements from sequence.
Is it possible to have the same, but for **last** elements?

**Comment by cjdb** [comment]
I think this is solved by `view::take_exactly(size(r) - n)`.

**Comment by tower120** [comment]
You can't take_exactly with pipe :)

With "drop_last" you could:
```
list | drop_last(1)
```

**Comment by ericniebler** [comment]
> You can't take_exactly with pipe :)

Says who? https://godbolt.org/z/zWQwgt You can also use slice for this, but take and take_exactly are the better answers.

**Comment by lewissbaker** [comment]
> I think this is solved by `view::take_exactly(size(r) - n)`.

This would prevent usage with input ranges or be inefficient for ranges where `size(r)` is not O(1), though.

**Comment by ericniebler** [comment]
How would you drop the last N elements of an input range? When would you know how to stop taking elements if you didn't know the size? And size(r) is required to be O(1).

**Comment by ericniebler** [comment]
That's a very "react" answer. :-) The views generally avoid copying/storing the elements. However, for a forward range (not input), a `drop_last` view could have iterators that stored two iterators into the underlying sequence, one N elements ahead of the other. (`begin()` would have to advance one iterator and cache it in the view to avoid incurring quadratic behavior in downstream adaptors). Deref would be from the "slow" iterator and comparison with the end would check the "fast" one. Increment would advance them both, obviously.

**Comment by CaseyCarter** [comment]
FWIW: That's how `view::sliding` works. I suspect there's some useful commonality there that could be factored out.

**Comment by tower120** [comment]
Just to note. For BidirectionalIterator case, it seems it's doable without caching iterators. [drop_last sentinel can be calculated on creation - by just `prev(end)` n times and comparing with `begin`]
So there would be 3 versions/specializations: RandomAccess, Bidirectional and Forward...

**Comment by ericniebler** [comment]
> drop_last sentinel can be calculated on creation

This is a tempting and flawed implementation strategy. For one, it makes view creation O(N), which is poor form. But more seriously, there is a high chance that the sentinel will dangle after the view has been copied or moved, which means that it must be recomputed (at O(N) cost) on copy/move. Views are required to have O(1) copy/move.

**Comment by tower120** [comment]
> there is a high chance that the sentinel will dangle after the view has been copied or moved

How sentinel can dangle/invalidate on copy/move? Not that I argue with this, just don't understand.

**Comment by CaseyCarter** [comment]
> How sentinel can dangle/invalidate on copy/move?

Because a copy of an iterator that denotes an element in a view doesn't result in an iterator that denotes the same element in a copy of the view.

FWIW, `view::sliding` uses a similar technique for bidirectional common ranges: it calculates the final iterator when `end` is called and caches it. And for random access ranges it caches nothing since we can calculate the final iterator in O(1) time.

**Comment by tower120** [comment]
> Because a copy of an iterator that denotes an element in a view doesn't result in an iterator that denotes the same element in a copy of the view.

But why exactly? When this can happened? I suppose container iterators not affected with this. Is this because of view may stash some data inside themself, and then iterators have pointers to that stashed data?

**Comment by pfultz2** [comment]
The iterator may have a pointer to the view. When you make a copy, this pointer should point to the new view. The same is true for containers.

**Comment by tower120** [comment]
> The iterator may have a pointer to the view ...

Thanks, that's more clear now.

**Comment by apmccartney** [comment]
@kirkshoop 
> This is usually done with a queue/ring of size N that only pops off the front when adding to the end.

@ericniebler 
> That's a very "react" answer. :-) The views generally avoid copying/storing the elements. 

I believe there's an an argument to be made that this sort of implementation may have a place in ranges, or perhaps if not in the core ranges-v3 library then in auxilary libraries provided by the wider community. Lazy computation is central to the many of the views, whether during dereference (`transform`) or traversal (`filter`). Naturally, these operations can be expensive in some use cases and may benefit from memoization.

@CaseyCarter 
> FWIW: That's how view::sliding works. I suspect there's some useful commonality there that could be factored out.

In my organization, we've encountered a number of applications where sliding provides a convenient abstraction, but the range-v3 implementation was introducing noticable overhead during traversal as a result of repeated computation. We ended up providing a number of inhouse implementations along the lines of what Kirk describes, based on a few design decisions:

cache storage:
1. should the cache exist on the range, effectively requiring the sliding range model an input view
1. should the cache exist on the view iterator itself, meaning iterators are potentially not cheap to copy

cache size:
1. compile time
1. dynamic

cache elements:
1. cache elements of the underlying range
1. cache iterators into the underlying range

To the credit of the range-v3 library, once we got a handle on how the underlying machinery for defining views works, it was a remarkably low effort affair to get these views stood up. Our experience has thus far has been that cache storage option (2) and cache size option (2) have not seen much use in practice. We've found these views useful when working with.

1. input ranges
1. ranges with potentially expensive dereference operations, e.g. `view::transform`
2. ranges with potentially expensive increment operations, e.g. #801

**Comment by johelegp** [comment]
This can be closed.
