### ISSUE TITLE
Documentation of meta::list_cat is wrong

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/range-v3#98]
See it [here](https://github.com/ericniebler/range-v3/blob/master/include/range/v3/utility/meta.hpp#L416), looks like a copy/paste error from `meta::list::size`. It should probably state that `list_cat` _concatenates_ a sequence of lists. 

I don't know about its complexity in terms of templates instantiations tho, either O(N) where N is the total number of elements or, depending on how the compiler handles parameter packs, it might be O(L) where L is the number of lists passed (independent on the number of elements).

**Comment by ericniebler** [comment]
Thanks for spotting this. The complexity of the current implementation (in total # of template instantiations) is O(L/3) -- very efficient.

**Comment by ericniebler** [comment]
I wonder why I called this `list_cat` instead of `meta::concat`. Huh.

**Comment by gnzlbg** [comment]
So that's is why there are "too many" specializations. Does that means that
by just adding more specializations one can make this O(L/M) efficient
where M is the number of specializations?

About the name I prefer `join`, but I think it comes from `tuple_cat`.

**Comment by ericniebler** [comment]
> Does that means that by just adding more specializations one can make this O(L/M) efficient where M is the number of specializations?

Yes. I picked 3 because of how `repeat_n` is defined:

    template<std::size_t N, typename T>
    struct repeat_n_c_
    {
        using type =
            concat<
                list<
                    eval<repeat_n_c_<N / 2, T>>,
                    eval<repeat_n_c_<N / 2, T>>,
                    eval<repeat_n_c_<N % 2, T>>>>;
    };

> About the name I prefer `join`

Interesting, thanks.
