### ISSUE TITLE
O(1) unordered_remove algorithm+action ?

### ISSUE THREAD

**Issue by tower120** [ericniebler/range-v3#988]
`action::remove_if` erase elements that satisfies predicate with O(n) complexity, and keep order.
Overwriting each erased element with the last one, have O(1) complexity, but loose order.
This unordered remove useful when using vector-alike container as fast iterable "set"/unordered list.

I would like to make a PR with this feature. But not sure, does range library actually need this.

In essence, it looks like this:
algorithm:

```cpp
    template<typename I, typename C, typename P = ranges::ident>
    I unordered_remove_if(I begin, I end, C pred, P proj = P{})
    {
        using namespace ranges;
        CONCEPT_ASSERT(BidirectionalIterator<I>());

        I i = begin;
        while(i!=end)
        {
            if((invoke(pred, invoke(proj, *i))))
            {
                --end;
                if (i==end) break;

                *i = iter_move(end);
            } else {
                ++i;
            }
        }
        return end;
    }
```

action:
```cpp
template<typename Rng, class Pred, class Proj>
Rng operator()(Rng&& rng, Pred pred, Proj proj) const{
    auto it = unordered_remove_if(ranges::begin(rng), ranges::end(rng), std::move(pred), std::move(proj));
    ranges::erase(rng, it, ranges::end(rng));
    return static_cast<Rng&&>(rng);
}
```

**Comment by CaseyCarter** [comment]
I think this is a useful algorithm - it's basically `partition` except that it uses move assignment instead of swap - although I'd name it `unstable_remove_if` (by analogy to the `stable_XXX` algorithms) and implement it in terms of `find_if` and `find_if_not` (I'm a big fan of "using the library to implement the library"):
```c++
namespace ranges 
{
    inline namespace v3 
    {
        template <typename I, typename Pred, typename Proj = identity,
            CONCEPT_REQUIRES_(BidirectionalIterator<I>() &&
                Permutable<I>() &&
                IndirectUnaryPredicate<Pred, projected<I, Proj>>())>
        RANGES_CXX14_CONSTEXPR I 
        unstable_remove_if(I first, I last, Pred pred, Proj proj = {})
        {
            while(true)
            {
                first = find_if(std::move(first), last, pred, proj);
                last = find_if_not(
                    make_reverse_iterator(std::move(last)),
                    make_reverse_iterator(first),
                    pred, proj).base();
                if (first == last) return last;
                *first = iter_move(--last);
            }
        }
    }
}
```

**Comment by tower120** [comment]
@CaseyCarter Your version is more efficient => it omits unnecessary moves from end. I think it is impossible to implement `std::partition` in this fashion.

I'll make PR soon.

**Comment by kirkshoop** [comment]
should first be incremented at the end of the loop? that value was already tested by the predicate in `find_if_not` and would be tested again by `find_if`

```cpp
                if (first == last) return last;
                *first = iter_move(--last);
                if (first++ == last) return last;
```

**Comment by CaseyCarter** [comment]
> should first be incremented at the end of the loop?

Yes it should. Fixed.

**Comment by CaseyCarter** [comment]
> I was checking for the empty sequence before incrementing first

`first++ == last` is equal to `first == last`. At that point in the program, we know they're not equal since `*last` satisfied the predicate and `*first` did not satisfy it (before the `iter_move`, that is). `if (++first == last) return last;` is sensible, but I'm letting the empty case wrap back around to reduce codegen size.

**Comment by kirkshoop** [comment]
That does not seem to account for ‘iter_move(--last)’ which moves last. I would expect this to require another test before also moving first.

**Comment by CaseyCarter** [comment]
> That does not seem to account for ‘iter_move(--last)’ which moves last. I would expect this to require another test before also moving first.

You need to account for the "off-by-one" `reverse_iterator` weirdness: `reverse_iterator(x).base() == x`, but `*reverse_iterator(x) == *prev(x)`. So the return from `find_if` is either `reverse_iterator(first)` if no element is found that matches the predicate, or `reverse_iterator(x + 1)` if `x` denotes the rightmost element that satisfies the predicate.

**Comment by CaseyCarter** [comment]
> last is not a reverse_iterator. It is the result of .base() on the reverse_iterator

Correct. If the `find_if_not` failed, that `reverse_iterator` is `reverse_iterator(first)`, and `first == reverse_iterator(first).base()` is true: we've determined that all elements in `[first, last)` satisfy the predicate and should be removed.

If the `find_if_not` doesn't fail then it returns `reverse_iterator(x + 1)` such that `*x` does not satisfy the predicate but all the elements in `(x, last)` do and should therefore be removed. `reverse_iterator(x + 1).base()` is `x + 1`, which we store into `last`. After comparing that value with `first` to discover the `find_if_not` succeeded, we decrement `last` to get `x` and `iter_move` its element into `*first`. We now know that all elements in `[original_value_of_first, first]` don't satisfy the predicate, and all elements in `[last, original_value_of_last)` either do satisfy the predicate or are moved-from.
