### ISSUE TITLE
ericniebler.com is down

### ISSUE THREAD

**Issue by pthom** [ericniebler/range-v3#989]
Hello,

I just wanted to inform that your blog seems down.
I was about to try to post a comment onto your blog (ericniebler.com), and the website went down in front of me just when I was trying to use the "preview comment" button. 

I do not know if the site failure (`Error establishing a database connection`) was triggered by my comment or not. Anyhow, here is what I was entering (nothing too fancy, as you will see):

<pre>
Hello

`````
    int main() {

    }
````
</pre>

(Note the misbalanced `)
I"m sorry if I was the original cause of this 😞

**Comment by ericniebler** [comment]
LOL. I host my own wordpress instance in GCE, and it gets wedged every now and then. This is not your fault. I've restarted it. Thanks for reporting the problem.
